### ISSUE TITLE
文件系统点击新建的 + 号能否中途弹出弹窗，进行配置再去新建

### ISSUE THREAD

**Issue by andy00614** [opensumi/core#1000]
业务场景需要配置一些资源后再创建文件，请问现有的文件系统是否支持上述所说的场景

**Comment by erha19** [comment]
@andy00614 文件树场景下的新建文件不具备该定制能力，建议通过自定义命令的方式往文件树上注册响应的菜单命令，代码位置在：[file-tree-contribution.ts#L1101](https://github.com/opensumi/core/blob/3863dbb82e7f9a5a594ba63f1019231b1b1bd22d/packages/file-tree-next/src/browser/file-tree-contribution.ts#L1101)

如这里可以插件一个新的 `NEW_FILE_WITH_DIALOG` 类似的命令，同时实现上可以基于自己实现的逻辑结合 FileService 能力去创建文件，文件树将会自动响应外部的文件变化

尝试一下，该问题暂时先关闭了
