### ISSUE TITLE
[BUG] vscode-languageserver-protocol@3.17 导致构建失败

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1004]
https://www.npmjs.com/package/vscode-languageserver-protocol/v/3.17.0

<img width="432" alt="CleanShot 2022-05-10 at 23 35 29@2x" src="https://user-images.githubusercontent.com/13938334/167666971-3f40f529-f1a5-4aad-9e15-d6d99110272f.png">

vscode-languageserver-protocol@3.17 导致构建失败

一小时前发布了新版。

<img width="1011" alt="CleanShot 2022-05-10 at 23 36 25@2x" src="https://user-images.githubusercontent.com/13938334/167667176-26822027-af8d-41fe-9ac0-2b8f4a98dfd7.png">

**Comment by bytemain** [comment]
这个包是要锁版本的，要把2.16/2.17的也都锁了。

2.18我们换成最新版3.17，协议变成更细分了，有TextDocumentFilter这些了

**Comment by erha19** [comment]
会在 2.16.15, 2.17.4 版本中锁定为 3.16.0 版本

**Comment by erha19** [comment]
已在 2.16, 2.17 最新版本中修复
