### ISSUE TITLE
[BUG] DebugToolbarView 不能点击

### ISSUE THREAD

**Issue by kidswong999** [opensumi/core#1009]
当在最上面的时候，不能点击，拖下来的时候就可以。

不能点击的位置：
![截图_16522515293060](https://user-images.githubusercontent.com/9582040/167785939-50102874-e373-4f0f-9c91-43d26301ea1a.png)

可以点击的位置：
![截图_16522516833](https://user-images.githubusercontent.com/9582040/167786011-8b0c2148-ba44-4aa1-8cab-3949f10a0dbe.png)

**Comment by erha19** [comment]
这里初步怀疑是因为层级问题导致的，对于的组件文件在：[debug-toolbar.view.tsx](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx#L279) 应该需要调整一下响应的层级关系，可以尝试修一下

另外调试工具栏距离顶部的距离可以通过修改 `debug.toolbar.top` 配置的方式进行配置，也可以在 Windows 下采用一个菜单高度作为 `debug.toolbar.top` 的值

**Comment by songhn233** [comment]
![Kapture 2022-05-13 at 12 57 07](https://user-images.githubusercontent.com/47357585/168214058-8718e9eb-ef2f-446d-859d-ebc4529a4749.gif)
这里好像不太能复现问题

**Comment by kidswong999** [comment]
我使用的操作系统是windows10，electron

@songhn233

**Comment by situ2001** [comment]
在最上面的话 确实无法点击

OS: Windows 11

**Comment by situ2001** [comment]
Windows vscode下的debug行为默认如下，且无法拖动至菜单栏上，我想应该可以在这里加个判断 `isElectronRenderer` 且 `isWindows`时给`debug.toolbar.top`赋上菜单栏的高度

https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx#L238

![image](https://user-images.githubusercontent.com/28241963/173118584-39b6843b-efb7-4c69-90b7-8f371d44a67b.png)

**Comment by erha19** [comment]
> Windows vscode下的debug行为默认如下，且无法拖动至菜单栏上，我想应该可以在这里加个判断 isElectronRenderer 且 isWindows时给debug.toolbar.top赋上菜单栏的高度

@situ2001 你这个思路可以的，可以提个 PR 上来

**Comment by situ2001** [comment]
我注意到了title的CSS rule `app-region`

![image](https://user-images.githubusercontent.com/28241963/177460474-70c2beb7-2cb7-4d56-86ff-9b0314520c5e.png)

https://github.com/electron/electron/issues/1354 这里有提到app-region吞掉了click事件的解决方法

我来修修吧

**Comment by situ2001** [comment]
> > Windows vscode下的debug行为默认如下，且无法拖动至菜单栏上，我想应该可以在这里加个判断 isElectronRenderer 且 isWindows时给debug.toolbar.top赋上菜单栏的高度
> 
> @situ2001 你这个思路可以的，可以提个 PR 上来

我参考了 https://github.com/opensumi/core/issues/1009#issuecomment-1175733141 里的解决方案

如果只更改的Windows electron下的默认位置，有点奇怪

**Comment by situ2001** [comment]
> 当在最上面的时候，不能点击，拖下来的时候就可以。
> 
> 不能点击的位置： ![截图_16522515293060](https://user-images.githubusercontent.com/9582040/167785939-50102874-e373-4f0f-9c91-43d26301ea1a.png)
> 
> 可以点击的位置： ![截图_16522516833](https://user-images.githubusercontent.com/9582040/167786011-8b0c2148-ba44-4aa1-8cab-3949f10a0dbe.png)

准确来说是debug toolbar在title上的那部分无法点击

https://github.com/opensumi/core/blob/3340fa89eab63413a00335f52a81d6cfa20dd2e5/packages/electron-basic/src/browser/header/header.tsx#L227

https://github.com/opensumi/core/blob/5d673cb572ef9580a9414385701a144287dde672/packages/electron-basic/src/browser/header/header.module.less#L12-L13
