### ISSUE TITLE
[FEATURE] 使用 SmartIDE 国内的 OpenVSX 镜像作为插件市场默认源

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#1021]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

https://marketplace.smartide.cn/api

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
对比看了一下，部分插件的版本号同步情况不一致，可能需要同步或修改一下最新可用版本，如：

VS Code JavaScript Debugger

国内镜像站：https://marketplace.smartide.cn/extension/ms-vscode/js-debug 最新版本为 1.66.1 版本
OpenVSX：https://open-vsx.org/extension/ms-vscode/js-debug 最新版本为 1.67.2 版本

**Comment by iamxukai** [comment]
![QQ截图20220513103325](https://user-images.githubusercontent.com/85668115/168199964-e07e00dd-5da9-468d-a1ca-8f69a777e4d9.png)
这个链接我打不开

**Comment by Aaaaash** [comment]
> ![QQ截图20220513103325](https://user-images.githubusercontent.com/85668115/168199964-e07e00dd-5da9-468d-a1ca-8f69a777e4d9.png) 这个链接我打不开

这个链接不需要打开，在内部调用会拼接成类似这样的接口
https://marketplace.smartide.cn/api/-/search?query=vscode

**Comment by iamxukai** [comment]
我有兴趣解决一下

**Comment by ups216** [comment]
> 

同步现在已经是自动化的，可以看看是不是需要调整一下同步频率 https://github.com/SmartIDE/eclipse-openvsx/actions/workflows/smartide-openvsx-extensions-sync.yml

**Comment by erha19** [comment]
> 同步现在已经是自动化的，可以看看是不是需要调整一下同步频率 https://github.com/SmartIDE/eclipse-openvsx/actions/workflows/smartide-openvsx-extensions-sync.yml

@ups216 看了一下目前同步的插件貌似都只有某一个版本？是否对历史版本的插件也提供插件的同步能力，毕竟不同的框架版本支持的插件版本也是存在差异的

**Comment by ups216** [comment]
@zlweicoder 可以跟进一下这个事情

**Comment by zlweicoder** [comment]
插件历史版本问题和更新延迟问题由：
https://github.com/SmartIDE/eclipse-openvsx/issues/2 
记录。

另外提出建议：
请 opensumi 考虑是否可以将 marketplace 做成IDE界面设置处可配置的方式，这样既能够避免修改插件市场后的镜像需要修改者自行打包，也可以兼容 opensumi 在企业内网中被使用的情况。

**Comment by erha19** [comment]
> 请 opensumi 考虑是否可以将 marketplace 做成IDE界面设置处可配置的方式，这样既能够避免修改插件市场后的镜像需要修改者自行打包，也可以兼容 opensumi 在企业内网中被使用的情况。

@zlweicoder 对于插件市场的源，在应用场景下应该是一个相对固定的地址，如果需要修改，我们这边的建议还是重新打包，这块目前是作为产品/项目配置存在的，不适合放到 IDE 设置面板中让用户自行修改

**Comment by zlweicoder** [comment]
@erha19 
marketplace.smartide.cn已完成：
1. 插件历史版本同步逻辑增加，已完成所有插件每个至少5个历史版本（由新到旧）的同步。（插件历史记录数据量太大，数量达到十万级别，逐步分批次同步中）
2. 定时机制已添加，每日增量检查更新。

请确认opensumi所使用插件及所使用插件版本是否已经存在，如缺少任何内容，请告知，我们优先同步。

**Comment by erha19** [comment]
@zlweicoder 目前功能测试下一切正常，已完成 PR 替换 #1045，另外问一下，镜像站是否有海外的部署节点或计划？

**Comment by ups216** [comment]
> @zlweicoder @ups216 感谢你们的贡献，目前功能测试下一切正常，已完成 PR 替换 #1045，另外问一下，镜像站是否有海外的部署节点或计划？

@erha19 海外镜像站可以有，不过我想知道目的是什么，海外使用open-vsx.org的速度还是不错的，是希望通过geo-dns实现自动切换海外镜像吗？

**Comment by erha19** [comment]
> 海外镜像站可以有，不过我想知道目的是什么，海外使用open-vsx.org的速度还是不错的，是希望通过geo-dns实现自动切换海外镜像吗？

目前唯一的目的可能是保障海内外相对一致的访问体能为我们减少一些答疑成本。想了解一下你们的计划，目前看问题不大。

**Comment by ups216** [comment]
> 目前唯一的目的可能是保障海内外相对一致的访问体能为我们减少一些答疑成本。想了解一下你们的计划，当前看问题不大。
我觉得可以分步实施，现在OpenSumi的目标用户应该主要还是国内，SmartIDE当前也是专注于国内市场的开拓，所以我们可以暂时先针对国内开发者解决问题。
SmartIDE本身也有国内(https://smartide.cn)海外(https:// smartide.dev)两个域名，后续我们可以根据用户反馈情况按需添加外海节点，现在部署和插件同步机制都已经自动化，所以实施速度应该很快。
另外，再提一下之前 @zlweicoder 提过的建议，如果把插件市场做成可配置项，其实可以作为当前的一个折中方案，同时对于企业内网私有部署也提供比较好的体验。

**Comment by erha19** [comment]
@ups216 @zlweicoder 关于配置项的支持，我们在另外的 issue 中跟进 #1049.
