### ISSUE TITLE
[REFACTOR] 替换 `getKaitianIcon` 为 `getIcon`

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1032]
**描述你的问题（Describe the bug）**

<img width="774" alt="image" src="https://user-images.githubusercontent.com/9823838/168471789-59050d55-35c8-4670-a3d6-0638cc2eac7d.png">

如图，代码中不需要在名称上硬编码 `kaitian` 带来用户疑惑，这里可以替换为 `getIcon`, 考虑到集成方可能有在使用，需要补充相关 BrakingChange 信息至 [Wiki/Breaking-Changes](https://github.com/opensumi/core/wiki/%E9%9B%86%E6%88%90%E6%8E%A5%E5%85%A5-Breaking-Changes)

代码位置：[components/src/icon/util.ts](https://github.com/opensumi/core/blob/f1e74ec6a773a43981fab331cd6b953d0a54c9dd/packages/components/src/icon/util.ts)

**Comment by songhn233** [comment]
https://github.com/opensumi/core/blob/554c11b770333f7282c4963b500eec06dbeea188/packages/core-browser/src/style/icon/icon.ts#L8-L9

看起来是有暴露对应的接口，应该只要内部用法统一一下？

**Comment by erha19** [comment]
> 看起来是有暴露对应的接口，应该只要内部用法统一一下？

@songhn233 对的，这里主要要将内部的用法统一一下
