### ISSUE TITLE
[BUG] registerToolbarItems时，调用removeMenubarItem删除后，文字遗留

### ISSUE THREAD

**Issue by Luna-luo** [opensumi/core#1042]
调用registerToolbarItems方法时，删除如下两个item(文件和):
`registerToolbarItems(registry: ToolbarRegistry) {
    registry.menuRegistry.removeMenubarItem(FILE_COMMANDS.NEW_FILE.id);
    registry.menuRegistry.removeMenubarItem(FILE_COMMANDS.NEW_FOLDER.id);
  }
`
预期效果：
文件与文件夹的功能被移除。

实际效果：
页面仅图标被移除，但出现文字。
![Screen Shot 2022-05-16 at 17 33 48 (2)](https://user-images.githubusercontent.com/56943859/168569727-528c8029-24fa-4fc4-bdd5-c75a4b2d1282.png)

**Comment by erha19** [comment]
相关代码见：[base.ts#L221](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/core-browser/src/menu/next/base.ts#L221), 初步怀疑该逻辑代码无法正常移除 MenuBar 菜单副作用，下个迭代解决，有兴趣处理的可以认领一下。

**Comment by iamxukai** [comment]
![QQ截图20220517144959](https://user-images.githubusercontent.com/85668115/168747168-231e5d70-7ea7-4cc0-b886-e57056ffa805.png)
我只注释了 [file-tree-contribution.ts #L1102~#L1117](https://github.com/opensumi/core/blob/main/packages/file-tree-next/src/browser/file-tree-contribution.ts#L1102)
@erha19  好像没有显示多余的文字

**Comment by erha19** [comment]
@iamxukai 这里的场景应该不是注释掉代码的情况，而是通过模块集成的方式，引入一段 contributionPoint 逻辑，希望通过调用 `registry.menuRegistry.removeMenubarItem(FILE_COMMANDS.NEW_FILE.id);` 去移除这块的注册逻辑

**Comment by iamxukai** [comment]
我有兴趣解决一下。
@erha19

**Comment by bytemain** [comment]
没有复现这个问题：

加了这两行并没有移除任何界面上的东西。
```
registry.menuRegistry.removeMenubarItem(FILE_COMMANDS.NEW_FILE.id); registry.menuRegistry.removeMenubarItem(FILE_COMMANDS.NEW_FOLDER.id);
```

但我自己试了一下，想移除这两个按钮可以先用：

```
    registry.menuRegistry.unregisterMenuItem(MenuId.ViewTitle, FILE_COMMANDS.NEW_FILE.id);
    registry.menuRegistry.unregisterMenuItem(MenuId.ViewTitle, FILE_COMMANDS.NEW_FOLDER.id);
```

**Comment by erha19** [comment]
@iamxukai 可能这个问题是出现在纯前端场景的，可以尝试复现一下

**Comment by erha19** [comment]
@Luna-luo 看一下是否可以补充更多的信息帮助我们复现一下问题？

**Comment by iamxukai** [comment]
> @iamxukai 可能这个问题是出现在纯前端场景的，可以尝试复现一下

在纯前端下，我没有成功复现出来。
