### ISSUE TITLE
[FEATURE] 支持通过集成配置的方式来实现对 OpenVSX 源的配置能力

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1049]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

当前框架尽管支持了对于插件市场的源配置，见：[server.ts#L58](https://github.com/opensumi/core/blob/42f28bc6621251ebad3b0a2c3c388ed4729d4d7b/tools/dev-tool/src/server.ts#L58)

格式如：

```
  ...
  marketplace: {
      endpoint: `${DEFAULT_OPENVSX_REGISTRY}/api`,
      showBuiltinExtensions: true,
   }
  ...
```

但依旧存在部分对 `DEFAULT_OPENVSX_REGISTRY` 的硬编码逻辑依赖，主要为前端代码部分，如：[extension/index.tsx](https://github.com/opensumi/core/blob/42f28bc6621251ebad3b0a2c3c388ed4729d4d7b/packages/extension-manager/src/browser/extension/index.tsx) 等。

**描述你预期的功能表现（Describe the solution you'd like）**

期望能够通过 Node 层的配置，抹除前端硬编码的 Registry 逻辑，思路：

可以考虑在前端插件市场初始化时接收后端返回的 `endpoint` 路径 （建议移除掉 `/api` 这一段 path，后端自主拼接），进一步渲染后续内容

**Comment by iamxukai** [comment]
我有兴趣解决一下。
