### ISSUE TITLE
[FEATURE] ide-overlay 的 IDialogService 的 dialog 支持自定义属性

### ISSUE THREAD

**Issue by wangxiaojuan** [opensumi/core#1057]
在弹框内容比较多的情况下需要对宽度进行自定义，目前该组件不支持添加className，也不支持自定义属性
两者满足其一即可。

**Comment by erha19** [comment]
相关代码位置见：[dialog.service.ts](https://github.com/opensumi/core/blob/f3fd01381d6ee854102d491b14957e9e634941a3/packages/overlay/src/browser/dialog.service.ts)  是不是可以考虑加一个 `props` 的传参用于传递弹窗额外的属性定义，如 `className` 等

**Comment by songhn233** [comment]
感觉可以加两个属性，`className` 和 `style`

**Comment by tyn1998** [comment]
Hi，大家好。我发现在文件列表中用右键删除一个文件和左键选中后用快捷键删除一个文件，确认对话框弹出的动画效果是不一样的，请问这是有意设计的吗？

用右键删除是从窗口左方放大到窗口中央；用快捷键删除是从窗口正中央放大到正中央。

**Comment by tyn1998** [comment]
赞！明白了~
