### ISSUE TITLE
Discussion on OSPP and channel of communication 

### ISSUE THREAD

**Issue by Rispectech** [opensumi/core#1075]
**描述你的问题（Describe your question here）**

Hello, I am Rishabh Verma, an undergraduate CS student at UIET, India, Punjab University.
I have set up the project in my local system and am really interested in working on this project for OSPP'22. 
**Implementation of cross-end and cross-window file system service base on OpenSumi**
However, I can't figure out how to communicate with you all as DingTalk always gives me a network error. 
I would be really grateful if I could get some help on this and directions to work on this project.

**Comment by erha19** [comment]
Hi, @Rispectech I will create a discussion about `Implementation of cross-end and cross-window file system service based on OpenSumi` today, maybe we can talk there.

**Comment by erha19** [comment]
@Rispectech I create a discussion here [#1086](https://github.com/opensumi/core/discussions/1086), if you are interested in it, you can show your ideas or other question.

I will close this issue cause it is duplicated.

**Comment by Rispectech** [comment]
hey, @erha19 thanks for the head-ups.  I have started researching the vscode methods.
