### ISSUE TITLE
[BUG] Terminal 上的下拉按钮没反应  (2.18 prerelease)

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1079]
**描述你的问题（Describe the bug）**

如果是装了 js debug 是有的，但如果默认没装，点击后没有反应。

**复现路径（To Reproduce）**
打开 Terminal panel，点击 + 号旁边的下拉按钮

**预期表现（Expected behavior）**
添加几个默认的行为，比如显示当前系统支持的几个 默认的 profile

**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/2226423/169731958-eaa07671-1d5e-4cdb-bb06-a7ad2ae35ca9.png)

**环境信息（Environment）**

- OS: macOS calalina
- Browser: Electron
- OpenSumi Version: 2.17.6-next-1652879563.0

**补充信息（Additional context）**

**Comment by erha19** [comment]
这个应该是加了的，可能是因为依赖的 Changed 事件写的有点问题，我看一下

**Comment by life2015** [comment]
> 这个应该是加了的，可能是因为依赖的 Changed 事件写的有点问题，我看一下

这个是终端做重连改造的时候，获取clientID代码地方的bug，因为直接从WSChanelHandler那边拿的话，到Electron场景就会出问题，我做下处理吧。

**Comment by erha19** [comment]
fixed #1100
