### ISSUE TITLE
[BUG] DEBUG CONSOLE 样式异常 (2.18 prerelease)

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1082]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
1. debug 一个项目，打开调试控制台就会复现

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/2226423/169735217-77bc90b9-b898-4fc3-bc33-1f8ca09804df.png">

**环境信息（Environment）**

- OS: macOS catalina
- Browser: electron
- OpenSumi Version: OpenSumi Version: 2.17.6-next-1652879563.0

**补充信息（Additional context）**

**Comment by erha19** [comment]
duplicate #1067.
