### ISSUE TITLE
[BUG] 文件树新建的文件无法在文件树上立即展示 (2.18 prerelease) 

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1084]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
1. 打开一个新项目，直接在展开的目录右键新建文件
2. 右侧编辑器会打开新建的文件，但左侧的文件树会消失

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
![screenshort_20220523-110839](https://user-images.githubusercontent.com/2226423/169736032-cd61e4d6-ea88-4aff-8026-861450b54a8c.gif)

**环境信息（Environment）**

- OS: macOS catalina
- Browser: electron
- OpenSumi Version: OpenSumi Version: 2.17.6-next-1652879563.0

**补充信息（Additional context）**

**Comment by erha19** [comment]
初步判断应该还是 macOS 环境下文件服务将 “新建” 类型的文件事件处理为 "更新" 类型了，我排查看看
