### ISSUE TITLE
[FEATURE] 编辑器的关闭按钮添加 hover 样式

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1085]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

关闭按钮没有 hover 样式，和其它按钮的默认样式不同
![image](https://user-images.githubusercontent.com/2226423/169738905-075c7063-c88c-484f-9e34-f4234f7db684.png)

**描述你预期的功能表现（Describe the solution you'd like）**
在鼠标移动到编辑器 tab 的关闭按钮时，出现对应的 hover 样式

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by iamxukai** [comment]
我有兴趣解决一下
