### ISSUE TITLE
[BUG] 使用终端Open打开的文件不会被纳入到watch中导致不更新

### ISSUE THREAD

**Issue by life2015** [opensumi/core#1089]
**描述你的问题（Describe the bug）**

打开的非fileTree文件不会被纳入到watch中导致不更新。
在使用OpenSumi查看日志这个场景下比较明显，影响使用体验。

**复现路径（To Reproduce）**

- 在fileTree之外的地方创建一个文件
- 使用file schema 或者 终端open之类的能力，用OpenSumi打开该文件
- 然后使用vim修改该文件
- opensumi无反应

**预期表现（Expected behavior）**

预期文件在OpenSumi中也被实时修改掉。

**问题截图（Screenshots）**

展示内容和cat出来的内容不一致。
如图：
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/12879047/169782402-417d6ce9-9888-4284-90ff-75ce47dcd075.png">

**环境信息（Environment）**

Chrome + Linux 研发容器

**补充信息（Additional context）**

应该把这部分文件也纳入到filewatch中

**Comment by erha19** [comment]
@life2015 这个问题不是这个版本才有的问题，可以放到后面的迭代再处理了
