### ISSUE TITLE
[FEATURE] 升级Monaco版本

### ISSUE THREAD

**Issue by life2015** [opensumi/core#1099]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

目前依赖的monaco版本有些老旧，性能和功能都有些落后，需要升级一下。

**Comment by hacke2** [comment]
目前主要依赖了新版的哪些功能？

**Comment by hacke2** [comment]
> > 目前主要依赖了新版的哪些功能？
> 
> 功能上没啥太强依赖，主要是性能差距有些大

这个感觉如何而来？或者有没有相应性能提示的 PR？

**Comment by life2015** [comment]
新功能 括号颜色匹配
性能 Git diff 性能优化

**Comment by erha19** [comment]
now the monaco editor core is 0.35.x.
