### ISSUE TITLE
ASoC 2022: support and adapt for IDEA related shortcut

### ISSUE THREAD

**Issue by bk1012** [opensumi/core#1105]
### Background
This is a normal subject of [ASoC 2022](https://opensource.alibaba.com/asoc2022) and https://github.com/opensumi/core/issues/1103 .

The built-in shortcut keys of OpenSumi shall be very easy for front-end developers that get used to VS Code. But it is not the case for Java developers who come from IDEA.  
It will be great if the same shortcut key mapping support can be provided for IDEA.  
In the VSCode, `IntelliJ IDEA Keybindings plugin` provisions most of the shortcut keys mapping in IDEA, but two problems remain:

1. When OpenSumi runs in Web mode, some shortcut keys conflict with browser's, and it cannot be overridden directly. Including but not limited to Cmd/Ctrl + W, Cmd/Ctrl + N, Cmd/Ctrl + T, etc.  
2. The plugin has different or unsupported functionality in the corresponding OpenSumi `commands`, which results into unexpected behavior for a portion shortcut keys

### Target
1. A Chrome plugin that can resolve the conflict between OpenSumi and Chrome browser shortcuts
2. Adapt the commands for common shortcut keys of `IntelliJ IDEA Keybindings` plugin in OpenSumi

### Difficulty
Normal

### Mentor
@bk1012 [sijie.zsj@alibaba-inc.com](sijie.zsj@alibaba-inc.com)

### Technical Requirement
1. Proficient in TypeScript and React
2. Understand OpenSumi shortcut keys and Command related modules
3. Basic knowledge in Chrome browser plugin 

### 背景
这是一个[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022) 的基础课题 https://github.com/opensumi/core/issues/1103 。

目前 OpenSumi 默认内置的快捷键对习惯使用 VS Code 的前端开发来说会十分熟悉，但对于从 IDEA 切换过来的 Java 开发会非常陌生，因此需要能提供跟 IDEA 一样的快捷键映射支持。在 VSCode-Java 生态中，IntelliJ IDEA Keybindings 插件支持了大部分 IDEA 快捷键的映射支持，但还是存在如下两个问题：
1. 当 OpenSumi 使用 Web 模式运行于浏览器中的时候，部分快捷键与浏览器快捷键有冲突且无法被直接覆盖，比如 Cmd/Ctrl + W、 Cmd/Ctrl + N 、 Cmd/Ctrl + T 等等。
2. OpenSumi 中使用该插件后部分快捷键的功能跟预期不符，主要是IntelliJ IDEA Keybindings中快捷键对应的 command 在 OpenSumi 中不支持或者不一致导致的

### 目标
1. 一个可以解决 OpenSumi 与 Chrome 浏览器快捷键冲突的 Chrome 插件
2. 适配 OpenSumi 中 IntelliJ IDEA Keybindings 插件常用快捷键的 command

### 难度
普通

### 导师
@bk1012 [sijie.zsj@alibaba-inc.com](sijie.zsj@alibaba-inc.com)

### 技术要求
1. 熟练掌握 TypeScript 及 React
2. 掌握 OpenSumi 快捷键及 Command 相关模块
3. 了解 Chrome 浏览器插件开发

**Comment by bk1012** [comment]
[IntelliJ IDEA Key Bindings for Visual Studio Code 快捷键梳理(版本1.4.5)](https://www.yuque.com/bk1012/msfgdq/veowyu)

**Comment by erha19** [comment]
Done by @iamxukai.
