### ISSUE TITLE
[BUG] 插件 API sendText 异常（2.18 prerelease) 

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1140]
**描述你的问题（Describe the bug）**

使用插件示例 https://github.com/microsoft/vscode-extension-samples/tree/main/terminal-sample 
（之前的版本正常， 2.18 版本异常）
不能正常通过 terminal.sendText 执行命令

**复现路径（To Reproduce）**
1. 链接 Terminal Sample 插件到 OpenSumi  ~/.sumi/extensions 中
2. 打开 OpenSumi localhost:8080，在 Cmd+P 弹出的 quick open 中输入 Terminal API sendText
3. 正常情况是会执行 echo  hello world

**预期表现（Expected behavior）**

2.16.10 版本中测试是正常执行 sendText 的内容

**问题截图（Screenshots）**
![screenshort_20220530-153040](https://user-images.githubusercontent.com/2226423/170940495-b3bb06cd-f6a2-41b2-8f53-d245a2fbd0cf.gif)

**环境信息（Environment）**

- OS: macOS
- Browser: Chrome
- OpenSumi Version: 2.18 prerelease

**补充信息（Additional context）**

**Comment by erha19** [comment]
main 分支测试正常，@yantze 检查看看是不是没有重新编译插件进程..

![image](https://user-images.githubusercontent.com/9823838/171079229-7059e996-a4f9-47de-a45f-ab939434b153.png)
