### ISSUE TITLE
[BUG] 选中workspace后在文件列表中hover触发的highlight会覆盖蓝色边框

### ISSUE THREAD

**Issue by tyn1998** [opensumi/core#1141]
**描述你的问题（Describe the bug）**

选中workspace后，在文件列表中hover触发的highlight会覆盖蓝色边框。

**复现路径（To Reproduce）**

1. 点击左侧workspace文件树的空白区域
2. workspace会被选中，外侧出现蓝色边框
3. 鼠标hover到一个文件上
4. 会发现高亮的左右两侧把蓝色边框覆盖了

**预期表现（Expected behavior）**

这是在vscode中相同操作得到的截图：

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/32434520/171002451-a1589d9f-c41d-43be-9968-41059ee93e6e.png">

**问题截图（Screenshots）**

这是问题描述的情况：

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/32434520/171002650-27568e4d-d4b5-4a82-8bbd-905872f2cbb1.png">

**环境信息（Environment）**

- OS: MacOS 12.4 Apple M1
- Browser: chrome
- OpenSumi Version: "[main](https://github.com/opensumi/core/commit/51ddf9e2d86f0c47fe6cf9286ddb8899c4de418e)" branch

**补充信息（Additional context）**

无。

**Comment by erha19** [comment]
@tyn1998 这确实是个样式问题，相关的样式代码见：[file-tree-node.module.less](https://github.com/opensumi/core/blob/d6060f67cfcb1d7df7bdeafa4d7aa99319ac41b4/packages/file-tree-next/src/browser/file-tree-node.module.less) 

同时，这里外部的边框实现方式有些特殊，是采用 `outline` + `outline-offset` 的方式实现的。

你可以尝试解决试试 ~
