### ISSUE TITLE
[FEATURE] 移除 core/tools/electron

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1155]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

core/tools/electron 有一些冗余，之后 electron 的问题可以直接向 ide-electron 提交。

**描述你预期的功能表现（Describe the solution you'd like）**

1. 在 core 可以直接通过脚本 submodule 直接 clone  ide-electron
2. 通过脚本自动 link-local
3. 需要一个新的脚本实现自动化的流程

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
感觉框架内应该还是需要一个直接的验证方式的，如果移除后按照上面的流程，调试成本比较高，而且 link 之后可能会有一些其他问题出现

**Comment by yantze** [comment]
link 的问题已经找到原因了
