### ISSUE TITLE
[BUG] tools下的electron无法打开终端

### ISSUE THREAD

**Issue by situ2001** [opensumi/core#1171]
**描述你的问题（Describe the bug）**

(已尝试过重新build)

`tools/electron` 下的electron无法打开终端，提示如下

```powershell
[node][extHost:error] TypeError: _spdlog.setAsyncMode is not a function
    at LogService.createSpdLogLoggerPromise (C:\Users\situ\github\opensumi\core\tools\electron\app\dist\node\index.js:160279:21)
    at new BaseLogService (C:\Users\situ\github\opensumi\core\tools\electron\app\dist\node\index.js:160181:41)
    at new LogService (C:\Users\situ\github\opensumi\core\tools\electron\app\dist\node\index.js:160355:9)
    at LogServiceManager.getLogger (C:\Users\situ\github\opensumi\core\tools\el...[node]innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\situ\github\opensumi\core\tools\electron\node_modules\node-pty\lib\windowsPtyAgent.js
- C:\Users\situ\github\opensumi\core\tools\electron\node_modules\node-pty\lib\windowsTerminal.js
- C:\Users\situ\github\opensumi\core\tools\electron\node_modules\node-pty\lib\index.js
- C:\Users\situ\github\opensumi\core\tools\electron\app\dist\node\index.js
    at Function.Module._resolveFilename (node:internal/modules/...[node][node:error] IPty#spawn native exception Error: The module '\\?\C:\Users\situ\github\opensumi\core\tools\electron\node_modules\node-pty\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 103. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object...
```

**复现路径（To Reproduce）**

在仓库根目录下运行`start:electron`

或前往`tools/electron`下运行README所提及的命令

**预期表现（Expected behavior）**

运行之后，打开electron版opensumi下的终端，将会出现如下图所示的错误

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/28241963/171606661-056fcde3-6ec8-49eb-8ac5-1ed6bba73960.png)

![image](https://user-images.githubusercontent.com/28241963/171606676-6f138e4b-5f2f-42c5-afec-7b359155681c.png)

**环境信息（Environment）**

- OS: Windows11 Pro 22000.708
- Node: v14.19.3
- Browser: electron 
- OpenSumi Version: main branch until cd7aa15464d7fbcacf687cbe9bb9c51a075ad6c3

**Comment by yantze** [comment]
1. 使用 force 去 rebuild 下 `npm run rebuild-native -- --force-rebuild=true`
2. 如果有 tools/electron/app/node_modules ，删除一下再运行

**Comment by situ2001** [comment]
> 1. 使用 force 去 rebuild 下 `npm run rebuild-native -- --force-rebuild=true`
> 2. 如果有 tools/electron/app/node_modules ，删除一下再运行

试了试，不能work，还是提示一样的错误，请问有Windows机器跑起来的吗？

**Comment by yantze** [comment]
> > 1. 使用 force 去 rebuild 下 `npm run rebuild-native -- --force-rebuild=true`
> > 2. 如果有 tools/electron/app/node_modules ，删除一下再运行
> 
> 试了试，不能work，还是提示一样的错误，请问有Windows机器跑起来的吗？

可以的，你试试 https://github.com/opensumi/ide-electron 是否正常能运行起来，然后帮忙排查一下 tools/electron 有没有问题

**Comment by situ2001** [comment]
@yantze 我在`tools/electron`下运行`npx electron-rebuild -f -w node-pty`后即可正常工作

![image](https://user-images.githubusercontent.com/28241963/173113229-7da24c9e-bd29-416e-adcc-ba722b0f98ae.png)


参考自 https://github.com/electron/electron/issues/21065

以及 https://github.com/electron/electron-rebuild

**Comment by situ2001** [comment]
而我发现`npx electron-rebuild -f -w node-pty`之前并没有如下目录

![image](https://user-images.githubusercontent.com/28241963/173113532-617a0159-f44e-4f81-9b9d-101ecd90d625.png)

即使`rebuild-native.js`这里有用到该路径

https://github.com/opensumi/core/blob/5a5eec2eea61b41e64da846693efc7e90f40b680/tools/electron/scripts/rebuild-native.js#L25

**Comment by situ2001** [comment]
https://github.com/opensumi/ide-electron 默认也无法打开 但没有报错 而是显示`init...`

![image](https://user-images.githubusercontent.com/28241963/173115453-eab0c5dd-4464-4cfa-adf1-263a4605d914.png)

**Comment by yantze** [comment]
看起来应该是第一次使用 

> 而我发现 在执行`npx electron-rebuild -f -w node-pty`之前 并没有如下目录
> 
> ![image](https://user-images.githubusercontent.com/28241963/173113532-617a0159-f44e-4f81-9b9d-101ecd90d625.png)
> 
> 即使`rebuild-native.js`这里有用到该路径
> 
> https://github.com/opensumi/core/blob/5a5eec2eea61b41e64da846693efc7e90f40b680/tools/electron/scripts/rebuild-native.js#L25

这个看起来是你的执行环境不是 git-bash ，指定位置错误导致的 electron 头文件下载失败。晚点我修下。

**Comment by yantze** [comment]
> https://github.com/opensumi/ide-electron 的终端也无法打开 但没有报错 而是显示`init...`
> 
> ![image](https://user-images.githubusercontent.com/28241963/173115453-eab0c5dd-4464-4cfa-adf1-263a4605d914.png)

已经提交到 ide-electron main 分支，使用 yarn 进行安装依赖吧。是第三方依赖包升级导致的异常。
