### ISSUE TITLE
[BUG] 先 focus 搜索输入框，此时刷新页面，重新加载后编辑器内的上下方向键无法使用了

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#1203]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

https://user-images.githubusercontent.com/20262815/173488987-9a057d3a-083f-4e36-97ad-1812a630b58b.mp4

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by tyn1998** [comment]
问题能被复现，我想尝试解决一下~

**Comment by tyn1998** [comment]
问题应该被锁定了：

1. 当搜索框处于selected状态时重载页面的话，与搜索框相关的keybinding仍然是enable状态（搜索框中的上下键为切换搜索历史）
2. 于是导致了bingings中该binging是enable状态，该binding执行完直接return true
3. 从而导致“cursorDown/Up”根本没有机会被执行。

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/32434520/174035984-eea2c948-1a7d-4973-a2ec-6f2abf94fcf9.png">

maintainers们有没有一些提示或建议，我可以fix下提PR上来~

**Comment by tyn1998** [comment]
谢谢 @bytemain  的提示！我捣鼓捣鼓

**Comment by tyn1998** [comment]
新发现：

- OpenSumi会将UIState存储到localStorage，每次重载页面会读本地的UIState恢复现场
- 于是问题变成了目前恢复现场“不够到位”，虽然UIState.isSearchFocus是true，但是实际上UI中的搜索框没有被focus

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/32434520/174071539-ccf831b3-9848-441c-94b7-83dd401d4a8b.png">

解决思路：

- 个人认为最好能够做到准确恢复现场，即当`UIState.isSearchFocus === true`时，重载页面恢复现场的时候就把光标focus在搜索框中，而不是editor中


大家怎么看？

**Comment by bytemain** [comment]
isSearchFocus 确实是可以不存的，就这样做吧

**Comment by bytemain** [comment]
所以这里的 browserStorageService 存储的时候看看怎么优化一下，或者把 isSearchFocus 从 UIState 中挪出来单独放一块

**Comment by tyn1998** [comment]
收到~我想想思路，然后发在这儿，到时候 @bytemain 帮忙把把关~
