### ISSUE TITLE
[BUG] 引入#1205后连续reload两次会“忘记”session信息

### ISSUE THREAD

**Issue by tyn1998** [opensumi/core#1216]
**描述你的问题（Describe the bug）**

在引入 #1205 后，连续reload两次，OpenSumi就：
- “忘记”了哪些文件是已经被打开了的
- 还会“忘记”上次的layout，即上次左侧在搜索界面，但是reload两次后到默认的explorer界面了

**复现路径（To Reproduce）**

1. 连续刷新页面两次

**预期表现（Expected behavior）**

无论reload多少次，每次都能正确恢复上次关闭时的现场：
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/32434520/174466724-ad28722c-2947-4fdb-b298-8f92a6c48cb7.png">

**问题截图（Screenshots）**

连续reload两次，表现为session信息丢失：
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/32434520/174466745-82b12352-4250-4dad-aded-789a006633f2.png">

**环境信息（Environment）**

- OS: macOS 11.2 Apple M1
- Browser: chrome, safari
- OpenSumi Version: https://github.com/opensumi/core/commit/5162259e49e163eda1dd4dbf6209ec1daf788950 or later

**补充信息（Additional context）**

checkout到 #1205 之前的版本是没问题的。

**Comment by tyn1998** [comment]
用`npm run start:electron`起的electron端没有这个问题。

**Comment by erha19** [comment]
我来看一下这个问题
