### ISSUE TITLE
monaco 配置 `overflowWidgetsDomNode` 导致 hover 出现问题

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#124]
#105 会出现鼠标无法移动到 hover 的 widget 上，https://github.com/microsoft/monaco-editor/issues/2156 这个 issue 解释了为什么。

related:

- https://github.com/microsoft/monaco-editor/issues/2156
- https://github.com/microsoft/monaco-editor/issues/2233

**Comment by erha19** [comment]
close by #1676.
