### ISSUE TITLE
[FEATURE] 提供 contributes 的 Opensumi Extension API 的代码片段语法提示

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#1249]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

例如
![image](https://user-images.githubusercontent.com/20262815/176406451-f7d84972-a108-491b-b721-694feed32175.png)

对于插件开发来说，可以通过代码片段就能知道我们提供了哪些 contribute 可以注册

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
kaitianContributes 需要提供以下代码片段
- [ ] browserViews
- [ ] menu-extend
- [x] menubars
- [x] submenus
- [ ] toolbar

目前仅有 menubars 和 submenus

**Comment by Ricbet** [comment]
新增 browserViews 的 code snippet

https://user-images.githubusercontent.com/20262815/176864275-49d498d9-98ab-4f70-9a3f-97c6ccc0bc23.mp4

**Comment by Ricbet** [comment]
由于需要待补充的 contributes 代码片段实在太多了，该 issue 以及对应的 pr 暂时先解决 kaitianContributes 下的所有可填写字段的 code snippet，后续 vscode 本身的 contribute 另开 issue 解决

剩下待补充的 code snippet 有
- [ ] browserMain
- [ ] nodeMain
- [ ] workerMain
- [ ] menubars(改进)
- [ ] menus
- [ ] viewsProxies
- [ ] toolbar

**Comment by Ricbet** [comment]
toolbar contributes 的 code snippet 优化

1. 简化填写 actions 项时的步骤
![image](https://user-images.githubusercontent.com/20262815/177151819-cf73479c-39b0-4bb0-b8fd-74cfaf2022b2.png)

2. 自动补全 type 为 button 或 select 时不同的必填项
![image](https://user-images.githubusercontent.com/20262815/177153152-a9ab84de-924a-44be-ab8d-41564969a3f2.png)

3. 所有字段添加必要的描述或枚举项
![image](https://user-images.githubusercontent.com/20262815/177151991-55d12ea6-5df9-46e3-abaf-f02b35acb051.png)

PS: 目前还没做的是根据客户端环境（web or electron）来动态调整 preferredPosition location 的枚举项，根据下方文档描述，枚举项的值是和环境相关的
![image](https://user-images.githubusercontent.com/20262815/177153832-bdce972b-d503-4d2b-805a-25868ede8390.png)

**Comment by bytemain** [comment]
Thanks a lot! it was so fantastic!

**Comment by Ricbet** [comment]
> 由于需要待补充的 contributes 代码片段实在太多了，该 issue 以及对应的 pr 暂时先解决 kaitianContributes 下的所有可填写字段的 code snippet，后续 vscode 本身的 contribute 另开 issue 解决
> 
> 剩下待补充的 code snippet 有
> 
> * [x]  browserMain
> * [x]  nodeMain
> * [x]  workerMain
> * [x]  menubars(改进)
> * [ ]  menus
> * [x]  viewsProxies
> * [x]  toolbar

考虑到既然支持了 menus，再多加一个 submenus contributes
- [ ] submenus
