### ISSUE TITLE
docker 启动 opensumi 如何设置访问密码

### ISSUE THREAD

**Issue by hausen1012** [opensumi/core#1250]
我想要一个如 basic 认证那样的功能，这样能让我感到更安心

**Comment by erha19** [comment]
@hausen1012 目前我们的示例项目只展示最基础的功能，如果你需要做认证相关的能力，比较建议你通过集成侧的代码去实现，如在自己实现的 Server 层做密码认证，然后通过后再调用 `renderApp` 方法展示编辑器。

针对 WS 通信的鉴权服务，我们 2.19 版本会上线一个简化的版本，可以看这里跟进 https://github.com/opensumi/core/pull/1228

**Comment by erha19** [comment]
@hausen1012 这个 Issue 先关闭了，有其他问题可以单独再提 ~
