### ISSUE TITLE
[BUG] 使用 docker 方式安装后无法安装插件

### ISSUE THREAD

**Issue by hjue** [opensumi/core#1252]
使用 docker 方式安装后无法安装插件

**复现路径（To Reproduce）**
1. 使用 docker 方式安装 sumi，docker run --rm -d  -p 8080:8000/tcp ...
2. 通过 web 访问 ip:8080
3. 选择镜像市场，安装 python 插件

**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/1135045/176587954-921235a8-574b-4966-bd38-15766acff48c.png)

打开chrome dev-tools，网络中有访问主机:8899端口，而 docker 启动命令中并未映射8899端口

**Comment by erha19** [comment]
@Aaaaash 帮忙看下，看起来是 docker 内没有启动 webview server
