### ISSUE TITLE
[Bug] 在 ide-electron 中,git日志报错. --enable-proposed-api vscode.git. 

### ISSUE THREAD

**Issue by mu-fumi** [opensumi/core#1306]
**描述你的问题（Describe you question here）**
复现路径（To Reproduce）

git clone https://github.com/opensumi/ide-electron.git 
yarn
yarn build
yarn rebuild-native -- --force-rebuild=true
yarn download-extension 
yarn start

启动后,点击打开带有git仓库的目标文件夹, git 输出开始报错

问题截图（Screenshots）

![1657531597979](https://user-images.githubusercontent.com/22007967/178233411-a204fd08-2d93-4371-89c7-8be93a702686.jpg)

预期表现（Expected behavior）

可以像 opensumi/core 项目中,启动 npm run start 后,网页版效果,可以实时读取git仓库文件变动

![1657531843879](https://user-images.githubusercontent.com/22007967/178234230-f8cfa394-f8fb-4c81-9711-f7af6c06c2be.jpg)

**Comment by erha19** [comment]
@mu-fumi yarn start 的时候是不是有什么报错？提供一下，看起来是插件进程没有正确启动

**Comment by mu-fumi** [comment]
看起来启动没有报错
![1657533907457](https://user-images.githubusercontent.com/22007967/178240762-1427322d-de2e-4e56-9a00-4fb258b4b7a4.jpg)

但是在程序端就会报 git 无法读取打开文件夹,且左边的分支图标等都没有加载
![1657534032532](https://user-images.githubusercontent.com/22007967/178241133-669800da-fc05-4936-bd5d-1a76f0781787.jpg)

**Comment by yantze** [comment]
看起来 git 插件太新了，目前降会仓库里面的版本就好了

**Comment by mu-fumi** [comment]
谢谢!  问题解决了
我换成了 1.54.0 

`
      "vscode": [
        {
          "name": "git",
          "version": "1.54.0"
        },
        {
          "name": "git-ui",
          "version": "1.54.0"
        },
        {
          "name": "git-base",
          "version": "1.54.0"
        }
      ]
`
git 插件运行正常

![1657590488023](https://user-images.githubusercontent.com/22007967/178391418-fce7cba1-457f-4a68-bcad-08abdb0eac4c.jpg)

建议更改  ide-electron 仓库内的插件版本号
