### ISSUE TITLE
[BUG] 设置里改变终端 cursor style，但当前已打开的终端的样式还是没有变

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1318]
改变终端的 Cursor Style，不会反映到当前已打开的终端上：
<img width="366" alt="CleanShot 2022-07-12 at 12 06 23@2x" src="https://user-images.githubusercontent.com/13938334/178406532-a6b37f23-9d10-4b4c-b065-2244107a6171.png">
<img width="365" alt="CleanShot 2022-07-12 at 12 06 07@2x" src="https://user-images.githubusercontent.com/13938334/178406534-92c07530-78e7-4490-977f-10cbdb5147b2.png">

而且 VSCode 上的叫 line，我们的叫 bar

**Comment by life2015** [comment]
👌🏻，我处理下，今天PR
