### ISSUE TITLE
[BUG] Outline 开启光标跟随后，将 Outline 上的选中态上下滑动到可视区域外，再点击相同区域，此时 Outline 没有回到可视区域

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1323]
**描述你的问题（Describe the bug）**
详看视频，将 Outline 此时的选中移出可视区域，然后在编辑器中选中该位置，Outline 没有跳转。

https://user-images.githubusercontent.com/13938334/178413842-542a312d-0c0c-414c-aafb-7fa83e80cada.mp4

**Comment by erha19** [comment]
@bytemain 这个目前是 byDesign，如果选择的语法块跟上次一致的话，是不会再触发定位的命令的
