### ISSUE TITLE
[BUG] electron 下调试悬浮窗的位置不对

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1324]
期望展示的位置应该是 tab 栏以下，如：
<img width="1247" alt="CleanShot 2022-07-12 at 13 21 04@2x" src="https://user-images.githubusercontent.com/13938334/178414592-f56ff3b1-baa6-42d1-a2b2-a6b549f90bc3.png">

实际展示效果是直接在顶部的状态栏了
<img width="1073" alt="CleanShot 2022-07-12 at 13 22 13@2x" src="https://user-images.githubusercontent.com/13938334/178414653-cfd837ee-1ebc-4b40-a452-03997bf15a99.png">
<img width="1138" alt="CleanShot 2022-07-12 at 13 22 08@2x" src="https://user-images.githubusercontent.com/13938334/178414657-2a5234f9-2ea5-4d27-a762-536bf0ac970d.png">

**Comment by erha19** [comment]
这个在 Electron 环境下应该设置一下新的顶部高度
