### ISSUE TITLE
[FEATURE] 关于支持 tauri 的几个前置条件

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1337]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

1. [ ] 升级到 webpack 5，明确区分 Node.js 模块以及 mock 部分
2. [ ] 治理 Electron  webContents 以及 BrowserWindow 的 id 混乱问题，涉及 menu 以及 preload 
3. [ ] 整合 electron-basic 和 core-electron-main 为一个包

有其它问题可以在后面评论

**Comment by erha19** [comment]
目前看 tauri 对于纯前端的应用感觉友好一些，对于那些基于 NodeJS API 实现的功能可能存在不少兼容性问题，这块应该是最花时间的部分。
