### ISSUE TITLE
[Bug] Global locale doesn't change the entire language

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1338]
### Discussed in https://github.com/opensumi/core/discussions/1332

<div type='discussions-op-text'>

<sup>Originally posted by **nguyenhongphat0** July 12, 2022</sup>
I tried to set the global locale when the app initialized:

```ts
export class ProjectSwitcherContribution  implements ClientAppContribution {
  initialize() {
    setLanguageId('en-US');
  }
}
```

And it's working with the most of the IDE, excepts for these commands:

<img width="1112" alt="Screen Shot 2022-07-12 at 19 11 59" src="https://user-images.githubusercontent.com/29925961/178486970-bb26ce04-c115-4a5b-aab3-421f4e0593e4.png">

I'm not sure what is that module, and how can change the language of it to English? Sorry that I don't know Chinese, and my target users of the IDE neither!
Thank you!</div>

**Comment by bytemain** [comment]
done by https://github.com/opensumi/core/pull/1341
