### ISSUE TITLE
[BUG] 新建文件后 ctrl + s 保存 网页会崩溃

### ISSUE THREAD

**Issue by dabaoshu** [opensumi/core#1358]
**描述你的问题（Describe the bug）**

新建文件后 ctrl + s 保存 网页会崩溃
**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@dabaoshu 有使用的版本以及项目信息吗？无法复现你这个问题

**Comment by dabaoshu** [comment]
windows环境  master分支最新版本
