### ISSUE TITLE
[BUG] 删除文件无效

### ISSUE THREAD

**Issue by relife957** [opensumi/core#1364]
**描述你的问题（Describe the bug）**

opensumi版本2.18.10-next-1657724169.0， 编译部署到docker中
当对文件使用删除时，console会报错，对应方法为`file-tree-model.service.ts#deleteFileByUrls`
本地调试启动（yarn start）没问题，

**复现路径（To Reproduce）**

1. opensumi-ide-startup项目，使用版本2.18.10-next-1657724169.0
2. build后部署到docker中，远程访问，删除文件无效，cosole报错

**预期表现（Expected behavior）**

可以删除成功

**问题截图（Screenshots）**

![截屏2022-07-18 11 45 54](https://user-images.githubusercontent.com/27293981/179443118-93f7c1b4-b816-4bac-9d34-a78eda1db4cc.png)

![截屏2022-07-18 11 46 38](https://user-images.githubusercontent.com/27293981/179443136-4e94e941-3e06-467c-b4b4-6e2042242acc.png)

**环境信息（Environment）**

- OS: docker部署
- Browser: chrome
- OpenSumi Version: 2.18.10-next-1657724169.0

**补充信息（Additional context）**

本地yarn start 有效

**Comment by erha19** [comment]
@relife957 是否可以在前端断点看一下，报错的这行 `t` 变量的值

**Comment by relife957** [comment]
> @relife957 是否可以在前端断点看一下，报错的这行 `t` 变量的值

@erha19 t是空数组
![截屏2022-07-18 13 37 40](https://user-images.githubusercontent.com/27293981/179450817-4386e9d2-be9e-432f-b8d5-e74505f34ddd.png)
，

**Comment by relife957** [comment]
有时候走到分支77034行else if，有时候走到77036行else，删除同一个文件

**Comment by erha19** [comment]
@relife957 你用的是否为 ide-startup 标准工程？我这边试了一下没有遇到这个问题，如果是修改后的，请提供一下修改后的内容可以帮你看一下问题

**Comment by relife957** [comment]
好的，我自己再检查下

**Comment by relife957** [comment]
> @relife957 你用的是否为 ide-startup 标准工程？我这边试了一下没有遇到这个问题，如果是修改后的，请提供一下修改后的内容可以帮你看一下问题

大佬解决了，需要构建build的时候的workspace_dir和运行时的workspace_dir环境变量一样，我这边是分开进行的，所以会异常
