### ISSUE TITLE
[BUG] 修改文件 OpenType 后无法返回正常的代码展现

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1368]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/9823838/179469725-c65e7622-9fbc-45b0-990f-ce1949ba2572.png)

**复现路径（To Reproduce）**

打开一个 MD 文件，修改为视图展示后，再次切换，无法切换回代码视图

**预期表现（Expected behavior）**

正常切换

**Comment by Ricbet** [comment]
@erha19 这个是不是可以 close 掉了
