### ISSUE TITLE
使用Docker 镜像安装https 运行报错

### ISSUE THREAD

**Issue by hjue** [opensumi/core#1370]
使用docker方式安装 运行后，https 访问主机端口，浏览器控制台报错如下图

![image](https://user-images.githubusercontent.com/1135045/179478503-8fd79681-840c-4c71-9a57-b5ae0d149561.png)

错误信息如下：
bundle.js:2 Mixed Content: The page at 'https://xxx/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxx/service'. This request has been blocked; this endpoint must be available over WSS.

如何设置opensumi 启用 wss ?

**Comment by erha19** [comment]
@hjue 这里改一下就行了 https://github.com/opensumi/ide-startup/blob/9d02f578b35db2a76d32cb22335242d21d694090/src/browser/render-app.ts#L22 ， 有一个 wsPath 的参数
