### ISSUE TITLE
[BUG] core/tools/electron 运行错误

### ISSUE THREAD

**Issue by songhn233** [opensumi/core#1393]
**描述你的问题（Describe the bug）**

`ide-electron` 可以正常运行（需要删除 `yarn.lock` 重新解析依赖）

`core/tools/electron` 运行流程：

```sh
cd ...
npm i
npm run init

cd tools/electron
npm i
npm run link-local
npm run build
npm run rebuild-native -- --force-rebuild=true
npm run start
```
在 link 后 build 时有部分 warning：

```sh
WARNING in xx/opensumi/node_modules/ws/lib/validation.js
    Module not found: Error: Can't resolve 'utf-8-validate' in 'xx/opensumi/node_modules/ws/lib'
```

rebuild-native：

<img width="740" alt="image" src="https://user-images.githubusercontent.com/47357585/179944111-b76ecfa4-ab23-4f56-a648-b5866d897a30.png">

Start log：

<img width="716" alt="image" src="https://user-images.githubusercontent.com/47357585/179944308-54ef1acc-788c-4892-990c-dd381e2906dc.png">

窗口输出：

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/47357585/179944385-da13106a-e5f8-4caa-88b7-a90a853007d2.png">

**环境信息（Environment）**

- OS: macOS 12.4 Apple M1
- Browser: electron
- Node: 14.19.3
- npm: 6.14.17
- yarn: 1.22.19

**Comment by erha19** [comment]
@yantze @bytemain 帮忙看下这个项目运行的问题

**Comment by bytemain** [comment]
![CleanShot 2022-07-25 at 12 03 05@2x](https://user-images.githubusercontent.com/13938334/180696595-3ceed18a-a94c-46f8-96a2-43066f7caeb5.png)

似乎是 arch 不对，是不是在 arm64 的 arch 上装了 x64 的 Node？
因为最后的 electron 是根据系统的 arch 来判断的。

可能是 arm64 的 electron 运行了 x64 的 native module

执行一下

```
node -p "process.arch"
```

看看结果

<img width="304" alt="CleanShot 2022-07-25 at 12 05 27@2x" src="https://user-images.githubusercontent.com/13938334/180696827-53adb542-ca61-40a6-942c-f2ce51a6982e.png">

**Comment by songhn233** [comment]
@bytemain 

嗯，因为之前在 node 16 下 `npm run init` 一直有问题，所以是在 14 下运行的

node 14 应该没有 arm 版本只有 x86 吧

如果只是 `tool/electron` 在 16 下构建的话，`build native` 会正常返回 ok，可以挂载（能使用 devtool）但是初始化还是有问题

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/47357585/181333844-b3fb9b2a-1db4-4784-83ef-753673583ac7.png">


但是如果 core 在 16 下重新 `install && init` 的话则也会报错

<img width="675" alt="image" src="https://user-images.githubusercontent.com/47357585/181335820-cf7b9842-36eb-4b73-89b1-8a28bf3371cb.png">

arm 下有什么合适的方案来处理这种情况吗 😂

**Comment by yantze** [comment]
@songhn233 第一个 devtools 里面的截图是 core 中的代码有问题，你直接更新到最新的版本就好了。第二个目前是 core 对 Node.js 16 支持不太好，先避免用 16 吧。

**Comment by songhn233** [comment]
> @songhn233 第一个 devtools 里面的截图是 core 中的代码有问题，你直接更新到最新的版本就好了。第二个目前是 core 对 Node.js 16 支持不太好，先避免用 16 吧。

因为是在 core 的 `tools/electron` 里运行的, 所以应该没有更新的说法

devtools 这个截图就是 core 用 14 然后 `tools/electron` 用 16 的报错情况

如果都用 14 的话 electron native 编译会出问题, devtools 也起不来这样

**Comment by yantze** [comment]
> > @songhn233 第一个 devtools 里面的截图是 core 中的代码有问题，你直接更新到最新的版本就好了。第二个目前是 core 对 Node.js 16 支持不太好，先避免用 16 吧。
> 
> 因为是在 core 的 `tools/electron` 里运行的, 所以应该没有更新的说法
> 
> devtools 这个截图就是 core 用 14 然后 `tools/electron` 用 16 的报错情况
> 
> 如果都用 14 的话 electron native 编译会出问题, devtools 也起不来这样

就拉一下最新的 core 代码即可，就这个问题导致的 https://github.com/opensumi/core/pull/1428

**Comment by tyn1998** [comment]
+1，新clone了一遍按照流程来复现了同样的问题，web端没问题的。

环境：
- macOS Monterey M1
- Node v14.17.6

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/32434520/181908524-b2760d7c-09b9-4617-89a6-ff0eca9765dd.png">

**Comment by songhn233** [comment]
+1

在拉取了最新的代码后还是类似的问题

<img width="514" alt="image" src="https://user-images.githubusercontent.com/47357585/182039216-e18c0d8c-9464-4599-93d6-0947b46c447d.png">

因为在 node14 下 electron rebuild native 不能正常执行，运行也是报错

在 node16 下错误和之前一致 /cc @yantze

**Comment by tyn1998** [comment]
我这在tools/electron下运行`npm run rebuild-native -- --force-rebuild=true`是可以执行且没报错的（看着应该没错吧），但也是黑屏。

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/32434520/182052117-f83d853c-a88c-43c0-b7d1-8691b3299b1c.png">

...

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/32434520/182052138-098bf400-c65e-4e04-9fec-2a469ed7df0a.png">

**Comment by yantze** [comment]
这个 pr 合到了 2.19 分支，还没回源，先切换到 2.19 分支运行 https://github.com/opensumi/core/pull/1428 @songhn233 @tyn1998 

@erha19 需要提交一个到 main 分支

**Comment by tyn1998** [comment]
亲测可行：

1. 检出v2.19分支
2. cd tools/electron
3. npm run build
4. npm run rebuild-native -- --force-rebuild=true
5. npm run start

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/32434520/182056242-f2ed685b-6415-4d3c-af1b-eca6eca309b1.png">

**Comment by erha19** [comment]
@yantze @tyn1998 @songhn233 相关代码已回源至 main, 可以再试试

**Comment by tyn1998** [comment]
@erha19，竟然还是不行，黑屏了。步骤是：

1. 检出main分支，并且git pull upstream main
2. cd tools/electron
3. npm run build
4. npm run rebuild-native -- --force-rebuild=true
5. npm run start 得到黑屏

之后我又切回v2.19做了之前同样的操作，结果v2.19也黑屏了，很奇怪！

**Comment by erha19** [comment]
@tyn1998 大概率还是用 arm64 的 electron 去运行了带 x64 原生依赖的代码，检查一下使用的 Node 版本，如果是 14，可以用 `nvm` 的 `nvm install 14 -s` 命令去安装 arm64 版本，然后运行在项目根目录下下面脚本：

```
npm i
npm run init
npm run start:electron
```
我这边试了是可以跑起来的

**Comment by tyn1998** [comment]
@erha19，运行了`npm run init` 和 `npm run start:electron`就可以了！

我的node的确是用nvm装的14.17.6。所以应该还是我没重新运行`npm run init`的缘故。
