### ISSUE TITLE
[FEATURE] Tree Drag API

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#1402]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

- [ ] TreeDragAndDropController
- [ ] dragAndDropController
- [ ] DataTransfer
- [ ] DataTransferFile
- [ ] DataTransferItem

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
测试案例：https://github.com/microsoft/vscode-extension-samples/tree/drop-file-transfer
