### ISSUE TITLE
[FEATURE] Terminal Location API

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#1406]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

- [x] TerminalEditorLocationOptions
- [x] TerminalLocation
- [x] TerminalOptions.location
- [x] TerminalOptions.isTransient
- [x] TerminalSplitLocationOptions
- [x] ExtensionTerminalOptions.location
- [x] ExtensionTerminalOptions.isTransient

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by bytemain** [comment]
看了下，这个的空实现等于没实现。
我先假装我们支持这个功能，我各处加加吧
