### ISSUE TITLE
[FEATURE] SourceControl enabled

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#1407]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
这里的 API 我在 https://github.com/opensumi/core/pull/1702 应该已经实现掉了，支持了 SourceControl#ActionButton 相关 API
