### ISSUE TITLE
[BUG] 编辑器切换 Tab 后不会自动 Focus 到编辑器导致部分快捷键不可用

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1414]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/9823838/180346837-ca6e4aa9-3c1f-47d6-8e77-d5bcab811013.png)

**复现路径（To Reproduce）**

切换 Tab，按下 Cmd+F，无法呼出搜索功能

**预期表现（Expected behavior）**

正常聚焦，正常使用快捷键

**Comment by Aaaaash** [comment]
closed #1448
