### ISSUE TITLE
补全列表使用鼠标选择会自动去掉 "." 符号

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#143]
![CF1FBAEB-F85F-4DA6-B31E-F7EB024D672A](https://user-images.githubusercontent.com/20262815/146516729-a5e1e2fa-ef2f-4113-8bc3-07fdcd770253.gif)

**Comment by Ricbet** [comment]
之前针对 completion 做的体积优化主要做了以下两个事情

1. 在 provideCompletionItems 阶段去掉了 insertText 等字段
2. 再在 resolveCompletionItem 阶段补充剩余的所有字段，包括 insertText。

实测证明鼠标的点击是会走到 resolveCompletionItem 阶段的，出现该问题的原因就是鼠标事件优先于 resolveCompletionItem 阶段的触发，点击后文本已经写入，而后再触发也就没用了

![image](https://user-images.githubusercontent.com/20262815/146519201-69db4f30-81b7-4f59-a705-1a61a3d9d2c6.png)

**Comment by Aaaaash** [comment]
em, 所以点击时要先 `resolveCompletion` 一下

**Comment by Ricbet** [comment]
> em, 所以点击时要先 `resolveCompletion` 一下

你 say 的 right

**Comment by Ricbet** [comment]
monaco 内部使用 suggetController 来做 completion 的处理，其中它的 suggestWidget 有四个事件
![image](https://user-images.githubusercontent.com/20262815/146705390-d88f5c65-2a4c-4469-b20f-f4fdac7aba31.png)

1. 在上下选择的时候走的是 onDidFocus 事件
2. 鼠标直接点击走的是 onDidSelect 事件

而 suggestController 内部这两个事件对 resolveCompletion 的处理逻辑不一样

focus 事件是会去同步 resolve
![image](https://user-images.githubusercontent.com/20262815/146705895-de5f9480-b142-49d9-99b6-48393dcf054b.png)

而 select 不会
![image](https://user-images.githubusercontent.com/20262815/146705950-b5d8d8d8-6b37-4d23-8898-8fbceac8a9cf.png)

**Comment by Aaaaash** [comment]
by design 还是 bug? 我猜是 bug

**Comment by Aaaaash** [comment]
但我看了下 onDidSelect 事件监听直接走了_insertSuggestion，这里面是有 resolve 的，可能是某个条件导致没走到那个分支里？

**Comment by Ricbet** [comment]
> 但我看了下 onDidSelect 事件监听直接走了_insertSuggestion，这里面是有 resolve 的，可能是某个条件导致没走到那个分支里？

是有，但它是异步的，且主要是用来处理 additionalTextEdits 的

**Comment by Aaaaash** [comment]
em, 确实，所以要么把 insertText 放回去，要么转换成 additionalTextEdits ?

**Comment by Ricbet** [comment]
> em, 确实，所以要么把 insertText 放回去，要么转换成 additionalTextEdits ?

您是说 provideCompletionItems 阶段把 insertText 都转成 additionalTextEdits 吗

**Comment by Aaaaash** [comment]
> > em, 确实，所以要么把 insertText 放回去，要么转换成 additionalTextEdits ?
> 
> 您是说 provideCompletionItems 阶段把 insertText 都转成 additionalTextEdits 吗

是的

**Comment by Ricbet** [comment]
已修复: https://github.com/opensumi/monaco-editor-core/pull/5
