### ISSUE TITLE
[BUG] 已删除的文件内容依然可以在搜索面板搜到

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1438]
**描述你的问题（Describe the bug）**

已删除的文件内容依然可以在搜索面板搜到

**复现路径（To Reproduce）**

删除一个文件 -> 搜索文件内容

**预期表现（Expected behavior）**

已删除的文件不应该出现在搜索内容中

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/9823838/181473909-95e70253-b0b6-4678-b03d-57132c5dcc1e.png)

**Comment by Aaaaash** [comment]
https://github.com/opensumi/core/pull/1979
