### ISSUE TITLE
希望实现文件列表属性过滤，例如按“我创建的”、文件业务状态（代码检查结果：正常、异常），希望框架可提供扩展支持。

### ISSUE THREAD

**Issue by ainflying** [opensumi/core#1442]
团队开发的情况下，希望实现文件列表属性过滤，例如按“我创建的”、文件业务状态（代码检查结果：正常、异常），希望框架可提供扩展支持。
1、能否从本地缓存 直接实现文件属性过滤功能。
2、能对接业务数据库，实现文件属性过滤功能。

**Comment by erha19** [comment]
@ainflying 该功能建议通过 TreeView API 实现相关的插件面板实现，框架层默认不会支持业务属性的功能
