### ISSUE TITLE
新增增加性能扩展机制的说明

### ISSUE THREAD

**Issue by ainflying** [opensumi/core#1443]
这个框架的性能扩展机制，可否也在文档上完善下？
这个也是框架的核心竞争力之一。
包括是否支持集群部署？（部署集群后，一些功能，如版本比对是否就用不了？）
并发数超过一定阀值后，增加集群数量后，需要做那些工作？

**Comment by hacke2** [comment]
一般做 Cloud IDE 都会基于 K8s 之类的容器编排服务来编排你的工作空间（Pod）。Pod 里运行了 OpenSumi 的 Server 端，让前端可以通过 WebSocket 来通信。
为了更好的隔离性，一般是通过人+项目维度来创建这个 Pod，一个 Pod 可以有一个 Container，也可以有多个 Container。
人和工作空间的是一对多的关系，如果有协作功能，可能就是多对多的关系。Pod 是横向扩展的，可以在上层应用做写同时运行个数的限制。一般 Pod 也是有生命周期，比如多久没有前端通信则需要停止这个 Pod，然后回收。不同场景有不同的生命周期，这里主要描述的是代码仓库这个场景的生命周期。
