### ISSUE TITLE
[BUG] Debug session not firing `stop` event(s)

### ISSUE THREAD

**Issue by nguyenhongphat0** [opensumi/core#1444]
**描述你的问题（Describe the bug）**

I'm launching a debug session like below 👇 
```tsx
const debugSession = await debugSessionManager.start({
  index: 1,
  configuration: {
    "name": "Debug Zalo Mini App",
    "request": "launch",
    "type": "chrome",
    "url": `http://localhost:${simulatorState.port}`
  }
})
```

After the debug session is stoped (by user clicking on the Stop button or closing the Chrome debug window), I need to handle some cleanup logics. However neither `debugSession.onDidStop` or `debugSession.on('stopped')` triggered.

More information: 
1. `debugSession.onDidChangeState` only fired when the state is `1` (`Initializing`). After closing the debug session, console.log tell me the `debugSession.state` was `0` (`Inactive`), but the event didn't fired that `0` state.
2. When testing with the code below 👇, only the `initialized` and `output` event working, I didn't managed to have the others (or at least the `exited`, `stopped` or `terminated` events) triggered. 
```tsx
[
  'breakpoint',
  'capabilities',
  'continued',
  'exited',
  'initialized',
  'loadedSource',
  'module',
  'output',
  'process',
  'stopped',
  'terminated',
  'thread',
  'progressStart',
  'progressUpdate',
  'progressEnd',
  'invalidated'
].forEach(event => {
  debugSession.on(event as any, (e) => {
    alert(event);
  })
})
```

**复现路径（To Reproduce）**

1. Launch a debug session 
```tsx
const debugSession = await debugSessionManager.start({
  index: 1,
  configuration: {
    "name": "Debug Zalo Mini App",
    "request": "launch",
    "type": "chrome",
    "url": `http://localhost:${simulatorState.port}`,
    "webRoot": "${workspaceFolder}",
    "runtimeArgs": [
      `--window-size=${simulatorState.device.viewport.width},${simulatorState.device.viewport.height}`,
      `--window-position=${bound.width},${bound.y}`,
      `--app=http://localhost:${simulatorState.port}`,
      "--remote-debugger-handles"
    ]
  },
  workspaceFolderUri: currentWorkspace
})
```
2. Click the red square Stop button
<img width="214" alt="Screen Shot 2022-07-30 at 15 51 34" src="https://user-images.githubusercontent.com/29925961/181903059-f7a0c0b3-8529-4b50-90d5-b8bcf05c3eda.png">

3. The stop event doesn't fired

**预期表现（Expected behavior）**

One of these `stop` or `terminated` event should have been fired. Or please tell me if there is something else I could do to known when a debug session is stoped.

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: MacOS 12.4 - M1 chip
- Browser: Electron
- OpenSumi Version: 2.18.9

**补充信息（Additional context）**

**Comment by erha19** [comment]
@nguyenhongphat0 thanks for your report, I'll try to fix it next week.

**Comment by nguyenhongphat0** [comment]
@erha19 thank you very much 🙏 You rock!

**Comment by erha19** [comment]
Hi @nguyenhongphat0, I just figured out your needs, on the `opensumi/core`, the `DebugSession` is designed for a channel to receive messages from the Debugger thread, so when you click the `stop` button, the Debugger thread will be closed with any message, this is what we expected.

In your case, you can use the `DebugSessionManagerService` to get all the Debug events triggered, see the codes here: https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/extension/src/browser/vscode/api/main.thread.debug.ts#L150

I hope this helps you, if you have any other questions, please feel free to ask.

**Comment by nguyenhongphat0** [comment]
Thank you very much @erha19, the above callback on `sessionManager` worked. I'm closing this issue now 🎉
