### ISSUE TITLE
什么时候opensumi能支持标准sql语句的高亮提示呢？[Question] 

### ISSUE THREAD

**Issue by jojogh** [opensumi/core#1445]
什么时候opensumi能支持标准sql语句的高亮提示呢？

或者这个功能如何可以拓展上去？

**Comment by erha19** [comment]
@jojogh 你可以在插件市场检索并安装相应的语法插件，如 `SQL Language Server` 等，对于语言的高亮支持大部分都是通过插件来支持的。

**Comment by jojogh** [comment]
好的，我如果要开发一个自定义编辑器，实现对sql的语法支持，这个我该如何操作？

**Comment by erha19** [comment]
@jojogh 建议看一下我们文档里面提供的案例，选择你期望实现的平台后实现就行了 https://opensumi.com/zh/docs/integrate/quick-start/web
