### ISSUE TITLE
[BUG] 可折叠展开视图（如侧边栏）上的Webview，在关闭再打开的时候，webview和主进程的通信机制丢失

### ISSUE THREAD

**Issue by shilin8805** [opensumi/core#1476]
**描述你的问题（Describe the bug）**

vscode插件在侧边栏（activitybar）上使用webview渲染一个视图界面，webview和主界面使用postMessage机制进行通信，当webview隐藏关闭后再打开，通信机制丢失，在vscode下没问题，在opensumi下出现该问题

**补充信息（Additional context）**
初步分析是下面监听视图隐藏后，把整个webview所在的iframe都销毁了，再重新显示后，未重新绑定消息监听事件
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/3340210/183243820-2951f893-c61a-4c82-9e8b-3a55a5c50ac1.png">

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/3340210/183243781-39fcdefa-8516-45f1-b8ab-a3ea0c977847.png">

**Comment by erha19** [comment]
@shilin8805 感谢反馈，这个问题我们看一下

**Comment by erha19** [comment]
@shilin8805 Done #1518, will be published on v2.19.7.
