### ISSUE TITLE
[BUG] 修改 launch.json 配置文件，调试管理器下拉框选项没有实时同步

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#1491]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/183800387-674bf9b8-3256-40c3-b9b6-c44e813df47b.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
文件服务异常，可能在  #1437 解决，可以后续观察一下 @Ricbet

**Comment by Ricbet** [comment]
新版 2.20 没复现这个问题，可 close
