### ISSUE TITLE
[Question] 如何能监听到websocket会话开启、断开以及重连的状态呢？

### ISSUE THREAD

**Issue by likuner** [opensumi/core#1494]
**描述你的问题（Describe you question here）**

需求是这样的，ide开启后会向java服务端发送心跳，以统计ide的使用时间，websocket断开后停止发送心跳，重连后再次发起心跳。目前没有找监听websocket状态钩子函数，想问目前openSumi提供了这方面的能力吗？

**Comment by erha19** [comment]
@likuner 你可以基于 EventService 去监听 WebSocket 的变化，相关事件见：
https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-common/src/connection.ts
用法上可以采用引入 `IEventService` 的方式来搞:

```ts
@Autowired(IEventBus)
 protected eventBus: IEventBus;

this.eventBus.on(BrowserConnectionCloseEvent, () => {})
```

另外也有装饰器的用法，可以框架代码里面搜一下 `@OnEvent`

**Comment by likuner** [comment]
@erha19 好的 谢谢！我尝试一下。

**Comment by erha19** [comment]
@likuner 那这个问题先关闭了，有其他问题再重新提一下 ~
