### ISSUE TITLE
[BUG] vscode API createWebviewPanel, ViewColumn.Beside 类型不兼容

### ISSUE THREAD

**Issue by jianghai** [opensumi/core#1505]
**描述你的问题（Describe the bug）**

使用 vscode.window.createWebviewPanel，当 viewColumn 定义成 ViewColumn.Beside 时会抛这个错误
Cannot read properties of undefined (reading 'modifiedEditor'

**复现路径（To Reproduce）**

```ts
import * as vscode from "vscode";
const { window, ViewColumn } = vscode;
const panel = window.createWebviewPanel(
  '',
  '新建页面2',
  // i18n.format('extension.iceworksMaterialHelper.materailImporter.title'),
  { viewColumn: ViewColumn.Beside, preserveFocus: true },
  {
    enableScripts: true,
    retainContextWhenHidden: true,
  },
);
```

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
尝试了一下这个代码，无法复现相关问题，@jianghai 看下是否是其他原因导致的？

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/9823838/184608252-350e3c8e-8b30-4fb6-a45a-152cfb0dc972.png">
