### ISSUE TITLE
[BUG] WebView 切换后通信异常

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#1510]
**描述你的问题（Describe the bug）**

WebView 切换后通信没有走到

临时解决：使用 retainContextWhenHidden 参数

https://user-images.githubusercontent.com/6399899/184606359-04454fb9-a080-45e1-9593-35223fba9051.mp4

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
看起来跟这个 #1476 是类似的问题

**Comment by hacke2** [comment]
OK，那关了吧
