### ISSUE TITLE
[BUG] Errors occur when saving files on the web side.

### ISSUE THREAD

**Issue by Necho-dev** [opensumi/core#1511]
**Errors occur when saving files on the web side**

- First, I create new files normally.

![Lenovo Browser](https://user-images.githubusercontent.com/38178217/184667000-9635c1a4-8f85-421f-a67b-4122a35e27fe.png)
↑↑↑ Lenovo Browser

![Edge](https://user-images.githubusercontent.com/38178217/184669147-a4692fa2-bc68-47b0-93a5-ddfe69602eaf.jpg)
↑↑↑ Edge

- When I want to save the file, an error occurred.

![Lenovo Browser](https://user-images.githubusercontent.com/38178217/184667380-55d24967-cb5f-4ec1-8feb-3f61a366e7b6.png)
↑↑↑ Lenovo Browser
![Edge](https://user-images.githubusercontent.com/38178217/184669068-fe856976-7147-4358-afec-4fa5b15d1be6.jpg)
↑↑↑ Edge

**环境信息（Environment）**

- OS: Windows11
- Browser: Edge & Lenovo Browser (All based on Chromium)
- OpenSumi Version: 2.19.6

**Comment by erha19** [comment]
same issue #1358.
