### ISSUE TITLE
[BUG] Antd 表单Select组件下拉项残留

### ISSUE THREAD

**Issue by fjb040911** [opensumi/core#1535]
**描述你的问题（Describe the bug）**
我用的 antd版本为 4.22.2， Windows环境，Mac环境还没尝试
当我的自定义编辑器视图中用到表单和 antd 的Select组件时， 类似[例子使用antd](https://github.com/opensumi/opensumi-module-samples/tree/main/modules/use-antd)用法
发现Select下拉后会出现下拉项残留。
1，焦点离开Select后下拉项看着还在页面上存在
2，实际dom已经不存在，但图像还在，所以怀疑跟View渲染逻辑有关系
现象不好描述，直接看下面截图更加好理解

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
![微信截图_20220818100441](https://user-images.githubusercontent.com/8717555/185276203-e51fdc94-f6b2-4194-ac10-58a1a47071ee.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by fjb040911** [comment]
![微信截图_20220818105434](https://user-images.githubusercontent.com/8717555/185283152-b7e59530-796b-42cb-8687-44411e958246.png)
可以确定是View渲染的问题

**Comment by erha19** [comment]
@fjb040911 是否可以在 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/use-antd 这里复现出这个问题？是否有指定  `getPopupContainer` 属性？

**Comment by fjb040911** [comment]
> 
hi，我在问题描述中已经说明，在 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/use-antd 里可复现
另外，指定了getPopupContainer 依然有问题

**Comment by erha19** [comment]
@fjb040911 好的，今天我看一下这个问题，看起来是 `getPopupContainer` 指定的节点需要进一步扩大到整个框架页面，目前应该只是指定到编辑器页面内，所以点击 Tab 不会被响应，有个基础思路是直接在全局 #main 节点上面挂载这个 getPopupContainer 属性，你可以先试试

**Comment by fjb040911** [comment]
> 
```
<Select 
     getPopupContainer={ triggerNode => triggerNode.parentNode || document.body }
     options={options} 
  />
```
如果代码如上所示，下拉项不会带到其他Tab中，但是依然残留在父组件中。或许我需要尝试看看有没手动收回下拉项的方法

**Comment by erha19** [comment]
@fjb040911 问题是解决了吗？

**Comment by fjb040911** [comment]
关闭此issue，因为这样看来是 antd ui组件的问题

**Comment by fjb040911** [comment]
> 
如果把 antd 中的 Select 组件 open 属性手动控制（点击选择框设置为 true，点击选项设置为 false）就不会有问题，但这会带来比较复杂的逻辑。所以这里我直接用 @opensumi/ide-component 中提供的 Select
