### ISSUE TITLE
[BUG] 文件目录不显示

### ISSUE THREAD

**Issue by iamxukai** [opensumi/core#1536]
**描述你的问题（Describe the bug）**
存放在 workspace 的文件目录不显示

**复现**

-  在 workspace 文件夹内存放项目内容

![lQLPJxaZ9F20c4XMrs0BdLA5tV1zvvEMgQL9TjIjAKEA_372_174](https://user-images.githubusercontent.com/85668115/185281169-e603cae2-c60e-4ea4-86d7-5cb02eb3b103.png)
路径（To Reproduce）

- `yarn run start` 运行 OpenSumi Core

**预期表现（Expected behavior）**
可以显示 workspace 的文件目录

**问题截图（Screenshots）**

![lQLPJxaZ9F7lnWrNA47NAZWwEoxr2dSZUOEC_U4yuIAnAQ_405_910 png_620x10000q90](https://user-images.githubusercontent.com/85668115/185280612-d16f76ec-e832-45d0-935b-a3438ba9025f.jpg)

**环境信息（Environment）**

- OS: Windows10
- Browser: edge
- OpenSumi Version: 2.19.7

**补充信息（Additional context）**

**Comment by bytemain** [comment]
我来看一下
