### ISSUE TITLE
[BUG] 工作区 file-tree 操作

### ISSUE THREAD

**Issue by songhn233** [opensumi/core#1556]
**描述你的问题（Describe the bug）**

指定任意类型工作区后，复制粘贴等文件交互操作失效

原因为 paste/cut 的 target，`fileTreeService.getNodeByPathOrUri` 返回结果为 undefined，直接退出。

**复现路径（To Reproduce）**

https://user-images.githubusercontent.com/47357585/185787986-0e95d45b-0cb4-4050-b43e-94ed992093fa.mov

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1]
- Browser: [e.g. chrome, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

Related to https://github.com/opensumi/core/issues/1259

**Comment by songhn233** [comment]
看了一下问题应该出在 compact mode 的 map 处理上，对于单 root 的情况下

<img width="439" alt="image" src="https://user-images.githubusercontent.com/47357585/185801429-3bb9af0a-ca17-4b9a-8042-754f6c49f9f8.png">

而 workspace 为 multi 的情况下，映射有问题

对于两个 root 的组合
<img width="222" alt="image" src="https://user-images.githubusercontent.com/47357585/185802258-736b814f-c069-4807-91d0-529b000b3fce.png">
两个 root 分别为 `home/opensumi/tools/workspace` 和 `google/Qualification Round 2020 - Code Jam 2020`

此时复制 code jam 下的 A.cpp，得到的 path 为 `/root_121/A.cpp`

但实际在 TreeMap 的结构为

![SCR-20220822-1a4](https://user-images.githubusercontent.com/47357585/185802511-3f0085f7-8a8c-44a1-ad52-11657f39ea0e.png)

所以直接返回了 undefined

**Comment by erha19** [comment]
@songhn233 这里的文件路径主要还是用于 Tree 内部维护，如果需要做复制粘贴场景，建议通过 fsPath 或文件本身 filestat 内的 uri 去传递，相关评论见：https://github.com/opensumi/core/issues/1259#issuecomment-1221699590

**Comment by songhn233** [comment]
> 如果需要做复制粘贴场景，建议通过 fsPath 或文件本身 filestat 内的 uri 去传递

@erha19 嗯，看了下这里原来的逻辑，对于复制的来源是可以采用 uri 方式然后利用 TreeAPI 的 copy/mv（内部还是通过 file-api 通用的对 from 和 to 进行操作）

但是对于 target 来说，还是依赖于 TreeModel，之前的情况是对于 paste 的 to 获取 `parent` 直接为 undefined

https://github.com/opensumi/core/blob/d0a2a788f35350a96fcdc7ae1cbe682ec7e05b03/packages/file-tree-next/src/browser/services/file-tree-model.service.ts#L1572-L1576

问题出在
https://github.com/opensumi/core/blob/d0a2a788f35350a96fcdc7ae1cbe682ec7e05b03/packages/file-tree-next/src/browser/file-tree.service.ts#L579-L604
对于
```js
// this.root.path 为映射的 root1
// 在 multi roots 情况下 rootUrl 实际为 root1/xx
// roots 情况为 root1/xx 和 root1/yy
// rootUri.relative(pathURI) 对于 xx/1.txt 得到 1.txt
// 所以最后组合为 root1/1.txt, 但真实结果是 roo1/xx/1.txt
if (rootUri.isEqualOrParent(pathURI)) { 
  path = new Path(this.root.path).join(rootUri.relative(pathURI)!.toString()).toString(); 
} 
```
改为
```diff
        if (rootUri.isEqualOrParent(pathURI)) {
          path = new Path(this.root.path)
+           .join(rootUri.displayName)
+           .join(rootUri.relative(pathURI)!.toString())
+           .toString();
        }
```

之后复制粘贴操作就可以正常工作了，这个 issue 可以等到 PR merge 后关闭，应该是 workspace 现存的问题

https://user-images.githubusercontent.com/47357585/187092653-57bc70d3-6567-4ad7-bf7a-c39228ad865e.mov

看到 `getFileTreeNodePathByUri` 其实也有类似的逻辑，通过 displayName 来拼接文件路径压缩

https://github.com/opensumi/core/blob/d0a2a788f35350a96fcdc7ae1cbe682ec7e05b03/packages/file-tree-next/src/browser/file-tree.service.ts#L430-L460

这是多工作区下的情况，对于多窗口的复制粘贴我准备采用和 multi roots 类似的处理，多加一个判断来模拟多 roots 的情况

> 具体来说对于 getNodeByPathOrUri 增加一个 flag 参数，在 paste 时判断当前没有待复制的文件同时 clipboard 有文件并且同意复制后开启这个 flag，和 `isMultipleWorkspace` 走类似的 case 处理

---

不过这其实有个额外的问题，我理解 Path 会进行 compact 路径压缩，通过 _root.path 存储，之后进行拼接，在普通单 root 模式下 root 本身和 rootUri 是一样的

但是 multi roots 情况下如果还是按照这种拼接逻辑，key 依赖 displayName 的话，不同 root 下是相同的 displayName，那 FileMap 应该就会获取到错误的结果（两个 workspace 的根文件夹同名或者多窗口情况下工作区同名的情况）

**Comment by erha19** [comment]
@songhn233 可以提个 PR 单独修复一下这个问题
