### ISSUE TITLE
[BUG] 自定义终端名称刷新后，自定义名称会被覆盖

### ISSUE THREAD

**Issue by DebugIsFalse** [opensumi/core#1562]
**描述你的问题（Describe the bug）**
初始化唤起终端名称
![image](https://user-images.githubusercontent.com/16201487/185878017-39f739a4-30cd-4449-b669-6b55e413b951.png)
刷新后终端名称被覆盖了
![image](https://user-images.githubusercontent.com/16201487/185877943-149f6a39-61ea-4cdf-8222-ddae551550cc.png)

**复现路径（To Reproduce）**
```js
// browser/service.ts
class BrowserPreviewService {
    @Autowired(ITerminalApiService)
    private readonly terminalApiService: ITerminalApiService;
    async createTerminal() {
        const terminalItem: Data = await this.terminalApiService.createTerminal({
            name: 'BrowserPreview'
        });
    }
}
```

**预期表现（Expected behavior）**
希望刷新前后，终端名称保持一致

**问题截图（Screenshots）**

**环境信息（Environment）**

所有版本都存在这个问题

**补充信息（Additional context）**

**Comment by life2015** [comment]
这是因为之前做了一个功能：终端widget的name会跟随着检测到的终端processName做动态的变化，有个前端逻辑用来保证用户指定的widget name是更高优先级的，但是在用户刷新之后这个前端状态会丢失，导致了这个case。
<img width="881" alt="image" src="https://user-images.githubusercontent.com/12879047/185882194-7dcf2a33-ba58-4cf1-a1b2-3452d422da84.png">
