### ISSUE TITLE
[BUG] 默认启动后，无法打开目录

### ISSUE THREAD

**Issue by baiyuxiong** [opensumi/core#1574]
**描述你的问题（Describe the bug）**

默认启动的时候控制台有报错，页面可以正常访问，但是无法打开目录
**复现路径（To Reproduce）**
执行完：
$ git clone git@github.com:opensumi/ide-startup.git
$ cd ide-startup
$ yarn					   # 安装依赖
$ yarn start		       # 并行启动前端和后端

这四个指令后，访问8080端口，此时控制台有报错
`
[log] ExtHostCommands#registerCommand git.rebaseAbort
[extHost:error] [Extension-Host][Activate Exception] vscode.git:  TypeError: i.workspace.registerResourceLabelFormatter is not a functionError: i.workspace.registerResourceLabelFormatter is not a function
	at new u (/Users/baiyuxiong/html/ide-startup/extensions/vscode.git/dist/main.js:10:469455)
	at C (/Users/baiyuxiong/html/ide-startup/extensions/vscode.git/dist/main.js:1:96236)
	at async T (/Users/baiyuxiong/html/ide-startup/extensions/vscode.git/dist/main.js:1:98025)
	at async Object.t.activate (/Users/baiyuxiong/html/ide-startup/extensions/vscode.git/dist/main.js:1:98894)
	at async t.default.activateExtension (/Users/baiyuxiong/html/ide-startup/hosted/ext.process.js:2:1794895)
[extHost:debug] exthost $activateExtension vscode.emmet
[extHost:debug] emmet - /Users/baiyuxiong/html/ide-startup/extensions/vscode.emmet
[extHost:debug] exthost $activateExtension path /Users/baiyuxiong/html/ide-startup/extensions/vscode.emmet
[extHost:debug] exthost $activateExtension vscode.merge-conflict
[extHost:debug] merge-conflict - /Users/baiyuxiong/html/ide-startup/extensions/vscode.merge-conflict
[extHost:debug] exthost $activateExtension path /Users/baiyuxiong/html/ide-startup/extensions/vscode.merge-conflict
[extHost:debug] try activate emmet
`

`
[vscode-icons] v11.15.0 activated!

[extHost:error] [extHost:error] [Extension-Host] command 'extension.js-debug.clearAutoAttachVariables' not found 

Error: command 'extension.js-debug.clearAutoAttachVariables' not found
    at StandaloneCommandService.executeCommand (http://127.0.0.1:8080/bundle.js:334440:35)
    at MonacoCommandService.executeCommand (http://127.0.0.1:8080/bundle.js:80869:39)
    at async MainThreadCommands.$executeCommand (http://127.0.0.1:8080/bundle.js:97394:20)
`

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

<img width="607" alt="Xnip2022-08-25_03-17-04" src="https://user-images.githubusercontent.com/230689/186504423-34a48fc2-59ee-4957-bf92-53064ca8fa02.png">

**环境信息（Environment）**

- OS: Darwin 192.168.3.59 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64

- Browser: 版本 104.0.5112.101（正式版本） (x86_64)
- OpenSumi Version: clone 自 ide-startup 仓库，最新版本，版本号不知道去哪里看

**补充信息（Additional context）**

**Comment by erha19** [comment]
@baiyuxiong 感谢反馈，你上面的报错信息可能会影响部分 Git 插件功能，但对整体 IDE 功能影响较小，对于打开目录这个功能支持，背景可以看这里 #1083 ，主要原因是 Web 环境下去实现该功能需要对 `workspaceDir` 参数做额外处理，而这部分参数处理逻辑可能在不同集成方存在不同需求，故这里没有硬编码实现逻辑 (仅在 Electron 上做了处理)，如需在 Web 上实现该功能，可以通过自己注册命令的方式去实现，参考：https://github.com/opensumi/core/blob/c26945d8f9fe6d524a1db5d5d007d1ad06467a38/packages/file-tree-next/src/browser/file-tree-contribution.ts#L865

目前 ide-startup 上支持两种工作区指定方式，一种是默认打开项目目录下的 `workspace` 目录，第二种就是通过 URL 去指定 https://github.com/opensumi/ide-startup#%E5%90%AF%E5%8A%A8

**Comment by baiyuxiong** [comment]
好的，我研究一下，建议更新下文件  https://opensumi.com/zh/docs/integrate/quick-start/web

**Comment by erha19** [comment]
@baiyuxiong 在 https://github.com/opensumi/ide-startup/pull/45 提供了简单的案例
