### ISSUE TITLE
[BUG] QuickOpen 组件文本存在裁切问题

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1588]
**描述你的问题（Describe the bug）**

文本存在裁切问题

**复现路径（To Reproduce）**

SCM 面板点击新建分支可复现该问题

**预期表现（Expected behavior）**

正常展示

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/9823838/187166452-2b761c3a-4179-4306-ab72-6cb4a6a60814.png)

**Comment by hacke2** [comment]
![image](https://user-images.githubusercontent.com/6399899/187172146-85e5d8a7-4d9e-4bc6-b883-3ea12bf97379.png)

我这边是正常的

**Comment by hacke2** [comment]
是不是 Chrome 插件问题？

**Comment by erha19** [comment]
@hacke2 我猜测应该是 codespell check 之类的属性影响
