### ISSUE TITLE
[BUG] SCM 打开变更文件的 Diff 视图，右上角的 "Open File" 偶现无法打开的情况

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#1600]
**描述你的问题（Describe the bug）**

https://user-images.githubusercontent.com/20262815/187363712-784df2a2-1e45-469c-8eea-65f5834649b7.mp4

**复现路径（To Reproduce）**

1. 第一次打开变更的文件，打开文件按钮有效
2. 关闭打开的文件，再次点击
3. 点击无反应

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
close by #1615.
