### ISSUE TITLE
[BUG] 内容粘贴到 webview 内 input 后内容重复

### ISSUE THREAD

**Issue by jianghai** [opensumi/core#1603]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

webview 内 <input /> 随便粘贴一个字符串，会追加一次，变成2份内容

**预期表现（Expected behavior）**

一次

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/2820736/187405002-79281eae-bfcd-48bb-9323-1b9b5fe78548.png)

**环境信息（Environment）**

**Comment by erha19** [comment]
@jianghai 是否可以提供一下一个可复现的例子？

**Comment by erha19** [comment]
@jianghai 由于长时间未响应，该 Issue 将会被关闭，如果仍有问题，请重新提交 Issue 进行反馈 ~
