### ISSUE TITLE
[BUG] Incorrect detection of file type

### ISSUE THREAD

**Issue by situ2001** [opensumi/core#1622]
**描述你的问题（Describe the bug）**

It seems that uri passed to function `FileSystemEditorComponentContribution.getFileType` always returns fileType `text`

**复现路径（To Reproduce）**

Just open a non-text file, for instance, an image file.

**预期表现（Expected behavior）**

fileType of file with ext `.jpg` should be `image`, not `text`

**问题截图（Screenshots）**

Note: I have assigned the returning value of function `getLanguageIdFromMonaco` to a variable `langID` so that I can find out what it returns.

https://github.com/opensumi/core/blob/d6dc837dd21fc09c215c284315f6341dec48bcbe/packages/file-scheme/src/browser/file-scheme.contribution.ts#L163-L173

Opening file with extesnion `.js`

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/28241963/188054053-948c9fa5-51c9-489d-90a8-8d48536ec034.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/28241963/188054382-995c3972-35f5-4ecf-91a0-e125c29f0532.png">

While opening file with extension `.jpg`, langID is `"unknown"`

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/28241963/188054135-4b686b06-8e56-462e-8495-b28c30afba29.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/28241963/188054349-d7e2ac89-6ebb-42c6-af96-b2ce5e6a7050.png">

**环境信息（Environment）**

- OS: macOS 12.5.1 ARM
- Browser: chrome
- OpenSumi Version: 2.19.10

**Comment by Ricbet** [comment]
@situ2001 thanks for your report，we have fixed #1644

**Comment by situ2001** [comment]
> @situ2001 thanks for your report，we have fixed #1644

Thanks. May I add some unit tests for `file-scheme.contribution`?

**Comment by Ricbet** [comment]
> > @situ2001 thanks for your report，we have fixed #1644
> 
> Thanks. May I add some unit tests for `file-scheme.contribution`?

Welcome！
