### ISSUE TITLE
[BUG] 插件宿主开发模式下，status bar 的文字颜色看不清楚

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1631]
如图所示：
<img width="743" alt="CleanShot 2022-09-05 at 13 23 07@2x" src="https://user-images.githubusercontent.com/13938334/188367053-8b1991dc-91a1-4261-94ce-55fe15d9551d.png">

**Comment by erha19** [comment]
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/9823838/188545054-28861232-8edc-4ae3-b3ca-234d6f934d29.png">

HC 模式下也有样式异常，我来处理一下

**Comment by bytemain** [comment]
<img width="1502" alt="CleanShot 2022-09-06 at 12 11 46@2x" src="https://user-images.githubusercontent.com/13938334/188545385-fc87ae56-0cfe-447b-b19a-fa73ff9c9391.png">

我没有复现我图里的问题了，不知是什么情况下才会出现这种前景色为灰色的情况。

**Comment by erha19** [comment]
嗯，这个问题我也遇到过 https://github.com/opensumi/core/issues/1620#issuecomment-1235023874

**Comment by erha19** [comment]
定位到问题了，这里是由于调试态的样式是通过 `this.commandService.tryExecuteCommand('statusbar.changeBackgroundColor', 'var(--statusBar-debuggingBackground)')` 以及 `this.commandService.tryExecuteCommand('statusbar.changeColor', 'var(--statusBar-debuggingForeground)')` 的方式去控制的，最终一次性注入到每个 StatusBar 的 entries 里面，而对于新增的状态按钮，就容易出现不匹配的问题导致异常

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/9823838/188561645-a38c1992-f1d9-414f-a02f-852b4c6d7cb3.png">
