### ISSUE TITLE
是否支持自定义语法呢？想要定义一套自己的语法体系，如何做呢？

### ISSUE THREAD

**Issue by xinnai** [opensumi/core#1634]
您好，想要达到类似[Monaco Editor]中Language syntax definition的功能，自定义语法和关键字等，是否支持呢，如何来实现呢？效果如这个链接：
https://microsoft.github.io/monaco-editor/monarch.html

**Comment by erha19** [comment]
@xinnai 建议通过语法插件的形式去实现，参考 VS Code 的语法插件文档

 https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

相关案例：

https://github.com/microsoft/vscode-extension-samples

**Comment by xinnai** [comment]
感谢回复，就是说我们的sumi框架可以直接使用vs code插件对吗？

**Comment by erha19** [comment]
是的，目前 1.65.0 以下版本的标准 API 都是兼容的

**Comment by xinnai** [comment]
谢谢，还有个疑问，目前团队都是vue技术栈，要基于sumi开发自己的IDE，要转react来才行吗？

**Comment by erha19** [comment]
> 谢谢，还有个疑问，目前团队都是vue技术栈，要基于sumi开发自己的IDE，要转react来才行吗？

是的，基于 React 可以更好的拓展 IDE 视图能力
