### ISSUE TITLE
[BUG] 通过vscode terminal 接口创建的终端实例，执行sendText 命令未生效

### ISSUE THREAD

**Issue by shawnt22** [opensumi/core#1641]
**描述你的问题（Describe the bug）**

我们的VSCode插件使用了terminal相关接口，主要是 vscode.window.createTerminal、terminal.sendText 两个接口。预期是在插件激活时自动通过terminal实例执行一个cli命令，cli命令的功能是在当前镜像内启动一个本地的koa服务器，为插件内的其他模块提供websocket、http rest访问能力。这个功能在桌面VSCode内运行良好，但在opensumi内cli命令并没有被正常执行。

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

插件激活时，自动通过terminal启动本地koa服务器

**问题截图（Screenshots）**

**环境信息（Environment）**

- Browser: chrome 105.0.5195.102
- OpenSumi Version: 1.0.0

**补充信息（Additional context）**

**Comment by life2015** [comment]
已知问题，之前修复了，但部署的版本不是最新的，更新到最新版可以看到问题已经被fix。
