### ISSUE TITLE
[BUG] 不存在的 icon text 收集

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1658]
现在有一些 VSCode 支持的 icon text OpenSumi 还不支持：

- `$(git-commit)`
<img width="407" alt="CleanShot 2022-09-15 at 17 49 26@2x" src="https://user-images.githubusercontent.com/13938334/190373322-06a710d5-fdc0-4eea-b88b-e76842c81ffb.png">

**Comment by erha19** [comment]
文件树上点击 `Copy Remote Url` 时，缺少 `$(repo)` 图标

![image](https://user-images.githubusercontent.com/9823838/190375622-1a9cb17f-30c2-4acf-b0f6-d8014fe14588.png)

**Comment by Ricbet** [comment]
这里的图标都是 [codicon](https://microsoft.github.io/vscode-codicons/dist/codicon.html) 里的吧，我猜都是因为没做转换，但其实图标我们都是支持的

**Comment by Aaaaash** [comment]
quickOpen 里用 iconService 转换一下就可以了，类似这里

https://github.com/opensumi/core/blob/main/packages/extension/src/common/index.ts#L267-L275
