### ISSUE TITLE
[BUG] Label should not set line-height in Editor Group Tab 

### ISSUE THREAD

**Issue by yiliang114** [opensumi/core#1668]
**描述你的问题（Describe the bug）**

Editor Tab 上设置了行高 100% 之后，文本会被部分遮挡

**复现路径（To Reproduce）**

1. 打开 [web 版](https://opensumi.github.io/ide-startup-lite/)
2. 随便打开几个文件，即可观察到

**预期表现（Expected behavior）**

![image](https://user-images.githubusercontent.com/11473889/190847209-22924aca-988e-4bf5-912d-26d9856040a1.png)
类似 vscode， tab 文本不被遮挡

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/11473889/190847111-0cdff3a7-76c0-4fe4-9fa2-c48e02b49ad7.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11] Mac 
- Browser: [e.g. chrome, safari, electron] chrome 
- OpenSumi Version: [e.g. 2.13.0] 2.19.12

**补充信息（Additional context）**

**Comment by yiliang114** [comment]
问题截图中的 `g` 部分被遮挡了

**Comment by Ricbet** [comment]
这个问题在 https://github.com/opensumi/core/pull/1500 中已修复
