### ISSUE TITLE
[FEATURE] 面包屑上支持右键菜单

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1670]
希望面包屑上也有右键菜单，可以有一些专属功能：

- Reveal In File Tree
- Copy Path
- Copy Relative Path

**Comment by Ricbet** [comment]
@wangxiaojuan 可以先把这三个菜单项加上去，具体实现都是有的，只需要将对应的 command 注册在 MenuId.EditorTitleContext 上

**Comment by wangxiaojuan** [comment]
https://github.com/opensumi/core/pull/2258
