### ISSUE TITLE
[BUG] 亮色主题下看不清 下拉框的下拉按钮

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1678]
![CleanShot 2022-09-20 at 00 16 12@2x](https://user-images.githubusercontent.com/13938334/191064526-4d609036-39df-4c4b-884f-e593d871792c.png)

此时下拉按钮的颜色是 --kt-icon-foreground

**Comment by erha19** [comment]
![image](https://user-images.githubusercontent.com/9823838/191161568-59c70707-09d3-4954-8a53-6f97b94a6b00.png)

主题色的适配也有点问题，合理的颜色应该是

![image](https://user-images.githubusercontent.com/9823838/191161634-ba10ae23-8e58-4de3-8bbb-eb52a917ffa9.png)

这里使用的下拉组件可能不一致

**Comment by erha19** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/9823838/191189717-35b5dd7b-4573-4c9e-9f8a-f9296f792178.png">

输入框 selection 也无法看清
