### ISSUE TITLE
[BUG] 主题配置内存在冗余的样式计算和仅在集成侧使用的 Token 定义

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1736]
**描述你的问题（Describe the bug）**

代码见：https://github.com/opensumi/core/pull/1735/files#diff-3448736c3c31a91f63f3a686023016388d5c73261dcb1768627c918421304239R442

**预期表现（Expected behavior）**

修改集成侧依赖，移除冗余代码

**Comment by bytemain** [comment]
可以用这个方法：

```ts
import { registerColor } from '@opensumi/ide-theme';

const backgroundM1 = registerColor(
  'background.m1',
  { dark: '#17171F', light: '#FFFFFF', hc: '#FFFFFF' },
  'background-m1'
);
```

**Comment by bytemain** [comment]
原来的代码是想根据原主题进行一些 patch，于是就 hardcode 在代码中了，现在还想做 patch 主题的话需要给出 willApplyTheme 的接口

**Comment by bytemain** [comment]
#2502 已经完成了，如果集成方想自己魔改主题的变量之类的，可以参考下原 PR 里给出的例子。
