### ISSUE TITLE
[BUG] QuickPick 面板一些样式问题

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1742]
**描述你的问题（Describe the bug）**

底部少了一点边距，视觉效果有点奇怪
<img width="797" alt="image" src="https://user-images.githubusercontent.com/9823838/193175068-cc2d5f20-bfec-45ba-8546-a8f63b61df47.png">

**复现路径**

点击 Gitlens 面板中的下面按钮：
<img width="433" alt="image" src="https://user-images.githubusercontent.com/9823838/193175331-4cbc54ed-6b7d-4fae-ac79-f3b1fc51089f.png">

**Comment by wangxiaojuan** [comment]
https://github.com/opensumi/core/pull/2299/commits
