### ISSUE TITLE
[FEATURE] IWindowDialogService.showOpenDialog 支持输入路径

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1769]
<img width="489" alt="CleanShot 2022-10-11 at 17 17 43@2x" src="https://user-images.githubusercontent.com/13938334/195050530-ac0d1f07-54bc-4423-bd51-d5c35b0b1a32.png">

现在的路径信息是要选择的，有的时候可以直接输入

**Comment by erha19** [comment]
@bytemain 这个参照了 Mac 下文件打开交互，只能选择

**Comment by erha19** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/9823838/195064112-2c9a3ec0-9fb8-4a13-80d4-0cbb5ad49f95.png">

保存文件的弹窗会有输入框，这个暂时不实现了，有需要再说
