### ISSUE TITLE
[BUG]electron版在windows上debug, 无法打断点，toolbar 上的几个控件无法点击

### ISSUE THREAD

**Issue by alyzhao** [opensumi/core#177]
**问题描述**

opensumi electron版在windows上debug, 无法打断点，toolbar 上的几个控件无法点击, 可以用这个 mock debug demo 来调试 

**复现路径（To Reproduce）**

clone 下来 debug 的插件 demo, git@code.alipay.com:longyan.zly/mock-debug-demo.git, 在 opensumi 中启动 electron, 将插件 link 到 extensions 目录, 打开 sampleWorkspace 进行调试。

**预期表现（Expected behavior）**
能够打断点, toolbar 操作可用

**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/24472439/147030423-68796933-98c0-44f9-9238-5304b1d90d4a.png)

**环境信息（Environment）**
 - OS: Windows10/Windows11
 - OpenSumi Version, 用的是 kaitian 2.12.8

**Comment by Ricbet** [comment]
@alyzhao 快捷键按 F5 有效果吗

**Comment by alyzhao** [comment]
> @alyzhao 快捷键按 F5 有效果吗

没有

**Comment by Ricbet** [comment]
> > @alyzhao 快捷键按 F5 有效果吗
> 
> 没有

可以提供下 mock debug 插件的版本吗

**Comment by erha19** [comment]
初步在 Windows 下定位了一下，发现 `debug-call-stack....tsx` 文件下的 setSubSection 方法存在一些问题导致下面一个报错

![截屏2021-12-22 上午11 25 19](https://user-images.githubusercontent.com/9823838/147050886-0c2d4dfc-e541-466d-91b5-f1ecf4ab4b3c.png)

![截屏2021-12-22 上午11 25 38](https://user-images.githubusercontent.com/9823838/147051009-1a86f166-2eed-4a3c-8b77-abc3fbcbd6d0.png)

最新的 mock debug 插件会导致 Windows 下调试的 IPC 通道阻塞挂掉
![截屏2021-12-22 上午11 45 37](https://user-images.githubusercontent.com/9823838/147051072-65c38bbd-0ee2-48f2-bbee-f3f3b817c35d.png)
