### ISSUE TITLE
[BUG] 未打开编辑器时，顶部高度与左侧栏不同。

### ISSUE THREAD

**Issue by sheng-di** [opensumi/core#1802]
**描述你的问题（Describe the bug）**
未打开编辑器时，顶部高度与左侧栏不同。

**复现路径（To Reproduce）**
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/13643746/196374122-7be77c2a-b3e5-4835-b5e4-2a8251f10408.png">

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@bytemain 看一下，这个貌似是集成侧对底部页面的定制样式问题

![image](https://user-images.githubusercontent.com/9823838/196583737-2eaff5e3-dd22-41e5-9fa3-cf4d46ad9436.png)
