### ISSUE TITLE
[BUG] Node.js / Worker 可能会启动插件两次

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1809]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

没有明确的复现路径，偶现

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
![abce1](https://user-images.githubusercontent.com/2226423/196594387-83297792-5de0-4624-981d-cfc70c1cb767.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: Electron
- OpenSumi Version: 2.20.6

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
这就是分别两个环境有代码，后面有标签区分
