### ISSUE TITLE
[BUG] mock debug 插件重复发送 breakpointLocations DAP 请求

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#181]
**描述你的问题（Describe the bug）**
安装 mock debug 最新版本（0.46.4），启动调试后 debug toolbar 点击无反应，且界面有一定的卡顿

**复现路径（To Reproduce）**
1. 随机打上几个断点
2. 启动调试
3. 等待一段时间后，显示被暂停的代码行，但点击 "继续" 按钮无反应

**预期表现（Expected behavior）**
debug toolbar 点击有反应

**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/20262815/147056322-8354b4bb-2938-484c-80ea-837334892e2f.png)

发现开启调试后 breakpointLocations 似乎进入到了循环请求

**环境信息（Environment）**
 - OS: macOS
 - Browser: chrome
 - OpenSumi Version: 2.13.0

**补充信息（Additional context）**

**Comment by erha19** [comment]
link #177
