### ISSUE TITLE
[BUG] 菜单栏中【选择】菜单有些项不可用

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1814]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/13938334/196891547-61673152-9625-42e5-9301-049bb891b0b3.png)

在行尾添加光标无效

其他几项可以选中，但是此时焦点已经不在编辑器了，会导致无法编辑。

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by pipiiiiii** [comment]
这几个功能是正常的，有问题的点是在浏览器里面点菜单的时候会导致编辑区失焦，用快捷键是正常的
尝试改了下：https://github.com/opensumi/monaco-editor-core/commit/ff956d205c3f9f2d8bd8fb8b0ef39c3af79be3c5
可以看下有没有必要修这个问题

**Comment by erha19** [comment]
@pipiiiiii 这里可能存在多个编辑器的情况，可能要通过 `editorService.currentEditor` 的方式去判断并激活一下编辑器焦点，感觉应该在 core 内将这块逻辑进行一下二次封装合理一点。

**Comment by bytemain** [comment]
为什么 VSCode 没有丢失焦点呢，我们是不是漏了一步什么

**Comment by pipiiiiii** [comment]
分两方面
1. 客户端的这个选项是在系统顶部栏的，这个不会导致焦点丢失，我们的 electron 版本也不会有这个问题。
2. 浏览器上面点菜单会导致焦点丢失，这个是浏览器的行为，试了下 vscode，他们会有丢失焦点 -> 重新聚焦的过程，我再去看下他们这个行为是再哪实现的

**Comment by bytemain** [comment]
在 Windows 上，electron 版本也是自己画的顶部栏，顶楼截图的内容就是 Windows 上的 electron 应用。

**Comment by Ricbet** [comment]
这个在 core 里面修复吧，应该不是 monaco 的问题

**Comment by pipiiiiii** [comment]
破案了，`monaco` 的 `menubar` 有个逻辑，`focusin` 的时候会[记录](https://github.com/opensumi/monaco-editor-core/blob/feat%2Fmonaco-core-0.35.x/src/vs/base/browser/ui/menu/menubar.ts#L159)上一个 `dom` 元素，`focusout` 时候[重新](https://github.com/opensumi/monaco-editor-core/blob/feat%2Fmonaco-core-0.35.x/src/vs/base/browser/ui/menu/menubar.ts#L701) `focus`。

我们是同步实现这个 `focus` 相关的逻辑比较好，还是针对这几个 `command` 单独处理 `editor.focus()` 呢?

同时这个问题跟一个历史的 commit 有关 https://github.com/opensumi/core/commit/c1cd3f027564778206b4c3d0846b829315cceed9

**Comment by Ricbet** [comment]
针对这几个 command 单独处理吧 @pipiiiiii

**Comment by bytemain** [comment]
我觉得应该实现下这个逻辑。

> monaco 的 menubar 有个逻辑，focusin 的时候会[记录](https://github.com/opensumi/monaco-editor-core/blob/feat%2Fmonaco-core-0.35.x/src/vs/base/browser/ui/menu/menubar.ts?rgh-link-date=2023-02-01T08%3A08%3A22Z#L159)上一个 dom 元素，focusout 时候[重新](https://github.com/opensumi/monaco-editor-core/blob/feat%2Fmonaco-core-0.35.x/src/vs/base/browser/ui/menu/menubar.ts?rgh-link-date=2023-02-01T08%3A08%3A22Z#L701) focus。

**Comment by bytemain** [comment]
1. 不能针对所有 command 都 focus editor
2. 不要一个个 command 处理，我觉得 menubar 这种方式处理就挺好的，凡是在 selection 这个 menubar 下的 command都没问题了。

**Comment by bytemain** [comment]
1. 不要让所有 command 都 focus editor
    比如用户开启了 auto save，那他在操作其他地方的时候，突然编辑器就获得焦点了
2. 不要一个个 command 处理，我觉得 menubar 这种方式处理就挺好的，凡是在 selection 这个 menubar 下的 command都没问题了。
