### ISSUE TITLE
[Question] yarn 安装依赖过程中提示插件安装失败

### ISSUE THREAD

**Issue by li-code01** [opensumi/core#1816]
**描述你的问题（Describe you question here）**
clone完项目后，运行yarn，到 node scripts/download.js，之后开始提示插件安装失败

**Comment by erha19** [comment]
@li-code01 `scripts/donload.js` 命令为安装插件，该命令依赖的是海外的 OpenVSX 源，国内用户可能会有访问缓慢问题，你可以根据这个文档切换到合适的镜像站使用 [自定义插件市场镜像#配置方式](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-marketplace-entrypoint#%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F)
