### ISSUE TITLE
[FEATURE] 终端支持右键菜单 

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#182]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

**描述你预期的功能表现（Describe the solution you'd like）**

提供基础的终端右键菜单功能，支持选中复制、粘贴文件等操作

**补充信息（Additional context）**

类似 VS Code
![image](https://user-images.githubusercontent.com/17701805/147174607-550374c5-3375-4771-a31c-6a5ea0f4f76c.png)

**Comment by yantze** [comment]
可以先实现一个简单一点的
