### ISSUE TITLE
[BUG] 大纲跟随光标功能失效

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#1839]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/197750202-9b84eb07-c9ea-4a95-804f-a2b8dcfd1783.png)

如图，光标选中并没有在大纲里显示选中态

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
偶现

**Comment by erha19** [comment]
这个问题目前找不到稳定复现路径，之前遇到的时候就点第二次就好了，看一下后续是否有稳定的复现路径后再考虑修复
