### ISSUE TITLE
[BUG] 重复计算了不同分组下的同一份未保存文件的数量

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#1841]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/197764999-76797886-6ef2-48ba-a380-b373b7cdc60b.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
fixed https://github.com/opensumi/core/pull/1827.
