### ISSUE TITLE
[Question] 如何根据不同文件后缀展示不同文件icon

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#1843]
**描述你的问题（Describe you question here）**
根据不同文件后缀展示不同的自定义图标，.ceg后缀文件使用自定义的svg作为图标如何实现

**Comment by erha19** [comment]
@767746649zyy 定义不同文件的图标，我们一般采用图标主题的方式进行定义，你可以自己开发相关插件，也可以在插件市场中搜索 `icon theme` 安装并启用相关的插件看是否满足需求。

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/9823838/197915635-6121f42a-4308-4ddc-ac97-fb1b7cb82989.png">
