### ISSUE TITLE
[BUG] 点击搜索结果第一次不会定位到行列

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1844]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

- 下载 https://github.com/opensumi/ide-electron/actions/workflows/pack-for-test.yml
- 打开项目后，打开搜索面板
- 找到一个文件内容超过一屏的结果
- 点击结果，第一次不会只打开文件没有定位到行列

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

https://user-images.githubusercontent.com/2226423/197915287-a21130e2-c626-462d-8d7c-7d0d8a4a608e.mov

**环境信息（Environment）**

- OS: macOS 12
- Browser: Electron
- OpenSumi Version: 2.20.9-next-1666579869.0

**补充信息（Additional context）**

**Comment by erha19** [comment]
fixed https://github.com/opensumi/core/pull/1833.
