### ISSUE TITLE
[BUG] quickpick 最匹配的命令没有在第一列

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1846]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

1. 下载 https://github.com/opensumi/ide-electron/actions/workflows/pack-for-test.yml
2. 直接打开 quickpick (cmd+shift+p)
3. 输入 reload 内容后复现

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/2226423/197916199-3ea2ac4f-d59f-41bd-aa4a-c5e132427088.png)

`.sumi` 里面对应的命令没有 diff / merge
`  "RECENT_COMMANDS": "[\"theme.toggle\",\"theme.toggle\"]"`

**环境信息（Environment）**

- OS: macOS 12
- Browser: Electron
- OpenSumi Version: 2.20.9-next-1666579869.0

**补充信息（Additional context）**

**Comment by hacke2** [comment]
![image](https://user-images.githubusercontent.com/6399899/198503760-4f92b04c-5aa3-4f52-bf1a-47387ec9f824.png)

我们是和 VS Code 一样的，这个排序是通过下面配置控制的

https://github.com/opensumi/core/blob/76efb84ca0955fb8d543ecd36e386e45160a3b10/packages/quick-open/src/browser/quick-open.command.service.ts#L94-L96

开启后会默认按照 Label 排序，会很奇怪

![image](https://user-images.githubusercontent.com/6399899/198504167-9ae97547-b927-4aec-91da-68e88e5d127c.png)


建议和 VS Code 一样保持一致吧
