### ISSUE TITLE
[BUG] 打不开 Terminal 面板

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1848]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

1. 下载 https://github.com/opensumi/ide-electron/actions/workflows/pack-for-test.yml
2. 打开项目后，点击 Terminal 面板
3. 一直转圈，然后就没了

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
<img width="683" alt="image" src="https://user-images.githubusercontent.com/2226423/197916711-4ad9a699-7388-447c-a516-65b206c9e6d5.png">

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/2226423/197916685-5bf877e2-ceb9-420c-b38f-89cece105a52.png">

**环境信息（Environment）**

- OS: macOS 12
- Browser: Electron
- OpenSumi Version: 2.20.9-next-1666579869.0

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
https://github.com/opensumi/ide-electron/blob/main/package.json#L42-L47

**Comment by life2015** [comment]
electron那边也一起bump以下xterm.js 版本试试呢   感觉是xterm和render插件版本匹配的问题。

**Comment by yantze** [comment]
打包中

**Comment by yantze** [comment]
升级后正常了
