### ISSUE TITLE
[FEATURE] loading图标展示不完整或者不是动态效果

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#1853]
**描述你的问题（Describe the bug）**
`
 
  const statusBarService: IStatusBarService = useInjectable(IStatusBarService);;
` statusBarService.addElement('234', {
      text: `$(loading)正在加载...`,
      alignment: 0,
    });`

loading图标仅展示一半，在网站https://microsoft.github.io/vscode-codicons/dist/codicon.html 上展示的loading图标也只展示一半

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/23164065/197941221-21db051f-50e0-4f96-a971-9631daa295f7.png)

![image](https://user-images.githubusercontent.com/23164065/197944568-1c9d2241-052d-49cb-8d54-4e01dff32b9c.png)

**Comment by erha19** [comment]
@767746649zyy 这是 OpenSumi 中还没有实现的一个特性，下个版本 2.22 会支持一下，通过在图标后追加 `~spin` 可以让图标动起来，如将 `$(loading)` 修改为 `$(loading~spin)`.

**Comment by erha19** [comment]
@767746649zyy 该特性在很早版本就支持了，你可以修改一下使用 `$(loading~spin)`

**Comment by 767746649zyy** [comment]
已用，没问题了，感谢回复
