### ISSUE TITLE
[BUG] 打开文件资源管理器中文件失败

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#1858]
**描述你的问题（Describe the bug）**
打开文件资源管理器中文名称文件报错

例如打开“中文.yaml”文件
` const res: string[] | undefined = await electronNativeDialogService.showOpenDialog({
              title: '请选择要导入的文件',
              buttonLabel: '选择',
              properties: ['openFile', 'showHiddenFiles', 'treatPackageAsDirectory', 'noResolveAliases'],
              filters: [{ name: '', extensions: ['yaml'] }],
            });`
**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/23164065/198002923-50bc4b55-b78d-407d-8ecb-35a59007ba27.png)
![image](https://user-images.githubusercontent.com/23164065/198003003-30a4ab0b-5236-410a-bbfa-895ec42341ff.png)

其他信息：win10 node：v14.17.6 opensumi: "2.18.15"

**Comment by erha19** [comment]
@767746649zyy 看你这里的用法是通过 `electronNativeDialogService.showOpenDialog` 方法获取了选择文件的路径，之后是进行了新的什么操作吗？看有一个 `invalid file content` 的报错，可以看一下后面执行的操作是否存在异常，例如路径错误之类的

**Comment by 767746649zyy** [comment]
的确是后续操作的问题，感谢
