### ISSUE TITLE
[BUG] 编辑器撤销操作表现奇怪

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#1906]
复现和操作步骤如下（附和vscode的对比，注意vscode不要开保存时自动格式化
新建任意文件，初始化内容为空

  | IDE表现 | vscode表现
-- | -- | --
输入“ab”，保存 | 正常显示“ab” | 正常显示“ab”
在b后输入c，不要保存，然后退格删掉bc，保存 | 正常显示“a” | 正常显示“a”
cmd+z撤销 | 显示为“abc” | 显示为“abc”
退格删除c，保存一次，再退格删除b，保存一次，然后按cmd+z撤销 | 显示为“abc” | 显示为“ab”

**Comment by erha19** [comment]
这个后续修复了可以补充一个 E2E 固定一下交互

**Comment by bytemain** [comment]
研究发现：
输入第二个字符按保存后，monaco editor 并没有把这个变更 push 到 editStack 中。
但是这个时候，点击一下编辑器，这个变更就被 push 到 stack 里了。

也就是说，保存后点一下编辑器，保存后点一下编辑器表现就和 vscode 一样了

**Comment by bytemain** [comment]
保存的时候补偿一个 pushStack 应该就好了
