### ISSUE TITLE
[BUG] QuickInputOptions里面的password不生效

### ISSUE THREAD

**Issue by gagalincheng** [opensumi/core#1936]
**描述你的问题（Describe the bug）**

QuickInputOptions里面的password不生效，输入框没有遮挡住密码
![lQLPJxbacLhL-DZdzQKDsN0pPAE7NaGrA2b1e74AHAA_643_93](https://user-images.githubusercontent.com/15609261/200489957-a32bede1-20de-4d50-9f9f-106e0c7f6616.png)

**复现路径（To Reproduce）**
代码如下
![lQLPJxbacLhL-fJ7zQHbsDk2wrY2YnmyA2b1e7vA-wA_475_123](https://user-images.githubusercontent.com/15609261/200490007-a5c75f3f-b709-4703-89bb-10cc3c6648b2.png)

**预期表现（Expected behavior）**

应该遮挡住密码，不显示明文

**环境信息（Environment）**

- OS: [Windows10]
- Browser: [chrome,]
- OpenSumi Version: [2.16.9]

**补充信息（Additional context）**
![lQLPJxbacLhL-MJ-zQNrsPOYQ-jYMaDsA2b1e7nAiQA_875_126](https://user-images.githubusercontent.com/15609261/200490332-3cd17a48-91f4-4527-b962-deae1b4315b6.png)

**Comment by Ricbet** [comment]
在 2.18 版本已经修复了这个问题: https://github.com/opensumi/core/pull/926

**Comment by erha19** [comment]
@gagalincheng 可以根据集成接入文档升级一下相关依赖 [Breaking Changes](https://github.com/opensumi/core/wiki/%E9%9B%86%E6%88%90%E6%8E%A5%E5%85%A5-Breaking-Changes)。
