### ISSUE TITLE
更新了2.20.12之后，发现messageService.open的通知现在会自动消失了，之前是常驻的

### ISSUE THREAD

**Issue by gagalincheng** [opensumi/core#1951]
**描述你的问题（Describe you question here）**

更新了2.20.12之后，发现messageService.open的通知现在会自动消失了，之前这样实现是常驻的

![image](https://user-images.githubusercontent.com/15609261/201042985-c6f5edba-fe50-43fa-8a79-070693239b1a.png)

请问让通知不消失，有其他的处理方式吗

**Comment by erha19** [comment]
@gagalincheng 目前针对 `messageService.open` 方法是有一个确切的消息停留时间设计的， Info 类型是 15s，warning 类型是 18s，error 类型是 20s，原有常驻的表现是代码问题导致的。

目前具备常驻弹窗能力的服务是 `IDialogService` 你可以看一下是否符合你的需求。

**Comment by gagalincheng** [comment]
@erha19 我试了下`IDialogService `，不太符合我的需求，我需要是通知形式
![image](https://user-images.githubusercontent.com/15609261/201254972-34f037dc-b800-42be-b39b-acc1fe55f4a9.png)

**Comment by erha19** [comment]
@gagalincheng  那应该 `IProgressService` 比较符合你的需求，我晚点补充个示例

**Comment by erha19** [comment]
@gagalincheng 案例已添加，见 https://github.com/opensumi/opensumi-module-samples/pull/14.
