### ISSUE TITLE
[BUG] snippet 补全后光标位置异常

### ISSUE THREAD

**Issue by yantze** [opensumi/core#1956]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

用 2.20.12 偶现问题，输入 clg 补全 console.log 后，光标位置不会删除字符，但前面几个字符会被删除。重新打开窗口就正常

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/2226423/201099400-793a8d0b-d8c0-4b2b-a71f-59c459cd15f4.png">
具体的错误行为：

https://user-images.githubusercontent.com/2226423/201099672-e924e1a4-513a-4f12-9ac0-e39d1db9528e.mov

**环境信息（Environment）**

- OS: macOS 13.0
- Browser: electron
- OpenSumi Version: 2.20.12-rc-1667974420.0

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
@yantze 2.22 版本试试呢？

**Comment by Ricbet** [comment]
@yantze 现在这个问题还会出现吗

**Comment by yantze** [comment]
> @yantze 现在这个问题还会出现吗

good 现在好了
