### ISSUE TITLE
[BUG] Message 弹窗样式存在异常

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1959]
**描述你的问题（Describe the bug）**

<img width="472" alt="image" src="https://user-images.githubusercontent.com/9823838/201283466-e5312eaf-1e7f-493e-ae25-6dc22a2018f7.png">

**复现路径（To Reproduce）**

使用 IMessageService 弹出消息

**预期表现（Expected behavior）**

图标对齐，文本溢出自动换行

**环境信息（Environment）**

- OpenSumi Version: 2.21.3

**Comment by erha19** [comment]
该问题主要是在 IMessageService 中引入 Markdown 解析后引入的问题，字符串可能被解析为 `code/pre` 等块导致样式不受控

**Comment by bytemain** [comment]
https://github.com/opensumi/core/pull/1903 这个 pr 已经将生成的字符串放入一个 div 中了，可以增加那个 div 的样式内容

**Comment by erha19** [comment]
这里是 `notification` 相关样式，跟 dialog 相关性还不大
