### ISSUE TITLE
🤖 OpenSumi PreRelease Mon Dec 27 2021

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#196]
### [b4b6ed8f142ec65bff97234846023d6421ef4031](https://github.com/opensumi/core/compare/6b85e4b700bd21d114f33e71e4fbf721e1567487...b4b6ed8f142ec65bff97234846023d6421ef4031)

> 27 December 2021

#### 🐛 Bug Fixes

- 修复 Toolbar 按钮的 min-width 属性名 [#152](https://github.com/opensumi/core/pull/152) by [@yantze](https://github.com/yantze)

- 去掉多余的主题 fallback 逻辑 [#188](https://github.com/opensumi/core/pull/188) by [@Aaaaash](https://github.com/Aaaaash)

#### 📚 Documentation Changes

- update PullRequest template [#153](https://github.com/opensumi/core/pull/153) by [@erha19](https://github.com/erha19)

- replace tnpm as npm [#173](https://github.com/opensumi/core/pull/173) by [@erha19](https://github.com/erha19)

- use OpenSumi theme preview image [#180](https://github.com/opensumi/core/pull/180) by [@erha19](https://github.com/erha19)

#### 💄 Code Style Changes

- 优化文件树渲染性能 [#149](https://github.com/opensumi/core/pull/149) by [@Aaaaash](https://github.com/Aaaaash)

- 优化大纲面板 treeview 渲染性能 [#176](https://github.com/opensumi/core/pull/176) by [@Aaaaash](https://github.com/Aaaaash)

#### 💄 Style Changes

- 优化编辑器 Tab 栏图标样式 [#157](https://github.com/opensumi/core/pull/157) by [@Aaaaash](https://github.com/Aaaaash)

#### 🪚 Refactors

- 格式化 scripts 目录中的的脚本 [#185](https://github.com/opensumi/core/pull/185) by [@yantze](https://github.com/yantze)

- 弃用 ongiWasmPath 使用 ongiWasmUri [#187](https://github.com/opensumi/core/pull/187) by [@yantze](https://github.com/yantze)

#### 🧹 Chores

- 更新插件下载脚本，新增默认主题 [#161](https://github.com/opensumi/core/pull/161) by [@Aaaaash](https://github.com/Aaaaash)

- Update workflow, add workflow_dispatch [#170](https://github.com/opensumi/core/pull/170) by [@Aaaaash](https://github.com/Aaaaash)

- 移除 GitHub workflow release 发布脚本 [#163](https://github.com/opensumi/core/pull/163) by [@yantze](https://github.com/yantze)

- show extension download progress [#179](https://github.com/opensumi/core/pull/179) by [@erha19](https://github.com/erha19)

- chore: v2.13.4 (#191) [#191](https://github.com/opensumi/core/pull/191) by [@erha19](https://github.com/erha19)

- 添加 prerelease workflow [#197](https://github.com/opensumi/core/pull/197) by [@Aaaaash](https://github.com/Aaaaash)

- chore: update workflow (#201) [#201](https://github.com/opensumi/core/pull/201) by [@Aaaaash](https://github.com/Aaaaash)

- 使用 fork 的 @opensumi/vscode-ripgrep ，避免国内下载失败 [#192](https://github.com/opensumi/core/pull/192) by [@Aaaaash](https://github.com/Aaaaash)

- chore: show correct tips while running changelog script (#202) [#202](https://github.com/opensumi/core/pull/202) by [@erha19](https://github.com/erha19)

- 更新 prerelease workflow [#203](https://github.com/opensumi/core/pull/203) by [@Aaaaash](https://github.com/Aaaaash)

- fix: install dependencies first (#204) [#204](https://github.com/opensumi/core/pull/204) by [@Aaaaash](https://github.com/Aaaaash)

- 发布 prerelease 版本时使用唯一的版本号 [#207](https://github.com/opensumi/core/pull/207) by [@Aaaaash](https://github.com/Aaaaash)

- use GITHUB_SHA as changelog title if exist [#208](https://github.com/opensumi/core/pull/208) by [@erha19](https://github.com/erha19)

- Add basic release workflow [#209](https://github.com/opensumi/core/pull/209) by [@Aaaaash](https://github.com/Aaaaash)

- 版本发布后自动@ issue owner [#213](https://github.com/opensumi/core/pull/213) by [@Aaaaash](https://github.com/Aaaaash)

**Comment by lengthmin** [comment]
牛啊
https://www.npmjs.com/package/@opensumi/ide-addons
![image](https://user-images.githubusercontent.com/13938334/147255524-fc2a56af-86e7-4b8d-bb45-5e7c65907554.png)

**Comment by erha19** [comment]
cool

**Comment by vagusX** [comment]
厉害了

**Comment by Aaaaash** [comment]
测试完关了
