### ISSUE TITLE
[BUG] 修改 Midway 项目代码后每次会重新激活 Debug 面板影响编码

### ISSUE THREAD

**Issue by erha19** [opensumi/core#1966]
**描述你的问题（Describe the bug）**

修改 Midway 项目代码后每次会重新激活 Debug 面板影响编码

**复现路径（To Reproduce）**

使用如下调试配置：

```
{
  // 使用 IntelliSense 了解相关属性。 
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "command": "npm start",
      "name": "Run npm start",
      "request": "launch",
      "type": "node-terminal"
    }
  ]
}
```

**预期表现（Expected behavior）**

单次调试进程只应该在首次激活 Debug 面板，而不是每次 attach 后激活一次

**问题截图（Screenshots）**

https://user-images.githubusercontent.com/9823838/201599236-9f6b0533-34f4-459e-8c24-cc8838784d21.mp4

**环境信息（Environment）**

- OpenSumi Version: 2.21.3

**Comment by Ricbet** [comment]
这个设置一下 debug.openDebug 配置就好了吧

**Comment by erha19** [comment]
> 这个设置一下 debug.openDebug 配置就好了吧

这个主要是对齐了一下  VS Code 的调试体验，用户并不想加配置
