### ISSUE TITLE
[BUG] 暗色主题下，文件树下未选中文件的字体颜色与背景色相近，视觉上非常不舒服

### ISSUE THREAD

**Issue by dossweet** [opensumi/core#1973]
**描述你的问题（Describe the bug）**

如题，暗色主题下，文件树下未选中文件的字体颜色与背景色相近，视觉上非常不舒服。

**复现路径（To Reproduce）**

界面左下角打开偏好设置 --> 选择颜色主题 --> 选择IDE Dark

**预期表现（Expected behavior）**

文件树中未选中的文件的字体颜色为浅色（因为主题色是暗黑色）

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/38655923/201827277-2ff17aa9-4b8a-4123-b04b-c94ec0f79d21.png)

**环境信息（Environment）**

- OS: [Windows10]
- Browser: [chrome]
- OpenSumi Version: [v2.21.3]

**补充信息（Additional context）**

不确定是不是设计风格就是这种，作为开发者，个人感觉使用起来视觉上有点不舒服。

**Comment by erha19** [comment]
@dossweet 该问题是非预期的，初步看了一下是根节点下引入了一个错误的 `body` 样式导致的样式覆盖，我来跟进一下这个问题。

**Comment by dossweet** [comment]
好的，魁武老师！

**Comment by erha19** [comment]
@dossweet 该问题为 antd 引入的脏样式导致的问题，可以用一下在这个分支跑一下，移除了 antd 依赖 https://github.com/opensumi/ide-startup-lite/pull/35，后续如需要使用 antd，需要对 body 下的样式进行覆盖如下内容：

```css
body {
  color: var(--foreground);
}
```

**Comment by dossweet** [comment]
好的！
