### ISSUE TITLE
[BUG] statusbar pophover 支持 icon 展示

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#1977]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/6399899/202093901-9a8a000d-c424-4181-ab69-11bc648e8230.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
https://github.com/opensumi/core/blob/fbb5ce9e7613898255a8ba82dc730b6fe5890ec4/packages/core-browser/src/utils/label.tsx 可以统一用这个方法，不过目前缺少对 ~spin 动态图标的支持

**Comment by erha19** [comment]
![image](https://user-images.githubusercontent.com/9823838/215303784-8dfde4cb-5370-413c-82c1-f412d737392f.png)

类型问题

**Comment by bytemain** [comment]
https://github.com/opensumi/core/blob/edeb80d61dc57c50af3edb74e729f031387cd8cf/packages/core-browser/src/utils/parse.ts#L32

这个文件里的方法支持:
- `$(kticon/sync~spin)`
