### ISSUE TITLE
[BUG] 使用vscode的api注册command，然后在回调里面console.log 看不到消息

### ISSUE THREAD

**Issue by wtc842017068** [opensumi/core#1993]
**描述你的问题（Describe the bug）**

使用vscode的api注册command，然后在回调里面console.log 看不到消息
**复现路径（To Reproduce）**
就很简单的注册一个回调函数，查看是否被调用起来，尝试使用console.log 看不到输出，使用vscode.window.showInformatinMessage 可以看大弹窗输出信息

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@wtc842017068 针对插件调试场景，目前还不支持将插件内的 `console.log` 输出至前台，后续会在调试模式下支持。

目前提供的两种方式：
1. 你上面提到的利用 `vscode.window.showInformatinMessage` 输出调试的方式
2. 运行服务端代码时追加  `IS_DEV=true` 标识，以 `ide-startup` 项目为例 `IS_DEV=true yarn start` 运行进入页面加载后，你可以通过默认的调试端口`9889`查看并调试插件进程, 如下图所示：

<img width="895" alt="截屏2022-11-21 16 02 42" src="https://user-images.githubusercontent.com/9823838/202996606-fbf77337-c1d4-4c4f-8007-bad5fbbded51.png">
