### ISSUE TITLE
[BUG] 搜索文件后编辑对应内容，搜索内容没有变动

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#2001]
![CleanShot 2022-11-23 at 11 07 45@2x](https://user-images.githubusercontent.com/13938334/203462261-af5ed7fa-1dc9-48ba-a160-4bacea6968e5.png)

比如我搜索的是 ossMeta，看到的结果是 `Record<string, any>`，我改成了 `Record<string, string>`，但是搜索的内容还是原来的

**Comment by erha19** [comment]
@bytemain 试一下最新 main 分支，应该修复了

**Comment by erha19** [comment]
closed by https://github.com/opensumi/core/pull/2102.
