### ISSUE TITLE
[BUG]: o.workspace.registerTimelineProvider is not a functionError

### ISSUE THREAD

**Issue by l1shen** [opensumi/core#2016]
**描述你的问题（Describe the bug）**

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/8299540/204073661-34c6daec-c48d-4a90-a532-6d38395e78a0.png">

启动项目之后就会提示这个错误，看起来是来自于 vscode.git 插件使用了 registerTimelineProvider 这个方法，但是 opensumi 没有实现
**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@l1shen 该 `registerTimelineProvider` API 是 VS Code 中提供的一个实验性 API，仅在部分插件中被使用，其中包括低版本的 `vscode.git` 插件，如果你使用了最新的 OpenSumi 版本（2.21+）你可以升级 `vscode.git` 以及 `vscode.git-base` 至 1.64.0 以上，后续 Git 插件版本中没有再使用该 API。

另外，OpenSumi 本身对于 VS Code 的实验性 API 没有计划性的适配计划，仅会对部分重要或需求较多的实验性 API 进行定向适配，如果后续有需求，也可以提交 Issue 或讨论区描述场景，我们会根据社区反馈更新适配计划 ~

**Comment by l1shen** [comment]
升级 `vscode.git` 至 `1.64.0` 解决了此报错

感谢解答
