### ISSUE TITLE
[BUG]: Unexpected keyboard event mapped to a chord

### ISSUE THREAD

**Issue by l1shen** [opensumi/core#2018]
**描述你的问题（Describe the bug）**

编辑器中随意输入 console 警告 Unexpected keyboard event mapped to a chord

**复现路径（To Reproduce）**
https://opensumi.github.io/ide-startup-lite/ 中随便创建一个文件然后输入任意东西

**预期表现（Expected behavior）**
输入没有 warn

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by l1shen** [comment]
看起来是 https://github.com/opensumi/core/blob/main/packages/monaco/src/browser/monaco.resolved-keybinding.ts#L70
```typescript
public isChord(): boolean {
    return this.parts.length >= 1;
}
```
这个判断造成的
在 vscode 中是https://github.com/microsoft/vscode/blob/main/src/vs/platform/keybinding/common/baseResolvedKeybinding.ts#L54
```typescript
public isChord(): boolean {
    return (this._parts.length > 1);
}
```
请问这里重写 `baseResolvedKeybinding` 并且使用 `>= 1` 的判断是有什么原因吗

**Comment by erha19** [comment]
@l1shen 感谢你的反馈，这里确实是存在这个问题，OpenSumi 在 2.20 版本后升级了内置 monaco 依赖至 0.35+，该部分升级导致了 `isChord` 这里的判断出现问题，方便的话你可以提一个 PR 修复一下这个判断问题，代码见  https://github.com/opensumi/core/blob/main/packages/monaco/src/browser/monaco.resolved-keybinding.ts#L70。

如果你这边没有时间，后续我们也会修复这个问题 ~ 再次感谢你的反馈。
