### ISSUE TITLE
[BUG] ToolTip组件位置显示异常

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2034]
**描述你的问题（Describe the bug）**
当我的画布style样式设置transform: translate(4px, -2px)时，展示的ToolTop组件位置异常

![企业微信截图_16698844805895](https://user-images.githubusercontent.com/23164065/205007584-253fdd0f-9972-4e38-9caa-e77108a4d743.png)

**复现路径（To Reproduce）**
当没有transform translate属性设置时，显示没问题

**预期表现（Expected behavior）**
![企业微信截图_16698845608458](https://user-images.githubusercontent.com/23164065/205007874-628604db-df9e-475e-945d-d3fe0f3d76c9.png)

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@767746649zyy 框架内目前实现的 Tooltip 组件比较简陋，预计在设置了 Transform 属性后，相关的位置计算逻辑会出错，计算代码见：https://github.com/opensumi/core/blob/85b3e5f1ca7e815929d8148d2e93062a1681171f/packages/components/src/tooltip/index.tsx#L29 ，可以先调试看看是否有更好的计算方式。

另外，如果只是简单的信息展示，也可以直接通过 css 的方式去实现 tooltip 的显示隐藏及位置控制。
