### ISSUE TITLE
[BUG] 中文模式下搜索不到 Rerun last task 这个命令

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#2035]
<img width="643" alt="CleanShot 2022-12-01 at 17 39 58@2x" src="https://user-images.githubusercontent.com/13938334/205019017-584fb965-0b9e-4236-9446-c758975241ac.png">

依稀记得当时做了 i18n 的

**Comment by erha19** [comment]
@bytemain  图里面最后一个不就是吗？

**Comment by bytemain** [comment]
噢，my fault.

正确表现是它应该也会显示一句英文。

**Comment by Ricbet** [comment]
现在这个问题是什么？

**Comment by bytemain** [comment]
问题就是搜索 rerun last task 无法搜到这个命令。

<img width="634" alt="CleanShot 2023-02-01 at 13 57 15@2x" src="https://user-images.githubusercontent.com/13938334/215963397-e432b610-4655-44cc-a852-19ce09f4495e.png">
<img width="740" alt="CleanShot 2023-02-01 at 13 57 36@2x" src="https://user-images.githubusercontent.com/13938334/215963447-eb23025a-381d-4cd2-81ae-9ee2b19df1c5.png">

**Comment by bytemain** [comment]
<img width="823" alt="CleanShot 2023-02-01 at 13 58 49@2x" src="https://user-images.githubusercontent.com/13938334/215963622-b5ed9e57-2b9d-4b47-9bca-13a22d8ef982.png">

是因为这里没有使用 alias 字段，所以中文模式下不知道这个命令是有 alias 的，也就不能根据这个命令的英文名来搜索。

需要添加一层抽象，如果这个字段只设置了 `%xxx%` 的 label，那么给它解析上 label 为当前语言，alias 为默认英文

**Comment by bytemain** [comment]
#2481 已经修复。
