### ISSUE TITLE
[BUG] 激活 codeAction 菜单面板后，该面板无法响应快捷键

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#2037]
**描述你的问题（Describe the bug）**

<img width="416" alt="CleanShot 2022-12-04 at 17 34 22@2x" src="https://user-images.githubusercontent.com/13938334/205483697-afccf313-02db-489a-828c-d40d3f393e41.png">

这个面板，无法响应 ArrowUp, ArrowDown, Enter 等快捷键。

**补充信息（Additional context）**

排查后发现，相关命令和快捷键都已经被 OpenSumi 注册了，但是当响应 Enter 快捷键的时候需要判断 "codeActionMenuVisible" 这个 ContextKey 的时候查不到该 key 的值：
![CleanShot 2022-12-04 at 17 35 40@2x](https://user-images.githubusercontent.com/13938334/205483761-83fc92d3-f468-496a-8d67-3279602dc290.png)

<img width="1597" alt="CleanShot 2022-12-04 at 17 36 28@2x" src="https://user-images.githubusercontent.com/13938334/205483802-68134f61-aa1e-4655-be7a-0ea7fda94c6a.png">

还有一个疑点，该 dom 节点在 monaco-editor 之外，可能因为这个原因导致没有取到 context-key

**Comment by erha19** [comment]
看了一下，这个问题貌似是由于 `CodeActionMenu` 为懒加载的逻辑，即其注册的 `ContextKey` 为后置绑定的，见: https://github.com/opensumi/monaco-editor-core/blob/1040fc062307fe4fd7845fa4e19b51360e64bb86/src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts

而 OpenSumi 复用了 monaco 内置的 ContextKeyService 实例，该实例仅会创建默认的 ContextKey（不包含 `CodeActionMenu` 这类懒加载逻辑创建的 ContextKey），导致该问题。

**Comment by bytemain** [comment]
还有另一个似乎也是 contextKey  的问题：
![CleanShot 2022-12-05 at 11 04 44@2x](https://user-images.githubusercontent.com/13938334/205540619-4ca9ecb2-40c9-43a9-9bd9-a7762f27359a.png)

![image](https://user-images.githubusercontent.com/13938334/205540639-9d19eaef-0a4b-4706-b2b5-a3ff6e94327f.png)

**Comment by Aaaaash** [comment]
https://github.com/opensumi/monaco-editor-core/pull/13
