### ISSUE TITLE
[BUG] 偶现 Git SCM 提示 未注册任何源代码管理实现 的问题

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2100]
**描述你的问题（Describe the bug）**
![image](https://user-images.githubusercontent.com/20262815/208635280-9b43aa0e-49af-4a0f-891d-d87cfea6f145.png)

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
是不是窗口开多了，消息串了

**Comment by Ricbet** [comment]
2.21 版本已修复
