### ISSUE TITLE
[BUG] Git SCM 面板偶现菜单图标重复渲染的问题

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2126]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/209609364-6dbdf91b-eaf6-4105-9d8a-0590341aa0cf.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
这个问题偶尔就会出现，有啥好复现的路径吗？

**Comment by Ricbet** [comment]
是重复存在插件的问题，可关闭
