### ISSUE TITLE
[Question] 启动后点击最近的工作空间e:/test123,chrome浏览器是被关闭又重新打开了吗？

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2174]
ide-electron项目，使用selenium启动之后，自动化操作dom点击最近的工作空间e:/test123,chrome浏览器是被关闭又重新打开了吗？因为我发现当我再次使用自动化操作dom的时候提示我window被关闭了,如果先前的window被关闭了 我要如何能再次控制新的浏览器window呢![image](https://user-images.githubusercontent.com/23164065/210983075-0f6384ad-ee8a-45d6-ac23-1625b62080b1.png)

**Comment by erha19** [comment]
@767746649zyy  这块应该是欢迎页面没有处理好 Windows 下的路径问题，需要处理一下 ，代码见：https://github.com/opensumi/core/blob/939513e78e9cfa44c9187335ec6a70508bbd7df6/packages/electron-basic/src/browser/welcome/welcome.tsx#L37 这里的路径展示应该用 `new URI(workspace).codeUri.fsPath` 展示就行了。

**Comment by 767746649zyy** [comment]
启动的时直接就可以打开工作空间了是嘛

**Comment by 767746649zyy** [comment]
“路径展示用 new URI(workspace).codeUri.fsPath 展示就行了“ 这里只是修改了用作展示的内容，跟打开工作空间时浏览器被关闭又重新打开没有关联呀 可能我没理解你的意思 望解答 感谢

**Comment by erha19** [comment]
@767746649zyy 如果你采用的是 ide-electron 示例项目，你可以修改 https://github.com/opensumi/ide-electron/blob/8ac54e4c2964d5ddf549b23553069320bd95d724/src/browser/app.tsx#L16 去实现"启动的时直接打开指定工作空间" 的效果。

欢迎界面下，打开的项目的代码是下面这句 
```ts
windowService.openWorkspace(new URI(workspace), { newWindow: false })
```
最终调用的逻辑在这里

https://github.com/opensumi/core/blob/0469c5f4d54ed00d8ba6d5bae352b1239bed9f55/packages/core-electron-main/src/bootstrap/app.ts#261

如果期望新窗口打开，可以把 newWindow 设置为 true

**Comment by 767746649zyy** [comment]
明白了感谢
