### ISSUE TITLE
[BUG] Electron 打包后，vscode 插件注册TreeProvider 的tree item menu bar  回调函数回触发多次

### ISSUE THREAD

**Issue by wtc842017068** [opensumi/core#2187]
**描述你的问题（Describe the bug）**
Electron 打包后，vscode 插件注册TreeProvider 的tree item menu bar  回调函数回触发多次

我注册了一个回调函数到item的menu bar ，第一次点击正常。第二次点击，调用两次，第三次点击调用三次
**复现路径（To Reproduce）**
编写插件注册TreeProvider，通过package.json 向Item 注册menu bar（view/item/context ）,右键点击目录树，触发回调函数。点三次，后每次点击会触发三次。控制台提示，Ielectron 监听Event 数量过多

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@wtc842017068 请提供一下你使用的 OpenSumi 版本以及最好带上可复现问题的插件代码，方便我们复现该问题。

**Comment by erha19** [comment]
@wtc842017068 这里可能与 [ctxmenu/electron.ts](https://github.com/opensumi/core/blob/d84eb8980975d831cc2a3c3e8417e0164d65829f/packages/core-browser/src/menu/next/renderer/ctxmenu/electron.ts)  实现相关，导致部分命令会出现重复执行的问题。

会在 https://github.com/opensumi/core/issues/2359 统一处理。

**Comment by wtc842017068** [comment]
收到，感谢

**Comment by wtc842017068** [comment]
我这边发现了一个新的问题，我关闭devtools后之前的问题转变为如下现象。有两个Treeview,其中一个TreeviewProvider 右键为空菜单，右键点击多次。在另一个有右键菜单的Treeprovider 上右键点击，会多次触发右键菜单注册的command
