### ISSUE TITLE
[BUG] 主题搜索框输入关键词后，默认生效的主题有误；vscode 是正确的。

### ISSUE THREAD

**Issue by MichaelToLearn** [opensumi/core#2209]
**描述你的问题（Describe the bug）**
cmd+K、cmd+T 输入 light 后，搜索框中已经过滤了主题，但是整体主题没变，需要使用方向键再次切换才能生效；vscode 可以直接生效

**复
现路径（To Reproduce）**
1、切换到暗色主题。
2、键入 cmd+K、cmd+T，打开主题搜索框。
3、键入 light，此时搜索框结果中全部都是亮色主题。
4、观察此时的主题，却仍然是暗色主题，而且不是之前的暗色主题。
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/46712585/212800127-fbb92e7b-b8b6-4e7e-8f85-9a83221c4fd4.png">

vscode 测试无问题。
推测：搜索结果展示后，应用的主题并不是从搜索结果中选取的，而是从全部主题列表中选取的，因此就会设置为之前的暗色主题。

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
这应该优化一下 quick open 的筛选选择，感谢反馈

**Comment by Ricbet** [comment]
@winjo 这个问题看看？
