### ISSUE TITLE
[Question] 搜索命令 GIT:clone 后 点击 然后输入框输入git地址 按回车没反应 输入框也关不掉

### ISSUE THREAD

**Issue by zhangjs19970923** [opensumi/core#2211]
**描述你的问题（Describe you question here）**
搜索命令 GIT:clone 后  点击  然后输入框输入git地址   按回车没反应  输入框也关不掉

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/54264656/213107394-45b91e05-7bf4-4236-ac95-592bf6780603.png">

**Comment by zhangjs19970923** [comment]
是不是拉git仓库这块的逻辑得自己实现？  也没有提示我登录git账号

**Comment by Ricbet** [comment]
这应该是 git 插件适配的问题，我们修复一下，正常是会有一个下拉框选项的。
输入框的问题可以按 esc 关闭

**Comment by erha19** [comment]
duplicate https://github.com/opensumi/ide-startup/issues/40, 晚点我看一下
