### ISSUE TITLE
[BUG] 文件树颜色缺失

### ISSUE THREAD

**Issue by wangxiaojuan** [opensumi/core#2212]
现象：代码修改了，但是没有提交
预期效果
颜色变橙色
![image](https://user-images.githubusercontent.com/1762334/213352001-11b0a29f-5c17-479f-b7aa-d6a16ff5f7b5.png)
目前效果：
颜色无变化
![image](https://user-images.githubusercontent.com/1762334/213352034-8584b834-9029-4242-a44e-8d7b79a1cb20.png)

**Comment by erha19** [comment]
@wangxiaojuan 麻烦提供一下你这边使用的 OpenSumi 版本，同时检查 Git 插件是否成功启动，该颜色是通过 Git 插件提供的装饰逻辑提供

**Comment by Ricbet** [comment]
@wangxiaojuan 这个问题升级到 git 插件到 1.62.3 版本就可以了
