### ISSUE TITLE
[BUG] 3-Way Merge Editor styles issue

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2222]
**描述你的问题（Describe the bug）**
情况1：
![image](https://user-images.githubusercontent.com/9823838/215446466-13c96bf1-b2ba-4c84-a297-ff2beb9d4cab.png)
情况2：
![image](https://user-images.githubusercontent.com/9823838/215446491-c603c934-bf8b-40e5-92dc-6ac133b46168.png)

**复现路径（To Reproduce）**

情况 1：
在顶部第二行位置制造冲突后可复现
情况 2：
基于情况 1，先点击 `x` ，然后点击文件的 `撤销` 按钮后可复现

**预期表现（Expected behavior）**

装饰器及图标对齐

**环境信息（Environment）**

- OS: macOS
- Browser: Electron
- OpenSumi Version: 2.22.1

**Comment by Ricbet** [comment]
看截图应该是中间 result 视图的 codelens 影响了 stickiness 的位置计算

**Comment by Ricbet** [comment]
图标错位问题也已修复

**Comment by AhkunTa** [comment]
顺便把 Result 的国际化改了呗
