### ISSUE TITLE
[Question] 更新到版本2.21后右上角出现执行按钮，如何去掉

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2223]
**描述你的问题（Describe you question here）**
右上角的执行按钮在哪里隐藏掉，因为我们注册了自己的执行和暂停按钮
![image](https://user-images.githubusercontent.com/23164065/215642156-aca0f86e-068d-43e5-967e-89dcc12b830c.png)

**Comment by Ricbet** [comment]
看一下有哪个插件贡献了 editor/title/run 这个菜单项

**Comment by 767746649zyy** [comment]
debug-contribution里有注册
![image](https://user-images.githubusercontent.com/23164065/215654521-81146527-9c50-429b-8be2-718f5de75f07.png)

**Comment by Ricbet** [comment]
@767746649zyy 不是，我是说你激活的插件里的 package.json 文件有没有注册 editor/title/run 这个贡献点，例如像这样的
```
"contributes": {
    "menus": {
      "editor/title/run": [
        {
          "command": "xxxxxxx"
        }
      ]
    },
}
```

**Comment by 767746649zyy** [comment]
没有

**Comment by 767746649zyy** [comment]
我尝试通过menuId移除这个menu但是并不生效![image](https://user-images.githubusercontent.com/23164065/215678549-9aafe9f3-1b76-4c8e-9d9b-c2b87a10b0e7.png)

**Comment by 767746649zyy** [comment]
换了一种写法 可以了
![image](https://user-images.githubusercontent.com/23164065/215679250-7b2ebc0e-42fa-4851-ab57-0238b5f4d870.png)

**Comment by Ricbet** [comment]
是可以通过这种注销命令的方式去掉，但貌似没有找到根因
因为我们在 2.21 版本修复了这个问题，如果没有任务插件去注册 editor/title/run 贡献点的话是不会出现这个按钮的

或者你们试试 2.22 版本？

**Comment by 767746649zyy** [comment]
好的，你们速度好快 都有2.22版本啦
