### ISSUE TITLE
[BUG] 2.21版本 删除文件后，更改其他同类型文件名为刚才删除的文件的名字，显示有误

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2225]
### 操作步骤1：删除”11.lua”文件
![image](https://user-images.githubusercontent.com/23164065/215702595-cc3e4f9e-2dbc-43a2-a24a-4be64faf3ecb.png)
**2：更改“12.lua“文件名为“11.lua“**
![image](https://user-images.githubusercontent.com/23164065/215702869-c5fd2473-da7e-4347-b11e-21255030b4f0.png)
**显示11.lua已删除**
![image](https://user-images.githubusercontent.com/23164065/215703013-1c54d54d-78e5-493d-92e7-56646faf0cd4.png)
**预期效果：没有“已删除“三个字**

**Comment by Ricbet** [comment]
贴一下你们写的代码？

**Comment by Ricbet** [comment]
看起来像是自己注册上去的 toolbar 模块里有去获取文件名的逻辑，我们需要你提供更多信息 @767746649zyy

**Comment by 767746649zyy** [comment]
跟我们代码没关系，你们给的简易的electron框架里就有这个问题，(https://opensumi.com/zh/docs/integrate/quick-start/electron)，克隆git@github.com:opensumi/ide-electron.git

**Comment by Ricbet** [comment]
嗯，这个我们看一下
但还是建议下次可以根据我们的 issue 模版来提供更多信息，因为我们支持 web/electron/纯前端 三端，也有助于我们排查问题 @767746649zyy

**Comment by 767746649zyy** [comment]
https://user-images.githubusercontent.com/23164065/216220518-428e83c9-0553-4e69-8f1e-bc8e2cb3ce7a.mp4

看一下这个

**Comment by yantze** [comment]
看这个界面是很老的样式，是不是没有更新到最新版

**Comment by 767746649zyy** [comment]
21版本的，你们可以看一下22版本有没有这个问题，没有就关了吧

**Comment by yantze** [comment]
在 2.22.1 版本复现了，我们这里看下
