### ISSUE TITLE
[BUG] MergeEditor can not be opened on this conflicts case

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2232]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/9823838/216224132-bf456502-90f9-4730-8c85-3e1f58b171e6.png)

特定合并冲突类型无法调起冲突合并编辑器。

**复现路径（To Reproduce）**

以 `opensumi/core` 项目为例子

1. git checkout main 
2. git reset --hard 58523a9279df10af2b561276
3. 修改 `tools/playwright/src/output-view.ts` 文件，在代码中追加一行代码，提交 commit
4. git pull origin main 

**预期表现（Expected behavior）**

正常可通过合并编辑器处理冲突，VS Code 下目前可正常通过合并编辑器处理

![image](https://user-images.githubusercontent.com/9823838/216224371-0f2e3547-1671-4471-8dc7-254f0d1d10cf.png)

**环境信息（Environment）**

- OpenSumi Version: 2.22.1

**Comment by Ricbet** [comment]
这个冲突文件他的类型是 both added，而 git 插件里面只对 both modified 的文件类型做了 open.mergeEditor 处理，所以这是正常的打开表现

git 插件这样处理的原因估计是因为，both added 的情况下，这俩分支的共同祖先分支 base 内容是 `空` 的，所以如果还是以 3-way 视图来展示的话，中间的 base 视图就是空白的了，这样的交互反而降低了解决冲突的效率
