### ISSUE TITLE
[BUG] 终端启动失败标题应该跟着改变

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#224]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/13938334/147527212-3ffd99dd-71f9-44bf-b567-18bac8d36ccf.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by HadesTang** [comment]
it seems that this issue has been solved.
