### ISSUE TITLE
[FEATURE] Please use translation for this placeholder. Thank you!

### ISSUE THREAD

**Issue by nguyenhongphat0** [opensumi/core#2244]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

Pressing Ctrl+F on the Terminal shows a search box in Chinese language even though the global language is set to English:

![z4073271931428_3627ee0e58b4da8c9ecd858bcd6f5610](https://user-images.githubusercontent.com/29925961/216871259-3d1ace41-58a0-4f03-8982-7c228139e4bc.png)

**描述你预期的功能表现（Describe the solution you'd like）**

Please put the placeholder inside a translatable string. Thank you!

**描述你考虑过的替代方案（Describe alternatives you've considered）**

N/A

**补充信息（Additional context）**

https://github.com/opensumi/core/blob/e01ac8905f003a1ae0fdea2bd585de068712c964/packages/terminal-next/src/browser/component/terminal.view.tsx#L101

**Comment by erha19** [comment]
@nguyenhongphat0 you can create a pr for this fix on v2.22 branch, we will publishing a patch version later.

**Comment by Ricbet** [comment]
@wangxiaojuan 看一下这个问题哈

**Comment by nguyenhongphat0** [comment]
> @nguyenhongphat0 you can create a pr for this fix on v2.22 branch, we will publishing a patch version later.

Hi, I've submitted a PR; please review #2249. Thank you!
