### ISSUE TITLE
[Question]  我想在webview关闭的时候阻塞住，然后弹窗给用户来决定后续是否保存内容

### ISSUE THREAD

**Issue by wtc842017068** [opensumi/core#2248]
**描述你的问题（Describe you question here）**
当前的现状是可以通过onDidDispose 获取到webview关闭的事件，但是无法阻塞住。会导致页面先被关闭后，才有弹窗

**Comment by erha19** [comment]
@wtc842017068 有简单的可复现的例子吗？提供一下方便做排查，可能是 API 实现上有一些问题。
