### ISSUE TITLE
[BUG] SCM面板问题

### ISSUE THREAD

**Issue by AhkunTa** [opensumi/core#2255]
**描述你的问题（Describe the bug）**
scm面板存在部分问题

**复现路径（To Reproduce）**
1. 右键点击SCM面板里的文件夹报错

<img width="1178" alt="截屏2023-02-08 16 46 59" src="https://user-images.githubusercontent.com/31676999/217479984-9d8f5772-5ef5-4860-8b08-bcdfe8eacff2.png">

2. 树状列表和平铺列表切换状态后无法点击，无法展开收起

https://user-images.githubusercontent.com/31676999/217481151-6ea15b72-5cd5-4cd5-9220-c685247d6493.mov

**问题截图（Screenshots）**

**环境信息（Environment）**

- Git Extension Version: 1.62.3
- OpenSumi Version: 2.22.2

**Comment by Ricbet** [comment]
第 2 个问题已经解决了，第 1 个问题仍然存在

**Comment by Ricbet** [comment]
@AhkunTa 再看看哈，可以修复一下
