### ISSUE TITLE
[BUG] Marked's deprecated warning message should be removed

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2256]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/9823838/217501684-a3d66a17-4935-4206-a59f-cd0db840b589.png)

**环境信息（Environment）**

- OpenSumi Version: 2.22

**Comment by stealth-bombeer** [comment]
Greetings, I've dealt with a similar problem before, and I could able to resolve it, so please assign it to me.

**Comment by erha19** [comment]
@stealth-bombeer thanks, if you have any questions, feel free to ask.

**Comment by erha19** [comment]
@stealth-bombeer Hi, are you still working on resolving this issue?

**Comment by bytemain** [comment]
We reverted #2591 because #2725.
