### ISSUE TITLE
[BUG] Extension Marketplace keep loading forever

### ISSUE THREAD

**Issue by nguyenhongphat0** [opensumi/core#2261]
**描述你的问题（Describe the bug）**

Our users could not search and install extensions on the Marketplace. It keeps loading forever (see the recording below)

**复现路径（To Reproduce）**

https://user-images.githubusercontent.com/29925961/217784320-bb60c93e-a501-4c5d-9a1c-8dc6c8968511.mov

![Detail console logs](https://user-images.githubusercontent.com/29925961/217784361-76d21c3c-689b-4a8a-a488-4186cd3888b4.png)

**预期表现（Expected behavior）**

The list should be filled with extensions matched the name. For example:
![Screenshot 2023-02-09 at 17 19 07](https://user-images.githubusercontent.com/29925961/217784876-b9d3d123-d59c-4d5c-82ac-16b7f1ef2270.png)

**环境信息（Environment）**

- OS: macOS 13.1 (22C65) Apple M1
- Browser: Electron
- OpenSumi Version: 2.22.1

**补充信息（Additional context）**

Original issue: https://mini.zalo.me/community/2984525288170401735/khong-the-enable-marketplace-

**Comment by erha19** [comment]
@nguyenhongphat0 see https://opensumi.com/en/docs/integrate/universal-integrate-case/custom-marketplace-entrypoint , the `smart-ide` mirror doesn't work, you can use the `Eclipse Open VSX` or `Ant CloudIDE Marketplace`.

**Comment by nguyenhongphat0** [comment]
Thank you, I solved the issue by using Eclipse Open VSX!
