### ISSUE TITLE
[BUG] SCM 的 badge 数字过大导致显示有问题

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2272]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/218366714-3fe98dad-06ad-451a-ada9-bb633240d0c9.png)

应该在超过 99 时显示 99+

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by wangxiaojuan** [comment]
https://github.com/opensumi/core/pull/2274
