### ISSUE TITLE
[BUG] ValidateInput delete键删除不生效

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2285]
**描述你的问题（Describe the bug）**
ValidateInput组件输入内容后delete键删除失效
**复现路径（To Reproduce）**
1.输入框输入文字‘1234’
2.光标移动到2和3之间
3.按一下 delete键 

**预期表现（Expected behavior）**

预期3被删除 实际3没有被删除

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: Windows10
- Browser: electron
- OpenSumi Version: 2.21.10

**补充信息（Additional context）**

**Comment by erha19** [comment]
@767746649zyy 这个问题我来看一下

**Comment by erha19** [comment]
@767746649zyy 目前我无法复现你这边这个问题，是否可以录屏展示一下？另外，你把光标移动到 2-3 之间，删除键应该是删除数字 2 才是对的？

**Comment by 767746649zyy** [comment]
delete键删除，不是backspace键删除

**Comment by erha19** [comment]
> delete键删除，不是backspace键删除

@767746649zyy 接了个键盘尝试了一下，功能目前也是正常的，你有具体的功能代码或复现案例吗？是否独立做了快捷键监听？

**Comment by erha19** [comment]
@767746649zyy 这个问题还存在吗？

**Comment by 767746649zyy** [comment]
等我下午验证一下告诉你吧

**Comment by 767746649zyy** [comment]
我看github上clone下来的简单例子没问题，可是我们的项目里delete删除键不向后删除 奇怪

**Comment by erha19** [comment]
@767746649zyy 这块需要你提供一下可复现案例，可以检查一下是否有自定义的逻辑，例如注册了全局的 delete 快捷键导致的问题
