### ISSUE TITLE
[Question] 请问有没有现成的二进制包？

### ISSUE THREAD

**Issue by anycodes** [opensumi/core#2286]
我正在做一个 WebIDE 的平台，可以支持很多种 WebIDE，目前想要集成 opensumi，想了解一下，咱们有没有 WebIDE 侧的二进制包，直接通过一行命令就能启动的？如果没有的话只能自己打这个包了。

**Comment by erha19** [comment]
@anycodes 我们提供了 Docker 部署的简单示例，可以看一下 https://github.com/opensumi/ide-startup
