### ISSUE TITLE
[BUG] web-lite 版本，github 示例首次渲染文件树列表为空，需要手动刷新才能展示

### ISSUE THREAD

**Issue by fankangsong** [opensumi/core#2308]
**描述你的问题（Describe the bug）**
startup-web-lite 的纯前端版本，`yarn start` 启动后，首次渲染左侧文件夹树列表为空，虚手动点击“刷新”按钮后可展示。

![Snipaste_2023-02-17_17-17-01](https://user-images.githubusercontent.com/554934/219603500-abe09afa-76b0-49e6-b860-fd810baa8534.png)

**Comment by erha19** [comment]
@fankangsong  可以参考一下这里的修改 https://github.com/opensumi/ide-startup-lite/pull/44，问题出现在首次加载时网络请求一般会稍慢，而 BrowserFS 读取文件时较快，最终导致读取到的文件不准确，这里修改了 BrowserFSProvider，在等待 HttpFileService 初始化完成后在进行文件读取操作。

**Comment by fankangsong** [comment]
> 

感谢支持，非常给力👍。
