### ISSUE TITLE
[Question] does sumi support custom layout 

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2326]
**描述你的问题（Describe you question here）**
It seems sumi only support customize the slot content, is it possible to customize the layout component, to use other react component replacing @opensumi/ide-main-layout

**Comment by erha19** [comment]
@geekeren we are using `@opensumi/ide-main-layout` to associate the view, you can fork this module and remained some services logic, it's ok to replace the built-in component with your custom React Component, but this modification will be relatively difficult, and you need to have enough understanding of the framework.

You can also take a look at this issue https://github.com/opensumi/docs/issues/83 to get an overview of the current view customization capabilities, and we will write this part into the document later.
