### ISSUE TITLE
[Question] PreferenceContribution贡献点咨询……

### ISSUE THREAD

**Issue by hnhhzy** [opensumi/core#2328]
https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config

比如这里的 appName是如何配置的？

```
import { PreferenceContribution } from '@opensumi/ide-core-browser';
import { Domain, PreferenceSchema } from '@opensumi/ide-core-common';

export const PEditorPreferenceSchema: PreferenceSchema = {
    type: 'object',
    properties: {
        'appName': {
        type: 'string',
        default: 'test',
        description: 'test'
        }
    }
};

@Domain(PreferenceContribution)
export class PEditorPreference implements PreferenceContribution {
  public schema: PreferenceSchema = PEditorPreferenceSchema;
}
```

好像毫无反应。。

**Comment by erha19** [comment]
@hnhhzy 以 WebIDE 的启动案例为例，这里的代码 https://github.com/opensumi/ide-startup/blob/main/src/browser/index.ts#L12~L28 ，这里传入 `renderApp` 方法的参数便是前端集成配置中的 AppConfig，你可以在这里追加：
```ts
renderApp({
  // 追加配置
  appName: 'OpenSumi',
  // 原有内容
  modules: [
    ...CommonBrowserModules,
    ExpressFileServerModule,
  ],
  layoutConfig,
  useCdnIcon: false,
  useExperimentalShadowDom: false,
  defaultPreferences: {
    'general.theme': 'opensumi-dark',
    'general.icon': 'vscode-icons',
  },
  defaultPanels: {
    'bottom': '@opensumi/ide-terminal-next',
    'right': '',
  },
});
```

**Comment by hnhhzy** [comment]
uriScheme
workspaceDir也都是再这里传吗。
主要是文档有点看不懂。。。
文档说“定义可见 @opensumi/ide-core-browser 中的 AppConfig 定义。”
我翻去 https://github.com/opensumi/core/tree/8a433729452ba8397a553e9a886796b467774106/packages/core-browser/src
又找不到相关的定义的复写的地方。。

**Comment by erha19** [comment]
@hnhhzy  文档这块目前仅提取了部分常用的配置项，完整配置项可以看这里 https://github.com/opensumi/core/blob/9e931275bd5bb74af8309e8bf54ad0d27baf165a/packages/core-browser/src/react-providers/config-provider.tsx#L14~#L245 ，TS 代码内你可以直接通过代码跳转定义的方式看到完整的参数属性。

**Comment by hnhhzy** [comment]
这个地方我有找到

主要是文档看的我有点迷糊。。我想知道按照文档中
“OpenSumi 提供了自定义配置能力，基于 OpenSumi 的 [Contribution Point](https://opensumi.com/zh/docs/develop/basic-design/contribution-point) 机制，只需要实现 PreferenceContribution 即可进行配置注册。”

他这个应该怎么做才是正确的。

我在src\browser\index.ts里renderApp的modules添加了我自己的PEditorModule

PEditorModule
`@Injectable()
export class PEditorModule extends ElectronBasicModule {
  providers = [
    {
      token: IHelloService,
      useValue: createElectronMainApi(IHelloService),
    },
    PEditorPreference,
    EditorEmptyComponentContribution,
  ];
}`

PEditorPreference
`import { PreferenceContribution } from '@opensumi/ide-core-browser';
import { Domain, PreferenceSchema } from '@opensumi/ide-core-common';

export const PEditorPreferenceSchema: PreferenceSchema = {
    type: 'object',
    properties: {
        'appName': {
        type: 'string',
        default: 'test',
        description: 'test'
        }
    }
};

@Domain(PreferenceContribution)
export class PEditorPreference implements PreferenceContribution {
  public schema: PreferenceSchema = PEditorPreferenceSchema;
}`

我这样的写法是哪里错了吗？

**Comment by erha19** [comment]
@hnhhzy 你这里的代码实现上应该没啥问题，理论上你后续可以通过下面方式获取到配置值
```ts

@Autowired(PreferenceService)
protected readonly preferenceService: PreferenceService;

...
this.preferenceService.get('appName')
```

这里的配置指的是 IDE 内的 `settings.json` 或者说框架运行态的配置项，而 `AppConfig` 是为集成方提供了一种在集成阶段进行预配置的能力，实现上存在差异，指的也是不同的东西。

**Comment by hnhhzy** [comment]
原来如此。。。这是不同的东西
那在自定义集成参数里，我要复写AppConfig里的参数，在不动core的代码情况下有什么办法吗？
而不是再renderApp这里。

**Comment by erha19** [comment]
@hnhhzy  文档这块我们优化一下，另外，你这里应该采用的是 `ide-electron`  这个示例仓库修改的，不同的一点是，由于示例项目考虑了通过空 IDE 界面唤起的情况，将 `workspaceDir` 从 `electronEnv.env.WORKSPACE_DIR` 中获取 , 见 ：
https://github.com/opensumi/ide-electron/blob/8ac54e4c2964d5ddf549b23553069320bd95d724/src/browser/app.tsx#L17

这里的参数最终还是传入并构建了 `new ClientApp(...)`，原理上是一致的，你如果需要对 `workspaceDir` 做额外的配置，参考上面指出的这段代码即可。

**Comment by hnhhzy** [comment]
https://github.com/opensumi/core/blob/df680e662bb52a381f02c6c237a3c903d07890d2/packages/workspace/src/common/constants.ts 这个里面的
export const DEFAULT_WORKSPACE_SUFFIX_NAME = 'sumi-workspace';

目前还没办法覆写吧

**Comment by hnhhzy** [comment]
electron目前的版本还没到最新，我手动指定最新core好像会报错。。

另外插件需要^1.67.0有什么办法可以解决吗？ opensumi好像是1.63.2的内核

**Comment by hnhhzy** [comment]
希望可以支持 https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack
haxe插件

**Comment by erha19** [comment]
> electron目前的版本还没到最新，我手动指定最新core好像会报错。。
> 
> 另外插件需要^1.67.0有什么办法可以解决吗？ opensumi好像是1.63.2的内核

@hnhhzy  https://github.com/opensumi/core/discussions/1885#discussioncomment-4025680 参考这里的做法

在 `ide-startup` 项目中也有示例，可以一起看下 https://github.com/opensumi/ide-startup/blob/bd9327994db462e2d46c214347cd293178e3cc3b/src/extension/ext-host.ts

**Comment by erha19** [comment]
> 希望可以支持 https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack haxe插件

@hnhhzy 你可以尝试在框架内使用，有问题可以另外提 Issue 反馈，另外，如果要升级内核版本，可以参考发布日志中的 Changelog 信息进行升级，可能会有一部分 Breaking Changes https://github.com/opensumi/core/blob/v2.22/CHANGELOG.md#breaking_changes_2.22.0 .

**Comment by hnhhzy** [comment]
我有看到 https://github.com/opensumi/ide-startup/blob/bd9327994db462e2d46c214347cd293178e3cc3b/src/extension/ext-host.ts 这个issus，也尝试去改了 app\extension\index.js的版本号。但是会报错。估计他有用到高版本的特性。。

**Comment by erha19** [comment]
@hnhhzy 你这里的报错为权限问题  `Permission denied` ，影响日志文件的写入，可以修改一下日志文件位置，避免这块问题

**Comment by hnhhzy** [comment]
一样，改了位置他也是Permission denied 这个应该是electron版本的bug.

从这个输出错误信息来看，之前是说版本低，改了版本以后说是 .[node][extHost:error] [extHost:error] Error: Invalid commandline class : src.Main should be MainError: Invalid commandline class : src.Main should be Main
应该还是这个插件用了新版本的特性。

**Comment by hnhhzy** [comment]
![image](https://user-images.githubusercontent.com/215678/220893118-a9db5465-8da2-4fcc-acb8-849bc60134d1.png)
开发者工具看插件错误是这样

**Comment by erha19** [comment]
@hnhhzy 看起来是你使用的插件内报错，使用的插件及版本提供一下

**Comment by hnhhzy** [comment]
https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack
这个插件包 应该是Haxe和HashLink Debugger这两个报错，分别是language server和debug工具

**Comment by erha19** [comment]
后续在 https://github.com/opensumi/core/issues/2331 这里更新进度，晚点我们排查看下，可能是插件 API 适配上的问题。

**Comment by hnhhzy** [comment]
感谢 目前opensumi有讨论群组的吗？我看官网的钉钉二维码扫不了。

**Comment by erha19** [comment]
> 感谢 目前opensumi有讨论群组的吗？我看官网的钉钉二维码扫不了。

感谢反馈，二维码我们修复一下，你可以先通过群号搜索加一下群 34355491
