### ISSUE TITLE
[FEATURE] 希望添加对haxe语言的插件支持

### ISSUE THREAD

**Issue by hnhhzy** [opensumi/core#2331]
https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack

**Comment by erha19** [comment]
@hnhhzy 当前插件在 OpenSumi 下是支持的，运行效果如下：

https://user-images.githubusercontent.com/9823838/222650744-25924681-e59a-4d5b-b28c-973acbbecc39.mp4

由于插件同步的问题，目前 `https://marketplace.opentrs.cn/square` 及 `https://open-vsx.org/` 均没有该插件下载，你可以通过手动下载插件包本地解压缩的方式进行使用。

即 `xxx.visx` 重命名为 `xxx.zip` 后解压，取内部的 `extension` 目录作为插件根目录，相关插件地址可以看你上面提供的报地址链接
https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack

**Comment by hnhhzy** [comment]
请问方便同步进ide-electron吗？我在ide-electron里尝试还是不正常

**Comment by hnhhzy** [comment]
不对，我看了一下也还是不正常

**Comment by hnhhzy** [comment]
[3DSprite.zip](https://github.com/opensumi/core/files/10887465/3DSprite.zip)

这是测试工程。
[安装好haxe环境后安装一下](https://heaps.io/documentation/installation.html) 这里是haxe的环境、hashlink环境安装
'''
haxelib install hlopenal
haxelib install hlsdl
haxelib install hldx
'''
安装库

然后f5不正常，ctrl单击进类也不正常。代码提示也不正常

**Comment by erha19** [comment]
@hnhhzy 麻烦提供一下输出里面 `Haxe` 完整的输出日志，应该是语言服务没有正常启动，类似 `/usr/local/lib/haxe/lib/heaps/1,10,0/hxd/App.hx:13: character 7 : Invalid character 0x2013` ?

**Comment by hnhhzy** [comment]
```
Debugger listening on ws://127.0.0.1:1707/8287d21c-1e63-41ff-9fa7-50d24e8f6679
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6002
Done.
[Error - 10:40:36] Request textDocument/definition failed.
  Message: Invalid commandline class : src.Main should be Main
  Code: -32603 
[Error - 10:40:36] Request textDocument/hover failed.
  Message: Invalid commandline class : src.Main should be Main
  Code: -32603 
[Error - 10:40:37] Request textDocument/definition failed.
  Message: Invalid commandline class : src.Main should be Main
  Code: -32603 

```

**Comment by hnhhzy** [comment]
语言服务有启动，但是他没办法读取环境变量里的库

**Comment by erha19** [comment]
@hnhhzy 看了一下可能与这个 PR 修复内容有关联 https://github.com/opensumi/core/pull/2347 ，目前我这边本地与 VS Code 内的表现是一致的，语言服务均会有下面的报错
```log
/usr/local/lib/haxe/lib/heaps/1,10,0/hxd/App.hx:13: character 7 : Invalid character 0x2013
```

我基于当前 main 分支发了一个 RC 版本，一会发布完成后你可以到下面地址拿一下版本测试一下

https://github.com/opensumi/core/actions/runs/4339405636

**Comment by hnhhzy** [comment]
我用的ide-electron能同步一份吗，一会下午我也试下

**Comment by erha19** [comment]
@hnhhzy 这部分是测试版本代码，暂时不会往示例项目同步，你可以自行修改项目内 `package.json` 中的 `@opensumi/*` 系列包版本到这个版本上 `2.22.7-rc-1678070695.0` , 然后重新安装依赖运行一下。

**Comment by hnhhzy** [comment]
替换2.22.7-rc-1678070695.0
build报错了
```
webpack 5.75.0 compiled with 1 warning in 4948 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:node" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by erha19** [comment]
@hnhhzy 你用最新的 https://github.com/opensumi/ide-electron 项目修改版本号测试吧，你本地这个项目应该是没适配过这块 BreakingChange 修改的 https://github.com/opensumi/ide-electron/pull/56

**Comment by hnhhzy** [comment]
我用了2.22.7-rc-1678070695.0还是不正常，我试试 https://github.com/opensumi/ide-electron

**Comment by hnhhzy** [comment]
我编译插件看看吧。。。到底是什么原因导致的

**Comment by hnhhzy** [comment]
像是
`final hxmlFileWatcher = workspace.createFileSystemWatcher("**/*.hxml");`
这个api没生效。导致读不到项目下的hxml正确的环境变量

**Comment by erha19** [comment]
@hnhhzy 我本地的那个报错是我错误修改 heaps 文件导致的，重装一下 lib 就解决了，目前我本地看代码跳转是正常生效的

https://user-images.githubusercontent.com/9823838/223073835-71c663f1-3346-4a1a-a734-0cd9dbb95827.mp4

另外，调试功能链路也是通畅的，运行调试时后端会报错 `/bin/sh: hl: command not found` （macOS 环境） , 应该是少安装了命令行工具，这块不是很熟，你可以看一下

**Comment by hnhhzy** [comment]
我晚点试试网页版的。奇了怪了，我在[ide-electron](https://github.com/opensumi/ide-electron)版本，我在跟插件的代码。workspace.createFileSystemWatcher像是没正确回调，导致他找不到项目下的hxml文件读取环境

**Comment by erha19** [comment]
`workspace.createFileSystemWatcher` 这个 API 是用于获取文件的 Watch 句柄，用于监听文件变化的，应该是修改文件后才能获取到回调信息的

**Comment by erha19** [comment]
@hnhhzy 代码如果执行到你发的地方，本地报错应该不是 `/bin/sh: hl: command not found`, 另外，如果你本地连代码跳转都不行的话，那可能还是插件没装好或者是版本问题。

你也可以克隆一下这个仓库 https://github.com/opensumi/core ，将插件 link 到 `tools/extensions` 目录下面进行测试，运行的命令就是 

```bash
$ yarn && yarn run init
$ MY_WORKSPACE={你的测试项目路径} yarn start
```

**Comment by hnhhzy** [comment]
我用vscode
插件进入
```
context.subscriptions.push(displayArguments.onDidChangeArguments(onDidChangeDisplayArguments));

	function onDidChangeDisplayArguments(displayArguments:Array<String>) {
		rawArguments = displayArguments;
		window.showErrorMessage("did==" + rawArguments.toString());
		update();
	}
```
会弹出compile.hxml

在opensumi里不会进这个方法。郁闷了

**Comment by hnhhzy** [comment]
最终问题出在这个地方……
```
			if (files != null) {
				foundFiles = files.map(uri -> pathRelativeToRoot(uri)).filter(path -> Path.withoutDirectory(path) != "extraParams.hxml");
			}

			window.showErrorMessage(Std.string(foundFiles));
```

vscode可以正确打印出文件名，

但是opensumi打印不出文件名

src/vshaxe/HxmlDiscovery.hx:44: ===========aaa(files)===============
src/vshaxe/HxmlDiscovery.hx:45: [
  t {
    scheme: 'file',
    authority: '',
    path: '/MakeProject/Haxe/3DSprite/compile.hxml',
    query: '',
    fragment: '',
    _formatted: null,
    _fsPath: '\\MakeProject\\Haxe\\3DSprite\\compile.hxml'
  },
  t {
    scheme: 'file',
    authority: '',
    path: '/MakeProject/Haxe/3DSprite/compile copy 9.hxml',
    query: '',
    fragment: '',
    _formatted: null,
    _fsPath: '\\MakeProject\\Haxe\\3DSprite\\compile copy 9.hxml'
  },

**Comment by hnhhzy** [comment]
已发现问题windows下 uri.fsPath 未正确读出盘符名

**Comment by erha19** [comment]
@hnhhzy 我根据测试情况写了一个修复，但我本地 Windows 机器上还有一些环境问题无法验证，你方便验证一下这个分支吗？ https://github.com/opensumi/core/pull/2381

**Comment by hnhhzy** [comment]
好 吃了饭回来试

**Comment by hnhhzy** [comment]
```
Error: Failed opening file C:\Users\Albin\.sumi-oss\logs\20230307\extHost.log for writing: Permission denied
    at createRotatingLogger (E:\MarkProject\HeapsPlus\PEditor\node_modules\spdlog\index.js:34:9)
    at E:\MarkProject\HeapsPlus\PEditor\node_modules\spdlog\index.js:27:7
    at E:\MarkProject\HeapsPlus\PEditor\node_modu...[node][extHost:error] [extHost:error] [Extension-Host] o.workspace.registerTimelineProvider is not a function

TypeError: o.workspace.registerTimelineProvider is not a functionError: o.workspace.registerTimelineProvider is not a function
        at p.ensureProviderRegistration (E:\MarkProject\HeapsPlus\PEditor\extensions\vscode.git\dist\main.js:2:1010965)
        at p.onRepositoriesChanged (E:\MarkProject\HeapsPlus\PEditor\extensions\vscode.git\dist\main.js:2:1011215)
        at Emitter.fire (E:\MarkProj...[node][extHost:error] [extHost:error] Error: Invalid commandline class : src.Main should be MainError: Invalid commandline class : src.Main should be Main
        at handleResponse (E:\MarkProject\HeapsPlus\PEditor\extensions\nadako.vshaxe-2.27.0\bin\index.js:1:172812)
        at processMessageQueue (E:\MarkProject\HeapsPlus\PEditor\extensions\nadako.vshaxe-2.27.0\bin\index.js:1:168885)
        at Immediate.<anonymous> (E:\MarkProject\HeapsPlus\PEditor\extensions\nadako.vshaxe-2.27.0\bin\index.js:1:16864...[node][extHost:error] Code actions of kind 'quickfix' requested but returned code action is of kind 'source.sortImports'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code action.
Code actions of kind 'quickfix' requested but returned code action is of kind 'source.organizeImports'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code action.

```

奇怪 好像报错另外个了o.workspace.registerTimelineProvider is not a function

**Comment by hnhhzy** [comment]
这个path能打到2.22.7-rc-1678070695.0上试吗？ 这个分支我运行不起来。。

**Comment by erha19** [comment]
> 这个path能打到2.22.7-rc-1678070695.0上试吗？ 这个分支我运行不起来。。

https://github.com/opensumi/core/actions/runs/4351839461 一会用一下这里的版本 @hnhhzy

**Comment by hnhhzy** [comment]
插件代码如下：
```
			x.appendLine("==============开始foundF读取========");
			if (files != null) {
				x.appendLine(Std.string(files));
				foundFiles = files.map(uri -> pathRelativeToRoot(uri)).filter(path -> Path.withoutDirectory(path) != "extraParams.hxml");
			}
			x.appendLine(Std.string(foundFiles));
			x.appendLine("==============开始foundF读取========");
```

2.22.7-rc-1678175723.0中少了盘符名
```
==============开始foundF读取========
[file:///MakeProject/Haxe/3DSprite5/compile.hxml]
[]
==============开始foundF读取========
```
vscode中正常
```
==============开始foundF读取========
[file:///e%3A/MakeProject/Haxe/3DSprite5/compile.hxml]
[compile.hxml]
==============开始foundF读取========

```

2.22.7-rc-1678175723.0的patch中，`createFileSystemWatcher`的`onDidCreate`和`onDidDelete`的回调的uri正常了，之前不正常
```
		fileWatcher = workspace.createFileSystemWatcher(pattern, false, true, false);
		fileWatcher.onDidCreate(uri -> {
			files.push(pathRelativeToRoot(uri));
			onFilesChanged();
		});
		fileWatcher.onDidDelete(uri -> {
			files.remove(pathRelativeToRoot(uri));
			onFilesChanged();
		});
```

**Comment by erha19** [comment]
@hnhhzy 发了进一步的修复版本 https://github.com/opensumi/core/actions/runs/4360557088

**Comment by hnhhzy** [comment]
插件完全正常了。不过删除文件会出错

**Comment by erha19** [comment]
@hnhhzy 修复项目启动后控制台报错问题 https://github.com/opensumi/core/actions/runs/4360780319

**Comment by hnhhzy** [comment]
使用`2.22.7-rc-1678245382.0`分支插件功能看起来已经正常了。
但是文件树中删除文件好像有问题。另外加载项目后，会有如下的错误，暂时不知道影响了什么

```
[node]server listen on path \\.\pipe\sumi-ipc-electron-windowmzeEhySCy8VbOzs7mlGU2
ready
[node][node:error] Failed to search on path file:///e%3A/MakeProject/Haxe/3DSprite5.
Error: spawn E:\MakeProject\HeapsPlus\PEditor\node_modules\@opensumi\vscode-ripgrep\bin\rg.exe ENOENT
[node][extHost:error] [extHost:error] [Extension-Host] Failed opening file C:\Users\hnhhzy\.sumi-oss\logs\20230308\extHost.log for writing: Permission denied

Error: Failed opening file C:\Users\hnhhzy\.sumi-oss\logs\20230308\extHost.log for writing: Permission denied
    at createRotatingLogger (E:\MakeProject\HeapsPlus\PEditor\node_modules\spdlog\index.js:34:9)
    at E:\MakeProject\HeapsPlus\PEditor\node_modules\spdlog\index.js:27:7
    at E:\MakeProject\HeapsPlus\PEditor\node_mo...[5156:0308/111733.570:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE i
```

另外下断点调试后，调试面板没有变为继续按钮，控制台报错如下
```
[node][extHost:error] [error] [onDidChangeActiveTerminal] cannot find terminal with id: CODE_WINDOW_CLIENT_ID:1|Pr_33xcC1gRlk9OmsrOjo

[node][extHost:error] [error] [onDidChangeActiveTerminal] cannot find terminal with id: CODE_WINDOW_CLIENT_ID:1|Pr_33xcC1gRlk9OmsrOjo
```

![d661c4b9fc6cbfd0df2dfbb10f2a7c0](https://user-images.githubusercontent.com/215678/223611715-008b012a-2ba9-46a9-aaf1-cb6d12092432.png)

**Comment by erha19** [comment]
@hnhhzy 我这边本地复现了调试的问题，但不存在本地无法删除文件的问题，目前是可以正常删除的。

https://user-images.githubusercontent.com/9823838/223682506-2b9849e1-0cd9-4338-a839-4f26b5f7ce4d.mp4

**Comment by hnhhzy** [comment]
我是ide-electron版本。在cmd里用yarn start启动的。晚点我也试试web版本

**Comment by hnhhzy** [comment]
web版可以正常删除文件，ide-electron不行

**Comment by erha19** [comment]
@hnhhzy 调试功能已支持，可以用一下这里的版本 https://github.com/opensumi/core/actions/runs/4381858668

**Comment by hnhhzy** [comment]
调试已正常。
删除文件还是不行
