### ISSUE TITLE
[BUG] 空文件的撤销快捷键失效

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2349]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/222039013-a019170d-ff85-49ea-a402-dcb0fad1898a.png)

按 cmd + z 失效，其他文件是可以的

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by pipiiiiii** [comment]
这个没复现，是不是加载了某些模块导致的
