### ISSUE TITLE
[BUG] Electron 环境删除文件会提示两次

### ISSUE THREAD

**Issue by yantze** [opensumi/core#2359]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
1. cd ./core 
2. yarn run init
3. yarn run start:electron

Electron  稳定复现，Web 不会出现

**预期表现（Expected behavior）**
只用删除一次即可

**问题截图（Screenshots）**

https://user-images.githubusercontent.com/2226423/222347013-025d9af1-aa6a-4c2a-bf38-43b0684ba3a9.mov

**环境信息（Environment）**

- OS: macOS 13.0
- Browser: electron
- OpenSumi Version: v2.22 分支

**补充信息（Additional context）**

**Comment by erha19** [comment]
本地复现了，我看一下这个问题

**Comment by erha19** [comment]
相关问题 https://github.com/opensumi/core/issues/2187

**Comment by erha19** [comment]
排查到问题出在 PR https://github.com/opensumi/core/pull/1583 ，这里引入了针对本地客户端通信的 capture 逻辑，将 IPCRenderer 的 `ipcRenderer.on` 监听额外进行了包裹，如：
```ts
  const originalIpcRendererOn = ipcRenderer.on;
  ipcRenderer.on = (channel, handler) => {
    const proxyHandler = (event, ...args) => {
      capture({ ipcMethod: 'ipcRenderer.on', channel, args });
      handler(event, ...args);
    };

    return originalIpcRendererOn.call(ipcRenderer, channel, proxyHandler);
  };
```

这里的逻辑处理会导致 [utils/electron.ts](https://github.com/opensumi/core/blob/d6fd4002f52264d21277a58e64587f82a222a74e/packages/core-browser/src/utils/electron.ts#L27~L29) 中 `ElectronIpcRenderer.removeListener` 卸载逻辑失效，进而导致 [ctxmenu/electron.ts#L112](https://github.com/opensumi/core/blob/d84eb8980975d831cc2a3c3e8417e0164d65829f/packages/core-browser/src/menu/next/renderer/ctxmenu/electron.ts#L112) 下相关的通信监听没有被成功 `dispose`，最终导致了这个重复执行问题。

**临时的解决方案：关闭所有入口针对 `devtools` 的配置。**

**Comment by tyn1998** [comment]
@erha19 收到，我先看看上下文~

**Comment by tyn1998** [comment]
做了个大复习😆

## 原因分析

直接原因正如 @erha19 指出的那样：这里出现了二重代理。

1. [preload](https://github.com/opensumi/core/blob/5d8e4fcf717531446c838d142f7601699fd50d0f/packages/core-electron-main/browser-preload/index.js#L24-L32)中先代理了一次ipcRenderer.on（`proxyHandler`），并将代理后的ipcRenderer作为`global.ElectronIpcRenderer`暴露给renderer进程。

2. renderer进程中，[core-browser/src/utils/electron.ts](https://github.com/opensumi/core/blob/d6fd4002f52264d21277a58e64587f82a222a74e/packages/core-browser/src/utils/electron.ts#L17-L60)中的操作相当于又代理了一次ipcRenderer.on（`wrappedListener`）。

3. 于是，由于`.removeListener(name, listener)`方法的listener必须和`.on(name, listener)`时的listener完全一样才能成功移除，但是现在两个对应的listener其实分别是`wrappedListener`和`proxyHandler`，而不是都为`wrappedListener`。于是造成了dispose逻辑不会成功。

## 对 Electron IPC 通信的新认识

去年我在完成ASoC“实现一个查看OpenSumi通信消息的Chrome DevTools插件”任务时，其实对Electron IPC通信消息的认识是比对前后端RPC通信消息的认识要模糊很多的。

对于RPC消息，我知道其核心思想是通过Proxy将调用的服务方法转换为RPC消息，到达对方后再通过Proxy把RPC消息转换成方法调用。前后端可以互相调用对方的服务。这里的前端可能是web前端，也可能是处于remote模式的Electron端。

但是在那时，对于Electron客户端，我其实不大清楚Main和Renderer进程之间的通信内容主要是什么，在测试的时候只是知道与顶部菜单栏交互式是可以触发到IPC通信的。

这次看了几个相关代码：

- [core-common/src/menu.ts](https://github.com/opensumi/core/blob/main/packages/core-common/src/menu.ts)
- [core-browser/src/utils/electron.ts](https://github.com/opensumi/core/blob/d6fd4002f52264d21277a58e64587f82a222a74e/packages/core-browser/src/utils/electron.ts)
- [core-browser/src/menu/next/renderer/ctxmenu/electron.ts](https://github.com/opensumi/core/blob/d84eb8980975d831cc2a3c3e8417e0164d65829f/packages/core-browser/src/menu/next/renderer/ctxmenu/electron.ts)
- [core-electron-main/src/bootstrap/api.ts](https://github.com/opensumi/core/blob/main/packages/core-electron-main/src/bootstrap/api.ts)
- [core-electron-main/src/bootstrap/services/menu/index.ts](https://github.com/opensumi/core/blob/main/packages/core-electron-main/src/bootstrap/services/menu/index.ts)

发现特定于Electron端的service也有“PRC”的影子，即不是显式地使用ipcMain和ipcRenderer进行通信，而是在底层用代理包装后，后序直接调用service的方法。其中一个service的例子就是在Renderer进程中调用Main进程的[menu](https://www.electronjs.org/docs/latest/api/menu#menupopupoptions)能力。虽然也叫service，但这个service不是前后端语境下的service，而仅仅是Electron前端内的service（**这么说对吗？**）。

## 解决思路

如果Electron端内大多数涉及IPC通信的场景都是通过这种“service + Proxy”方式的话，不妨把IPC通信消息的捕获从[browser-preload](https://github.com/opensumi/core/blob/5d8e4fcf717531446c838d142f7601699fd50d0f/packages/core-electron-main/browser-preload/index.js#L9-L62)搬到[core-browser/src/utils/electron.ts](https://github.com/opensumi/core/blob/d6fd4002f52264d21277a58e64587f82a222a74e/packages/core-browser/src/utils/electron.ts)。大家怎么看？@erha19 @yantze

**Comment by erha19** [comment]
@tyn1998 感觉可以，不过相关的捕获能力还是需要受 AppConfig 中的 devtools 配置控制，默认关闭。

**Comment by tyn1998** [comment]
> 如果Electron端内大多数涉及IPC通信的场景都是通过这种“service + Proxy”方式的话，不妨把IPC通信消息的捕获从[browser-preload](https://github.com/opensumi/core/blob/5d8e4fcf717531446c838d142f7601699fd50d0f/packages/core-electron-main/browser-preload/index.js#L9-L62)搬到[core-browser/src/utils/electron.ts](https://github.com/opensumi/core/blob/d6fd4002f52264d21277a58e64587f82a222a74e/packages/core-browser/src/utils/electron.ts)。

验证可行，接下来应该只会捕获Electron Renderer进程这侧的`ipcRenderer.on`和`ipcRenderer.send`的消息了，因为“service + proxy”的模式就只用了这两个API。ipcRenderer其他方法的消息就不捕获了。

OpenSumi DevTools的IPC界面也可以进一步优化（细化）。两边调通后，我会提PR到各自仓库的~
