### ISSUE TITLE
[BUG] Bookmark extension doesn't worked on v2.20.0+

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2367]
**描述你的问题（Describe the bug）**

安装 Bookmarks 插件，点击开启书签后无法及时展示书签节点
![image](https://user-images.githubusercontent.com/9823838/222614792-585127e4-b34f-4ae9-ab4b-cf2f871dd992.png)

正常效果如下：

https://user-images.githubusercontent.com/9823838/222614864-1d40bc07-592e-429e-af80-cff38915df5e.mp4

定位到问题代码大概发生在 https://github.com/opensumi/core/commit/f5edfd770872b18e901067c57a5980e317d1db9d 合并后

**复现路径（To Reproduce）**

1. 安装 Bookmarks 插件
2. 点击文件书签开关

**预期表现（Expected behavior）**

正常响应

**Comment by Ricbet** [comment]
目前定位到的原因是这里的改动引起的 https://github.com/opensumi/core/pull/2123, 和 https://github.com/opensumi/core/commit/f5edfd770872b18e901067c57a5980e317d1db9d 分支没关系

引起异常的代码块是 `doc-manager.host` 这里的 `openTextDocument`

```typescript
async openTextDocument(uriOrFileNameOrOptions?: Uri | string | { language?: string; content?: string }) {
  // ...
  const doc = this._documents.get(uri.toString());
  if (doc) {
    return doc.document;
  } else {
    await this._proxy.$tryOpenDocument(uri.toString());
    const doc = this._documents.get(uri.toString());
    if (doc) {
      return doc.document;
    } else {
      return new Promise<vscode.TextDocument>((resolve, reject) => {
        let resolved = false;
        setTimeout(() => {
          if (!resolved) {
            reject('Open Text Document ' + uri.toString() + ' Timeout. Current Timeout is 5 seconds.');
          }
        }, OPEN_TEXT_DOCUMENT_TIMEOUT);
        const disposer = this.onDidOpenTextDocument((document) => {
          if (uri.toString() === document.uri.toString()) {
            resolve(document);
            disposer.dispose();
            resolved = true;
          }
        });
      });
    }
  }
}
```

首先这个插件调用 `openTextDocument` 方法的时候，传入的 `uriOrFileNameOrOptions` 路径参数是有误的，在路径上会多出 `//`. 而我们会修正这个错误的路径并存放在 `_documents` 集合中。所以在这段逻辑中会找不到文档

此时会调用 `$tryOpenDocument` 尝试打开这个 `document`, 但问题又来了, `$tryOpenDocument` 函数又对这个路径做了修正, 调用完之后又通过 `_documents.get` 去获取文档, 自然找不到

所以就会出现 `'Open Text Document ' + uri.toString() + ' Timeout. Current Timeout is 5 seconds.'` 错误

**Comment by erha19** [comment]
我来一起看一下怎么处理好一点，这种不规范的路径处理起来有点麻烦
