### ISSUE TITLE
[BUG] Debug 控制台没有日志输出

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2385]
**描述你的问题（Describe the bug）**

调试Nodejs 代码时，控制台中无日志输出，预期应该和 vscode 一致

**复现路径（To Reproduce）**

1. 进入 Debug
2.  查看调试控制台

**预期表现（Expected behavior）**

<img width="861" alt="image" src="https://user-images.githubusercontent.com/13082375/223898557-9a03b1db-e2ff-4edc-b973-15b48416e7bb.png">

**问题截图（Screenshots）**

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/13082375/223898669-fb8d1568-cfdb-46b7-be61-a84b7188a46e.png">

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
提供一下 js debugger 插件版本

**Comment by geekeren** [comment]
"@opensumi/ide-debug": "2.21.8",
vscode "js-debug" 插件版本：1.67.2

**Comment by Ricbet** [comment]
你这个看起来是 serverless？看看是不是少了一些相关插件呢？或者提供一下你的 launch.json 的配置看看

**Comment by geekeren** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/13082375/223969685-f94bfbd9-440b-4220-8ccc-b218a9e0a52f.png">

**Comment by geekeren** [comment]
@Ricbet vscode上是没有问题的

**Comment by Ricbet** [comment]
你的 tasks.json 看看呢，这个配置项的 preLaunchTask 在启动之前有执行一些任务

**Comment by geekeren** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/13082375/223973441-e66589b8-32f5-4de2-81ce-dc2183e7e2de.png">

**Comment by erha19** [comment]
@geekeren 我这边本地复现了，晚点我会在 v2.22 上修复一下这个问题。

**Comment by geekeren** [comment]
问题已解决
