### ISSUE TITLE
我写了一个拓展编辑器,请问一下在这个编辑器下关闭tab的回调事件是什么？

### ISSUE THREAD

**Issue by hutieshan** [opensumi/core#2391]
参考的拓展编辑器的案例：
https://github.com/opensumi/opensumi-module-samples/tree/aad4e0418cd24c6c1085b65ba44a87866df6858e/modules/components

https://opensumi.com/zh/docs/develop/module-apis/editor
文档里说：
registerResource
用来在合适的时机向 ResourceService 注册可以在编辑器内打开的资源。

为了让一个 uri 能够在编辑器中被打开，首先需要向 ResourceService 注册一个用于解析 uri 至一个编辑器资源（IResource) 的 IResourceProvider。它的主要职责是在这个 uri 在编辑器标签 Tab 上显示时提供它的名称、图标、是否被编辑等状态，**以及相应这个 tab 被关闭时的回调等等。**
我找不到这个回调方法啊... 求大神指点

**Comment by erha19** [comment]
@hutieshan 这里的回调是可以在注册资源的时候传入，定义见：https://github.com/opensumi/core/blob/f5edfd770872b18e901067c57a5980e317d1db9d/packages/editor/src/common/resource.ts

用法如：
```ts
registerResource(service: ResourceService) {
    service.registerResourceProvider({
      scheme: DEBUG_MEMORY_SCHEME,
      provideResource: async (uri: URI): Promise<IResource<Partial<{ [prop: string]: any }>>> => ({
        uri,
        icon: getIcon('hex'),
        name: uri.displayName,
      }),
      close: async () => {
        /* 关闭回调 */
        console.log('返回 True，资源会被关闭，返回 False，关闭操作会被取消');
        return true;
      },
    });
  }
```

**Comment by hutieshan** [comment]
好的 谢谢

**Comment by hutieshan** [comment]
这个好像对我没用 我搞错了。。
`import { Autowired } from '@opensumi/di';
import { ClientAppContribution } from '@opensumi/ide-core-browser/lib/common';
import {
  BrowserEditorContribution,
  EditorComponentRegistry,
  EditorComponentRenderMode,
  WorkbenchEditorService,
  ResourceService,
} from '@opensumi/ide-editor/lib/browser/types';
import {
  CommandContribution,
  CommandRegistry,
  Domain,
  Schemes,
  StorageProvider,
} from '@opensumi/ide-core-common';
import { IWorkspaceService } from '@opensumi/ide-workspace/lib/common';
import { IconService } from '@opensumi/ide-theme/lib/browser';
import { IMenuRegistry, MenuContribution, MenuId } from '@opensumi/ide-core-browser/lib/menu/next';

import { FbxConverComponentsView } from './components.view';

import { IMainLayoutService } from '@opensumi/ide-main-layout';


const COMPONENTS_ID = 'cover:fbx';
const COMPONENTS_SCHEME_ID = 'fbx';

@Domain(BrowserEditorContribution, ClientAppContribution, CommandContribution, MenuContribution)
export class FbxConverComponentsContribution implements ClientAppContribution, BrowserEditorContribution, CommandContribution, MenuContribution {
  @Autowired(IWorkspaceService)
  protected readonly workspaceService: IWorkspaceService;

  @Autowired(IconService)
  protected readonly iconService: IconService;

  @Autowired(StorageProvider)
  protected readonly getStorage: StorageProvider;


  @Autowired(IMainLayoutService)
  private readonly layoutService: IMainLayoutService;

  @Autowired(WorkbenchEditorService)
  protected readonly editorService: WorkbenchEditorService;

  registerCommands(registry: CommandRegistry) {}

  registerMenus(registry: IMenuRegistry) {}

  registerEditorComponent(registry: EditorComponentRegistry) {
    registry.registerEditorComponent({
      uid: COMPONENTS_ID,
      scheme: COMPONENTS_SCHEME_ID,
      component: FbxConverComponentsView,
      // renderMode: EditorComponentRenderMode.ONE_PER_WORKBENCH,
      renderMode: EditorComponentRenderMode.ONE_PER_RESOURCE,
    });
    registry.registerEditorComponentResolver(Schemes.file, (resource, results) => {
      if (resource.uri.path.ext.toLowerCase() === `.${COMPONENTS_SCHEME_ID}`) {
        results.push({
          type: 'component',
          componentId: COMPONENTS_ID,
        });
        const handler = this.layoutService.getTabbarHandler('peditor-property-manager');
        handler?.show();
      }
    });
  }

  registerResource(service: ResourceService) {};

  async onDidStart() {}
}
`
现在是写了一个拓展编辑器 ，.fbx后缀的文件以FbxConverComponentsView打开，有没有所有的.fbx后缀的文件的tab关闭事件的回调啊？或者是监听所有的tab的关闭事件的回调

**Comment by hutieshan** [comment]
ConstructorOf<EditorDocumentModelRemovalEvent, any[]>): (target: object, key: string, descriptor: TypedPropertyDescriptor<...>) => void
import OnEvent
类型“TypedPropertyDescriptor<(e: EditorDocumentModelRemovalEvent) => Promise<void>>”的参数不能赋给类型“TypedPropertyDescriptor<(event: EditorDocumentModelRemovalEvent) => void>”的参数。
  属性“set”的类型不兼容。
    不能将类型“((value: (e: EditorDocumentModelRemovalEvent) => Promise<void>) => void) | undefined”分配给类型“((value: (event: EditorDocumentModelRemovalEvent) => void) => void) | undefined”。
      参数“value”和“value” 的类型不兼容。
        不能将类型“void”分配给类型“Promise<void>”。
也用不了啊 注解异常了

**Comment by erha19** [comment]
@hutieshan 我写了一个例子，你可以参考一下 https://github.com/opensumi/opensumi-module-samples/pull/22

**Comment by hutieshan** [comment]
好的谢谢谢谢感激不尽

**Comment by hutieshan** [comment]
您好 监听EditorDocumentModelRemovalEvent 事件 对于文本文件的监听是有效的 但是对于拓展编辑器没有触发事件 ,图片文件也是一样 无法触发事件。

**Comment by life2015** [comment]
> 您好 监听EditorDocumentModelRemovalEvent 事件 对于文本文件的监听是有效的 但是对于拓展编辑器没有触发事件 ,图片文件也是一样 无法触发事件。

因为这个事件是Opensumi自带编辑器耦合的EditorDocumentModel发出来的，而不是Monaco编辑器本身发出的。如果你是自定义的EditorComponent的话，就需要自己来fire这部分事件了。
<img width="816" alt="image" src="https://user-images.githubusercontent.com/12879047/225195267-156a9598-d09b-4dd5-be5b-2044033eda82.png">
