### ISSUE TITLE
[Question] 项目启动遇到 CLIENT_APP_TOKEN 错误

### ISSUE THREAD

**Issue by StarFishing** [opensumi/core#2411]
**描述你的问题（Describe you question here）**
项目启动遇到 CLIENT_APP_TOKEN 错误

![5e621ff6-6782-46de-8a97-a3e06b2876ff](https://user-images.githubusercontent.com/41889222/224959168-29499cb4-00cc-4fce-9c51-221005eb0a56.jpeg)

系统环境
node:v16.18.0
pnpm:v7.18.0
os: mac
复现仓库:  https://github.com/StarFishing/ide-test/tree/main

**Comment by erha19** [comment]
@StarFishing 这里有部分库无法正常安装，如 `@kunlun/kunlun-design`，直接看你这边的代码，`pnpm-lock.yaml` 文件内展示了多个版本的 `@opensumi/di`，如下：
![image](https://user-images.githubusercontent.com/9823838/224962038-2820e216-6046-42a6-b868-46de3dc8f831.png)

可以将 DI 版本均固定在 `1.8.0` 版本，替换掉部分 package 中的 `^1.4.0` 声明，应该可以解决你的问题。

**Comment by StarFishing** [comment]
@erha19 应该不是这个问题，这里虽然只是声明了 1.4.0,但实际安装的还是 1.8.0,我在推一下分支，去掉了不可用的依赖，你再试下

**Comment by bytemain** [comment]
应该是因为有多份不同的源码，多份不同的源码中相同名字的 Symbol 也是不一样的。

![CleanShot 2023-03-14 at 20 20 32@2x](https://user-images.githubusercontent.com/13938334/224999391-473320a8-8173-47d7-ba35-2a41e666bfec.png)

![CleanShot 2023-03-14 at 20 21 19@2x](https://user-images.githubusercontent.com/13938334/224999758-fb9deaea-c6d1-4816-bf68-10bfe0c34bc0.png)


造成这个报错的 module 是 aPaaSUIModule：
<img width="687" alt="CleanShot 2023-03-14 at 20 22 56@2x" src="https://user-images.githubusercontent.com/13938334/224999858-2f8892ff-784f-4d2d-89a6-c0e710e94e24.png">

**Comment by bytemain** [comment]
<img width="837" alt="CleanShot 2023-03-14 at 20 24 45@2x" src="https://user-images.githubusercontent.com/13938334/225000194-1d544b34-3ebd-42f2-9af1-2fc1bcbd1eb7.png">

看了下 node_modules，可能真的存在多份：
<img width="837" alt="CleanShot 2023-03-14 at 20 24 45@2x" src="https://user-images.githubusercontent.com/13938334/225000249-b9e9f2a1-0415-4e96-936c-b99f90bc932f.png">

**Comment by bytemain** [comment]
看起来是 core 内部的依赖关系没处理好导致的 pnpm 生成了多份

**Comment by StarFishing** [comment]
> <img alt="CleanShot 2023-03-14 at 20 24 45@2x" width="837" src="https://user-images.githubusercontent.com/13938334/225000194-1d544b34-3ebd-42f2-9af1-2fc1bcbd1eb7.png">
> 
> 看了下 node_modules，可能真的存在多份： <img alt="CleanShot 2023-03-14 at 20 24 45@2x" width="837" src="https://user-images.githubusercontent.com/13938334/225000249-b9e9f2a1-0415-4e96-936c-b99f90bc932f.png">

这个依赖应该不是我们这边可控了吧，至于那个 Symbol token 的问题，是我们还用方式不对吗，还说跟依赖重复的问题是一个

**Comment by bytemain** [comment]
symbol 的原因就是存在多份源码。
存在多份源码的原因就是使用 pnpm 安装的。
为什么使用 pnpm 安装会这样是因为它的依赖处理机制.

我研究了一下 pnpm 这个机制，发现会有两种包：opensumi_xxx 和 opensumi_xxx_react-dom

<img width="871" alt="CleanShot 2023-03-15 at 10 52 22@2x" src="https://user-images.githubusercontent.com/13938334/225192911-e14b1fdb-75c3-4cd0-8353-cacd8e06de7e.png">

把你的几个 module 的包里的 react-dom 版本也都指定到 ^16 就行了

<img width="1703" alt="CleanShot 2023-03-15 at 11 06 00@2x" src="https://user-images.githubusercontent.com/13938334/225194966-1ac72432-24b3-487a-8844-3caa362c4a96.png">

```diff
diff --git a/packages/ide/apaas-lowcode/package.json b/packages/ide/apaas-lowcode/package.json
index 18d8ed0..bc3b44f 100644
--- a/packages/ide/apaas-lowcode/package.json
+++ b/packages/ide/apaas-lowcode/package.json
@@ -18,6 +18,7 @@
     "@opensumi/ide-workspace": "2.22.8-next-1678359328.0",
     "@opensumi/monaco-editor-core": "0.35.0-patch.3",
     "lodash": "^4.17.21",
-    "react": "^16"
+    "react": "^16",
+    "react-dom": "^16"
   }
 }
diff --git a/packages/ide/apaas-ui/package.json b/packages/ide/apaas-ui/package.json
index 7d33b31..19282b4 100644
--- a/packages/ide/apaas-ui/package.json
+++ b/packages/ide/apaas-ui/package.json
@@ -14,6 +14,7 @@
     "@opensumi/ide-core-browser": "2.22.8-next-1678359328.0",
     "@opensumi/ide-core-common": "2.22.8-next-1678359328.0",
     "@opensumi/ide-theme": "2.22.8-next-1678359328.0",
-    "react": "^16"
+    "react": "^16",
+    "react-dom": "^16"
   }
 }
diff --git a/packages/ide/shell-service/package.json b/packages/ide/shell-service/package.json
index 5397296..5cf3b7b 100644
--- a/packages/ide/shell-service/package.json
+++ b/packages/ide/shell-service/package.json
@@ -11,6 +11,8 @@
     "@opensumi/ide-core-browser": "2.22.8-next-1678359328.0",
     "@opensumi/ide-core-node": "2.22.8-next-1678359328.0",
     "@opensumi/ide-utils": "2.22.8-next-1678359328.0",
-    "@opensumi/ide-workspace": "2.22.8-next-1678359328.0"
+    "@opensumi/ide-workspace": "2.22.8-next-1678359328.0",
+    "react": "^16",
+    "react-dom": "^16"
   }
 }

```

**Comment by StarFishing** [comment]
@opensumi/* 对 antd 这种的依赖产生了间接的 perDep，这个导致在 workspace 不同包下被 pnpm 以当前包内的信息计算了对应的版本

**Comment by StarFishing** [comment]
感觉这类依赖可以记一下，可能后面还会有类似的依赖出来

**Comment by erha19** [comment]
> @opensumi/* 对 antd 这种的依赖产生了间接的 perDep，这个导致在 workspace 不同包下被 pnpm 以当前包内的信息计算了对应的版本

OpenSumi 本身不依赖 antd，依赖的是部分  `rc-*` 库，这里的需要保障 `@opensumi/*` 包的唯一性确实是一个集成过程中容易遇到的坑，这里的问题是一个比较典型的案例了。

React 相关内容的依赖优化，我们会在 https://github.com/opensumi/core/issues/861 这里一起处理一下。

**Comment by StarFishing** [comment]
遇到了新的错误
![4dcf353e-2036-4b69-b3ba-e4326a56db1a](https://user-images.githubusercontent.com/41889222/225221934-5d60afe1-1bc0-41f3-a761-872dc1f275c0.jpeg)

**Comment by erha19** [comment]
@StarFishing 你这里采用了 webpack5 做代码打包，browser 环境下会缺少 `setImmediate` 这个全局属性，需要手动做一下 polyfill，如：

```ts
const baseWebpackTarget = () => ({
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json', '.less'],
    plugins: [
      new TsconfigPathsPlugin({
        configFile: tsConfigPath,
      }),
    ],
    fallback: {
      crypto: false,
      path: false,
      os: false,
      stream: false,
      net: false,
      fs: false,
      url: false,
      process: require.resolve('process/browser'),
      buffer: require.resolve('buffer/'),
      setImmediate: path.join(__dirname, 'polyfills/setimmediate/setImmediate'),
    },
  },
});
```

polyfill 文件可以参考 [setImmediate.js](https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js)。

**Comment by StarFishing** [comment]
@erha19  加了下似乎没有作用

**Comment by StarFishing** [comment]
代码更新过了

**Comment by erha19** [comment]
@StarFishing 提交了一个兼容性修改 https://github.com/StarFishing/ide-test/pull/1 ，这里有部分历史原因，我们前端的通信层由于早前的一些设计，引入了 Node 层的 JSONRPC 定义，这里使用到了 `setImmediate` 等一些在浏览器环境不兼容的方法，目前临时兼容处理已支持 Webpack5, 后面会整体替换前后端通信使用的 RPC 库来解决这个问题。

相关链接：
- https://github.com/opensumi/core/pull/1584
- https://github.com/opensumi/vscode-jsonrpc/pull/13

**Comment by geekeren** [comment]
升级到 2.24.2 同遇到这个错。看 yarn lock  di 和 opensumi 各模块只安装了一个版本。
