### ISSUE TITLE
[Question] 请问图标可以怎么替换掉，以及注册新的图标

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2423]
**描述你的问题（Describe you question here）**

请问图标可以怎么替换掉，以及注册新的图标？

**Comment by erha19** [comment]
@geekeren 框架中存在原始的内置图标集合，相关图标的映射关系见：[iconMap.ts](https://github.com/opensumi/core/blob/3d84700930ef07c4adc87e1b782ff35321e6cea5/packages/components/src/icon/iconfont/iconMap.ts)

对应的图标见：[内置图标](https://opensumi.github.io/core/iconfont.html)

你可以通过集成配置中的 `iconStyleSheets` 配置进行代码替换，如：

```ts
const iconStyleSheets: IconInfo[] = [
  {
      iconMap: {
        explorer: 'fanhui', // 这种是覆盖，因此在 Icon 中通过 `explorer` 去取
        shangchuan: 'shangchuan', // 这种是新增，因此在 Icon 中通过 `shangchuan` 去取
      },
      prefix: 'tbe tbe-',
      cssPath: '//at.alicdn.com/t/font_403404_1qiu0eed62f.css',
    },
];
```

另外，目前还有一个 [ProductIconTheme](https://github.com/opensumi/core/issues/581) 的方案正在做，后续也可以通过插件进行替换。

**Comment by erha19** [comment]
另外，一般图标我们采用 Icon 组件进行渲染，相关代码见：
```ts
import { Icon } from '@opensumi/ide-components';

const Sample = () => (
  <Icon icon='explorer' />
)
```

**Comment by fanweiren1217** [comment]
@erha19 iconStyleSheets 里的 cssPath 是直接贴 iconfont 的样式文件地址就行是吧？

新增自定义图标只需要将图标上传到个人的 iconfont 项目里，把 cssPath 改成新地址就可以了吗？

**Comment by Ricbet** [comment]
对

**Comment by fanweiren1217** [comment]
@Ricbet 
> ```ts
> const iconStyleSheets: IconInfo[] = [
>   {
>       iconMap: {
>         explorer: 'fanhui', // 这种是覆盖，因此在 Icon 中通过 `explorer` 去取
>         shangchuan: 'shangchuan', // 这种是新增，因此在 Icon 中通过 `shangchuan` 去取
>       },
>       prefix: 'tbe tbe-',
>       cssPath: '//at.alicdn.com/t/font_403404_1qiu0eed62f.css',  // iconfont 样式文件
>     },
> ];
> ```

1. cssPath 地址可以是本地的吗？比如我想用本地的一个 svg 图标替换系统中某图标
2. 如果只是用系统图标 B 去替换 A，此处 cssPath 该如何设置

**Comment by Ricbet** [comment]
`prefix` 字段加上 `iconfont` 试试呢

**Comment by fanweiren1217** [comment]
> 

11

**Comment by fanweiren1217** [comment]
`prefix`加了`iconfont`后，图标正常展示了

**输出面板的图标没生效应该是时机问题，辛苦你们看一下？**

- 生效的写法 
https://github.com/opensumi/core/blob/main/packages/debug/src/browser/view/console/debug-console.contribution.ts

- 不生效的写法
https://github.com/opensumi/core/blob/main/packages/output/src/browser/output-contribution.ts

**Comment by Ricbet** [comment]
> @Ricbet `prefix`加了`iconfont`后，图标正常展示了
> 
> **输出面板的图标没生效应该是时机问题，辛苦你们看一下？**
> 
> * 生效的写法
>   https://github.com/opensumi/core/blob/main/packages/debug/src/browser/view/console/debug-console.contribution.ts#:~:text=iconClass%3A%20getIcon(%27clear%27)%2C
> * 不生效的写法
>   https://github.com/opensumi/core/blob/main/packages/output/src/browser/output-contribution.ts#:~:text=commands.registerCommand(OUTPUT_CLEAR%2C

这个我们修一下

**Comment by fanweiren1217** [comment]
@Ricbet 发现[main-layout.contribution.ts](https://github.com/opensumi/core/blob/main/packages/main-layout/src/browser/main-layout.contribution.ts#:~:text=export%20const%20EXPAND_BOTTOM_PANEL%3A%20Command%20%3D%20%7B)这个文件里的图标定义方式都会导致通过 iconStyleSheets 配置的图标替换失效，这个问题该如何解决呢？

**Comment by Ricbet** [comment]
> @Ricbet 发现[main-layout.contribution.ts](https://github.com/opensumi/core/blob/main/packages/main-layout/src/browser/main-layout.contribution.ts#:~:text=export%20const%20EXPAND_BOTTOM_PANEL%3A%20Command%20%3D%20%7B)这个文件里的图标定义方式都会导致通过 iconStyleSheets 配置的图标替换失效，这个问题该如何解决呢？

和上面那个 output 的图标问题是一样的，时机过早了。
修复方式就是将注册图标的方法放在 `registerMenuItem` 里去注册。参考这个 pr https://github.com/opensumi/core/pull/2447/files

**Comment by Ricbet** [comment]
@fanweiren1217
