### ISSUE TITLE
[Question] ws 建连能否不阻塞编辑器的 UI 渲染

### ISSUE THREAD

**Issue by SunPeter** [opensumi/core#2425]
【目标】性能优化的诉求，希望类似 replit ，当 ws 连接还没 ready 时可以渲染出 IDE 的主要轮廓(不包含数据）。

【Q1】目前这块看上去是阻塞的  [bootstrap/connection.ts](https://github.com/opensumi/core/blob/main/packages/core-browser/src/bootstrap/connection.ts#L59) ，想初步判断下这块技术上是否可行。

【Q2】另外衍生一个问题：插件里自定义的主题（extensions 目录）是依赖于服务端么，如果服务端还没 ready，页面的渲染可能缺失相关主题样式。这块有无可能把插件中的样式提取出来，并发布到 CDN 上。看到目前 browser 启动有一个相关配置，不确定是否适用：
`opts.extensionDir = opts.extensionDir || process.env.EXTENSION_DIR;`

**Comment by erha19** [comment]
@SunPeter 

A1：目前这里阻塞的代码见：[app.ts#L223](https://github.com/opensumi/core/blob/836c7f34ce10404410314b2da25443b0e5805ce4/packages/core-browser/src/bootstrap/app.ts#L223)，原因是仅在后面的 
```ts
await this.injector.get(IApplicationService).initializeData();`  // 逻辑需要后端返回正确的 OS 类型保障后续系列服务的正常初始化，（这里不能依赖前端 OS 判断是因为后端服务与前端访问环境可能是不一致的）
await this.measure('Contributions.start', () => this.startContributions(container));
```
这里由于部分用户自定义的 ClientAppContribution 中的 `initialize` 等方法可能会有前后端通信逻辑，目前逻辑上有前置依赖，这部分依赖关系无法轻易改动。

基于 OpenSumi 的生命周期设计，可以给到你首屏时间的优化建议：

1. 非必要情况，不要将 `initialize、onStart` 等生命周期钩子定义为异步函数，如有异步请求，可以采用 `Promise.then` 方式改造


A2：目前 OpenSumi 会将主题的一份（主体区域）默认配色及布局在访问后进行缓存，下次访问会以骨架屏方式呈现，目前这部分数据是缓存在 LocalStorage 中，可以自行查看。

`extensionDir ` 是用来声明插件目录路径的，可见文档：[自定义配置](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config#%E6%B5%8F%E8%A7%88%E5%99%A8%E7%AB%AF%E9%85%8D%E7%BD%AE)。

**Comment by SunPeter** [comment]
感谢回复。
所以看上去目前不太好做彻底解耦，建连是渲染的前置条件，避免 `initialize` 阶段的阻塞来加快 `renderApp` 是比较重要的优化点。

对于主题的样式，遇到一个现象（如果目前前端渲染和 Server 建连无法解耦，此现象可忽略）：
本地
![image](https://user-images.githubusercontent.com/3616384/225528453-901e5eb2-194a-417a-8730-33617a0a61c3.png)    
  
发布 CDN 后
![image](https://user-images.githubusercontent.com/3616384/225529052-0cd5ff60-0c39-4980-a4ee-034f8206bfb7.png)

验证发现缺失的样式主要是来自于自定义了主题，而主题是存放在 Server\extensions 工程目录下： 
![image](https://user-images.githubusercontent.com/3616384/225530199-a28309a5-0d54-4cfe-8f98-0415da8994ba.png)  

这样完整的布局样式看上去还是依赖于后端服务的启动。这块主题样式的自定义有可能提出来和前端资源一起分发么？或者把 LocalStorage 的数据提取出来，在 HTML 访问时主动注入到用户的 LocalStorage 中（不确定是否能生效）

**Comment by erha19** [comment]
@SunPeter 目前插件主题是与后端服务有依赖关系的，尽管主题插件会第一时间加载，但仍需要一定时间，如果你希望在线上 CDN 的首次访问也能有合适的背景信息，你在用户启动时手动做一下默认值处理，伪代码如下：

```ts
const theme = window.localstorage.getItem('theme');
if (!theme) {
 window.localstorage.setItem('theme', { .... })
}
```

主题插件加载后，你就可以在 Localstorage 中看到这些变量了， 如下：
<img width="769" alt="image" src="https://user-images.githubusercontent.com/9823838/225546109-fa95692a-d99d-4cc2-be27-37e6431ff140.png">

**Comment by SunPeter** [comment]
@erha19 看了下 lite 模式的实现，有一些启发。
我在想是否可以借鉴其对于一些模块 mock ，以及插件从远端获取的实现，来在容器下 ws server 没 ready 前用于整体 IDE 框架的渲染。等建连后就可以从 lite ide 转换为 ide 模式。

**Comment by SunPeter** [comment]
试了下，分别使用两个 DOM renderApp 和 renderLiteApp，前者的 terminal 无法正常渲染。但如果只运行其中一种都没有问题。
Lite 对于一些模块的 mock 是全局影响的么？`const injector = new Injector();` 这块应该是独立的，想帮忙看看问题所在。目前应该是 terminal UI 没有正常渲染，导致  context 没有初始化。

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/3616384/226154484-e1896fb2-d4d0-435d-9a20-7e603c0073af.png">    
<img width="576" alt="image" src="https://user-images.githubusercontent.com/3616384/226154543-ba1a765b-fdb1-4074-b5e8-50576e84f389.png">

**Comment by erha19** [comment]
@SunPeter 你这里的 `renderApp` 和 `renderLiteApp` 是什么逻辑？ 按含义理解，你这里集成的时候只能二选一，纯前端（Lite）模式下是无法使用 Terminal 模块的，主要由于 Terminal 模块会依赖本地环境，浏览器上暂时无开源方案实现，故在集成阶段建议不引入 Terminal module 并对部分服务进行 mock，如 https://github.com/opensumi/ide-startup-lite/blob/f4570890d963207ffdab6d419d6f2cf33c2824fd/web-lite/index.ts#L57

**Comment by SunPeter** [comment]
@erha19 对应代码 https://github.com/opensumi/core/pull/2448  辛苦看看

**Comment by SunPeter** [comment]
我们的场景下会有容器冷启动的耗时，现实问题会存在比较久的耗时，因此希望先完成 IDE 框架 UI 渲染，后等待建连展示真实数据。
目前预期是类似建连前 Web IDE 隐藏，建连后 Lite IDE dispose，展示 Web IDE。
希望得到的效果类似下图：

https://user-images.githubusercontent.com/3616384/226250215-1d8adf80-684f-4af6-a9f5-1702d88d741b.mp4

**Comment by SunPeter** [comment]
理论上，lite ide 对于  `ITerminalProfileService` 的 mock 应该不会是全局的吧？
https://github.com/opensumi/core/blob/main/packages/startup/entry/web-lite/lite-module/index.ts#L49
https://github.com/opensumi/core/blob/main/packages/terminal-next/src/browser/index.ts#L124
稍微有点担心两种模式同时渲染会有一些冲突

**Comment by erha19** [comment]
@SunPeter 理论上服务的 mock 都是基于 `Injector` 初始化出来的实例的，但这里确实可能有一些数据冲突的情况：

1. LocalStroage
2. 本身用于在 DI 内实例化服务的 Token 出现了重复，如非 `Symbol` 包裹的常量会出现问题，`@opensumi/di` 内有一个全局的实例做管控

**Comment by erha19** [comment]
@SunPeter 尝试了一下，还是存在很多问题，除了 Injector 之外，许多全局变量\Browser 存储\样式等都会冲突，如果希望基于这个方案去做，建议将 WebIDE 或 WebLite IDE 其中一个放到 iframe 内做渲染，否则基于目前你实现的代码是无法同时在一个页面内渲染两种模式的。

**Comment by SunPeter** [comment]
了解了。想再讨论下，因为 WebIDE 能力上是覆盖 LIte 模式的，有可能先 mock 然后渲染 lite IDE. 等 socket 连接完成后整体 dispose，然后 renderApp 并 app.start(target，'web') 么，业务上可以保证只有一个 app 实例。
还是在于 dispose 是否能比较彻底的重置一些全局状态。

**Comment by erha19** [comment]
@SunPeter 这样做的方案中整体复杂度较高，目前我们实践过程中也没这样做过，按我理解目前是比较难做到的。

另外既然你这边的需求是优化首屏时间，不如一起看一下 WebIDE 场景下是否可以做到更快，如果是服务的冷启动需要时间，是否加一层中间服务先提供基础的数据，后续再做进一步的数据/服务启动，这样的方案可能会更靠谱一点。

**Comment by SunPeter** [comment]
嗯，是的。常规包优化会基于你的建议来开展，容器侧也会有一些池化的方案来推进，尽量优化首屏体积以及减少连接等待。
我们这个 issue 的本质诉求还是希望能基于 layoutconfig 自动来绘制骨架屏。（提供基础的数据可以把 mainlayout 绘制出来么）

**Comment by erha19** [comment]
@SunPeter 目前 OpenSumi 本身有内置骨架屏逻辑，不过相对比较粗，如果你这边有更精细的骨架屏需求，其实也可以通过 LocalStorage 中存储的 `layout` 和 `theme` 缓存数据做骨架屏的自定义渲染。
