### ISSUE TITLE
[BUG] 调试控制台 日志无法清空

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2429]
**描述你的问题（Describe the bug）**
调试控制台 日志无法清空

<img width="952" alt="image" src="https://user-images.githubusercontent.com/13082375/225503681-794871f0-efca-462f-a2b5-2e563d1f5654.png">

**复现路径（To Reproduce）**

进入调试，点击清空日志，日志无法清空

**预期表现（Expected behavior）**

点击清空

**Comment by Ricbet** [comment]
麻烦提供下版本号？目前这个问题已经在 2.22.9 修复了

**Comment by geekeren** [comment]
2.22.8-next-1678359328.0

**Comment by geekeren** [comment]
我升级一下试试
