### ISSUE TITLE
[Question] 我想关闭左侧模块为什么mainLayoutService 提供的api不好使

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2432]
![image](https://user-images.githubusercontent.com/23164065/225515350-a4db8370-c051-478c-9ec7-0034894d3e28.png)
`mainLayoutService.getAccordionService('Multiplex').revealView('subofmultiplex');
          mainLayoutService.replaceViewComponent({ id: 'Multiplex' });
          mainLayoutService.revealView('Multiplex');`

**Comment by 767746649zyy** [comment]
我想关闭左侧，展示文件树模块

**Comment by erha19** [comment]
@767746649zyy 可以参考一下这个案例 https://github.com/opensumi/opensumi-module-samples/blob/main/modules/toggle-panel/browser/toggle-panel.contribution.ts
