### ISSUE TITLE
[Question] 多个版本 mobx 提示版本冲突

### ISSUE THREAD

**Issue by gaoyiniy** [opensumi/core#2434]
**描述你的问题（Describe you question here）**
IDE 中版本为 ：
```JSON
  "mobx": "^5.9.4",
  "mobx-react-lite": "^1.3.1",
```
业务中的版本为：
```JSON
"mobx": "^6.6.1",
"mobx-react-lite": "^3.4.0"
```
运行时报错
![image](https://user-images.githubusercontent.com/33682340/225525449-34058b17-f0ff-4e31-b48c-26f4b186d1a2.png)
想了解我如果在 IDE 入口中配置为[独立模块](https://www.mobxjs.com/configuration)，有什么影响吗？
```ts
import { configure } from 'mobx';
configure({ isolateGlobalState: true });
```

**Comment by erha19** [comment]
@gaoyiniy 如果采用的 `yarn` ，可以采用 `resolutions` 属性在业务集成位置的 `package.json` 里面声明下面内容：

```json
  "resolutions": {
    "mobx": "^6.6.1",
    "mobx-react-lite": "^3.4.0"
  },
```

npm 8 后面也支持了 overrides 属性，也可以使用 https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by gaoyiniy** [comment]
@erha19 似乎不太对，你这里是强制让 IDE 的 mobx 升级，我在 demo 里试了下，会有新的报错：
![image](https://user-images.githubusercontent.com/33682340/225553409-70b3fce8-7290-4737-bbd7-dce08edee444.png)
是否只能强制让业务对齐 IDE 的版本，还有其他的解决办法吗？

**Comment by erha19** [comment]
@gaoyiniy 可以用一下 mobx 提供的 `isolateglobalstate` 配置 ：https://mobx.js.org/configuration.html#isolateglobalstate-boolean

**Comment by gaoyiniy** [comment]
@erha19 不知道我理解的对吗，这个如果设置为 true，代表是独立的 mobx 实例，不会共享一个 store，而 IDE 里面有很多模块都用到了 mobx。
![image](https://user-images.githubusercontent.com/33682340/225563504-74e6d07e-fbaf-4436-af93-a6839703f672.png)

**Comment by erha19** [comment]
@gaoyiniy 这里可以看一下网上一些现有案例，看看多 mobx 版本共存方案是否可行，如果不可行，那就需要两边对齐到一个版本才行了。

**Comment by gaoyiniy** [comment]
close

**Comment by erha19** [comment]
@gaoyiniy 方便同步一下最终的解决方案吗？
