### ISSUE TITLE
[Question] 设置工作区不生效

### ISSUE THREAD

**Issue by piLurk** [opensumi/core#2437]
**需求**
如何切换工作区，通过 workspaceService 可设置么？我试了下 workspaceService.setWorkspace ，没有生效

**尝试代码**
```
import { Autowired  } from "@opensumi/di";
import { 
  ClientAppContribution,
  Domain,
  // URI,
} from '@opensumi/ide-core-browser';
import { IFileServiceClient } from '@opensumi/ide-file-service';
import { IWorkspaceService } from '@opensumi/ide-workspace/lib/common/workspace.interface';

@Domain(ClientAppContribution)
export class ContextRegistryContribution implements ClientAppContribution  {

  @Autowired(IWorkspaceService)
  private readonly workspaceService: IWorkspaceService;

  @Autowired(IFileServiceClient)
  protected readonly fileServiceClient: IFileServiceClient;

  
  async onDidStart() {
    const url = "/Users/ide-sandbox/workspaces/test";
    const fileStat = await this.fileServiceClient.getFileStat(url);
    
    // 设置工作区
    this.workspaceService.setWorkspace(fileStat);
  } 
}
```

**Comment by piLurk** [comment]
@erha19 好像有点不符合预期
如果在 new ClientApp(opts) 初始化指定 workspaceDir ，再调用 workspaceService.setWorkspace(fileStat)，setWorkspace 的设置可以成功
如果初始化时不指定了 workspaceDir，setWorkspace 就不成功了

**Comment by erha19** [comment]
@piLurk 目前不支持直接在当前窗口下切换工作区，本身涉及到比较多的服务需要重置（没具体需求去实现），目前均是通过 `workspaceDir` 去指定一次性的工作区场景。

在你指定工作区后，就算设置成功了，相关的服务以及插件进程的部分信息应该还是没有正确被改变的。

**Comment by erha19** [comment]
@piLurk 你可以实现类似 https://github.com/opensumi/ide-startup/blob/main/src/browser/render-app.ts#L21 这里的逻辑去实现工作区的打开及切换。

**Comment by piLurk** [comment]
@erha19 没有理解，这里不是只有初始化么，切换指的是？

**Comment by piLurk** [comment]
额，者意思就是没有动态切换的能力是么。。必须重新渲染么

**Comment by erha19** [comment]
> 额，意思就是没有动态切换的能力是么。。必须重新渲染么

是的，动态切换能力目前没有需求支撑，没做实现，有兴趣可以看看能不能 PR 一下，一些修改的位置我这边可以给你指出来。

**Comment by piLurk** [comment]
嗯，可以贴一下哈

**Comment by erha19** [comment]
@piLurk 相关代码及功能如下：

1. 工作区初始化代码 [workspace-service.ts#L107~L130](https://github.com/opensumi/core/blob/48a4def3d2c79ab65de8f6d913e77e3ffe8a9b6d/packages/workspace/src/browser/workspace-service.ts#L107~L130)，这里需要重新新建一个新的初始化工作区的方法，如 `replaceWorkspace` ，设置新的工作区并将原有针对旧工作区的监听事件移除。
2. 部分默认从 `appConfig.workspaceDir` 内取值的地方需要修改，从 WorkspaceService 中获取最新的值（可以全局搜索一下 
 `.workspaceDir` 进行排查），如：
  - https://github.com/opensumi/core/blob/efbb3b4857818a3991d591d33da40a7750c1b5c3/packages/electron-basic/src/browser/header/header.service.ts#L103
  - https://github.com/opensumi/core/blob/0a8ad32fd3b932e9b1547bbf336f2d9184d02b1e/packages/editor/src/browser/untitled-resource.ts
  - https://github.com/opensumi/core/blob/ed89da252a8d7350863721f2c7028f0f229b0e4e/packages/core-browser/src/services/storage-service.ts
  - https://github.com/opensumi/core/blob/f35fe97a22c3f7d0173deb56bdab9208eff381a4/packages/comments/src/browser/comments.service.ts

3. 部分模块对于当前使用的 Workspace 有缓存，需要监听一下 `workspaceService.onWorkspaceChanged` 后进行更新（可以通过 `.tryGetRoots()`, `.workspace` 关键词搜索），如：
  - https://github.com/opensumi/core/blob/230e6c707a11ac7155e930e40d6bb12b263a9133/packages/task/src/browser/task.service.ts

4. 检查一下切换工作区后，文件树是否有正常更新，相关代码见：[file-tree.service.ts#L169](https://github.com/opensumi/core/blob/ad721ea4259a2305f2287d82e792ae9331abc0dd/packages/file-tree-next/src/browser/file-tree.service.ts#L169)
 
完成这些修改大致能实现这个需求

**Comment by piLurk** [comment]
@erha19 setWorkspace 这个函数原来的定位不是切换工作区么，还需要新增一个 replaceWorkspace ？
![image](https://user-images.githubusercontent.com/25706123/226229548-495b892f-0b7d-475b-990e-d71028020d2c.png)

**Comment by erha19** [comment]
@piLurk 原来的定位是从 “文件夹” 工作区 向类似于 `.sumi-workspace`(文件) 工作区的切换逻辑中使用的，如下面这段保存`.sumi-workspace`(文件) 工作区后切换的逻辑：
https://github.com/opensumi/core/blob/48a4def3d2c79ab65de8f6d913e77e3ffe8a9b6d/packages/workspace/src/browser/workspace-service.ts#L675~L700 

这里你也可以进一步优化这个方法，明确一下这里不仅处理这类工作区切换，也可以用于当前工作区的切换逻辑，不过因为这个方法是公开的服务，实现完成之后，需要在 [Changelog](https://github.com/opensumi/core/blob/v2.22/CHANGELOG.md#breaking_changes_2.22.0) 文档中补充相关的 BreakingChange 信息。
