### ISSUE TITLE
[Question] 如何重载 OutputModule

### ISSUE THREAD

**Issue by fanweiren1217** [opensumi/core#2444]
**描述你的问题（Describe you question here）**
背景：发现 IDE 启动时会打印一些 Git, Typescript 的输出信息，是否有办法屏蔽其输出，只展示特定 channel 的输出

目前想到的办法是通过重载 OutputModule 中的 OutputService，但如何实现能保证系统默认调用的 OutputService 也能被重载呢？

![image](https://user-images.githubusercontent.com/127910654/225894791-2a30a604-014e-48a0-a753-726dc1e5839e.png)

**Comment by erha19** [comment]
@fanweiren1217 目前 Output 面板没有提供屏蔽某些项输出的能力，如果需要实现，有两个路径：

1. 可以考虑往 `opensumi/core` 提交实现，代码见：[output.service.ts](https://github.com/opensumi/core/blob/695ae3dd23d3f64f96eeb78500a84a0ef73f6439/packages/output/src/browser/output.service.ts)，实现评估通过后发版提供该接口能力，建议先发 RFC 再做实现。
2. 重载 OutputService 服务去实现

另外，换个思路，目前你也可以在输出时，通过 `getChannel` + `updateSelectedChannel` 的方式去固定输出面板的选择的方式来曲线实现这个需求。

**Comment by fanweiren1217** [comment]
@erha19 方案一是个可行的方案

关于方案二 重载 OutputService 无法对系统默认输出生效吧？

另外通过 getChannel + updateSelectedChannel 方式切换输出面板后，同样也可以被系统内部对 updateSelectedChannel 的调用切换回去吧

**Comment by erha19** [comment]
@erha19 所有输出逻辑应该都是从 OutputService 这个服务走的，重载 OutputService 应该也是可以对默认输出生效的。

> 另外通过 getChannel + updateSelectedChannel 方式切换输出面板后，同样也可以被系统内部对 updateSelectedChannel 的调用切换回去吧

这个确实是的

**Comment by Ricbet** [comment]
可以使用 injector 参数来通过 DI 重载内部服务 https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config#:~:text=%E6%97%A0-,injector,-%E5%88%9D%E5%A7%8B%E5%8C%96%E7%9A%84

示例:
``` typescript
import { Injector } from '@opensumi/di';

const injector = new Injector({
        token: OutputService,
        useClass: CustomOutputService,
});
```

然后你自定义的 `CustomOutputService` 可以 `extends OutputService`，然后 `override getChannel`

**Comment by miserylee** [comment]
这个 injector 是在 appConfig 里面传进去的吗？ 是不是某个 token 已经被使用过的情况下，后面再追加的 module 里面提供了同 token 的 service 是不生效的？

**Comment by fanweiren1217** [comment]
@erha19 这个 injector 是在 renderApp调用时传入吗？其入参类型定义 IClientAppOpts 里没有关于 injector 的字段

```
export interface IClientAppOpts extends Partial<ApplicationConfig> {
  modules: ModuleConstructor[];
  contributions?: ContributionConstructor[];
  modulesInstances?: BrowserModule[];
  connectionPath?: UrlProvider;
  connectionProtocols?: string[];
  iconStyleSheets?: IconInfo[];
  useCdnIcon?: boolean;
  editorBackgroundImage?: string;
  /**
   * 插件开发模式下指定的插件路径
   */
  extensionDevelopmentPath?: string | string[];
}
```

**Comment by Ricbet** [comment]
> 

在 AppConfig 里

**Comment by Ricbet** [comment]
> 这个 injector 是在 appConfig 里面传进去的吗？ 是不是某个 token 已经被使用过的情况下，后面再追加的 module 里面提供了同 token 的 service 是不生效的？

对，是作为 new ClientApp 的参数传进去的。
理论上是不会的，你可以先试试，我们在内部是通过 `addProviders` 去添加服务的，如果 token 存在，则不会覆盖
