### ISSUE TITLE
[BUG] Debug skipFiles 选项不生效

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2445]
**描述你的问题（Describe the bug）**

1. skipFiles 的文件 还是会在 调试堆栈里显示，是opensumi目前还不支持这个选项
2. 有时在代码中没有设置断点，但调试还是会停

**复现路径（To Reproduce）**

进入调试，配置 skipFiles

**预期表现（Expected behavior）**

skipFiles 中的文件默认不显示在调试堆栈中

**问题截图（Screenshots）**
1. skipFile 会显示
<img width="560" alt="image" src="https://user-images.githubusercontent.com/13082375/226103327-831af3b2-e3e8-43e2-a4e3-a045ba92406b.png">

2. 下面这个断点，我没有打，但是偶尔还是会停，非必现

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/13082375/226103469-e1814604-1bc2-4d24-92b1-570c6c55930f.png">

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/13082375/226103334-6e968fe5-e00c-4008-a223-faaceffdc72d.png">

**补充信息（Additional context）**

**Comment by erha19** [comment]
@geekeren 我来看一下这个问题
