### ISSUE TITLE
[FEATURE] 桌面端使用 ide-components 模块时替换 cdn 为本地资源

### ISSUE THREAD

**Issue by yantze** [opensumi/core#2454]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

用户在使用插件时，插件的组件会用到 opensumi/ide-components/2.22.6-rc-1677637630.0/lib/xxx.js 相关的资源，目前桌面端也用的是 cdn 资源，但每次发布后， cdn 资源没有同步，导致插件的组件访问 cdn 资源会 404。

**描述你预期的功能表现（Describe the solution you'd like）**

桌面端在打包时，提供 ide-components 的资源到安装包。

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
https://github.com/opensumi/core/pull/2830 已解决
