### ISSUE TITLE
[BUG] Preference 的目录在 defaultPreferences 的exclude 中时，调用preferenceService.set('launch'报错

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2458]
**描述你的问题（Describe the bug）**

Preference 的目录在 defaultPreferences 的exclude 中时，调用preferenceService.set('launch'报错

**复现路径（To Reproduce）**
-  在 renderApp 中设置 workspacePreferenceDirName: '.kldx/ide',
- 在 defaultPreferences 添加隐藏：`'files.exclude': { '.kldx/**': true,`
- 在contribution 代码中使用 preferenceService 设置 launch 字段
```
 await this.preferenceService.set('launch', buildDebugConfigurations({
      unitInfo: selectedDebugUnit,
      context: await this.getContext(),
      mockParamsFilePath: await this.getMockedParamsFilePath(selectedDebugUnit.apiName),
    }));
```

**预期表现（Expected behavior）**

正常设置 launch.json

**问题截图（Screenshots）**

<img width="923" alt="image" src="https://user-images.githubusercontent.com/13082375/226543462-acabb247-443e-4772-bfeb-184b25a33d0c.png">

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

如果不设置隐藏自定义配置目录，可以正常运行

**Comment by erha19** [comment]
@geekeren 看了一下具体实现，这里是 byDesign，如果在 OpenSumi 内设置了 `'files.exclude': { '.kldx/**': true }`，则后续通过文件服务将读取不到对应目录下的文件内容，这里是由于文件读取不到导致的配置项设置问题，如果该配置项是必要且需要通过 IDE 内部变更，则不能把这个配置文件放到 `files.exclude` 内。

**Comment by geekeren** [comment]
现在的需求是系统修改 lanuch.json ，但是不想把这个文件暴露给用户

**Comment by erha19** [comment]
@geekeren `files.exclude` 参数一般用于隐藏 `.git/.cache` 等一些与用户无关联的文件夹展示, 如果你这边期望在 `.kldx/**` 下能让调试面板读取到 `launch.json` 内容，那就不能将这个目录隐藏，这会导致调试面板读取不到配置的值。


你这里如果只是希望一个前端显示上的过滤逻辑，你可以对 `file-treee.service.ts` 的这部分逻辑做重载实现，或新增一个 Filter 逻辑到 `opensumi/core` 来实现

https://github.com/opensumi/core/blob/ad721ea4259a2305f2287d82e792ae9331abc0dd/packages/file-tree-next/src/browser/file-tree.service.ts#L234-L248
