### ISSUE TITLE
[BUG] 运行时插件和 vscode 版本冲突

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2464]
**描述你的问题（Describe the bug）**
插件报了这个么个错误，感觉是插件依赖的 vscode 版本太高，运行时版本太低，这种一般怎么解决呀？
The language client requires VS Code version ^1.67.0 but received version 1.63.2

**复现路径（To Reproduce）**
lua 插件 sumneko  3.6.17  win32-x64
加载插件报错

```
Error: Failed opening file C:\Users\86186\.etest-oss\logs\20230322\extHost.log for writing: Permission denied
    at createRotatingLogger (C:\workspace\et_upper4\node_modules\.pnpm\spdlog@0.9.0\node_modules\spdlog\index.js:34:9)
    at C:\workspace\et_upper4\node_modules\.pnpm\spdlog@0.9.0\node_modules\spdlog\index.js:27:7
   ...[node]Failed to search: d:\workspace\qqq Error: spawn C:\workspace\et_upper4\node_modules\.pnpm\@opensumi+vscode-ripgrep@1.4.0\node_modules\@opensumi\vscode-ripgrep\bin\rg.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\workspace\\et_upper4\\node_modules\\.pnpm\\@opensumi+vsc...[node][extHost:error] [extHost:error] The language client requires VS Code version ^1.67.0 but received version 1.63.2      
[extHost:error] [Extension-Host] The language client requires VS Code version ^1.67.0 but received version 1.63.2
```

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@zhuzeyu22 可以升级一下 OpenSumi 版本至 2.23.0，我们将内核适配版本适配到了 1.68.0，应该可以解决你的问题，同时，可能会有部分 BreakingChange，可以参考一下这个文档 https://github.com/opensumi/core/blob/v2.22/CHANGELOG.md

**Comment by zhuzeyu22** [comment]
> 
更新相关包到 2.23.0 的版本，然后出现如下问题
![image](https://user-images.githubusercontent.com/13432873/226826607-9a9df50e-10c2-4725-a7e0-c0f7164cc8d6.png)

**Comment by erha19** [comment]
@zhuzeyu22 这里主要为写入文件的权限问题，Windows 下对用户目录写入内容可能是会有这个报错的，但暂时不影响功能使用， @yantze 看下这个问题吧，相关联的问题还有 https://github.com/opensumi/core/issues/2383.

**Comment by zhuzeyu22** [comment]
@erha19 外面的 log error 是权限问题，里面的似乎受到  utf-8-validate 这个包的版本影响，package 里面缺少 utf-8-validate 和 bufferutil 这两个包版本号的信息。

**Comment by erha19** [comment]
> @erha19 外面的 log error 是权限问题，里面的似乎受到 utf-8-validate 这个包的版本影响，package 里面缺少 utf-8-validate 和 bufferutil 这两个包版本号的信息。

这两个依赖应该只是子依赖，由包管理器自动处理版本号的，关键应该还是在权限问题上面

**Comment by zhuzeyu22** [comment]
更新 core 版本至 2.23.0 插件加载成功， 因为没有报错所以 log error 不再出现，但是不确定是否已解决。此 issue 可以关闭。
