### ISSUE TITLE
[BUG] NodeJS 调试首次调试时，暂停时自动定位的帧不是断点所处的位置

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2465]
**描述你的问题（Describe the bug）**
NodeJS 调试首次调试时，导致断点没有停在打断点的位置

**复现路径（To Reproduce）**
- 首次进入 IDE
-  添加一个 nodejs 断点
-  点击调试

**预期表现（Expected behavior）**

断点停在打断点的位置

**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/13082375/226807319-caf05a32-bd76-464c-9fa4-246ae8c83e56.png)

下面是二次调试的时候，是正常的。可以看出第一次调试时，断点停止所处位置是正常的第二条堆栈
![image](https://user-images.githubusercontent.com/13082375/226806760-b30b0aa6-83ea-4a84-b880-e328d94e7077.png)

可能的原因是：
第一次断点暂停时，堆栈帧列表中 **丢失了打断点的这一帧**，如下图。由于界面上由于会自动定位到列表第一项，从而定位到预期堆栈列表的 第二项（hooks.js ）。
![image](https://user-images.githubusercontent.com/13082375/226807065-55b0a996-2c0f-42c7-850d-ec2efddb9104.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
我来看一下

**Comment by Ricbet** [comment]
@geekeren  我这边本地没有复现，可以麻烦提供下最小可复现的示例么?

**Comment by Ricbet** [comment]
这里的堆栈信息列表都是直接从 DAP 的 stackTrace 请求去读取的，出现 “未知源” 可能是堆栈的 source 源为空，得看看第一次调试的时候 stackTrace 请求返回的列表的第一个 source 源是不是为空

https://github.com/opensumi/core/blob/42e27186b232d0ae8030152d65682899e28c7578/packages/debug/src/browser/model/debug-thread.ts#L137

**Comment by geekeren** [comment]
@Ricbet 
![image](https://user-images.githubusercontent.com/13082375/226838865-62569dd8-c8ce-44d1-8b87-183873aeb118.png)

第一次
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/13082375/226838590-64f516d1-c739-4612-ac06-67364100f8bf.png">

第二次
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/13082375/226838732-5e0055a1-0a99-495d-82e7-0132cba12882.png">

**Comment by geekeren** [comment]
第一次有个异常情况 ，第一次  frames（大小为1）的数据，id=0 关联的是当前断点行，后来又出现一个 id=0 的数据，就是那个未知源的

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/13082375/226840172-59e7a0d0-baab-43b0-a3f5-d054bb4e85d1.png">

**Comment by Ricbet** [comment]
看起来是被覆盖了，按理说堆栈列表的 id 是唯一的
你看看 `doFetchFrames` 里的 `stackTrace` 请求返回什么信息呢？

**Comment by geekeren** [comment]
@Ricbet 似乎没毛病？
![image](https://user-images.githubusercontent.com/13082375/226845731-921a6c03-734e-4a44-9e70-8c98307f24b9.png)

<img width="1578" alt="image" src="https://user-images.githubusercontent.com/13082375/226845636-671da237-9455-4801-b035-f160201e0e97.png">

**Comment by geekeren** [comment]
@Ricbet 这个是数据是来自于 vscode debug 插件吗，所以应该是插件的问题？

**Comment by Ricbet** [comment]
@geekeren 数据是来自于插件的，你可以在本地 VS Code 验证一下是不是也是同样的情况

**Comment by geekeren** [comment]
@Ricbet vscode 上没有复现。js-debug 版本 1.70.0

**Comment by geekeren** [comment]
@Ricbet 能不能看看 VSCode 这个地方是怎么处理的

**Comment by Ricbet** [comment]
> @Ricbet 能不能看看 VSCode 这个地方是怎么处理的

看了下 vscode 对 stackFrame 的实现，确实是没有对相同的 id 做覆盖，而是直接 concat 返回的，这块逻辑可以优化一下

**Comment by Ricbet** [comment]
vscode 是在这里直接 return 所有的 stackframes 的

https://github.com/microsoft/vscode/blob/99c19a6f6b614ef64c68a233061e60494638ef09/src/vs/workbench/contrib/debug/common/debugModel.ts#L579

然后在渲染的时候直接 concat 拼接上去了
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugModel.ts#L559

所以我们只需要把 debug-thread 文件的那一块 doUpdateFrames 逻辑优化一下应该就可以了

**Comment by geekeren** [comment]
@Ricbet 那需要把 _frames 的数据结构从 Map 改成数组，你看会有什么副作用吗，我来提个PR

**Comment by geekeren** [comment]
@Ricbet 或者把相同 ID 的frame的 ID 转换一下变成不一样的

**Comment by Ricbet** [comment]
> @Ricbet 那需要把 _frames 的数据结构从 Map 改成数组？？，你看会有什么副作用吗，我来提个PR

其实也不一定要改成数组，只需要保证后来的相同 id 不会覆盖前面的就行。👏欢迎提 PR
