### ISSUE TITLE
[Question] 如何针对 vscode 插件做一些定制调整？

### ISSUE THREAD

**Issue by miserylee** [opensumi/core#2474]
**描述你的问题（Describe you question here）**

请教下，现在有个 vscode 的插件的逻辑有点不符合预期，我们能通过 contribution 或者 service 来针对插件做一些定制逻辑吗？

merge-conflict 插件，改起来太重了
或者我们有什么办法能够监听到插件 ready 的回调吗，有些 ui 组件是在插件 ready 之后才有的，需要在插件加载好以后我们再调整一下

**Comment by erha19** [comment]
@miserylee 目前 OpenSumi 内针对插件的声明周期有一些事件可以使用，如 `ExtensionActivateEvent`，你可以监听后针对激活的插件进行自定义处理（内部有 topic 区分激活类型），相关代码见：

https://github.com/opensumi/core/blob/19e2f332b12a32cd6a0a87126d94f26bddfa26a0/packages/core-common/src/types/extension.ts#L94

你可以使用 `eventService` 或  `@onEvent` 去使用，不过从 UI 逻辑执行到渲染，可能还有个时间差，如果你在这些回调内进行视图修改，可能不能完全保障时序的有效性。

**Comment by miserylee** [comment]
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/vscode.merge-conflict.i18n.json

**Comment by erha19** [comment]
@miserylee 这里的插件使用了 VS Code 在 1.73 版本引入 1.76 版本完成的 `vscode.l10n` API， 相关内容见: 

https://github.com/microsoft/vscode/blob/cdc521af16e7791e0968016ef3fd9a5d3249750b/extensions/merge-conflict/src/mergeDecorator.ts#L90
https://github.com/microsoft/vscode/pull/163344

OpenSumi 中暂时还未对该 API 进行实现，你可以考虑使用一下旧版本的 MergeConflict 插件或尝试实现一下这个 API 能力。
