### ISSUE TITLE
[BUG] 在没有开启调试的情况下按 alt/option 键之后会导致 hover 语法失效

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#248]
**描述你的问题（Describe the bug）**

rt

**复现路径（To Reproduce）**

1. 不开启调试
2. 按 alt 或 option 键
3. 输入 `console.log('>>')` 代码
4. 鼠标 hover 在 log 上，会发现不提示语法效果

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/20262815/147652368-61955fc8-cc36-4628-94ac-aeec5ebb77f6.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
其实不用这么复杂，编辑器里按 alt 或者 option 键就会挂
