### ISSUE TITLE
[BUG] 在编辑器中偶现打开命令面板失败

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#2495]
**描述你的问题（Describe the bug）**

在编辑器中打开命令面板失败

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/6399899/227703721-ce295947-3184-40f4-b323-d4be8afb125b.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
closed by https://github.com/opensumi/core/pull/2117.
