### ISSUE TITLE
[Question] 请问如何动态添加 snippets 并且不影响原生配置的 snippets

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2503]
请问如何动态添加 snippets 并且不影响原生配置的 snippets，
以 lua 插件为例，目前我在 lua 插件里面 配置了一个 snippets 的 json ，但是我依然有动态配置 lua snippets 的需求，鉴于框架无法和插件通信，如何以尽量小的代价完成需求。

**Comment by erha19** [comment]
@zhuzeyu22 插件与框架是可以通信的，参考文档：[通信模型](https://opensumi.com/zh/docs/extension/opensumi-api/connection-mode)

另外，这里是插件进程在实现代码片段补全能力的具体代码，你参考着追加自定义的补全逻辑：

https://github.com/opensumi/core/blob/061ff4c6d9517a2d637bd06f547ee5e92ac5f156/packages/extension/src/browser/vscode/api/main.thread.language.ts#L282
