### ISSUE TITLE
[Question] editor title 的 menu 有办法定制 UI 吗？

### ISSUE THREAD

**Issue by miserylee** [opensumi/core#2508]
**描述你的问题（Describe you question here）**

![image](https://user-images.githubusercontent.com/16648966/227964023-eec72b42-7f63-4972-bbf8-bb7a0fdb7975.png)

编辑框上方的操作按钮，是否可以定制 UI，如果可以的话，可以提供一个示例参考一下，Thanks♪(･ω･)ﾉ

**Comment by erha19** [comment]
@miserylee 注册新的按钮的方式是 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/editor-title ，你这里是想替换图标吗？

**Comment by miserylee** [comment]
@erha19 这里是想接管按钮的 UI 层实现

**Comment by erha19** [comment]
@miserylee 相对麻烦，这里应该只有分屏和关闭全部的按钮是框架内实现的，见: https://github.com/opensumi/core/blob/65e38354879fa355b745d037b6411699504e6d54/packages/editor/src/browser/editor.contribution.ts#L1274-L1282

你可以通过 `menus.unregisterMenuItem` 卸载后重新注册的方式去重新实现按钮绑定。

**Comment by miserylee** [comment]
找到了一个定制的方式，注册菜单的时候直接传 component 字段进去就好了，这个组件可以完全接管 ui 
![image](https://user-images.githubusercontent.com/16648966/228213065-2bb74e0a-2807-40bd-93a7-acbc886d1b66.png)
