### ISSUE TITLE
[BUG] 垂直方向视图拖拽边框 z-index 问题

### ISSUE THREAD

**Issue by SunPeter** [opensumi/core#2509]
**描述你的问题（Describe the bug）**
```
.resize-handle-vertical {
  z-index: 999;
}
.resize-handle-horizontal {
  z-index: 4;
}
```

导致现象：
代码编写区域的提示被拖拽边框覆盖

看 `resize-handle-vertical` 的 `z-index` 提升是[resize.module.less#L34](https://github.com/opensumi/core/blob/feat/improve-ui-render-process/packages/core-browser/src/components/resize/resize.module.less#L34)的

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

提示不被覆盖

**问题截图（Screenshots）**

<img width="921" alt="image" src="https://user-images.githubusercontent.com/3616384/228153505-9768cfcb-4104-4b5b-93b5-c1cff5dd33dd.png">

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**
<img width="667" alt="image" src="https://user-images.githubusercontent.com/3616384/228155056-625c5e24-9195-4936-8ae0-bd0ece450e18.png">

**Comment by erha19** [comment]
@SunPeter 这里的修改考虑不周了 https://github.com/opensumi/core/pull/1852 ，你可以提个 PR 到 v2.23 分支修复一下，这里应该跟 `resize-handle-horizontal` 保持一致的层级，同时避免一下出现 https://github.com/opensumi/core/issues/1840 这里的问题。

这里应该把 `resize-handle-vertical` 层级修改为 4 可以解决这个问题。
