### ISSUE TITLE
[Question] 打开文件资源对话框，选择文件夹，使用哪个api

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2515]
我的具体需求是 用户点击页面上导出按钮，打开电脑文件资源对话框，选择一个文件后点击保存，我会在选中的文件夹下创建多个文件。现在不知道打开文件资源对话框选择文件用的是哪个api，只找到了IElectronNativeDialogService showOpenDialog  showSaveDialog 不满足需求

**Comment by erha19** [comment]
@767746649zyy 目前内置封装的只有 `showOpenDialog / showSaveDialog ` 两个方法，如果不满足需求的话可以自行封装方法使用，参考一下示例内实现。
