### ISSUE TITLE
[Question] 全局的 window.onbeforeunload 如何取消？

### ISSUE THREAD

**Issue by zmyiy** [opensumi/core#2519]
**描述你的问题（Describe you question here）**
页面刷新或者离开时经常会触发确认对话框，且这个是全局配置的，请问如何关闭。
![image](https://user-images.githubusercontent.com/33682340/228564052-ef1411c5-da26-499d-ac2b-1e569148bd42.png)

![image](https://user-images.githubusercontent.com/33682340/228563766-4e1a9dcc-9094-404c-8354-86f8abc239f2.png)

**Comment by yantze** [comment]
settings.json 里面加上配置 `  "application.confirmExit": "never"` 或者在集成 OpenSumi 的时候:
```ts
new ClientApp({
  defaultPreferences: {
    "application.confirmExit": "never"
  },
});
```
