### ISSUE TITLE
[BUG] cmd + shift + f 切换到搜索面板时需要全选输入框里的内容

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2522]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/228723185-0a495482-23ee-46f3-bd8f-6d884e8a3452.png)

先选中编辑器内的某段代码，然后通过快捷键切换到搜索面板，应该默认全选输入框里的内容
更好的做法是可以提供一个配置项去配置

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

![image](https://user-images.githubusercontent.com/20262815/228723460-de93711d-8b7e-47fe-af7a-abd362a23677.png)

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
输入框中的快捷键偶尔也会失效，如 CMD+A 这些，可能也得一起看一下，估计跟快捷键 when 条件冲突有关
