### ISSUE TITLE
[Question] menu菜单栏是否支持增加二级菜单，如果支持，请问如何添加

### ISSUE THREAD

**Issue by wtc842017068** [opensumi/core#2525]
**描述你的问题（Describe you question here）**

**Comment by Ricbet** [comment]
参考官方文档提供的示例 [注册二级子菜单](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-menu/#%E6%B3%A8%E5%86%8C%E4%BA%8C%E7%BA%A7%E5%AD%90%E8%8F%9C%E5%8D%95)
