### ISSUE TITLE
[Question] 请问在 ide-electron里如何添加一个自定义窗口（比如说 项目管理器）

### ISSUE THREAD

**Issue by hutieshan** [opensumi/core#2535]
请问在 ide-electron里如何添加一个自定义窗口（比如说 项目管理器）

每次进入先选择项目 然后再进入ide
有没有关于这方面的案例或者文档啊？谢谢

**Comment by erha19** [comment]
@hutieshan 可以参考这个案例 https://github.com/opensumi/app-desktop

**Comment by hutieshan** [comment]
好的谢谢
