### ISSUE TITLE
[Question] IDE 布局：如何设置左侧插槽最大宽度

### ISSUE THREAD

**Issue by fanweiren1217** [opensumi/core#2537]
**描述你的问题（Describe you question here）**
参考的 https://github.com/opensumi/core/blob/main/packages/startup/entry/web/layout.tsx 布局，如何设置左侧插槽(目录树)最大宽度

![image](https://user-images.githubusercontent.com/127910654/229031234-1f75ca4d-ca5f-4d7c-99ba-e6581a4c2ebf.png)

**Comment by erha19** [comment]
@fanweiren1217 这里有一个属性 `maxSize` 可以用，参考 https://github.com/opensumi/core/blob/0f7204fff6418d589722e54081d7212e2e81d244/packages/core-browser/src/components/layout/split-panel.tsx#L51

**Comment by geekeren** [comment]
@erha19 maxSize 是设置在SplitPanel 不是在设置在 SlotRenderer 上的。像下面的代码应该怎么改：
```
   <BoxPanel direction="top-to-bottom">
      <SlotRenderer defaultSize={35} slot="top" z-index={2} />
      <SplitPanel id="main-horizontal" flex={1}>
        <SlotRenderer
          backgroundColor={colors.sideBarBackground}
          slot="left"
          isTabbar={true}
          defaultSize={260}
          minResize={260}
        />
        <SplitPanel
          id="main-vertical"
          minResize={600}
          flexGrow={1}
          direction="top-to-bottom"
          className={clsx({
            [styles.fullScreen]: fullScreen,
          })}
        >
          <SlotRenderer backgroundColor={colors.editorBackground} flex={1} flexGrow={1} slot="main" />
          <SlotRenderer
            backgroundColor={colors.panelBackground}
            flex={1}
            defaultSize={280}
            minResize={100}
            slot="bottom"
            isTabbar={true}
          />
        </SplitPanel>
        <SlotRenderer slot="right" isTabbar={false} defaultSize={480} minResize={300} />
      </SplitPanel>
    </BoxPanel>
```

**Comment by geekeren** [comment]
@erha19 顺便反映一个问题。 slot="right"  defaultSize={480}  设置是无效的，清空了浏览器和，本地文件夹.sumi 缓存，右侧面板的 默认大小永远都是 384px

**Comment by erha19** [comment]
这里 https://github.com/opensumi/core/issues/2537#issuecomment-1495728989 具体是要实现什么布局效果？我看能不能做个示例 @geekeren

**Comment by geekeren** [comment]
@erha19 1. 在opensumi默认布局基础上，支持：左侧默认260，最小260，最大 420; 右侧插槽的默认大小480，但是没有生效

2. 然后其实我们还需要其它的效果，看现在也是不支持的，就是当插槽大小小于一定阈值的时候，就自动折叠。比如当 底部插槽小于 100（承载不了什么有效信息的时候，就自动最小化折叠在底部）

第一条 默认大小480，没有生效 应该是 bug? 最大大小是个新 feature 感觉可以支持下；第二条能支持就最好了
