### ISSUE TITLE
[BUG] OutputChannel messages not displayed in ide-electron

### ISSUE THREAD

**Issue by CaptainNeo2023** [opensumi/core#2538]
We would like to use **createOutputChannel** function to write output at **ide-electron** but the issue is that we were not able to import relevant module for example "@opensumi/ide-output" from opensumi libraries. To import the function, we defined a library in ide-electron\package.json file

"devDependencies": {
    "@opensumi/sumi": "^2.23.1",
    "@opensumi/ide-output": "2.23.1",
    // etc...

Here's a link to README.md file and below is the copy of the content.

https://www.npmjs.com/package/@opensumi/ide-output?activeTab=code

### 插件 API

插件中通过 `window.createOutputChannel` 也可以创建一个输出通道，该 API 底层即是通过 Output 模块实现的。

```ts
const channel = sumi.window.createOutputChannel('My Extension');

channel.appendLine('some logging...');
```
_My question is how to import createOutputChannel from openSumi module?_

<img width="573" alt="OUTPUT_CHANNEL" src="https://user-images.githubusercontent.com/129503968/229396015-218b6c6b-6443-48ad-97a9-28dda5a3711c.png">

The createOutputChannel function was found in @opensumi/sumi module but we don't know yet how to import the function from the module.

<img width="1065" alt="SUMI" src="https://user-images.githubusercontent.com/129503968/229401725-30fb8ff1-0f1a-49d1-9897-94cfcfef3124.png">

**Comment by erha19** [comment]
@CaptainNeo2023 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/editor-title 参考一下这个案例 ~

**Comment by CaptainNeo2023** [comment]
> 参考一下这个案例

If try to build the example in the above link, many errors are spawn by webpack and build fails because of unexpected token and loader isn't configured, how to configure webpack to build the example?

<img width="834" alt="ERROR" src="https://user-images.githubusercontent.com/129503968/229403777-ec555cbf-a820-4a6e-936a-6282baf79881.png">

**Comment by erha19** [comment]
@CaptainNeo2023 I don’t know what you have modified here. Standard-based [ide-electron](https://github.com/opensumi/ide-electron/issues) or [opensumi-module-samples](https://github.com/opensumi/opensumi-module-samples) project should be able to run normally. 

Maybe you should remove all the  `node_modules` or install them again, there may have some errors on the console.

Or provide an example that can reproduce your problem so that we can troubleshoot

**Comment by CaptainNeo2023** [comment]
> @CaptainNeo2023 I don’t know what you have modified here. Standard-based [ide-electron](https://github.com/opensumi/ide-electron/issues) or [opensumi-module-samples](https://github.com/opensumi/opensumi-module-samples) project should be able to run normally.
> 
> Maybe you should remove all the `node_modules` or install them again, there may have some errors on the console.
> 
> Or provide an example that can reproduce your problem so that we can troubleshoot

The build folder contains all webpack config files copied from ide-electron Github repository and the errors using webpack exists only if use @Autowired(OutputService) dependency injection which is imported from '@opensumi/ide-output/lib/browser/output.service' library.
 .
The errors from yarn build of ide-electron node_modules folders were all similar to the screenshot with "Module parse failed: Unexpected character '@' " message.

<img width="839" alt="UNEXCEPTED TOKEN" src="https://user-images.githubusercontent.com/129503968/229416305-cb5a26b4-2869-4e96-824a-c196c41a59e4.png">

**Comment by erha19** [comment]
@CaptainNeo2023 The resource of the `@opensumi/ide-output` contains `*.less` and `*.ts` files, if you want to compile with this module, you should add `less-loader` to compile the source, maybe you can see  https://webpack.js.org/loaders/less-loader/ to find some resolutions.

**Comment by CaptainNeo2023** [comment]
> @CaptainNeo2023 The resource of the `@opensumi/ide-output` contains `*.less` and `*.ts` files, if you want to compile with this module, you should add `less-loader` to compile the source, maybe you can see https://webpack.js.org/loaders/less-loader/ to find some resolutions.

The next steps were done based on the latest [ide-electron](https://github.com/opensumi/ide-electron) source code but the build has still errors same errors.

> git clone git@github.com:opensumi/ide-electron.git
> cd ide-electron
> pnpm i
> pnpm build
> pnpm rebuild-native -- --force-rebuild=true
> pnpm download-extension # install extension (Optional)
> pnpm start

**Comment by erha19** [comment]
@CaptainNeo2023 It looks like there have no errors, but have some code you write, please provide more detail or a sample that can reproduce your problem.

**Comment by CaptainNeo2023** [comment]
> @CaptainNeo2023 It looks like there have no errors, but have some code you write, please provide more detail or a sample that can reproduce your problem.

A bug

I build the sample [editor-title](https://github.com/opensumi/opensumi-module-samples/tree/main/modules/editor-title) to see whether OutputService works in ide-electron and web browser, but the result is that only web browser displays messages..

The web browser displays messages from the **OutputChannel** function in window, but the ide-electron **OutputService** fails and displays only red colored error messages in the slot of window instead of messages from the **OutputChannel** function.

<img width="713" alt="IDE-ELECTRON" src="https://user-images.githubusercontent.com/129503968/229974553-f1ace463-7908-4e57-b148-4e29afa27e1a.png">

_The source code is placed in ide-electron modules folder._

<img width="805" alt="EDITOR-TITLE" src="https://user-images.githubusercontent.com/129503968/229974660-0324117b-9054-4a12-902d-f60d1ed7dabb.png">
