### ISSUE TITLE
[BUG] 调试断点概率性丢失

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2552]
**描述你的问题（Describe the bug）**

调试的断点经常在页面刷新几次后丢失了，非必现，但是复现频率很高

**复现路径（To Reproduce）**
- 添加调试断点，刷新页面多次
- 断点丢失

**预期表现（Expected behavior）**
断点不丢失

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: 2.23.3-rc-1680530879.0

**Comment by erha19** [comment]
@geekeren 这个问题应该与 https://github.com/opensumi/core/pull/2485 问题类似，由于时序的提前导致数据获取问题，断点存储以及读取的逻辑位置是在：

https://github.com/opensumi/core/blob/367000b9d70d6b555eeaa7ac0a9ecb39b052161d/packages/debug/src/browser/breakpoint/breakpoint-manager.ts#L254-L289

最终断点会存储于 `~/.sumi/datas/debug.json` 中，这里进行断点加载时机较晚 https://github.com/opensumi/core/blob/53de6e7a04660d7e2f796fda5a99e6c7f5f261ba/packages/debug/src/browser/debug-contribution.ts#319

可以参考 #2485 增加一个 whenReady 状态位来保障断点的加载时序。可以尝试修一下

**Comment by geekeren** [comment]
@erha19 这是要给你们提 PR，还是改业务的代码？不仅是通过 API 拿断点会丢，编辑器的左侧的断点也会丢

**Comment by erha19** [comment]
@geekeren 提 PR 吧，框架上的问题，#2485 上面修复的是选中的调试配置丢失问题，没有解决断点的问题

**Comment by erha19** [comment]
@geekeren 基于 v2.23 分支去修改，指到这个分支，后面跟 2.23.3 的 patch 版本一起发布

**Comment by geekeren** [comment]
@erha19 现在的问题是什么呢？是 save 前没有load 完成？

**Comment by erha19** [comment]
> @erha19 现在的问题是什么呢？是 save 前没有load 完成？

初步判断是断点面板加载时 load 的时机没时序保证，导致有可能在没 load 前 save 了一个空对象导致断点丢失，可以打个 Log 到这两个方法上面看一下 @geekeren ，

**Comment by geekeren** [comment]
@erha19 执行顺序没有问题，发现是 storage.get('breakpoints' 取不到值 返回了 fallbackvalue。.sumi/datas/debug.json 文件里面是有断点数据的
