### ISSUE TITLE
[BUG] openSumi 不支持按规则(autoImportFileExcludePatterns)匹配自动引入 NPM 模块

### ISSUE THREAD

**Issue by zmyiy** [opensumi/core#2554]
**描述你的问题（Describe the bug）**
例如 package.json 安装了 lodash，在代码块输入相关 API 时，禁止自动导入提示：
![image](https://user-images.githubusercontent.com/33682340/230293513-d638a57c-acdb-424d-bdcd-651327637a42.png)

**复现路径（To Reproduce）**
配置 settings
```json
{
  "javascript.preferences.autoImportFileExcludePatterns": [
    "lodash"
  ]
}
```

**预期表现（Expected behavior）**
在 JS 文件中输入 `clone` 不会展示 lodash 相关的 API 提示。

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: 2.23.3-rc-1680530879.0
- typescript：5.0.2

**Comment by zmyiy** [comment]
目前短期解决方案为，全局关闭：
```json
{
  "javascript.suggest.autoImports": false
}
```

**Comment by Ricbet** [comment]
这个配置项只有在插件 `typescript-language-script  1.69` 以上版本才有，试试升级到 1.69 版本看看呢

**Comment by Ricbet** [comment]
@zmyiy

**Comment by zmyiy** [comment]
> 这个配置项只有在插件 `typescript-language-feature 1.69` 以上版本才有，试试升级到 1.69 版本看看呢



> 

@Ricbet 似乎最新版本为 [1.63](https://marketplace.opentrs.cn/extension/635f6abdffa7814f35a65753)，没有 1.69 这个版本。
![image](https://user-images.githubusercontent.com/33682340/230365445-50892a82-5aef-468b-b4ba-cddacf0a5490.png)

**Comment by Ricbet** [comment]
@zmyiy 插件市场已经上架了 1.70.2 版本，你可以下载试试，验证了下是支持 autoImportFileExcludePatterns 的
![image](https://user-images.githubusercontent.com/20262815/230533639-4a272489-a9d5-4290-b1ba-f938a10647ef.png)
