### ISSUE TITLE
[BUG] 打开左侧搜索面板时，应该默认选中所有的文字

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#2575]
VSCode 的表现是默认选中框内的文字的：
<img width="278" alt="image" src="https://user-images.githubusercontent.com/13938334/231192102-375341d2-a128-4a42-ab8e-7dd05e0e4174.png">

**Comment by Ricbet** [comment]
与 https://github.com/opensumi/core/issues/2522 重复了
