### ISSUE TITLE
[BUG] 安装了jupyter插件，加载插件报错

### ISSUE THREAD

**Issue by fishbar** [opensumi/core#2582]
**描述你的问题（Describe the bug）**
vscode-extensions.json 新增jupyter插件
```json
     {
        "name": "ms-toolsai_jupyter",
        "version": "2021.5.745244803",
      }
```

![image](https://user-images.githubusercontent.com/981128/231651650-132ef20b-7819-45b9-95e0-f7d032d55800.png)

**复现路径（To Reproduce）**

1. 插件搜索 jupyter， 并安装
2. 打开一个 jupyter 文件： [basic/notebook1.ipynb](https://raw.githubusercontent.com/jupyter/nbconvert-examples/master/basic/notebook1.ipynb)

**预期表现（Expected behavior）**

正常能打开：
![image](https://user-images.githubusercontent.com/981128/231652404-0aeadc77-fa0e-4e49-a447-80adf37d1038.png)

**环境信息（Environment）**

- OS:  macOS 11.2 Apple M1]
- Browser: chrome 112.0.5615.49 
- OpenSumi Version: git branch main

**Comment by erha19** [comment]
@fishbar 这里的问题主要还是旧版本插件的错误写法导致的报错，相关插件在 VS Code 下也是不能正常工作的
![image](https://user-images.githubusercontent.com/9823838/231685258-5fd01e68-bc14-4338-a675-c379fc466b67.png)

另外 Jupyter 插件对 Notebook API 有强依赖，暂时还没有这块实现计划，有兴趣可以一起共建 ~
