### ISSUE TITLE
[BUG] Terminal 无法优雅禁用，禁用 IDE 无法运行或者控制台报错

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2640]
**描述你的问题（Describe the bug）**

由于业务需要，我们希望命令终端不对用户开放。所以在renderApp ClientAppOpts modules 中移除 TerminalNextModule，此时 IDE 无法启动，会报错：
![image](https://user-images.githubusercontent.com/13082375/233826248-952f37a2-2220-4e09-860b-af132a0d90b2.png)
于是我们只是单独禁用 server 端的 terminal 模块，在前端只隐藏 terminal UI (依旧加载 TerminalNextModule）。

功能使用正常，但是浏览器 控制台依旧报错：
![img_v2_b6a73b6e-a441-4b7e-9fe7-81ebe410568g](https://user-images.githubusercontent.com/13082375/233826302-c0d22de2-fca8-4f49-83a1-7c181c65689a.jpg)

**复现路径（To Reproduce）**

 场景一：前端移除 TerminalNextModule，后端移除 TerminalNodePtyModule
- renderApp 移除 TerminalNextModule
- 进入 IDE
- 页面无法加载， 报错 not find Provider of Symbol(ITerminalProfileService)，
 
场景二：前端只禁用 terminal UI，后端移除 TerminalNodePtyModule
- layout-config     [SlotLocation.bottom]:  中移除 terminal
- 页面正常加载，报错caught (in promise) TypeError: Cannot read properties of undefined (reading 'isTerminalViewInitialized')
 

**预期表现（Expected behavior）**

可以抽离terminal，且控制台无报错

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: 2.23.4

**Comment by life2015** [comment]
可以在 LayoutConfig 出关掉 Terminal 的渲染
<img width="401" alt="image" src="https://user-images.githubusercontent.com/12879047/233827121-34d03a45-240a-44e8-b067-ea019afedad7.png">

**Comment by geekeren** [comment]
@life2015 关掉就是第二个场景 会有报错

**Comment by geekeren** [comment]
@life2015 希望 opensumi 可以支持 terminal module 完全不注册的情况，看 packages/extension/src/browser/vscode/api/main.thread.terminal.ts 这个对 terminal 会有耦合

**Comment by life2015** [comment]
这块的解耦可能不彻底，可以看下 ` TypeError: Cannot read properties of undefined (reading 'isTerminalViewInitialized') ` 的调用栈吗，看看它是上层的哪个方法调用的。

**Comment by geekeren** [comment]
@life2015 terminalController在初始化时需要调用 this.terminalContextKey, this.terminalContextKey 构造时会依赖 terminalView,  terminalView被隐藏了就会报这个错

**Comment by AhkunTa** [comment]
@geekeren  目前初始化的时候会初始化 `terminal` 的贡献点 如果想全部移除 `terminal`  模块这块可以使用 override 来hack 类似于这样 
```javascript
import {
  VSCodeContributesServiceToken,
  VSCodeContributesService,
} from '@opensumi/ide-extension/lib/browser/vscode/contributes';
import { TerminalContributionPoint } from '@opensumi/ide-extension/lib/browser/vscode/contributes/terminal';
import { DebuggersContributionPoint } from '@opensumi/ide-extension/lib/browser/vscode/contributes/debuggers';
import { BreakpointsContributionPoint } from '@opensumi/ide-extension/lib/browser/vscode/contributes/breakpoints';

export { VSCodeContributesServiceToken };


const OUTSIDE_POINT = [
  TerminalContributionPoint,
  DebuggersContributionPoint,
  BreakpointsContributionPoint,
];
export class VSCodeContributesServiceOverride extends VSCodeContributesService {
  constructor() {
    super();
  }
  ContributionPoints = [
    ...this.ContributionPoints.filter((contributtion) => {
      return !OUTSIDE_POINT.includes(contributtion);
    }),
  ];
}
```

**Comment by AhkunTa** [comment]
> @geekeren 目前初始化的时候会初始化 `terminal` 的贡献点 如果想全部移除 `terminal` 模块这块可以使用 override 来hack 类似于这样
> 
> ```js
> import {
>   VSCodeContributesServiceToken,
>   VSCodeContributesService,
> } from '@opensumi/ide-extension/lib/browser/vscode/contributes';
> import { TerminalContributionPoint } from '@opensumi/ide-extension/lib/browser/vscode/contributes/terminal';
> import { DebuggersContributionPoint } from '@opensumi/ide-extension/lib/browser/vscode/contributes/debuggers';
> import { BreakpointsContributionPoint } from '@opensumi/ide-extension/lib/browser/vscode/contributes/breakpoints';
> 
> export { VSCodeContributesServiceToken };
> 
> 
> const OUTSIDE_POINT = [
>   TerminalContributionPoint,
>   DebuggersContributionPoint,
>   BreakpointsContributionPoint,
> ];
> export class VSCodeContributesServiceOverride extends VSCodeContributesService {
>   constructor() {
>     super();
>   }
>   ContributionPoints = [
>     ...this.ContributionPoints.filter((contributtion) => {
>       return !OUTSIDE_POINT.includes(contributtion);
>     }),
>   ];
> }
> ```

在再外部 覆盖这个 injector
```
    {
      token: VSCodeContributesServiceToken,
      useClass: VSCodeContributesServiceOverride,
      override: true,
    },
```

**Comment by life2015** [comment]
> @life2015 terminalController在初始化时需要调用 this.terminalContextKey, this.terminalContextKey 构造时会依赖 terminalView, terminalView被隐藏了就会报这个错

正常的话 隐藏了 Terminal 之后这些方法就不会调用，我尝试在 OpenSumi core 仓库中使用方案 2关掉 Terminal 也是成功的。
<img width="782" alt="image" src="https://user-images.githubusercontent.com/12879047/233831988-e1ea8394-2766-423d-92e5-d695d09dd188.png">

你遇到的问题可能就是某些耦合没有清理干净
