### ISSUE TITLE
[Question] 通过editorService创建编辑器时，必须绑定文件系统中的某个文件吗？

### ISSUE THREAD

**Issue by fanweiren1217** [opensumi/core#2644]
背景：
需要在表单(Form)中放一个 json 编辑器，支持输入并获取其值。已知已知通过绑定文件系统重特定文件获取其ModelReference，进而拿到其MonacoModel实例，可以实现需求。
问：不想绑定文件系统文件，有办法实现 Form 中的 json 编辑器吗？
![image](https://user-images.githubusercontent.com/127910654/233985207-2ee6d4ca-4d4e-4c12-9df6-2cd70664631f.png)

**Comment by life2015** [comment]
https://github.com/opensumi/core/discussions/2396

查看一下这个 discussion 以及里面最后的 Sample 看看能不能帮到你
