### ISSUE TITLE
🏖 OSPP 2023: Better i18n / l10n support 

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2649]
## ⭐️ 前言

> 开源之夏是中国科学院软件研究所发起的开源软件供应链点亮计划系列暑期活动，旨在鼓励在校学生积极参与开源软件的开发维护，促进优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。
学生可自主选择感兴趣的项目进行申请，中选后在项目资深开发者（社区导师）的指导下进行开发。根据项目的难易程度和完成情况，结项者将获取开源之夏活动奖金和结项证书。

这是 2023 OSPP 开源之夏的进阶课题之一，题目主页：[优化 OpenSumi 框架提供的 i18n 本地化能力
](https://summer-ospp.ac.cn/org/prodetail/23dca0093?list=org&navpage=org)

在本次课题中，你将能完整了解 IDE 研发丰富的知识点，同时掌握如何修改 monaco 及自定义 IDE 的能力。

本课题为进阶课题，完成之后你将能获得 12,000 （人民币）的奖金，预计耗时 3 个月，希望能够认真对待本次课题。

## 🧐 题目背景

Monaco Editor Core （后续简称 monaco）是当前 OpenSumi 内使用的编辑器底层依赖，它提供了国际化的支持。目前，它的国际化 API 是通过导入`setLocale` 内置 API 来使用的，然而，这种方法的可维护性和易用性存在问题。

由于 monaco 的加载时机为 ClientApp 引入阶段，需要用户在加载前使用 `setLocale` 的方式明确语言类型，否则，在默认中文的影响下，用户的英文界面将不可避免的引入 “中文” 国际化内容。

即，当前的语言设置能力存在以下问题：

1. 不易维护：使用 `@opensumi/ide-monaco/lib/browser/monaco-localize` 导入国际化API不够直观，需要开发者熟悉框架国际化的内部实现。这使得在项目中使用 OpenSumi 时，维护困难。
2. 不易用：由于国际化 API 不够直观，使用起来也不够便捷。开发者往往需要同时进行两个语言设置，如通过 AppConfig.defaultPreferences 设置默认的语言 'general.language': 'zh-CN', , 同时仍需要通过 monaco 的 API 提前设置好语言类型。

进一步的，如果结合了 `registerExternalPreferenceProvider` 等配置注册逻辑，整体的配置项将是比较混乱的。

因此，建议改进框架当前的国际化 API 能力。

同时，针对本土化 l10n 能力也需要提供相应的支持以支持 [vscode.l10n](https://code.visualstudio.com/api/references/vscode-api#l10n) 接口能力。

## 👨🏻‍💻 实现思路

建议通过以下方式改进国际化的API：

提供文档和示例：我们建议提供更丰富的文档和示例，以便开发者更容易地学习和使用国际化 API。这将减少开发者在使用国际化 API 时的困惑，并提高其使用体验。

提供一个更直观的 API 接口：我们建议提供一个更直观的 API 接口，以方便开发者使用国际化 API。例如，将 monaco的加载时机后置于 与 ClientApp 创建之后，通过框架自身配置项能力去支持 monaco 的国际化，后续仅需要在默认配置项中声明 “语言” 配置即可。

## 💪 技术要求

- 熟悉 NodeJS 技术，能独立完成传统应用的前后端研发
- 熟悉 Monaco 等常见的编辑器方案
- 熟悉 React，TypeScript 编码

## ⚙️ 产出要求

- 优化 Monaco 的加载时序，首屏时间不影响的情况下，支持用户通过集成配置方式定义客户端语言
- 完整的方案文档及实现思路
- 支持 VS Code 的 l10n API 以提供更完整的本地化能力
- 阶段性的任务进展文档，并关联本文档

## 💬 相关讨论

- https://github.com/opensumi/core/discussions/2409
- https://github.com/opensumi/core/issues/2341

如对题目有疑问，也可在评论区留言交流 ~

**Comment by dingo-emperor** [comment]
可以尝试在opensumi客户端启动最开始用一个异步函数解析配置文件，然后所有依赖Monaco的组件都异步地加载（在解析配置文件的函数返回之后）。可能存在的风险主要是怕剥离不干净，导致异常。

**Comment by wjywy** [comment]
@dingo-emperor  Hello, I am a participant of another project, could you please add your contact information? So that we can discuss problems with each other.The contact information is on my home page

**Comment by dingo-emperor** [comment]
@erha19 老师您好，请问目前这个bug应该怎么复现呢？我尝试在我本地的Web端上在把语言设置成中文和英文，但好像没出现冲突。

**Comment by erha19** [comment]
@dingo-emperor 这个问题需要你在代码里面把 `setLocale`  的逻辑去掉才能复现，现在这种方式只是临时的解决方案，需要额外进行设置，相关代码见：
https://github.com/opensumi/core/blob/9dda754decd912eebd5fbdad89cb8900b844210f/packages/startup/entry/web/app.tsx#L6-L9
详细描述见：https://github.com/opensumi/core/discussions/2409

**Comment by dingo-emperor** [comment]
@erha19 我尝试把setLocale相关的代码去除，然后发现setLocale貌似是用来控制Monaco的语言的，所以在有setLocale相关代码的时候Monaco的语言不会随着用户在web IDE上的设置而变化，永远是上面代码中的defaultLanguage。

但是把setLocale相关代码删掉之后，用户在web IDE上进行语言设置并刷新后，Monaco的语言和其它组件的语言都会变成用户设置的语言。看到上面代码里的注释说如果不用setLocale传则默认会根据 PreferenceScope 的优先级从 LocalStorage 取值，那么用户在web IDE里的设置应该不会导致问题。

**Comment by erha19** [comment]
@dingo-emperor 这里在 monaco-editor-core 内还有一块 hack 逻辑，你要复现问题，最好每次都清理一下 LocalStorage，
这里的逻辑也是较为临时的处理方式，如果用户首次加载，是不存在 LocalStorage 默认值的 https://github.com/opensumi/monaco-editor-core/blob/478a796f4a04fe3a436d3e30c39e1693d3e7d686/src/vs/nls.mock.ts#L37-L57

**Comment by erha19** [comment]
@dingo-emperor l10n 我本周来实现一下，你可以看一下 monaco 那块问题。

**Comment by erha19** [comment]
由于学生 @dingo-emperor 时间问题，该课题结项失败，后续将转为另外的常规 Issue 处理，该课题关闭。
