### ISSUE TITLE
🏖 OSPP 2023: FileWatcher support nonRecursiveWatcher

### ISSUE THREAD

**Issue by pipiiiiii** [opensumi/core#2650]
## ⭐️ 前言

> 开源之夏是中国科学院软件研究所发起的开源软件供应链点亮计划系列暑期活动，旨在鼓励在校学生积极参与开源软件的开发维护，促进优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。
学生可自主选择感兴趣的项目进行申请，中选后在项目资深开发者（社区导师）的指导下进行开发。根据项目的难易程度和完成情况，结项者将获取开源之夏活动奖金和结项证书。

这是 2023 OSPP 开源之夏的基础课题之一，题目主页：[实现 OpenSumi 框架的多版本 FileWatcher(文件监听) 能力](https://summer-ospp.ac.cn/org/prodetail/23dca0202?list=org&navpage=org)

在本次课题中，你将能完整了解 IDE 研发丰富的知识点，同时掌握如何修改 monaco 及自定义 IDE 的能力。

本课题为基础课题，完成之后你将能获得 8,000 （人民币）的奖金，预计耗时 3 个月，希望能够认真对待本次课题。

## 🧐 题目背景

目前 Opensumi 已实现文件监听的能力，但是仅支持在单进程内对项目目录及文件进行递归监听。

由于统一的递归监听过于消耗系统资源，而且同时在插件进程、浏览器进程、NodeJs 进程监听会相互影响，导致发生一些异常情况会引起系统错误，所以需要提供一个非递归的文件监听系统，来提供给周边系统实现各自的监听能力。

本此项目需要基于 NodeJS 提供的文件系统，进行对单文件/单目录的文件监听，同时不影响已有的递归实现。

## 👨🏻‍💻 实现思路

建议使用 NodeJs 提供的 fs 模块，实现对单文件/目录的监听，同时在提供其他模块使用时，支持按需配置，使用递归/非递归监听模式

## 💪 技术要求

* 熟悉 NodeJS 技术，能独立完成传统应用的前后端研发
* 熟悉 Monaco 等常见的编辑器方案
* 熟悉 TypeScript 编码

## ⚙️ 产出要求

* 实现非递归模式的文件监听能力

## 💬 相关讨论

如对题目有疑问，也可在评论区留言交流 ~

**Comment by wjywy** [comment]
My name is JiaYu-wu. After being notified by GuTong, can I claim this issue now? @pipiiiiii

**Comment by wjywy** [comment]
古导师你好，由于最近在复习，所以项目的推动大概会在期末考试结束也就是七月一号开始进行。首先，我会先花十天时间熟悉本项目的一个具体构成以及Monaco这个编辑器方案。在七月十一号到八月十号左右，我会先将初版的demo写出来，在八月十号至八月底这个时间段，将会根据导师您的指导对此进行不断的修改，在九月初至九月三十号，就会尝试着进行PR并不断地进行改进，下面是我的一个初步研究方案
![非递归监听文件系统](https://github.com/opensumi/core/assets/108821231/2ff3cc6f-c171-4c59-a63a-328239854128)

**Comment by pipiiiiii** [comment]
> 古导师你好，由于最近在复习，所以项目的推动大概会在期末考试结束也就是七月一号开始进行。首先，我会先花十天时间熟悉本项目的一个具体构成以及Monaco这个编辑器方案。在七月十一号到八月十号左右，我会先将初版的demo写出来，在八月十号至八月底这个时间段，将会根据导师您的指导对此进行不断的修改，在九月初至九月三十号，就会尝试着进行PR并不断地进行改进，下面是我的一个初步研究方案 ![非递归监听文件系统](https://user-images.githubusercontent.com/108821231/246303513-2ff3cc6f-c171-4c59-a63a-328239854128.png)

时间安排可以的，图里有一个问题，在 watch 的时候，如果是文件夹，应该转换成对当前目录下的文件进行监听，不需要对目录进行监听行为

**Comment by wjywy** [comment]
导师请问一下，插件进程和浏览器进程有对应的实现文件吗？在本地开多个网页，这两个网页用了同一套node进程的文件监听，开第二个网页就会导致第一个网页失效，开多个网页的过程中涉及到另外两个进程了吗？另外两个进程通常会在什么情况下遇到呀？ @pipiiiiii

**Comment by wjywy** [comment]
vscode将递归监听和非递归监听作为两个类引入到diskfileSystem中，opensumi现在是统一引入一个FIleSystemWatcherServer到diskfileSystem，请问是这样吗

**Comment by pipiiiiii** [comment]
> 导师请问一下，插件进程和浏览器进程有对应的实现文件吗？在本地开多个网页，这两个网页用了同一套node进程的文件监听，开第二个网页就会导致第一个网页失效，开多个网页的过程中涉及到另外两个进程了吗？另外两个进程通常会在什么情况下遇到呀？ @pipiiiiii

不好意思才看到这个问题，这块 opensumi 的模型是 CS 的，对于 Client，每个网页就是一个 Client，而 node 的进程就是 Server。
至于插件进程，入口文件在这里：https://github.com/opensumi/core/blob/main/packages/extension/src/hosted/ext.process.ts
可以看下这部分的实现，了解下插件进程和其他进程之间的联系

**Comment by pipiiiiii** [comment]
> vscode将递归监听和非递归监听作为两个类引入到diskfileSystem中，opensumi现在是统一引入一个FIleSystemWatcherServer到diskfileSystem，请问是这样吗

@wjywy 是这样的，这个是代码的组织形式的问题，因为 opensumi 只有一种 watcher，所以没有区分，这块可以改动下

**Comment by wjywy** [comment]
好的 谢谢导师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opensumi/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月1日(星期二) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opensumi/core] 🏖 OSPP 2023: FileWatcher support nonRecursiveWatcher (Issue #2650)





  
vscode将递归监听和非递归监听作为两个类引入到diskfileSystem中，opensumi现在是统一引入一个FIleSystemWatcherServer到diskfileSystem，请问是这样吗
  
@wjywy 是这样的，这个是代码的组织形式的问题，因为 opensumi 只有一种 watcher，所以没有区分，这块可以改动下

**Comment by wjywy** [comment]
好的。谢谢导师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opensumi/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月1日(星期二) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opensumi/core] 🏖 OSPP 2023: FileWatcher support nonRecursiveWatcher (Issue #2650)





  
导师请问一下，插件进程和浏览器进程有对应的实现文件吗？在本地开多个网页，这两个网页用了同一套node进程的文件监听，开第二个网页就会导致第一个网页失效，开多个网页的过程中涉及到另外两个进程了吗？另外两个进程通常会在什么情况下遇到呀？ @pipiiiiii
  
不好意思才看到这个问题，这块 opensumi 的模型是 CS 的，对于 Client，每个网页就是一个 Client，而 node 的进程就是 Server。
 至于插件进程，入口文件在这里：https://github.com/opensumi/core/blob/main/packages/extension/src/hosted/ext.process.ts
 可以看下这部分的实现，了解下插件进程和其他进程之间的联系

**Comment by wjywy** [comment]
导师 我该怎么对非递归监听进行调试呢  有没有一个比较好的方法呢 @pipiiiiii

**Comment by wjywy** [comment]
现在非递归监听的整体结构基本搭建好了

**Comment by wjywy** [comment]
滴滴 @pipiiiiii

**Comment by pipiiiiii** [comment]
想要调试有几种方式：
1. 写一个插件，里面有监听文件的功能，试试只监听某个文件是否可行
2. mock 下使用到文件监听模块的内部模块（比如 scm），只对某些文件的变更触发，看看是否生效
