### ISSUE TITLE
🏖 OSPP 2023: Provide Local History support

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2651]
## ⭐️ 前言

> 开源之夏是中国科学院软件研究所发起的开源软件供应链点亮计划系列暑期活动，旨在鼓励在校学生积极参与开源软件的开发维护，促进优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。
学生可自主选择感兴趣的项目进行申请，中选后在项目资深开发者（社区导师）的指导下进行开发。根据项目的难易程度和完成情况，结项者将获取开源之夏活动奖金和结项证书。

这是 2023 OSPP 开源之夏的进阶课题之一，题目主页：[实现 OpenSumi 框架的 Local History（本地版本控制）能力](https://summer-ospp.ac.cn/org/prodetail/23dca0064?list=org&navpage=org)

在本次课题中，你将能完整了解 IDE 研发丰富的知识点，同时掌握插件 API 实现及自定义 OpenSumi 模块的能力。

本课题为进阶课题，完成之后你将能获得 12,000 （人民币）的奖金，预计耗时 3 个月，希望能够认真对待本次课题。

## 🧐 题目背景

在 IDE 里进行编码可能会发生因为误操作等原因导致代码丢失的情况，比如误操作 git reset、不在暂存区的文件撤销/回退栈丢失的问题等。

为了解决这个问题，就需要实现一个 Local History 功能，它可以保存代码的历史操作，并能够方便地进行版本比较和恢复。

与 Git 版本控制系统不同，Local History 可以记录项目的所有变更操作，包括代码编辑、保存、重命名、撤销/回退、来自 workspace edit 的操作等，并允许你回滚到文件的任何状态。即使你的项目还没启用 Git 版本控制，他也可以成为你的个人版本控制系统。

但与 Git 不同的是，Local History 需要设定存储的大小和时间，所以他并不是 Git 的替代品，而是作为一种兜底的方案来帮助你找回曾经丢失的代码

同类 IDE 的 Local History

WebStorm: https://www.jetbrains.com/help/webstorm/local-history.html#restore-changes-from-local-history

VS Code: https://code.visualstudio.com/updates/v1_66#_local-history

## 👨🏻‍💻 实现思路

对编辑器内的编码操作（代码编辑、撤销、回退、保存、重构操作）以及文件操作（重命名、创建、删除）等做实时记录，需要考虑存储资源的大小和存储格式的设计

## 💪 技术要求

- 熟悉 Typescript 和 Node.js
- 了解 IDE 领域知识，如编辑器、终端、调试等
- 了解 Git 并知晓一些常用命令

## ⚙️ 产出要求

- 完成对单文件的 6 个代码操作历史记录（创建、替换、代码保存、重命名、移动、undo/redo）
- 完成对应的视图展示和恢复/删除操作
- 进阶: 结合 git history 实现 registerTimelineProvider API

## 💬 相关讨论

- https://github.com/opensumi/core/discussions/2478

如对题目有疑问，也可在评论区留言交流 ~

**Comment by QinZiWeiS** [comment]
My name is ZiWei-Qin.I was notified by Ricbet that I was selected for the project.Can I claim this issue now?

**Comment by QinZiWeiS** [comment]
目前对TimeLine模块做了一个初始化，大致如下：
<img width="329" alt="image" src="https://github.com/opensumi/core/assets/78211515/b35fb139-d479-4434-ae8a-46c9825e2350">
但是由于timeline是一个新的模块，对于package.json中的一些字段不是很清楚该如何编写，以及后续timeline这个包的发布等

**Comment by erha19** [comment]
@QinZiWeiS 可以通过在项目内运行 `npm run create timeline` 创建基础项目结构，然后再选择性增删内容来让项目能跑起来，需要注意的是，由于项目内使用了 `yarn workspace` ，故 package.json 内的 @opensumi 依赖版本均需要修改为 `workspace:*`，参照一下其他项目写法。

**Comment by QinZiWeiS** [comment]
@Ricbet 感谢老师@erha19 感谢老师，timeline之前已经跑起来了，只是不太确定一些配置文件如何设置，现在这块也已经解决

**Comment by QinZiWeiS** [comment]
对于文件相关的监听实现可以直接放在timeline的模块service当中吗？还是需要另起localhistory模块

**Comment by erha19** [comment]
> 对于文件相关的监听实现可以直接放在timeline的模块service当中吗？还是需要另起localhistory模块

@QinZiWeiS  建议相关服务在 timeline 模块实现就行了，控制模块的简洁

**Comment by Ricbet** [comment]
> 对于文件相关的监听实现可以直接放在timeline的模块service当中吗？还是需要另起localhistory模块

@QinZiWeiS 就放在 timeline 模块的 service 里

**Comment by Ricbet** [comment]
@QinZiWeiS 
思路是没问题的，但需要考虑以下几点

1. 各个操作具体是有哪些操作？你可以先列一下然后按优先级先从简单的做起
2. 存储文件只需要存储修改前的文件内容即可。然后具体的设计方案可以简单画一画图或者伪代码看一下

然后还需要考虑存储文件的大小限制、操作频次（e.g x 秒内的同一操作）、存储个数限制等因素，具体可以看看 [RFC](https://github.com/opensumi/core/discussions/2478)

---

并不需要监听文件改动，因为没有实时存储文件代码内容的需求，只需要监听文件的保存就行，具体代码可以看看这个 workbenchEditorService 服务
https://github.com/opensumi/core/blob/v2.26/packages/editor/src/browser/editor.contribution.ts#L543


更多逻辑上的解答需要你先把 1 的问题列好了才能解答

**Comment by QinZiWeiS** [comment]
> 

操作有：创建，保存，替换，移动，重命名，Undo / Redo，目前想先实现监听文件创建（保存）然后进行存储，并在timeline中展示，想先将整个流程打通之后，再去增加对于存储的一些限制和因素

**Comment by Ricbet** [comment]
@QinZiWeiS  好的

你可以尝试先把 保存 做了，流程先起来。创建、替换、移动和重命名应该是同一类问题，可以一起再解。

文件保存你可以监听这个事件 
https://github.com/opensumi/core/blob/7e7e61b7ef8d96220c1be1e4a054f6bc5f86deca/packages/addons/src/browser/file-content-update-time.contribution.ts#L128

**Comment by QinZiWeiS** [comment]
> @QinZiWeiS 好的
> 
> 你可以尝试先把 保存 做了，流程先起来。创建、替换、移动和重命名应该是同一类问题，可以一起再解。
> 
> 文件保存你可以监听这个事件
> 
> https://github.com/opensumi/core/blob/7e7e61b7ef8d96220c1be1e4a054f6bc5f86deca/packages/addons/src/browser/file-content-update-time.contribution.ts#L128

`@OnEvent(EditorDocumentModelWillSaveEvent)
  handleEditorDocumentModelWillSaveEvent(event: EditorDocumentModelWillSaveEvent) {
    console.log('handleEditorDocumentModelWillSaveEvent');
  }`老师您好，我在timeline.contribusion.ts中添加了这样的监听函数，测试好像没有起效果 @Ricbet

**Comment by Ricbet** [comment]
@QinZiWeiS 贴一下完整代码，先确认一下 contribution 有没有放在 module 的 providers 列表里

**Comment by QinZiWeiS** [comment]
> @QinZiWeiS 贴一下完整代码，先确认一下 contribution 有没有放在 module 的 providers 列表里

`@Domain(MainLayoutContribution)
export class TimeLineContribution implements MainLayoutContribution {
  @Autowired(IMainLayoutService)
  private mainLayoutService: IMainLayoutService;

  onDidRender() {
    this.mainLayoutService.collectViewComponent(
      {
        component: TimeLine,
        collapsed: false,
        id: TIMELINE_VIEW_ID,
        name: localize('timeline.title'),
      },
      EXPLORER_CONTAINER_ID,
    );
  }

  @OnEvent(EditorDocumentModelWillSaveEvent)
  async handleEditorDocumentModelWillSaveEvent(event: EditorDocumentModelWillSaveEvent) {
    console.log('handleEditorDocumentModelWillSaveEvent');
  }
}
`

**Comment by QinZiWeiS** [comment]
> @QinZiWeiS 贴一下完整代码，先确认一下 contribution 有没有放在 module 的 providers 列表里

https://github.com/QinZiWeiS/core/blob/feat/provide-local-history-support/packages/timeline/src/browser/timeline.contribution.ts#L27C2-L27C2

**Comment by Ricbet** [comment]
@QinZiWeiS 你确定项目能正常跑起来？这里的文件导入是错误的，不存在这个文件
![image](https://github.com/opensumi/core/assets/20262815/54e28bc6-f0e8-4618-8c76-2f2cb4080dcf)

**Comment by Ricbet** [comment]
@QinZiWeiS 是不是最新代码没提交？

**Comment by QinZiWeiS** [comment]
> @QinZiWeiS 是不是最新代码没提交？

是的，那个是我之前写错了，现在更新了一下

**Comment by Ricbet** [comment]
> > @QinZiWeiS 好的
> > 你可以尝试先把 保存 做了，流程先起来。创建、替换、移动和重命名应该是同一类问题，可以一起再解。
> > 文件保存你可以监听这个事件
> > https://github.com/opensumi/core/blob/7e7e61b7ef8d96220c1be1e4a054f6bc5f86deca/packages/addons/src/browser/file-content-update-time.contribution.ts#L128
> 
> `@OnEvent(EditorDocumentModelWillSaveEvent) handleEditorDocumentModelWillSaveEvent(event: EditorDocumentModelWillSaveEvent) { console.log('handleEditorDocumentModelWillSaveEvent'); }`老师您好，我在timeline.contribusion.ts中添加了这样的监听函数，测试好像没有起效果 @Ricbet

@QinZiWeiS 我忘了告诉你应该先继承 `WithEventBus` 类了，像这样修改就可以了，你再试试

```typescript
import { WithEventBus } from '@opensumi/ide-core-browser';
// ...
export class TimeLineContribution extends WithEventBus implements MainLayoutContribution {
// ...
}
```

**Comment by QinZiWeiS** [comment]
> > > @QinZiWeiS 好的
> > > 你可以尝试先把 保存 做了，流程先起来。创建、替换、移动和重命名应该是同一类问题，可以一起再解。
> > > 文件保存你可以监听这个事件
> > > https://github.com/opensumi/core/blob/7e7e61b7ef8d96220c1be1e4a054f6bc5f86deca/packages/addons/src/browser/file-content-update-time.contribution.ts#L128
> > 
> > 
> > `@OnEvent(EditorDocumentModelWillSaveEvent) handleEditorDocumentModelWillSaveEvent(event: EditorDocumentModelWillSaveEvent) { console.log('handleEditorDocumentModelWillSaveEvent'); }`老师您好，我在timeline.contribusion.ts中添加了这样的监听函数，测试好像没有起效果 @Ricbet
> 
> @QinZiWeiS 我忘了告诉你应该先继承 `WithEventBus` 类了，像这样修改就可以了，你再试试
> 
> ```ts
> import { WithEventBus } from '@opensumi/ide-core-browser';
> // ...
> export class TimeLineContribution extends WithEventBus implements MainLayoutContribution {
> // ...
> }
> ```

可以了，感谢老师，感觉这一块可以在官网添加一下，之前尝试在官网找但没有相关的文档和信息

**Comment by Ricbet** [comment]
@QinZiWeiS browser 目录下都是前端模块的代码，是不能直接引入 node 模块的。你要读取文件内容的话得用 file service 模块，看一下官网的介绍 https://opensumi.com/zh/docs/develop/basic-design/core-modules#file-service

**Comment by QinZiWeiS** [comment]
@Ricbet 老师，因为前两周家里突发了意外导致项目进度稍微停滞了，目前完成了文件创建+保存，timeline的展示（待优化），全流程打通还需要如下：
1.替换，重命名，移动需要监听的事件
2.工作区切换文件展示的事件（用于timeline刷新并展示对应文件的历史记录）
3.timeline的视图更新（目前我用的是mainLayoutService的hide()和show()有效果，但是应该有更好的方式）
<img width="335" alt="image" src="https://github.com/opensumi/core/assets/78211515/44fb9b7c-a6ec-460e-ad38-b32311c550bf">

**Comment by Ricbet** [comment]
还有一个功能是打开 timeline 里的文件展示 diff 视图，这个可以先考虑加上。

第 3 点你说的 hide、show 有效果指的是什么？timline 里的文件列表更新？

**Comment by Ricbet** [comment]
你处理文件创建和保存的时候可以发送事件出来，然后在 timeline 视图里去监听，不要通过 hide 或 show 去控制。

diff 视图你可以使用 `editor.compare` 这个命令

**Comment by QinZiWeiS** [comment]
> 你处理文件创建和保存的时候可以发送事件出来，然后在 timeline 视图里去监听，不要通过 hide 或 show 去控制。
> 
> diff 视图你可以使用 `editor.compare` 这个命令

是使用createDiffEditor创建一个实例然后再调用compare去进行展示吗？

**Comment by Ricbet** [comment]
不是，是调用这个 command

https://github.com/opensumi/core/blob/a120d5eac23b8bad6fbfd4b350ae915c19d91eaa/packages/core-browser/src/common/common.command.ts#L356

你可以参考其他调用这个 command 命令的代码，主要传入两个 `URI`。

**Comment by Ricbet** [comment]
由于学生无法再继续完成该课题，该 issue 关闭，后续再另提 issue 处理
