### ISSUE TITLE
[BUG] openvsx 中的 python 扩展加载错误

### ISSUE THREAD

**Issue by l1shen** [opensumi/core#2654]
**描述你的问题（Describe the bug）**
在 ide-electron 项目的 extensions.json 中添加 python 扩展
https://open-vsx.org/extension/ms-python/python/2022.4.1
```json
"ms-python": [
        {
            "name": "python",
            "version": "2022.4.1"
        }
    ],
```
扩展，然后安装启动，extHost 进程会报错

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/8299540/234523925-396ea5ea-c4ed-4f55-b21c-08b96b44114a.png">

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

扩展可以正常工作

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by erha19** [comment]
@l1shen 看一下是不是集成的时候少引入了 Testing 模块 `TestingModule`, 在 `@opensumi/ide-testing` 这个包里。

**Comment by l1shen** [comment]
> @l1shen 看一下是不是集成的时候少引入了 Testing 模块 `TestingModule`, 在 `@opensumi/ide-testing` 这个包里。

加上之后没有报 `Cannot findProvider of Symbol(TestService)` 的错了, 但是语言服务器启动不成功

```shell
[node][extHost:error] [Arguments] {
  '0': '\x1B[31m[extHost:error]\x1B[0m',
  '1': 'write after end'
}
[Arguments] {
  '0': '\x1B[31m[extHost:error]\x1B[0m',
  '1': '[Extension-Host] write after end \n' +
    '\n' +
    'Error: write after endError: write after end\n' +
    '\tat new NodeError (node:internal/errors:371:5)\n' +
    '\tat _write (node:internal/streams/writable:319:11)\n' +
    '\tat Socket.Writable.write (node:internal/streams/writable:334:10)\n' +
    '\tat /Users/su/testing/...

```

控制台又报了这个错误

**Comment by erha19** [comment]
@l1shen 目前 Python 插件我们只支持到了 2020 的版本，后续版本对 Notebook API 有相应依赖没做具体适配，晚点我看一下能不能兼容一下除了 Notebook API 之外的逻辑。暂时的话，如果要使用，需要用 2020 的版本

**Comment by erha19** [comment]
@l1shen 试一下 https://marketplace.opentrs.cn/square 这里的版本

**Comment by l1shen** [comment]
> @l1shen 试一下 https://marketplace.opentrs.cn/square 这里的版本

换了  https://marketplace.opentrs.cn/square 里面的版本可以了，感谢
