### ISSUE TITLE
[Question] 怎么在 Lua 文档的活动状态下，动态增加 snippets

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2659]
**描述你的问题（Describe you question here）**
打开一个 lua 文档 根据 uri 的参数增加 snippets
切换选项卡的时候 重置 snippets 并且根据 uri 进行更新
请问怎么实现比较好呀？

**Comment by zhuzeyu22** [comment]
补充一下，原本需求是根据一些参数动态生成某些对象的代码提示，并不一定要通过 snippets 实现，有别的好的思路也可以讨论

**Comment by erha19** [comment]
这块可以考虑一下通过对语法插件的改造去实现，参考文档：

**Comment by zhuzeyu22** [comment]
anguages.registerCompletionItemProvider  这个模块在 opensumi 里面怎么调用 ？

**Comment by bytemain** [comment]
你提出的问题我们在这个 issue 里追踪：https://github.com/opensumi/docs/issues/126
