### ISSUE TITLE
[BUG] 安装扩展未生效问题

### ISSUE THREAD

**Issue by 15083055793** [opensumi/core#2661]
**描述你的问题（Describe the bug）**
 安装 volar（vue3） 扩展，然后在 .vue 文件中coding，除了有代码高亮，其他功能都没有（代码提示、引用跳转等）。

**复现路径（To Reproduce）**

如下：输入标签名称按 tab 无法生成标签，输入js代码，没有代码提示
<img width="383" alt="image" src="https://user-images.githubusercontent.com/19968984/235089664-2c6a505a-3f92-4582-953e-8b81f4bdcec7.png">

<img width="373" alt="image" src="https://user-images.githubusercontent.com/19968984/235090024-fd195d49-dc3e-4ce7-8e7b-68e3b0ccf0f1.png">
控制台在打开 vue 文件时，显示问题如下：
<img width="530" alt="image" src="https://user-images.githubusercontent.com/19968984/235090937-a2c05663-101a-4484-86de-b06a8a602785.png">

**预期表现（Expected behavior）**
能正常使用 volar 扩展，保持和在 vscode 下开发 vue3 一致的行为

**环境信息（Environment）**

- OS: macOS 11.6 Apple M1
- Browser: electron
- OpenSumi Version: 2.22.5

#### 插件市场源为
https://open-vsx.org

盲猜 volar 和 opensumi 版本不兼容导致的问题

**Comment by 15083055793** [comment]
本地调试看着像volar版本不兼容
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/19968984/235118261-dd74f4cc-7e6c-4cbc-83d1-e643b613a52f.png">

**Comment by erha19** [comment]
@15083055793 是的，你这里用一下 2.23.0 以上版本就可以正常使用了

**Comment by 15083055793** [comment]
@erha19 我更新opensumi/* 至2.41.0,然后执行pnpm run pack装到mac上后打开客户端的vue文件报的这个错
![d5a706cf-4051-40e3-8a1b-ddcb2e74c115](https://github.com/opensumi/core/assets/19968984/8959e544-2e9f-4732-b0ce-8fccd1b3f88a)

**Comment by erha19** [comment]
@15083055793 不确定这个插件是否硬编码依赖了 extensions 相对路径下的 node_modules，但你这里只需要在打包时，将插件依赖的 TypeScript 一起打包进去就行了，如：

```bash
| -- extensions
| ---- node_modules/typescript
| ---- ...(其他插件)
```

**Comment by 15083055793** [comment]
@erha19 我是这样做的，但是这只针对开发环境，run pack后运行客户端就不行了
<img width="248" alt="image" src="https://github.com/opensumi/core/assets/19968984/807383cf-e09e-4849-b59e-757a7180185f">

**Comment by 15083055793** [comment]
@erha19 是不是需要将volar插件作为内置插件放在extensions下，目前我是打开客户端后在插件市场安装的volar

**Comment by 15083055793** [comment]
已解决
分享下经验:
看了volar 源码，因为 volar 需要 typescript 模块的支持，我这里通过安装 vscode-typescript-next 扩展来解决 typescript 的依赖问题（vscode-typescript-next 扩展下存在 typescript 的模块）
<img width="689" alt="image" src="https://github.com/opensumi/core/assets/19968984/373e9df3-b2be-4783-b14e-dc16c1db526c">
