### ISSUE TITLE
[Question] 怎么实现跨视图控制显示与隐藏？

### ISSUE THREAD

**Issue by terrihonkai** [opensumi/core#2667]
![image](https://user-images.githubusercontent.com/132564832/236175851-e42f3f48-e83f-4253-b731-ac747f6022f2.png)

怎么实现topbar去控制两侧的展开与隐藏，还有两侧视图的原有icon隐藏呢？（类似小程序开发者工具的布局）

**Comment by bytemain** [comment]
Duplicate with https://github.com/opensumi/core/discussions/2668
