### ISSUE TITLE
[BUG] 来回切换主题时颜色 token 表现不一致

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2686]
**描述你的问题（Describe the bug）**

颜色像是随机切换一样

![Kapture 2023-05-09 at 11 45 34](https://user-images.githubusercontent.com/20262815/236989050-dcb876db-6ecf-4fc8-afb1-0c61e3ce6e00.gif)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by wjywy** [comment]
Kindly to ask if there is somebody working for this issue? if not, I'm glad to undertake it@pipiiiiii

**Comment by erha19** [comment]
@wjywy Hi, it's done and published, you can get this fix on version 2.25.0.

If you are finding some fixes for the OpenSumi project, you can see the issues here [good first issue](https://github.com/opensumi/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%91%A8%F0%9F%8F%BB%E2%80%8D%F0%9F%92%BB+good+first+issue%22).
