### ISSUE TITLE
[Question] 如何监听左侧菜单Tab切换事件

### ISSUE THREAD

**Issue by CocoaTouch123** [opensumi/core#2694]
**描述你的问题（Describe you question here）**
问题一：
本地开发过程中，自定义了左侧菜单，我这边需要监听菜单tab切换事件，比如从’资源管理器‘切换到’搜索‘

问题二：
自定菜单之后，怎么让SlotLocation.main区域展示我定制的内容，然后SlotLocation.left其他区域不展示

**Comment by Ricbet** [comment]
问题一：你看一下官方文档提供的布局模块里的 LayoutService 那部分
https://opensumi.com/zh/docs/develop/module-apis/layout#example
`getTabbarHandler ` 所需要的参数是左侧菜单的 container id 枚举，具体文件是在 [这](https://github.com/opensumi/core/blob/62c02aafb0477c3e7d7ad1dcda4de06987a5aa8f/packages/core-browser/src/common/container-id.ts)

如果是你自己自定义的菜单，那就是你注册视图时的 id

**Comment by Ricbet** [comment]
问题二：目前暂不支持 SlotLocation 视图的动态调整，如果只是为了让其不展示，可以考虑从样式上作调整

**Comment by erha19** [comment]
@CocoaTouch123 布局相关的实践，也可以看一下这个项目 https://github.com/opensumi/app-desktop

**Comment by CocoaTouch123** [comment]
> getTabbarHandler
谢谢你们的回复，请教下，比如说我在初始化的时候把SlotLocation.main的模块指定成我自己自定义的模块，如下代码：
```javascript
[SlotLocation.main]: {
    modules: [
    'repo-list'
  ],
  },
```
那么我通过getTabbarHandler监听到其他菜单切换后，在动态的修改SlotLocation.main的内容，如下模块
```javascript
[SlotLocation.main]: {
    modules: ['@opensumi/ide-editor'],
  },
```
该如何实现呢，期待你们的回复，谢谢

**Comment by erha19** [comment]
@CocoaTouch123 动态修改 Slot 的渲染模板相对复杂，这里的这份配置目前是集成侧的静态配置，可以参考
https://github.com/opensumi/app-desktop/blob/main/src/editor/modules/top-tab/top-tab.contribution.ts#L19

另外，你这里的做法不一定是合理的，还是从你们的需求出发，动态替换渲染内容不一定需要去替换整个渲染布局信息，如果只是替换展示内容，直接通过视图逻辑切换就行了

**Comment by CocoaTouch123** [comment]
> @CocoaTouch123 动态修改 Slot 的渲染模板相对复杂，这里的这份配置目前是集成侧的静态配置，可以参考 https://github.com/opensumi/app-desktop/blob/main/src/editor/modules/top-tab/top-tab.contribution.ts#L19
> 
> 另外，你这里的做法不一定是合理的，还是从你们的需求出发，动态替换渲染内容不一定需要去替换整个渲染布局信息，如果只是替换展示内容，直接通过视图逻辑切换就行了

好的，感谢，我之前看了文档也试了registry.registerSlotRenderer方式，没有达到我想要的效果。

**Comment by CocoaTouch123** [comment]
我这边先根据你们提供的信息我再试试看，谢谢

**Comment by CocoaTouch123** [comment]
@erha19  我这边换了一种思路：我自定义菜单后，在左侧区域显示一个列表，然后点击列表中的一项后，在main区域显示详细信息，是否有这种demo或者示例可以提供下，谢谢

**Comment by erha19** [comment]
@CocoaTouch123  可以看一下这个仓库有没有你需要的能力案例
