### ISSUE TITLE
[BUG] 下方 问题 tab 在提示语法问题得时候，多行显示样式异常

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2702]
![image](https://github.com/opensumi/core/assets/13432873/06850140-3fd7-4ee3-acda-b0cf971e803b)

![image](https://github.com/opensumi/core/assets/13432873/04ce501a-93b7-49d6-907f-ddec71454f38)

![image](https://github.com/opensumi/core/assets/13432873/83b6533d-f49f-413c-a2dd-c57e11c26cc8)

提示中出现换行符多行展示的时候，就有 bug

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**
预期正确收缩，没有空白没有重叠。

**环境信息（Environment）**

- OS: [Windows10]
- Browser: [electron]
- OpenSumi Version: [2.23.0]

**Comment by erha19** [comment]
@zhuzeyu22 使用的版本信息提供一下

**Comment by zhuzeyu22** [comment]
"@opensumi/ide-addons": "2.23.0",
    "@opensumi/ide-comments": "2.23.0",
    "@opensumi/ide-core-browser": "2.23.0",
    "@opensumi/ide-core-common": "2.23.0",
    "@opensumi/ide-core-electron-main": "2.23.0",
    "@opensumi/ide-core-node": "2.23.0",
    "@opensumi/ide-debug": "2.23.0",
    "@opensumi/ide-decoration": "2.23.0",
    "@opensumi/ide-editor": "2.23.0",
    "@opensumi/ide-electron-basic": "2.23.0",
    "@opensumi/ide-explorer": "2.23.0",
    "@opensumi/ide-extension": "2.23.0",
    "@opensumi/ide-extension-manager": "2.23.0",
    "@opensumi/ide-extension-storage": "2.23.0",
    "@opensumi/ide-file-scheme": "2.23.0",
    "@opensumi/ide-file-search": "2.23.0",
    "@opensumi/ide-file-service": "2.23.0",
    "@opensumi/ide-file-tree-next": "2.23.0",
    "@opensumi/ide-i18n": "2.23.0",
    "@opensumi/ide-keymaps": "2.23.0",
    "@opensumi/ide-logs": "2.23.0",
    "@opensumi/ide-main-layout": "2.23.0",
    "@opensumi/ide-markdown": "2.23.0",
    "@opensumi/ide-markers": "2.23.0",
    "@opensumi/ide-menu-bar": "2.23.0",
    "@opensumi/ide-monaco": "2.23.0",
    "@opensumi/ide-monaco-enhance": "2.23.0",
    "@opensumi/ide-opened-editor": "2.23.0",
    "@opensumi/ide-outline": "2.23.0",
    "@opensumi/ide-output": "2.23.0",
    "@opensumi/ide-overlay": "2.23.0",
    "@opensumi/ide-preferences": "2.23.0",
    "@opensumi/ide-process": "2.23.0",
    "@opensumi/ide-quick-open": "2.23.0",
    "@opensumi/ide-scm": "2.23.0",
    "@opensumi/ide-search": "2.23.0",
    "@opensumi/ide-static-resource": "2.23.0",
    "@opensumi/ide-status-bar": "2.23.0",
    "@opensumi/ide-storage": "2.23.0",
    "@opensumi/ide-task": "2.23.0",
    "@opensumi/ide-terminal-next": "2.23.0",
    "@opensumi/ide-testing": "2.23.0",
    "@opensumi/ide-theme": "2.23.0",
    "@opensumi/ide-toolbar": "2.23.0",
    "@opensumi/ide-userstorage": "2.23.0",
    "@opensumi/ide-variable": "2.23.0",
    "@opensumi/ide-webview": "2.23.0",
    "@opensumi/ide-workspace": "2.23.0",
    "@opensumi/ide-workspace-edit": "2.23.0",

**Comment by zhuzeyu22** [comment]
> @zhuzeyu22 使用的版本信息提供一下


    "@opensumi/ide-addons": "2.23.0",
    "@opensumi/ide-comments": "2.23.0",
    "@opensumi/ide-core-browser": "2.23.0",
    "@opensumi/ide-core-common": "2.23.0",
    "@opensumi/ide-core-electron-main": "2.23.0",
    "@opensumi/ide-core-node": "2.23.0",
    "@opensumi/ide-debug": "2.23.0",
    "@opensumi/ide-decoration": "2.23.0",
    "@opensumi/ide-editor": "2.23.0",
    "@opensumi/ide-electron-basic": "2.23.0",
    "@opensumi/ide-explorer": "2.23.0",
    "@opensumi/ide-extension": "2.23.0",
    "@opensumi/ide-extension-manager": "2.23.0",
    "@opensumi/ide-extension-storage": "2.23.0",
    "@opensumi/ide-file-scheme": "2.23.0",
    "@opensumi/ide-file-search": "2.23.0",
    "@opensumi/ide-file-service": "2.23.0",
    "@opensumi/ide-file-tree-next": "2.23.0",
    "@opensumi/ide-i18n": "2.23.0",
    "@opensumi/ide-keymaps": "2.23.0",
    "@opensumi/ide-logs": "2.23.0",
    "@opensumi/ide-main-layout": "2.23.0",
    "@opensumi/ide-markdown": "2.23.0",
    "@opensumi/ide-markers": "2.23.0",
    "@opensumi/ide-menu-bar": "2.23.0",
    "@opensumi/ide-monaco": "2.23.0",
    "@opensumi/ide-monaco-enhance": "2.23.0",
    "@opensumi/ide-opened-editor": "2.23.0",
    "@opensumi/ide-outline": "2.23.0",
    "@opensumi/ide-output": "2.23.0",
    "@opensumi/ide-overlay": "2.23.0",
    "@opensumi/ide-preferences": "2.23.0",
    "@opensumi/ide-process": "2.23.0",
    "@opensumi/ide-quick-open": "2.23.0",
    "@opensumi/ide-scm": "2.23.0",
    "@opensumi/ide-search": "2.23.0",
    "@opensumi/ide-static-resource": "2.23.0",
    "@opensumi/ide-status-bar": "2.23.0",
    "@opensumi/ide-storage": "2.23.0",
    "@opensumi/ide-task": "2.23.0",
    "@opensumi/ide-terminal-next": "2.23.0",
    "@opensumi/ide-testing": "2.23.0",
    "@opensumi/ide-theme": "2.23.0",
    "@opensumi/ide-toolbar": "2.23.0",
    "@opensumi/ide-userstorage": "2.23.0",
    "@opensumi/ide-variable": "2.23.0",
    "@opensumi/ide-webview": "2.23.0",
    "@opensumi/ide-workspace": "2.23.0",
    "@opensumi/ide-workspace-edit": "2.23.0",

**Comment by erha19** [comment]
@zhuzeyu22 晚点我处理一下这个问题，应该还是渲染上面的问题
