### ISSUE TITLE
[BUG] SCMModule 无法显示

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2704]
![image](https://github.com/opensumi/core/assets/13432873/a980615e-e704-4f74-99a0-1465bf5d581e)

新的空文件夹 SCMModule 显示为空

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: Windows11
- Browser: electron
- OpenSumi Version:  2.24.2

**Comment by erha19** [comment]
@zhuzeyu22 SCM 面板需要本地有 Git 仓库信息，运行过 git init？

**Comment by zhuzeyu22** [comment]
> @zhuzeyu22 SCM 面板需要本地有 Git 仓库信息，运行过 git init？

![image](https://github.com/opensumi/core/assets/13432873/203ca849-cc91-4353-97dd-e04eabe7918e)
运行过 git init 之后，因为没有配置所以还是空的

**Comment by erha19** [comment]
该问题为没有引入 Git 插件导致的不展示，关闭了
