### ISSUE TITLE
[Question] 请问 yarn 怎么单独更新部署 @opensumi/ide-core-electron-main 这一个模块？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2716]
我想要单独部署 @opensumi/ide-core-electron-main 这个包的一个测试版本方便调试
请问 yarn 需要做什么配置吗？
应该用什么命令进行构建与打包？

**Comment by erha19** [comment]
@zhuzeyu22 可以参考这里的这种组织方式 https://github.com/opensumi/opensumi-module-samples
