### ISSUE TITLE
[BUG] 带上路径搜索文件时，鼠标点击无法打开文件

### ISSUE THREAD

**Issue by wangxiaojuan** [opensumi/core#2718]
**描述你的问题（Describe the bug）**
![image](https://github.com/opensumi/core/assets/1762334/c7028142-4140-4b72-8b5f-fa232a2b2d73)
**复现路径（To Reproduce）**
1.搜索带有路径的文件：ide/ide-entry/vcs-entry.tsx，搜索出来只有一个结果
2.点击搜索出来的结果无反应

**Comment by Ricbet** [comment]
测试了下，是只有当搜索结果只有一个时，点击结果才没有反应，其他情况是正常的，目前正在排查中

**Comment by Ricbet** [comment]
![image](https://github.com/opensumi/core/assets/20262815/22cc454b-f6f7-4f5d-95b2-ed4eac90d731)

问题定位到了，是左右滑动的滚动条覆盖到了 item 结果上面，导致点击事件失效
