### ISSUE TITLE
[Question] 如何实现一个 DebugAdapter ？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2729]
我定义了一种自定义文档格式 Adoc 以及对应的 Alang
我有一个 Alang 的执行器（执行环境）
我想要通过一个 Alang Debug Adapter 来支持单步调试的功能

我设计的架构是
IDE 部分做一个 debugger service 将 Alang 转化为 DAP
debug Adapter 放在插件里面接收 DAP 然后将任务分发到实际的 debugger

请问我应该重点阅读一下哪些模块的实现？
有没有 example 可以参考？

**Comment by Ricbet** [comment]
你不需要在 opensumi 里拓展 debug 模块，你的 debug adapter 需要在插件里实现。

你可以参考 vscode 官方的 mock debug 插件示例 https://github.com/microsoft/vscode-mock-debug

**Comment by zhuzeyu22** [comment]
> 
修正一下

我定义了一种自定义文档格式 Adoc 以及对应的 Alang，因为 Adoc 不是MonacoEdit 而是 bpmn 的所以 IDE 应该不太能自动处理行号之类的信息，这块可能需要转化一下。

**Comment by Ricbet** [comment]
@zhuzeyu22 emmm 我没太看懂你的意思，你是说你的文档是渲染在自定义编辑器上？然后想在这个自定义编辑器里做 debug ？

**Comment by zhuzeyu22** [comment]
@Ricbet 是的，想要在自定义的编辑器里面做 debug，编辑器以图形方式显示，但是可以转化为文本，你可以理解成是一个低代码的开发编辑器，最终产出还是代码，但是数据结构比较特殊所以没有直接使用 MonacoEdit 。

**Comment by Ricbet** [comment]
目前没法做到在自定义编辑器内做 debug。
不过你都可以转化为文本了，还是建议在 monaco editor 里去做调试

**Comment by zhuzeyu22** [comment]
@Ricbet 虽然可以转化成文本了，但是对外显示和调试还是希望以图形化的方式去做交互，这块感觉也许需要重写 IExtHostDebugService ？或者内置一个隐藏的，不显示的 monaco editor ，隐藏的话，感觉会有问题，一个是不优雅，另一个是很多操作可能需要 active 的状态，编辑器和显示也耦合紧密。可能还是需要重新实现一个 debug 服务。   

这块有没有什么好的参考建议吗？

**Comment by Ricbet** [comment]
@zhuzeyu22 我建议还是不要依赖 opensumi 的 debug 模块去实现了。即使是要在图形化界面里做调试，那前端部分也是要自己自定义的，然后前端与 server 的交互甚至都不用 DAP 协议。

有一个插件不知道是不是你想要的效果，你参考一下 https://github.com/Almenon/birdseye-vscode

**Comment by zhuzeyu22** [comment]
@Ricbet    是类似的效果，图形化使用 bpmn 结构而不是 AST 结构。这个插件本质是通过 vscode-live-server-preview 同步展示 birdseye 这个pip 包的效果
