### ISSUE TITLE
[FEATURE] 兼容 opemsumi theme 的迁移

### ISSUE THREAD

**Issue by hacke2** [opensumi/core#274]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

因为旧的内部的主题 id 是 `ide-dark`，如果想迁移为 opensumi theme 时发现因为之前 localstorage 缓存，即便设置全局 preference，也不能无缝的迁移为 opensumi theme，因为可能存在用户设置为 ide-dark

![image](https://user-images.githubusercontent.com/6399899/147842990-b86be6ed-666f-4d63-b208-b10a0c22ae8e.png)

因为用户设置比全局设置权重高，所以不会显示 opensumi theme。即便将 ide-dark 也作为内置皮肤让 IDE 加载，因为 https://github.com/opensumi/core/pull/237 这个 PR 的原因，导致先激活 IDE 内置的 ide-dark 后，也没办法加载插件的 ide-dark（本质原因是 IDE 内置的 themeid 和 之前插件的 theme id 重名）。

**描述你预期的功能表现（Describe the solution you'd like）**

theme 迁移时能让集成方比较无感

**描述你考虑过的替代方案（Describe alternatives you've considered）**

目前临时解决方式为上层注册 registerExternalPreferenceProvider 覆盖 IDE 默认实现，在 get 时判断是否为 ide-dark，如果时则替换为框架默认配置（opensumi-dark）

```ts
  registerExternalPreferenceProvider(THEME_KEY, {
      set: (value: string, scope) => {
        if (scope >= PreferenceScope.Folder) {
          // earlyPreference不支持针对作用域大于等于Folder的值设置
          return;
        }
  
        if ((global as any).localStorage) {
          if (value !== undefined) {
            localStorage.setItem(getScopePrefix(scope) + `:${THEME_KEY}`, value);
          } else {
            localStorage.removeItem(getScopePrefix(scope) + `:${THEME_KEY}`);
          }
        }
      },
      get: (scope) => {
        if ((global as any).localStorage) {
          const themeId = localStorage.getItem(getScopePrefix(scope) + `:${THEME_KEY}`) || undefined;
          return themeId === 'ide-dark'? options.defaultPreferences!['general.theme'] : themeId;
        }
      },
    });
```

此逻辑是否需要每个集成方都加？是否应该有一个平滑迁移的方式？

**补充信息（Additional context）**

**Comment by erha19** [comment]
#237  这个 PR 主要解决的是在框架加载前，通过注册默认的主题色让整体框架符合基础的 `light` 或者 `dark` 色系，否则本身插件加载时序是慢于渲染的，如果没有这个 PR，会出现字体从黑变白的情况，具体看 PR 详情，属于正常的逻辑修复。

另外，上面提到的这段逻辑问题其实只会影响基于 `ide-dark` 做主题定制，同时没有修改插件 Theme ID 情况的集成方，这种定制方式本身在修改时就是存在问题的，我个人感觉是集成方需要主动发现并修复的问题，不应该在框架中委曲求全去兼容，如果集成方有这个问题，我们就提供二次修改逻辑进行修改，这部分集成方的数量应该是比较少且可控的，后续集成的开发者我们应该尽量提醒其规避该问题。
