### ISSUE TITLE
请问怎样对开发好的插件做测试？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2741]
opensumi 有标准的测试框架吗？

**Comment by Ricbet** [comment]
OpenSumi 没有提供测试框架，插件可以自己集成一些测试框架比如 Mocha 或 Jasmine

**Comment by erha19** [comment]
@zhuzeyu22 如果是验证插件功能，可以用 OpenSumi CLI 做快速验证 https://opensumi.com/zh/docs/extension/quick-start

**Comment by zhuzeyu22** [comment]
@erha19 是自动化测试，功能测试，代码覆盖测试。

**Comment by erha19** [comment]
> 是自动化测试，功能测试，代码覆盖测试。
@zhuzeyu22  这个没有，需要自行实现
