### ISSUE TITLE
[BUG] Javascript 调试在 node 17 及以上版本 或 ipv6-only 容器环境下无法工作

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2745]
**描述你的问题（Describe the bug）**

在我们 ipv6 only 的集群下，在调试后，IDE 在没有任何报错提示下自行退出，通过抓 websocket 包发现一个错误提示：

"{\"type\": 1, \"id\": \"90\", \"proxyId\": \"ExtHostDebug\",…yscall\":\"connect\",\"address\":\"::1\",\"port\":53180}]}"

初步判断是 vscode debugger 的 debug server 连接不上。通过阅读 [vscode js debug 源码](https://github.com/microsoft/vscode-js-debug/tree/main/src/dap)发现， debug server 会 hardcode地以 127.0.0.1 为 来起服务，将 vscode插件 127.0.0.1 的地方全部换成 ::1 就能解决问题，猜测可能是因为 opensumi 的debug 客户端连接时会缺省 host。

经过调查发现，在我们  ipv6 only  集群情况下，在缺省 host 情况下 客户端的会以 ::1 为本地 IP来连接服务器，参考如下代码
const client = new net.Socket();
  client.connect(8087,  () => {
   console.log('client', client.address())
  });
在 非 ipv6 only  或 IP 双栈情况下，在缺省 host 情况下 客户端的会以 127.0.0.1 为本地 IP来连接服务器，这样就能正常连接到 debug插件的调试服务。

我们无法得知 ipv6 only  集群对 net 客户端处理localhost的影响，但是通过把 node 版本升级到 17 及以上后，也能复现这一问题。

原因是 Node 17 后会优先将 localhost 解析为 IPV6 而非 IPV4: https://stackoverflow.com/questions/72648487/node-js-16-17-changed-resolution-of-localhost

可以通过如下代码来模拟调试服务及其连接过程
```javascript
const net = require('net');
const dns = require('dns');
dns.lookup('localhost', (err, address, family) => {
  console.log('IP 地址：', address);
  console.log('IP 地址族：', family);
});
const server = net.createServer((socket) => {
  // 新的连接建立时执行
  console.log('New client connected');

  socket.on('data', (data) => {
    // 当客户端发送新数据时执行
    console.log(`Received data from client: ${data}`);
  });

  socket.on('end', () => {
    // 当客户端断开连接时执行
    console.log('Client disconnected');
  });
});

// 模拟 debug server
server.listen({ port: 8087, host: '127.0.0.1' }, () => {
  console.log('server', server.address());
  
  console.log('Server started');
  const client = new net.Socket();

// 模拟 opensumi debug service
  client.connect(8087,  () => {
    console.log('client', client.address())
    console.log('Connected to server');
    client.write('Hello, server!');

  });

  client.on('data', data => {
    console.log('Received:', data.toString());
    client.destroy();
  });

  client.on('close', () => {
    console.log('Connection closed');
  });
});
```

# 测试结果：

## Node 16 和  ipv4/6 双栈集群，连接成功：

<img width="880" alt="image" src="https://github.com/opensumi/core/assets/13082375/9e0df176-dd4c-4712-9595-8da8432e53d1">

## Node 17 或者  ipv6-only 集群，连接失败：

<img width="680" alt="image" src="https://github.com/opensumi/core/assets/13082375/8ef888e8-9f69-46a8-854c-ba306dbe3897">

**复现路径（To Reproduce）**

- 使用 Node 17 启动 opensumi
- 调试一个Nodejs 代码

**预期表现（Expected behavior）**

正常调试

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by geekeren** [comment]
@erha19 vscode跑 在我们那个集群是没问题的，不确定是不是是不是 vscode 连接 debug-server也是 127.0.0.1 hardcode 写死的。如果是这样，是不是 opensumi这边连接本地也得写死为 127.0.0.1 ，可以告诉我连接的代码在哪，我可以提个 PR

**Comment by geekeren** [comment]
@erha19 https://github.com/opensumi/core/blob/e70e471cc0b24a4f8d4002154988ea652d25cc24/packages/extension/src/hosted/api/vscode/debug/extension-debug-adapter-starter.ts#L83-L91
最后走到这里吗？这里创建的服务器是代理到 vscode debug插件吗，那么与vscode debug 服务器建立连接的地方在哪呢

**Comment by erha19** [comment]
@geekeren 是的，看起来是这里建立链接的时候缺少了 host 导致的这一问题

![image](https://github.com/opensumi/core/assets/9823838/a20b7d63-b53c-42ae-977d-3b8ef0dd6c7e)

**Comment by geekeren** [comment]
@erha19 这个 port 信息是来自于哪里

**Comment by erha19** [comment]
@geekeren VS Code 内确实针对 Host 缺省情况做了 127.0.0.1 的处理，这里我们也可以加一下相似逻辑解决这个问题

https://github.com/microsoft/vscode/blob/4bd2f94ec1ece243eb5ef71bf5c91b507029c8e0/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L145

> 这个 port 信息是来自于哪里

JS Debug 插件的逻辑处理的，通过 `registerDebugAdapterDescriptorFactory` 注册的处理函数

**Comment by geekeren** [comment]
@erha19 还是你来改吧，感觉代码有点复杂 ╮(╯_╰)╭

**Comment by geekeren** [comment]
测试没有问题。

**Comment by erha19** [comment]
@geekeren 已在 2.24.5 版本中发布
