### ISSUE TITLE
如何监听状态栏的事件？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2757]
git 插件在加载之后改变了终端的环境变量，终端在状态栏弹出了一个警告，我想要优化用户体验自动消掉这个警告

TerminalEnvironmentService 没有开放对应的事件 

在 private updateCollections 里面处理了，这个也拦截不到

对状态栏直接使用 this.statusbarService.addElement 进行修改，也没有使用状态栏的命令，因此也没办法拦截命令。

因为 git 插件加载之后终端的环境变量才发生改变的，因此也不能在插件 active 的时候去消除状态栏的 icon （因为还没有）

这块有没有什么好的建议么

**Comment by zhuzeyu22** [comment]
补充一下，有没有在任意位置增加事件触发器或者拦截的方法，类似面向切面编程（AOP）的那种？

**Comment by zhuzeyu22** [comment]
再补充一点 new Emitter<IMergedEnvironmentVariableCollection>(); 出来的 event 似乎在 withEventBus 上面监听不到，好像 api 不兼容？

**Comment by erha19** [comment]
@zhuzeyu22 如果要使用 `withEventBus` 相关能力，用 `IEventBus` 这个服务，里面的 fire 和 on 分别代表事件的发送及监听，`new Emitter()` 是用于程序内部的事件。

**Comment by zhuzeyu22** [comment]
@erha19  刚刚看了一下有个 action 的装饰器，我在想是不是可以通过这个装饰器来拦截 action ？这个好像有点偏底层了，没有找到对应的 actionContribution

  @action
  addElement(entryId: string, entry: StatusBarEntry): StatusBarEntryAccessor

**Comment by erha19** [comment]
@zhuzeyu22 不行的，这个是 mobx 的 action，本身不具备这块能力，如果想添加相应能力，得在 statusbar 这个模块内暴露事件出来

**Comment by zhuzeyu22** [comment]
@erha19  我监听了 onDidChangeMenu 这个事件，在 menu 变化的时候清除 this._statusBarService.rightEntries 对应 id 的元素，但是渲染似乎有问题，初始化的时候好像是先触发 ChangeMenu 这个事件，然后渲染 status bar 的。之后随便动一动再触发一次 onDidChangeMenu  就能找到想要找的元素了。这块感觉渲染有点小问题。

**Comment by zhuzeyu22** [comment]
@erha19 这里要是把状态栏的 addElement 以命令的形式暴露出来就好了，ide-electron 2.23.0 的版本 加了个 StatusBarContribution 注册命令对外提供，但是内部没有对应的命令，而且缺少 remove 的命令

**Comment by erha19** [comment]
@zhuzeyu22 感觉有点走远了，如果只是限定 Terminal 的环境变量的话，可以看一下这个案例 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/terminal-env

**Comment by zhuzeyu22** [comment]
@erha19 目的是在插件加载后，插件改变 Terminal 的环境变量之后，消除由此产生的状态栏警告，使用户无感知，并不是单纯的限定环境变量。

**Comment by erha19** [comment]
@zhuzeyu22 本身 `IStatusBarService` 服务是支持追加及删除状态栏元素的，分别为：

```ts
@Autowired(IStatusBarService)
private  statusBar: IStatusBarService;

// 添加
this.statusBar.addElement('id', {...});
// 移除
this.statusBar.removeElement('id');
```

你也可以通过命令去调用 `StatusBarCommand.addElement`, 这里的 removeElement 没有实现，有需要可以 PR 上来实现。


你这里的终端在状态栏弹出错误信息没理解什么意思，如果是时机问题，要自己看一下具体的触发时机是什么时候，从你描述无法判断。

**Comment by zhuzeyu22** [comment]
@erha19  
![image](https://github.com/opensumi/core/assets/13432873/ba05d32d-84bb-458c-bb01-c2b5929fa082)

是时机问题，这个时机拿不到，因为菜单只会注册一个，所以第二次修改 status 栏里面的 this.entries 的时候拿不到任何事件。比较苦恼。

**Comment by erha19** [comment]
@zhuzeyu22  相关代码位置在这里 https://github.com/opensumi/core/blob/3d84700930ef07c4adc87e1b782ff35321e6cea5/packages/terminal-next/src/browser/terminal.environment.service.ts#L156 ， 可以考虑覆盖掉这里的实现

```ts
injector.override({
  token: EnvironmentVariableServiceToken,
  useClass: YourCustomClass,
})
```

**Comment by zhuzeyu22** [comment]
重写了 StatusBarService 然后 injector.override 覆盖掉，已解决
