### ISSUE TITLE
[FEATURE] 3-way-merge 功能增强

### ISSUE THREAD

**Issue by AhkunTa** [opensumi/core#2767]
**描述你预期的功能表现（Describe the solution you'd like）**

- 当冲突文件应用更改后，重新点击打开三路合并编辑器中间 result 期望获取最新的值，而不是重新渲染
- 期望增加下一个解决冲突提示 对大文件冲突展示友好
- 期望每次改动支持 cmd+z   cmd+shift+z 等回退操作 

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by bytemain** [comment]
中间区域的 Result 顶部应该展示 fsPath 而不是 uri，对一般开发者更友好
