### ISSUE TITLE
[BUG] 本版本 2.23.0，FileTreeModelService 获取的selectedFiles中的children为null，其实是有数据的

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2771]
![image](https://github.com/opensumi/core/assets/23164065/c3fc7702-7973-44fd-b828-6049537d4c8c)

**Comment by erha19** [comment]
@767746649zyy By Design，单个节点不会存储过深的节点层级，会带来性能问题

**Comment by erha19** [comment]
@767746649zyy 文件树上的文件都是按需加载按需展示的，可能不是你所想的 “全部文件数据”，会缺少一些没有加载出来的文件，如果是要真正的全部文件数据，建议从文件服务入手获取。文件树也可以获取文件，例如：

```ts
const { root } = this.filetreeModelService.treeModel;
for (let i = 0; i <= root.branchSize; i++) {
     const node = root.getTreeNodeAtIndex(i);
     // 遍历获取可见的文件
}
```

**Comment by 767746649zyy** [comment]
好的，谢谢了，我用node的fs读了
