### ISSUE TITLE
[BUG] 不支持 golang 调试

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2788]
**描述你的问题（Describe the bug）**
VSCode 下安装 go 插件后就能进行golang的调试，但是 opensumi 下报错
<img width="832" alt="image" src="https://github.com/opensumi/core/assets/13082375/bfa6ef44-8d52-483f-9b4b-a2a81a9fe6dd">

**复现路径（To Reproduce）**
- 安装 go 插件

- 编写 golang 代码

```golang
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}

```
- 创建配置

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "测试",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}/main.go",
            "env": {},
            "args": []
        }
    ]
}

```

**预期表现（Expected behavior）**

正常调试

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by geekeren** [comment]
@erha19 有什么进展吗？麻烦帮忙优先看下，业务上要求比较急

**Comment by erha19** [comment]
> @erha19 有什么进展吗？麻烦帮忙优先看下，业务上要求比较急

在看了，目前还在复现问题

**Comment by erha19** [comment]
@geekeren 你这边使用的是什么版本 OpenSumi？我在 main 上测试功能是正常的
![image](https://github.com/opensumi/core/assets/9823838/1d6205bc-c255-454b-b383-cc4c19199f11)

**Comment by geekeren** [comment]
@erha19 最新的正式版，你装的插件 package.json里的 name是什么，我看看是不是我插件装的不对

**Comment by erha19** [comment]
@geekeren 这个版本 
![image](https://github.com/opensumi/core/assets/9823838/677b0321-b05f-4188-a22e-68bcd4308f44)

**Comment by geekeren** [comment]
把 vscode go 插件降到 0.16.1 可以了
