### ISSUE TITLE
[Question] 调试控制台 如何区分代码中输出 和 系统日志

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2793]
**描述你的问题（Describe you question here）**
由于业务需要隐藏系统的日志输出，比如 Golang 下的 "API server listening at: 127.0.0.1:47239\n"}， js 下的 “Debugger attached.”

我打印了 debugSession 的输出，发现用户代码中的输出 和 系统的日志混在一起没有特别的标记进行区分。

<img width="444" alt="image" src="https://github.com/opensumi/core/assets/13082375/412b1448-e38e-47a3-81ab-fe8a7bcb55dc">
<img width="445" alt="image" src="https://github.com/opensumi/core/assets/13082375/9633c163-bd25-481d-b3e7-d14ab4e5006c">

![image](https://github.com/opensumi/core/assets/13082375/02594fd7-2bca-4841-809a-480213aae569)

请问有没有好的方式可以区分这两种日志

**Comment by erha19** [comment]
@geekeren DebugConsole 这里是通过 body.category 去做的用户日志类型区分的，可以参考：https://github.com/opensumi/core/blob/62c02aafb0477c3e7d7ad1dcda4de06987a5aa8f/packages/debug/src/browser/view/console/debug-console-session.ts#L78

**Comment by geekeren** [comment]
@erha19 问题是你看下 golang 日志输出， 系统 的 API server listening  和 用户代码中的 hello world.  category 都是 stdout没办法把 API server listening 区分出来

**Comment by erha19** [comment]
@geekeren 这个是调试器实现上的问题了，可能升级 golang 的调试插件可以解决问题，关键在于插件是否区分处理了这两类日志信息。

**Comment by geekeren** [comment]
@erha19 js 调试 系统日志category 是 stderr, 如果用户代码里写的是 console.error 是不是也区分不出来。

**Comment by erha19** [comment]
> @erha19 js 调试 系统日志category 是 stderr, 如果用户代码里写的是 console.error 是不是也区分不出来。

据我了解是的，除非后续调试器插件做了额外处理，本质上调试控制台也只能从接收到的信息做区分展示。

**Comment by geekeren** [comment]
@erha19 系统日志和用户日志 是在一个进程里面产生的吗
