### ISSUE TITLE
[BUG] Launch Editor 的一些异常逻辑

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2803]
**描述你的问题（Describe the bug）**

1. 多类型 scheme 配置添加时会出现报错，部分调试配置类型可能为数组，如: boolean, string，这种情况感觉可以考虑用户自行输入，然后对 true 和 false 字符串做额外处理
<img width="793" alt="image" src="https://github.com/opensumi/core/assets/9823838/3ac3c8ab-14ef-4456-a90c-2cf0bc161059">

2. 初次打开无默认选中，可以默认选中首个？
<img width="710" alt="image" src="https://github.com/opensumi/core/assets/9823838/967a6fe2-e265-4bbd-b097-e1482221764a">

3. 在框架内 ajv 版本为 6+ ，在引入了 @rjsf/validator-ajv8 后会引入双份 ajv 依赖，导致集成时存在一些解版本冲突问题

![image](https://github.com/opensumi/core/assets/9823838/85e00c44-6872-44b5-b4bd-02ad83078713)

**Comment by Ricbet** [comment]
1. 第一个报错的配置发一下
2. 这个我记得加上了呀
3. ajv 6 是不是版本有点旧了

**Comment by erha19** [comment]
第一个问题添加新项，选 osx 选项即可复现

<img width="826" alt="image" src="https://github.com/opensumi/core/assets/9823838/c4ead950-27b3-4e33-a012-de7cbcf76a00">


ajv8 用到的功能不多，但新增了不少文件，感觉 v6 够用了，原来框架版本也是 v6
