### ISSUE TITLE
[BUG] 纯前端版引入 扩展 sql snippet v0.0.4 不生效

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#2811]
**描述你的问题（Describe the bug）**

本地启动的纯前端版，引入vscode扩展sql snippet后，相关提示和代码片段没有生效

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

sql snippet的提示正常生效

**环境信息（Environment）**

- OS: [Windows11]
- Browser: [chrome,114.0.5735.133]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by erha19** [comment]
@Augustjoe 请提供一下使用的 sql snippet 插件具体版本及插件 ID 信息，便于定位问题

**Comment by Augustjoe** [comment]
sql snippet  版本 ：v0.0.4  扩展id：Miladfathy.sql-snippet

**Comment by PerfectPan** [comment]
> @erha19 sql snippet 版本 ：v0.0.4 扩展id：Miladfathy.sql-snippet

是说的 web 版么？纯前端版我看插件的 package.json 都需要指定 browser 字段
web 版的话需要看下有没有引入 sql 插件，单单引入 sql snippet 插件是不生效的，找不到对应注册的语言。VSCode 是内置了 sql 的语言插件，所以直接下载 sql snippet 就可以了。

**Comment by erha19** [comment]
@Augustjoe 大部分纯前端并没有在 蚂蚁/OpenVSX 插件市场中，可以考虑从 VS Code 插件市场获取，你这里安装的插件不是纯前端使用的版本，试试

https://marketplace.visualstudio.com/items?itemName=sadeghpm.sql-snippets
https://marketplace.visualstudio.com/items?itemName=rohit-chouhan.sqlite-snippet
https://marketplace.visualstudio.com/items?itemName=shinichi-takii.sql-bigquery

**Comment by Augustjoe** [comment]
@erha19 @PerfectPan 引入了[sadeghpm.sql-snippets](https://marketplace.visualstudio.com/items?itemName=sadeghpm.sql-snippets)

**Comment by Augustjoe** [comment]
@erha19  @PerfectPan  
我在列表中引入了这个插件[sadeghpm.sql-snippets](https://marketplace.visualstudio.com/items?itemName=sadeghpm.sql-snippets)
![image](https://github.com/opensumi/core/assets/50567203/b89a46ae-ba35-448d-ade1-e3a58aa47f8a)
可以请求到插件的package.json
![image](https://github.com/opensumi/core/assets/50567203/68cd1216-794b-472c-9a30-1eb0bf04fcad)
重新npm run compile:ext-worker后启动项目
编辑器中还是无法生效对应的功能
![image](https://github.com/opensumi/core/assets/50567203/3b3b0c84-9f3d-4103-bf8c-f3252e63c4bc)
麻烦两位老师帮忙看下，十分感谢！

**Comment by erha19** [comment]
@Augustjoe 如上面提到的，单纯引入 sql-snippet 插件不一定可用，你可能还需要引入 sql 语言插件，这块确实没试过，需要自己摸索一下，如果不可用，看一下控制台是否有相关报错。

**Comment by AhkunTa** [comment]
> @erha19 @PerfectPan 我在列表中引入了这个插件[sadeghpm.sql-snippets](https://marketplace.visualstudio.com/items?itemName=sadeghpm.sql-snippets) ![image](https://user-images.githubusercontent.com/50567203/251042134-b89a46ae-ba35-448d-ade1-e3a58aa47f8a.png) 可以请求到插件的package.json ![image](https://user-images.githubusercontent.com/50567203/251042363-68cd1216-794b-472c-9a30-1eb0bf04fcad.png) 重新npm run compile:ext-worker后启动项目 编辑器中还是无法生效对应的功能 ![image](https://user-images.githubusercontent.com/50567203/251042603-3b3b0c84-9f3d-4103-bf8c-f3252e63c4bc.png) 麻烦两位老师帮忙看下，十分感谢！

问题应该是 lite 项目插件的 snippets 引入 错误的使用了后端路径 导致无法引入插件的 snippets
<img width="357" alt="截屏2023-07-05 17 06 04" src="https://github.com/opensumi/core/assets/31676999/b2e140e2-62f0-4a51-957f-006ec076b798">

具体查看这个PR
https://github.com/opensumi/ide-startup-lite/pull/63

**Comment by Augustjoe** [comment]
@AhkunTa  朋友，你是真正的英雄！

但我引入你的代码后还有个问题
![image](https://github.com/opensumi/core/assets/50567203/84121da0-3ca2-4ee9-9e88-a12a47f4cba1)
这个问题我用resplace解决了，但没找到原因

**Comment by AhkunTa** [comment]
> @AhkunTa 朋友，你是真正的英雄！
> 
> 但我引入你的代码后还有个问题 ![image](https://user-images.githubusercontent.com/50567203/251368225-84121da0-3ca2-4ee9-9e88-a12a47f4cba1.png) 这个问题我用resplace解决了，但没找到原因

这个报错应该是 [这里](https://github.com/opensumi/ide-startup-lite/pull/63/files#diff-8cd6613b04e617d1c3825e9e187f69a8ceaaf95ae4a52dd40eba6691eabcca0dR30 ) 的 Uri.parse 解析有问题 没有考虑到 `:`  被解析成`%3A`的特殊情况导致的文件路径有问题 感兴趣的话 可以在这个 https://github.com/opensumi/ide-startup-lite/pull/63 基础上修复下
