### ISSUE TITLE
🏖 GLCC 2023: 优化 OpenSumi 日志能力以提升插件进程开发调试体验 

### ISSUE THREAD

**Issue by erha19** [opensumi/core#2816]
## ⭐️ 前言

> GitLink编程夏令营（GLCC），是在CCF中国计算机学会指导下，由CCF开源发展委员会（CCF ODC）举办的面向全国高校学生的暑期编程活动。活动将覆盖近千所高校，并联合各大开源基金会、开源企业、开源社区、开源专家，旨在鼓励青年学生通过参加真实的开源软件开发，提升自身技术能力，为开源社区输送优秀人才。为青年学生提供开放友好的交流平台，希望进一步推动国内开源社区的繁荣发展。

这是 2023 GLCC 开源之夏的课题之一，题目主页：[所有课题
](https://www.gitlink.org.cn/glcc/apply/subjects)

在本次课题中，你将能完整了解 IDE 研发丰富的知识点，同时掌握如何调试及优化调试体验

本课题为基础课题，完成之后你将能获得 6,000 （人民币）的奖金，预计耗时 3 个月，希望能够认真对待本次课题。

## 🧐 题目背景

在 OpenSumi 框架内，目前如果需要查看插件进程中 `console.*` 输出信息，必须断点到插件进程中查看，这在远程/线上服务中可行性较低，同时，插件本地开发/调试过程也相对依赖日志输出能力，目前只能通过两种方式解决这一问题：

1. 断点到插件进程查看（每次修改后都需要重新断点）
2. 使用替代的方式，如 `OutputChannel` 输出、使用 `vscode.window.showInformation` API 输出等方式。

### 问题一

当前针对插件进程的 `console.*` 有一个简单的代理逻辑 #2620 ，见：

https://github.com/opensumi/core/blob/40ee3db7865b4ce0e2b6b96fa9f91f3685d96d02/packages/extension/src/hosted/ext.process-base.ts#L126-#L137

这里简单处理了插件进程内的 `console.*` 方法防止被外部错误处理，同时，在 Node 进程中会监听插件进程输出进行二次输出

https://github.com/opensumi/core/blob/642e080eedc17fb3643d3a7a70a4a74676ffffcc/packages/extension/src/node/extension.service.ts#L366-L380

以下面代码为例：

https://github.com/opensumi/core/blob/5143643555643618dbb9899ce787515db57a0de7/packages/extension/src/hosted/api/vscode/ext.host.scm.ts#L720

在 Node 进程内输出格式如下（输出格式受到 [extension.service.ts#L366-L380](https://github.com/opensumi/core/blob/642e080eedc17fb3643d3a7a70a4a74676ffffcc/packages/extension/src/node/extension.service.ts#L366-L380) 控制，可读性较差）：

<img width="475" alt="image" src="https://github.com/opensumi/core/assets/9823838/a133ee7d-b696-4006-bf24-187fb6e013b3">

更合理的方式应该冻结 `console.*` 实现，并在插件进程进行更完整的默认实现。

如：支持在前端进程内输出插件进程日志信息。

### 问题二

目前大部分插件进程逻辑内，依赖的 `getDebugLogger` 去进程日志信息输出（实际上与 `console.*` 是一样的），最终导致部分日志信息仅能在插件进程中看到输出信息，无法区分是插件输出还是插件进程输出，见：

https://github.com/opensumi/core/blob/5143643555643618dbb9899ce787515db57a0de7/packages/extension/src/hosted/api/vscode/ext.host.scm.ts#L657

建议通过统一的 Logger 进行日志信息输出，与插件代码内的 `console.*` 区分

### 问题三

 框架内同时存在 `extension-log.ts` 和 `extension-log2.ts` 两个 Logger 文件，分别用于 （WokerHost 和 ExtHost） 两个环境下使用，建议统一使用同一个构造类

## 👨🏻‍💻 解决思路

针对插件进程实现一个独立的日志输出服务，将插件进程中的 `console.*` 方法进行充分代理（防止方法不支持导致的报错异常），从而实现对插件进程开发调试的可能（如支持在前端-浏览器中输出插件进程日志）。

该日志输出能力建议只在开发环境中启用，由集成方自行控制能力开关。

## 💪 技术要求

- 熟悉 NodeJS 技术，能独立完成传统应用的前后端研发
- 熟悉 Monaco 等常见的编辑器方案
- 熟悉 React，TypeScript 编码

## ⚙️ 产出要求

- 完整的方案文档及实现思路
- 支持开发态时在前台试试查看（并能清晰区分）插件日志信息
- 阶段性的任务进展文档，并关联本文档

## 💬 相关讨论

- https://github.com/opensumi/core/discussions/2743

如对题目有疑问，也可在评论区留言交流 ~

**Comment by faga295** [comment]
问题二指出无法区分是插件输出还是插件进程输出，通过统一logger进行日志信息输出，如果还是用console.*来实现日志输出，那么同样还是无法区分，这个问题有点困惑

**Comment by erha19** [comment]
> 问题二指出无法区分是插件输出还是插件进程输出，通过统一logger进行日志信息输出，如果还是用console.*来实现日志输出，那么同样还是无法区分，这个问题有点困惑

@faga295 可以考虑追加 log 时的命名空间区分，如 `[extension log] xxxx` ， `[extension host log] xxxx`

**Comment by zhuzeyu22** [comment]
问题一：可以使用在程序中插入 debugger 关键字来实现断点调试。
vscode 环境下配置 launch.json 直接启动 electron
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}/node_modules/ide-electron",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "args": ["."],
      "outputCapture": "std"
    }
浏览器环境下开发者工具理论上直接断在 debugger 位置。

**Comment by zhuzeyu22** [comment]
问题一和问题二，我觉得好的解决方案还是 node 进程之间 rpc 传输或者管道传输针对流做重定向。在主进程接收不同流的时候添加 [命名空间] [插件 id] 标签。

**Comment by faga295** [comment]
我看了看问题一 更好的实现应该是可以在前端进程中输出 那么就需要后端去调用前端的方法(log)，想知道该怎么去实现，我有看到opensumi的[文档](https://opensumi.com/en/docs/develop/basic-design/connection#user-guide)上有涉及，但是戛然而止

**Comment by zhuzeyu22** [comment]
> @erha19 我看了看问题一 更好的实现应该是可以在前端进程中输出 那么就需要后端去调用前端的方法(log)，想知道该怎么去实现，我有看到opensumi的[文档](https://opensumi.com/en/docs/develop/basic-design/connection#user-guide)上有涉及，但是戛然而止

按照这个思路的话，目前前后端通信的方式是 command，也就是前端 log service 需要提供 log command 这样可以在后端及插件中调用并且可以打印。

**Comment by erha19** [comment]
@faga295 关于前后端通信的实现，你可以看一遍这个例子 [TODO List sample](https://opensumi.com/zh/docs/develop/sample/overview)，需要有特定的约定式声明才能进行通信。

同时，在 [opensumi-module-sample](https://github.com/opensumi/opensumi-module-samples#samples) 里也有一些案例可以学习一下。

对于框架内的 Logger，这部分实现并不是很好，有一个 [log-core](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/logs-core) 模块，这里面声明了前后端及插件进程所使用的的一部分 logger，建议可以先梳理一下这块代码结构，不着急动手就写代码。

**Comment by zhuzeyu22** [comment]
> @faga295 关于前后端通信的实现，你可以看一遍这个例子 [TODO List sample](https://opensumi.com/zh/docs/develop/sample/overview)，需要有特定的约定式声明才能进行通信。
> 
> 同时，在 [opensumi-module-sample](https://github.com/opensumi/opensumi-module-samples#samples) 里也有一些案例可以学习一下。
> 
> 对于框架内的 Logger，这部分实现并不是很好，有一个 [log-core](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/logs-core) 模块，这里面声明了前后端及插件进程所使用的的一部分 logger，建议可以先梳理一下这块代码结构，不着急动手就写代码。

约定式声明感觉并不好，可以考虑抽象出某种注入的机制，或者想想有没有更好的实现方式。

**Comment by erha19** [comment]
> 约定式声明感觉并不好，可以考虑抽象出某种注入的机制，或者想想有没有更好的实现方式。

@zhuzeyu22 是的，这里有个 issue 有记录，一直还没时间搞 https://github.com/opensumi/core/issues/1270 ，有兴趣可以看看

**Comment by erha19** [comment]
该课题由于学生时间精力问题无法按时完成课题，该 ISSUE 后续将另外进行实现处理。
