### ISSUE TITLE
[BUG] 窗口拆分后，在自定义组件内注册的菜单按钮会显示多个

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#2827]
**描述你的问题（Describe the bug）**
窗口拆分多个，组件内注册的按钮会被注册多次，因为注册按钮写在useEffect(()=>{ registryMenus()},[]) 怎么去解决这个问题，难道只能在项目初始化的时候去注册，设置visible显示吗  

![image](https://github.com/opensumi/core/assets/23164065/ae0586de-5bed-49b8-87ed-97b68ccaa52b)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by 767746649zyy** [comment]
OpenSumi Version 2.24.5

**Comment by 767746649zyy** [comment]
Windows10
electron

**Comment by erha19** [comment]
@767746649zyy 这个问题是否有最小可复现的案例？或者在 ide-electron 上复现？

**Comment by 767746649zyy** [comment]
已解决
