### ISSUE TITLE
[BUG] browser 客户端生命周期被错误重置成 pending 状态

### ISSUE THREAD

**Issue by piLurk** [opensumi/core#2828]
**描述你的问题（Describe the bug）**

browser 客户端生命周期被错误重置成 pending 状态
![image](https://github.com/opensumi/core/assets/25706123/320a8922-f1df-41d2-a24d-603d01afa95c)

这会引发的一个问题：eventBus 中长链接状态中断或错误消息一直被阻塞，无法发出

![image](https://github.com/opensumi/core/assets/25706123/a5b2e141-80eb-4008-b0ff-d5d185dc768c)

**复现路径（To Reproduce）**
step: 1  yarn start:server & yarn start:client 正常渲染 ide
step: 2 kill 后端进程，无法触发 eventBus close 错误事件

**预期表现（Expected behavior）**
预期生命周期状态不要被重置为 pending 状态，期望是fulfilled,
看起来是下面这一行代码引发，是不是移除就可以了：
`this.deferred[this._state] = new Deferred();`

**Comment by hacke2** [comment]
正常渲染 ide 后 core_module_initialized 肯定是 resolve 的

**Comment by erha19** [comment]
> 正常渲染 ide 后 core_module_initialized 肯定是 resolve 的

@hacke2 单纯看代码逻辑，这里 state 变更后会重置上一个 state 状态为 pending, 例如生命周期进入 `started_contributions` 后，`core_module_initialized` 的状态会被置为一个新的 `core_module_initialized` 对象

**Comment by piLurk** [comment]
@hacke2 我这里移除了 `this.deferred[this._state] = new Deferred();` 这一行后，生命周期表现是 ok 的
这一段代码有其他作用么，我看逻辑上应该是不需要这个？

**Comment by hacke2** [comment]
> this.deferred

没有太懂，this.deferred[state] 只有 undefined 才会重新赋值

**Comment by piLurk** [comment]
@hacke2 你看下第一张图的 34 行，任何一个地方有对 state 赋值，它的上一个生命周期就会被重新赋值。这一样我理解应该是没有必要的

**Comment by hacke2** [comment]
> @hacke2 你看下第一张图的 34 行，任何一个地方有对 state 赋值，它的上一个生命周期就会被重新赋值。这一样我理解应该是没有必要的

看了下这块逻辑确实有点问题，可以改一下~，不过要注意 this._state 的初始化逻辑。当 this.deferred[this._state] 是 undefined 时还是要初始化一次的
