### ISSUE TITLE
[BUG] 【打开的编辑器】视图里点击不同文件会重复渲染选中态

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2838]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/20262815/0df9a1dc-3b05-4606-9654-1abf19f68083)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by pipiiiiii** [comment]
复现路径：
1. 打开两个文件
2. 选中文件 1
3. 刷新页面
4. 选中文件 2
5. 选中文件 1
