### ISSUE TITLE
[BUG] 插件开发无法触发deactivate方法

### ISSUE THREAD

**Issue by KeyNGAdnil** [opensumi/core#2860]
**描述你的问题（Describe the bug）**
问题表现：关闭IDE后，插件日志没有显示deactivate方法触发

**复现路径（To Reproduce）**

![image](https://github.com/opensumi/core/assets/45062469/5bbdb941-e9f5-4592-974c-9f9ed1ddac5c)

**预期表现（Expected behavior）**

关闭IDE后，deactivate方法触发，打印日志

**环境信息（Environment）**

- OS: [macOS 12.6 Apple M1]
- Browser: [electron]
- OpenSumi Version: 2.22.1

**Comment by erha19** [comment]
@KeyNGAdnil 目前针对整体 `deactivate` 的调用时机整体都是不太可靠的，该逻辑主要还是用于清理非必要的资源消耗，不建议在内部挂载复杂的逻辑，对于常规的调用有下面几个限制：
1. 在插件进程退出时，如通过“插件市场卸载/Disable” 等操作时，会有 4000ms 的时间去执行插件内的 `deactivate` 函数，超时将忽略
2. 整体执行的可靠性是不强的，如果像你上面提到的关闭 IDE，一旦 IDE 是直接将插件进程 Kill，`deactivate` 也不会有执行的机会

相关代码位置见：https://github.com/opensumi/core/blob/b0407c99900a7bbda0fdef7e15c6cd7722d37adf/packages/extension/src/hosted/ext.process-base.ts#L194
