### ISSUE TITLE
[Question] 通过主题设置符号颜色被业务代码覆盖

### ISSUE THREAD

**Issue by zmyiy** [opensumi/core#2862]
**描述你的问题（Describe you question here）**

 问题：monaco-editor-core 中重写了大括号「{」的颜色，导致通用的主题配置不生效。
- 预期：可以通过主题色配置符号颜色
![image](https://github.com/opensumi/core/assets/33682340/3324ea39-d760-471a-860f-02e3d8d83245)

**Comment by erha19** [comment]
@zmyiy  这里应该不是业务代码覆盖的，是 monaco-core 原有逻辑，相关代码见：
https://github.com/opensumi/monaco-editor-core/blob/d53f4c55443653a8ff20b1f1034d09ccf324adde/src/vs/editor/common/model/bracketPairsTextModelPart/colorizedBracketPairsDecorationProvider.ts#L102

**Comment by zmyiy** [comment]
@erha19 我这里说的业务指的是底层 monaco-editor-core，那么该如何配置通用的主题，让其配置在这里也生效呢？
![image](https://github.com/opensumi/core/assets/33682340/8993516e-4d6c-4e8c-8888-78744f3361f0)
![image](https://github.com/opensumi/core/assets/33682340/85671726-341f-4ed4-9667-ffc5cfd454e1)

**Comment by erha19** [comment]
@zmyiy 目前有两种方式，参考这个文档 https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide，使用主题插件的方式会更加简单，参考插件 https://github.com/opensumi/Default-Themes

**Comment by erha19** [comment]
@zmyiy 这块看了一下，主要原因是 OpenSumi 内默认开启了下面两个配置，可以关闭后尝试
<img width="1021" alt="image" src="https://github.com/opensumi/core/assets/9823838/7a9e6530-7a95-407e-912d-e5a165b28c38">
