### ISSUE TITLE
[评论模块] 请问如何调用评论模块？

### ISSUE THREAD

**Issue by czz362100** [opensumi/core#2866]
![image](https://github.com/opensumi/core/assets/37129738/dc02632d-f957-410e-87d3-07ad22f372f0)

请问现在要对文件diff作出评论，应该如何调用出这个评论节点呢？

**Comment by erha19** [comment]
@czz362100 

插件可以参考这个案例 https://github.com/microsoft/vscode-extension-samples/tree/main/comment-sample

模块中拓展需要使用 https://github.com/opensumi/core/blob/824a5a8c2c294495eee6f78084aedf60b4d7a289/packages/comments/src/browser/comments.service.ts#L54 去创建并管理

**Comment by czz362100** [comment]
<img width="579" alt="image" src="https://github.com/opensumi/core/assets/37129738/2105a363-7d4b-401e-88fc-a7078bfd6d62">
请问除了调用init函数之外，还需额外调用其他哪些函数呢？

**Comment by czz362100** [comment]
> @czz362100
> 
> 插件可以参考这个案例 https://github.com/microsoft/vscode-extension-samples/tree/main/comment-sample
> 
> 模块中拓展需要使用
> 
> https://github.com/opensumi/core/blob/824a5a8c2c294495eee6f78084aedf60b4d7a289/packages/comments/src/browser/comments.service.ts#L54
> 
> 去创建并管理
<img width="558" alt="image" src="https://github.com/opensumi/core/assets/37129738/b9c64ab7-8d81-4df3-86a0-108637278907">

请问除了调用init函数之外，还需额外调用其他哪些函数呢？

**Comment by erha19** [comment]
@czz362100 如果使用模块去实现，需要额外注册 `CommentsContribution` 贡献点函数，声明编辑器允许评论的位置及额外功能，见：
https://github.com/opensumi/core/blob/f35fe97a22c3f7d0173deb56bdab9208eff381a4/packages/comments/src/common/index.ts#L451-L462

**Comment by czz362100** [comment]
好的，十分感谢。这边试了一下可行的。
<img width="740" alt="image" src="https://github.com/opensumi/core/assets/37129738/71fd0da1-2df4-48de-9470-d9c23c38e42b">

**Comment by czz362100** [comment]
> 好的，十分感谢。这边试了一下可行的。 <img alt="image" width="740" src="https://user-images.githubusercontent.com/37129738/251069974-71fd0da1-2df4-48de-9470-d9c23c38e42b.png">

![image](https://github.com/opensumi/core/assets/37129738/973c45de-5722-48e7-b4e8-4e9b5beffcc5)
但是为什么会有两个评论logo呢？

**Comment by erha19** [comment]
@czz362100 ByDesign 已评论位置会有评论图标以展示此处有评论

**Comment by czz362100** [comment]
好的。感谢
