### ISSUE TITLE
[Question] i18n 请问怎么添加多语言的语言包呀

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2869]
我想要实现双语外的多语言环境，请问怎么添加语言包，以及设置默认语言，要求和插件语言环境保持一致。

默认语言设置这块相关代码或者配置在哪里呀？

**Comment by erha19** [comment]
@zhuzeyu22 https://opensumi.com/zh/docs/extension/interface/i18n 看一下这里
