### ISSUE TITLE
[Question] 如何在某些操作增加切面，比如安装插件时、卸载插件时等等

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#2874]
**描述你的问题（Describe you question here）**
我的需求是持久化插件列表，所以想在安装插件、卸载插件时支持增加切面去执行一些自定义操作。

**Comment by erha19** [comment]
@sleepyyj 建议重新实现 `extension-manager` 模块的部分服务，相关代码可见这个评论 https://github.com/opensumi/core/issues/2864#issuecomment-1619494417
