### ISSUE TITLE
[Question] 如何对 websocket server 增加贡献点

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#2881]
**描述你的问题（Describe you question here）**
想在后端 Websocket connection close 以及 heartbeat 增加一些贡献点，是否支持，或者有什么其他方式。

**Comment by Ricbet** [comment]
可以通过 `BrowserConnectionCloseEvent` 事件来监听 websocket close

代码示例
```typescript
@OnEvent(BrowserConnectionCloseEvent)
handleWebsocketClose() {
  // xxxx
}
```

其他事件比如 `open`、`error` 等，可以看这个文件
https://github.com/opensumi/core/blob/main/packages/core-common/src/connection.ts#L3C1-L7C70

不过 heartbeat 目前是没有的

**Comment by sleepyyj** [comment]
为什么不能在后端监听，另外 IServerAppOpts 里的 webSocketHandler 能实现一些什么功能

**Comment by Hitooooo** [comment]
这个问题还有后续吗？必须修改ide-connection模块实现后端监听webSocket事件吗？
