### ISSUE TITLE
[FEATURE]: remove less file ~ import

### ISSUE THREAD

**Issue by l1shen** [opensumi/core#2884]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

根据 webpack 的建议，使用 ~ import 库中的 less 已经被废弃，不再推荐使用
https://webpack.js.org/loaders/less-loader/#webpack-resolver
<img width="736" alt="image" src="https://github.com/opensumi/core/assets/8299540/eebcad16-f9d1-4b9f-a8d9-be269b5d9325">

**描述你预期的功能表现（Describe the solution you'd like）**

希望代码中使用正确的引用方式代替

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

使用正确的引用方式也有助于切换到其他的打包器如: vite 等

**Comment by erha19** [comment]
@l1shen thanks for the report, it has been fixed on https://github.com/opensumi/core/pull/2906.
