### ISSUE TITLE
[BUG] 不联网的情况下，代码无法高亮

### ISSUE THREAD

**Issue by CaptainNeo2023** [opensumi/core#2897]
**描述你的问题（Describe the bug）**

在联网的电脑上访问，代码可以高亮
![屏幕截图 2023-07-15 172004](https://github.com/opensumi/core/assets/129503968/6660f608-1e4a-4cb5-a7e5-daaf75018bd8)

在不联网的电脑上访问，代码无法高亮
![Screenshot from 2023-07-15 17-12-17](https://github.com/opensumi/core/assets/129503968/a1640fee-7a50-4137-83a9-11ff753c27ca)

**环境信息（Environment）**

- OS: ubuntu
- Browser: chrome/Firefox
- OpenSumi Version:

**Comment by erha19** [comment]
@CaptainNeo2023 部分功能依赖远端资源，可以看一下这篇文档做一下离线部署 https://opensumi.com/zh/docs/integrate/universal-integrate-case/offline-deployment

**Comment by CaptainNeo2023** [comment]
@erha19 非常感谢！
