### ISSUE TITLE
[Question] 请问两个自定义模块之间怎么进行数据交互啊?

### ISSUE THREAD

**Issue by hutieshan** [opensumi/core#2900]
请问 在没有后端的情况下一个底边栏和侧边栏之间的页面代码之间要怎么进行数据的交换和联动啊?

**Comment by erha19** [comment]
@hutieshan 一般可通过两种方式：
1. EventBus， 参考代码：https://github.com/opensumi/core/blob/1a8bb506c800d9e18c369c58c8737e881665109c/packages/editor/src/browser/editor.decoration.service.ts#206
2. Command, 参考文档：https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-command

当然，如果两个模块间有依赖关系，你也可以通过服务依赖的方式进行数据交互

**Comment by hutieshan** [comment]
好的谢谢
