### ISSUE TITLE
[BUG] SCM 模块【更多】按钮文本缺失

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#2903]
TitleActionList 里面没有提供 more title 的 tips 的文本编辑的地方

![image](https://github.com/opensumi/core/assets/13432873/a52778c4-8701-4eb5-8420-e0d87f0c7df2)

希望可以增加文本提示，并且支持多语言

**环境信息（Environment）**

- OS: [Windows11]
- Browser: [ all ]
- OpenSumi Version: [ core/main ]

**Comment by erha19** [comment]
@zhuzeyu22 这里确实应该追加相关按钮提示，可以参考这个效果加一下
<img width="141" alt="image" src="https://github.com/opensumi/core/assets/9823838/7b6ccfb3-2527-4559-b4c5-df64eea88502">
参考代码见：
https://github.com/opensumi/core/blob/4395276b43cbbf90e9069143647a08d6c863e0ab/packages/core-browser/src/components/actions/index.tsx#L379
组件应该存在默认值，如 “更多”，同时应该接受外部传参，去声明 `moreText`，如 https://github.com/opensumi/core/blob/4395276b43cbbf90e9069143647a08d6c863e0ab/packages/core-browser/src/components/actions/index.tsx#L327-L335
