### ISSUE TITLE
[BUG] 自定义Editor时，控制台报错key重复

### ISSUE THREAD

**Issue by MilkWangStudio** [opensumi/core#2907]
**描述你的问题（Describe the bug）**
继承BrowserEditorContribution自定义了一个数据源的资源管理页面，当打开多个editor时，会出现key重复的报错。
另外就是renderMode = ONE_PER_GROUP，同一个Group，切换tab时，同一个resource仍然会重新初始化，可能是这个key重复的问题导致的。

<img width="1781" alt="image" src="https://github.com/opensumi/core/assets/15866249/d38813d7-58ff-4406-b8fa-ae656391f226">

**复现路径（To Reproduce）**
1. 实现BrowserEditorContribution
2. registerEditorComponent时，将renderMode设定为EditorComponentRenderMode.ONE_PER_RESOURCE
3. 打开多个tab就会出现该报错

**预期表现（Expected behavior）**
key不应该重复，不然可能会导致props修改后，页面不重新渲染

**环境信息（Environment）**

- OS: MAC 13.0.1
- Browser: chrome
- OpenSumi Version: 2.24.2

**故障定位 (Caused By)**
跟踪代码后定位到原因是渲染editor时，key设置为resource.toString的问题，js里的toString默认是[object Object]。
代码：opensumi/core/packages/editor/src/browser/editor.view.tsx

```typescript
export const ComponentsWrapper = ({
  component,
  resources,
  current,
  ...other
}: {
  component: IEditorComponent;
  resources: IResource[];
  current: MaybeNull<IResource>;
}) => (
  <div className={styles.kt_editor_component_wrapper}>
    {resources.map((resource) => (
      <ComponentWrapper
        {...other}
        key={resource.toString()}
        component={component}
        resource={resource}
        hidden={!(current && current.uri.toString() === resource.uri.toString())}
      />
    ))}
  </div>
);
```

**Comment by erha19** [comment]
@MilkWangStudio 这里应该基于 `resource.uri` 和 `index` 去进行 key 的拼接更为合理，可以修一下提个 PR 到 v2.26 分支 ~

**Comment by bytemain** [comment]
fixed in https://github.com/opensumi/core/pull/3036/files
