### ISSUE TITLE
[BUG] 在入口文件导入 icon.less，无法正确解析 @import 的 css 文件路径

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#2921]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/20262815/eef3f05d-3b32-45e9-9d97-90dc65996031)
![image](https://github.com/opensumi/core/assets/20262815/f78baf17-7a4b-44cb-8f29-8440e0720f52)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by erha19** [comment]
@Ricbet https://github.com/opensumi/core/pull/2916 这个有试过吗？

**Comment by Ricbet** [comment]
这配置只对导入的 less 模块有效，这里是导入的 css 文件。可能还需要调整其他的配置
