### ISSUE TITLE
[BUG] docker 环境下 file watcher 报错

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#2950]
**描述你的问题（Describe the bug）**
在 terminal 中创建文件后，左侧文件树没有刷新。
<img width="705" alt="image" src="https://github.com/opensumi/core/assets/16175708/05a7dc8e-e6c0-4361-bcdd-fa46bbe01c13">

错误信息：
```
TypeError: n is not a function
    at n.start (/release/dist-node/index.js:329:4342)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async n.watchFileChanges (/release/dist-node/index.js:329:3025)
    at async v.watch (/release/dist-node/index.js:312:165419)
    at async t.RPCProxy.onRequest (/release/dist-node/index.js:41:88788)
```
看了下源码应该是 nsfw内部报错
<img width="1081" alt="image" src="https://github.com/opensumi/core/assets/16175708/39a614de-5b03-4927-90cc-675b49ce955e">

**复现路径（To Reproduce）**
1. 在 Ubuntu 22.04 的容器中启动 Opensumi server，本地启动 Opensumi clinet，
2. 在 terminal 中创建一个文件，可以看到左侧文件树没有刷新

**预期表现（Expected behavior）**
不报错且正常监听文件变化。

**环境信息（Environment）**
OS: Ubuntu 22.04.2 LTS
Browser: Chrome
Opensumi Version: 2.23.2

**Comment by erha19** [comment]
@sleepyyj 看着是容器内没有安装 nsfw 依赖导致的问题，怎么部署的 ？

**Comment by sleepyyj** [comment]
> @sleepyyj 看着是容器内没有安装 nsfw 依赖导致的问题，怎么部署的 ？

用这个 Dockefile 部署的，https://github.com/opensumi/ide-startup/blob/main/Dockerfile

**Comment by erha19** [comment]
@sleepyyj 看着与这个 BreakingChange 相关，需要把 `nsfw` 加到全局依赖内 https://github.com/opensumi/core/blob/95d666a99ea25a222891fc0e799fd93faeecce4e/CHANGELOG.md#5-revert-to-using-nsfw-watcher-library-in-linux

**Comment by sleepyyj** [comment]
是这个问题，谢谢

**Comment by sleepyyj** [comment]
@erha19 MacOS 上正常了，但是在 Ubuntu 还是报错。。
<img width="714" alt="image" src="https://github.com/opensumi/core/assets/16175708/d283b97b-a9ac-4414-99c5-aadf42b621c5">
