### ISSUE TITLE
[Question] 如何启用文件浏览窗口的 “打开目录” 按钮？更新到v2.26.2后这个按钮没有了

### ISSUE THREAD

**Issue by CaptainNeo2023** [opensumi/core#2952]
版本更新到v2.26.2后，文件浏览窗口的“打开目录”按钮没有了，没找到在哪里设置这个功能，帮忙看下在哪里设置。是否可以做成一个选项，启用或禁用该按钮？没有这个按钮，没法打开文件夹。我们现在有在文件菜单里面添加一个打开文件夹的选项，在菜单里打开。

![image](https://github.com/opensumi/core/assets/129503968/5c69c33c-367b-4c8b-8802-41d234214aae)

之前是有这个按钮的

![image](https://github.com/opensumi/core/assets/129503968/5451dc3e-f02f-4b5c-b505-4f91c435afb0)

**Comment by erha19** [comment]
@CaptainNeo2023 目前还有部分 2.26.3 版本的 patch 未发布，等发布后再试一下
