### ISSUE TITLE
[BUG] 资源管理器无法加载文件目录

### ISSUE THREAD

**Issue by CaptainNeo2023** [opensumi/core#2953]
资源管理器无法加载文件目录，需要点击刷新按钮，或者点击资源管理器区域才会加载文件目录。

![image](https://github.com/opensumi/core/assets/129503968/f212d92a-51a3-4241-86f7-0ddfaf7fe14d)

**复现路径（To Reproduce）**

输入IP地址进入opensumi web IDE，打开文件夹目录

**预期表现（Expected behavior）**

选择文件夹目录后，资源管理器正常加载文件树内容

**环境信息（Environment）**

- OS: Ubuntu22
- Browser: chrome
- OpenSumi Version: v2.26.2

**Comment by bytemain** [comment]
你好，我们也在关注这个问题，感谢反馈

**Comment by bytemain** [comment]
你好，2.26.3 会修复这个问题：

- https://github.com/opensumi/core/pull/2945
