### ISSUE TITLE
[Question] 如何将vscode插件引入到OpenSumi搭建的IDE中？

### ISSUE THREAD

**Issue by lenaRen** [opensumi/core#2987]
**描述你的问题（Describe you question here）**
如何将vscode插件引入到OpenSumi搭建的IDE中，并可以正确执行？

1、从vs code官网初始化了Hello world插件项目；
2、构建成 .visx文件；
3、本地安装在vs code中，code --install-extension helloworld-0.0.1.vsix；
4、在vs code 中运行此插件，可以看到 “Hello World”弹出；

5、找到vs code 插件安装目录；
6、拷贝undefined_publisher.helloworld-0.0.1插件包，到 ide-electron/extensions/目录下；
    （ide-electron为最新拉取的opensumi的Electron版本）
7、build，start后；
8、运行插件，无法正确执行；

错误日志：
Uncaught (in promise) Error: Contributed command 'helloworld.helloWorld' does not exist.Error: Contributed command 'helloworld.helloWorld' does not exist.
	at ExtHostCommands.$executeContributedCommand (D:\evas\project\ide-electron\app\extension\index.js:23229:35)
	at RPCProtocol._doInvokeHandler (D:\evas\project\ide-electron\app\extension\index.js:4157:23)

**Comment by fjb040911** [comment]
建议提供离线安装 .vsix 的入口

**Comment by Ricbet** [comment]
需要先解压 visx 文件，然后把里面的 extension 目录下的文件都放在你 helloworld 插件的根目录下

**Comment by lenaRen** [comment]
> 需要先解压 visx 文件，然后把里面的 extension 目录下的文件都放在你 helloworld 插件的根目录下

刚试过，依旧无法正确执行，报同样的错误

**Comment by erha19** [comment]
@lenaRen 看报错是你插件存在问题，可以在 VS Code 先验证一下，是否移动文件时缺少文件了

**Comment by lenaRen** [comment]
在VS Code上是可正确执行的，这是我构建的vsix文件
[helloworld-0.0.1.zip](https://github.com/opensumi/core/files/12309463/helloworld-0.0.1.zip)

**Comment by fjb040911** [comment]
@erha19 我也验证了这个问题，发现 1.7.* 以上的VSCode打包出的插件在 Opensumi 中不支持。建议你们在文档中插件部分加个兼容性描述，标注兼容到哪个版本的 VSCode
