### ISSUE TITLE
[Question] factory 类型的 module 的参数如何传递

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#2988]
**描述你的问题（Describe you question here）**

如何传递 TerminalClientFactory 的 options。目的是想通过 terminal.integrated.shellArgs.linux 添加 shell 的默认启动参数，但是又不想把这个配置在 terminal profile 中暴露给用户。
https://github.com/opensumi/core/blob/52c567911e334244cfd26a96876b36463bf92443/packages/terminal-next/src/browser/terminal.client.ts#L749C64-L749C64

**Comment by sleepyyj** [comment]
@erha19

**Comment by erha19** [comment]
@sleepyyj 参考一下 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/terminal-env
