### ISSUE TITLE
[FEATURE] 顶部菜单栏在缩小到一定尺寸后是否能折叠到一个图标菜单中

### ISSUE THREAD

**Issue by yinyinfurong8888** [opensumi/core#2989]
顶部菜单栏在缩小到一定尺寸后是否能折叠到一个图标菜单中？类似VScode那样，这样当缩小后还能选中菜单，不会因为菜单跟右侧的最小、最大、关闭按钮重合，而点不到想要的功能
![image](https://github.com/opensumi/core/assets/83274944/43fbc159-3aa2-424d-a644-8655af853068)

**Comment by erha19** [comment]
@yinyinfurong8888 https://github.com/opensumi/core/pull/2556 可以参考这个 PR 修改一下，基础能力应该已经是实现了的，目前是通过配置 `MenubarSettingId.CompactMode` 控制的

**Comment by yinyinfurong8888** [comment]
通过ide-electron main 拉取的v2.26.4 最新代码，start后 设置是否使用紧凑模式

**Comment by erha19** [comment]
@yinyinfurong8888 这个目前的实现效果就是这样的，需要改造，相关代码可以按需改一下

**Comment by erha19** [comment]
@yinyinfurong8888 你可以加一个图标，点击时调用如下代码就会有菜单展示： https://github.com/opensumi/core/blob/983c19e06a2cdd2269ce3098cf512d8db0337d99/packages/main-layout/src/browser/layout.service.ts#L315-L317

**Comment by yinyinfurong8888** [comment]
菜单栏隐藏可以用通过菜单控制，那菜单栏如何判断超出呢？

**Comment by yinyinfurong8888** [comment]
> @yinyinfurong8888 你可以加一个图标，点击时调用如下代码就会有菜单展示：
> 
> https://github.com/opensumi/core/blob/983c19e06a2cdd2269ce3098cf512d8db0337d99/packages/main-layout/src/browser/layout.service.ts#L315-L317

我加了图标，点击调用代码，没有反应，这是怎么回事？

**Comment by erha19** [comment]
这里需要覆盖一下相关实现：

1. 覆盖默认的 `IMenuRegistry` 实现

```ts
import { MenuRegistryImpl, IMenubarItem } from '@opensumi/ide-core-browser/lib/menu/next';
export const CORE_MENU_BAR = 'sumi/menu';
export const TOOLBAR_MENU = 'toolbar/menuentry';

@Injectable()
export class CustomMenuRegistry extends MenuRegistryImpl {
  registerMenubarItem(menuId: string, item: PartialBy<IMenubarItem, 'id'>): IDisposable {
    const superDisposable = super.registerMenubarItem(menuId, item);
    const toDispose = this.registerMenuItem(CORE_MENU_BAR, { submenu: menuId, ...item });
    return {
      dispose: () => {
        superDisposable.dispose();
        toDispose.dispose();
      },
    };
  }
}
```

2. 覆盖 token 实现，在创建 ClientApp 阶段覆盖，尽早

```ts
injector.overwrite({
      token: IMenuRegistry,
      useClass: CustomMenuRegistry,
})
```

3. 在贡献点内注册一下菜单，如：

将 CORE_MENU_BAR 注册为 TOOLBAR_MENU 的子菜单

```ts
menuRegistry.registerMenuItem(TOOLBAR_MENU, {
      submenu: CORE_MENU_BAR,
      group: 'navigation',
      iconClass: getIcon('menu'),
      label: 'menu',
      order: 1,
    });
```

4. 使用 `InlineMenuBar` 组件使用菜单，伪代码如下：

```jsx
@Autowired(AbstractContextMenuService)
private contextMenuService: AbstractContextMenuService;

getMenuBarMenu() {
    if (!this.menu) {
      this.menu = this.contextMenuService.createMenu({
        id: TOOLBAR_MENU,
      });
    }
    return this.menu;
}
...
 <InlineMenuBar className={styles.menu} menus={getMenuBarMenu()} />
...
```

@yinyinfurong8888

**Comment by yinyinfurong8888** [comment]
通过注册组件 electron-header 写自己header， 然后使用上面的方法， 唯一一处区别是覆盖 token 实现这里
renderApp 在new Injector获取实例后，直接注册（先注册的生效，后面再注册也没用）
injector.addProviders({
    token: IMenuRegistry,
    useClass: CustomMenuRegistry,
  });

最后结果
![1692943443712_82215206-F210-42b7-A00A-E3B8D78AD7F7](https://github.com/opensumi/core/assets/83274944/17bbaf88-0aaf-4978-8ec5-dcd2a1d432bc)
