### ISSUE TITLE
[Question] 如何更改右键菜单？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#2993]
![bmltYV8yNTYxNjQyXzE2OTE3MzU0MTc2MzhfMTFmZWFkYmUtY2UzYy00YzE0LTkwZmMtMDU3MDU5ODVjZGE0X2lt](https://github.com/opensumi/core/assets/50567203/1a5f9512-c1af-4c2e-b01d-ad8d7f061df1)
>
如图想在右键菜单中添加几个选项。

**Comment by bytemain** [comment]
参考下：https://opensumi.com/zh/docs/develop/basic-design/contribution-point/#%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95%E6%B3%A8%E5%86%8C

**Comment by Augustjoe** [comment]
@bytemain  您好，按照链接中的方法按钮别添加到顶部菜单了，我使用的是纯前端版本
![image](https://github.com/opensumi/core/assets/50567203/f7da8283-1f11-41ad-8864-30123e5a74c3)
这是我的代码
![image](https://github.com/opensumi/core/assets/50567203/c7e3fb14-46ee-4fdc-9b7c-03df6005f318)
![image](https://github.com/opensumi/core/assets/50567203/a3027f89-f8c8-4579-a89a-b733eb256d88)

**Comment by bytemain** [comment]
文档里没说清楚，这个我们后续更新下文档。

第一行代码的 registerMenubar 是注册顶部菜单栏，不是右键菜单，后续我们会删掉文档里的这几行代码。

直接看这个吧：
https://github.com/opensumi/opensumi-module-samples/blob/main/modules/custom-context-menu/browser/index.contribution.ts#L43

![CleanShot 2023-08-14 at 15 04 53@2x](https://github.com/opensumi/core/assets/13938334/27c36dbe-ffe6-449a-9ea2-cdb6cdae9ca5)

**Comment by bytemain** [comment]
看文档：https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-menu#%E6%B3%A8%E5%86%8C%E4%BA%8C%E7%BA%A7%E5%AD%90%E8%8F%9C%E5%8D%95

**Comment by Augustjoe** [comment]
@bytemain  抱歉老师，我太笨了，文档中的方法我尝试了下，不好用。
也可能是我表达的意思不对，我想在这加子菜单
![image](https://github.com/opensumi/core/assets/50567203/fa98d2cd-03e0-48b4-8530-031e42ef47a1)
我现在是这么写的感觉无法生效
![image](https://github.com/opensumi/core/assets/50567203/75b06287-227c-4cda-b134-f597b5068fba)

**Comment by erha19** [comment]
@Augustjoe https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-menu#%E6%B3%A8%E5%86%8C%E4%BA%8C%E7%BA%A7%E5%AD%90%E8%8F%9C%E5%8D%95 参考一下这个章节的例子

**Comment by Augustjoe** [comment]
@erha19 @bytemain 感谢两位老师，问题已解决。
