### ISSUE TITLE
[Question] 如何获得右键时，当前打开的文件夹目录？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#2997]
![image](https://github.com/opensumi/core/assets/50567203/8e4b0781-2f07-4e14-ace2-7f72910c1a98)
如图
我想实现点击GaussDB存储过程按钮就在sql文件夹下创建一个新的文件，文件中是已经写好的模板代码，但现在我不知道怎么获得右键文件路径。

**Comment by erha19** [comment]
@Augustjoe 你注册命令，命令执行时会携带两个参数，第一个为右键文件，第二个为选中的所有文件数组

**Comment by Augustjoe** [comment]
@erha19 谢谢老师！找到了

**Comment by Augustjoe** [comment]
@erha19 老师，我用改造的文件目录地址去调http-file-service.ts中的createFile方法，创建文件的接口是通的，控制台也没有报错，文件树上却没有显示创建的文件，刷新后创建的文件才显示出来，是我调用的创建文件的方法不对吗？

**Comment by erha19** [comment]
@Augustjoe 你可以创建后调用一下文件树的刷新接口，如：

```ts

@Autowired(IFileTreeService)
fileTreeService: IFileTreeService;

...
this.fileTreeService.refresh()
```

这里需要手动刷新是因为纯前端版本 Demo 是没有接入文件监听服务的，文件树无法感知文件创建动作，需要你手动触发一下

**Comment by Augustjoe** [comment]
@erha19 老师，是从这里引入吗？
![image](https://github.com/opensumi/core/assets/50567203/6ec784f1-d0c1-4f70-897d-0a0daef3991f)
这么引入会报错
![image](https://github.com/opensumi/core/assets/50567203/5ebeaa34-c6c6-45b2-9c4a-6e682fe9bffd)

**Comment by erha19** [comment]
@Augustjoe 你看清楚我的实例引入的 token，你引错了

**Comment by Augustjoe** [comment]
@erha19 
![image](https://github.com/opensumi/core/assets/50567203/908b5abb-fb88-4284-97a3-998fd8e04c97)
是这个吗？要不麻烦您直接告诉我从哪里引入吧，感谢。
这么用也会报相同的错误

**Comment by erha19** [comment]
@Augustjoe 你的服务声明少了 `@Injectable ` 声明，建议看一下文档 https://opensumi.com/zh/docs/develop/sample/use-service-by-di#%E4%BD%BF%E7%94%A8%E5%86%85%E7%BD%AE%E6%9C%8D%E5%8A%A1

**Comment by Augustjoe** [comment]
@erha19  刷新后文件树消失了
![image](https://github.com/opensumi/core/assets/50567203/3472ea62-7beb-491f-ae0d-624006944def)
![image](https://github.com/opensumi/core/assets/50567203/9380bb8f-d7b0-4262-aafe-343440e7d529)
我把刷新的方法直接放在了createfile下
