### ISSUE TITLE
[Question] DebugSession 是什么时候创建的，和调试代码中起的子进程是什么关系

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#3003]
**描述你的问题（Describe you question here）**
对 DebugSession 的概念理解不太清晰，特地咨询一下

- 一次调试会有几个 DebugSession，是什么时候创建的？currentSession 表示什么
- 和调试代码中起的子进程是什么关系? (问这个问题是因为发现nodejs调试如果代码里起了子进程，debugSession 会有多个）
- DebugSession 的 parentSession 是什么

**Comment by geekeren** [comment]
@erha19 可以帮忙回答下吗

**Comment by erha19** [comment]
> 一次调试会有几个 DebugSession，是什么时候创建的？currentSession 表示什么
可能会有多个，创建 DebugSession 相关代码可以看这里 https://github.com/opensumi/core/blob/8d973da27f8048c3aa8fcd0e3bfc6351e01b9577/packages/debug/src/browser/debug-session-manager.ts#L284

> 和调试代码中起的子进程是什么关系? 

子进程的 Session 会有一个 ParentDebugSession，这就是单纯的进程管理，例如父进程关闭了，子进程也需要清理

@geekeren

**Comment by geekeren** [comment]
@erha19 所以有几个调试代码里面通过 fork exec 起的子进程都会新建一个 debugSession ? 子进程和debugSession 一一对应？我之前似乎出现过没有子进程 但是会有两个 debugSession  的情况 符合预期吗

**Comment by geekeren** [comment]
其次 fork 和 exec 会调用 createDebugSession 这一块的链路是什么样

**Comment by erha19** [comment]
@geekeren 子进程和 DebugSession 确实是会一一对应的，有几个 DebugSession 取决于调试插件的实现，有一些调试逻辑会被通过 parent-> real 这种包裹形式执行。

只有在 Node 调试情况下才会走 fork ，否则一般为 createProcess 的方式，相关代码可以调试看一下：https://github.com/opensumi/core/blob/6d8acec54d23d98aa179dcbf3e9dfc01c713cf8a/packages/extension/src/hosted/api/vscode/debug/extension-debug-adapter-starter.ts#L15

**Comment by geekeren** [comment]
@erha19 可能我没有表达清楚，比如我调试如下一段代码。代码运行后，使用 execSync 启动了一个 npm 的子进程，这个时候 opensumi 会对应启动 DebugSession, 我调用的是 execSync , opensumi 是如何知晓启动一个 debugSession 的
<img width="710" alt="image" src="https://github.com/opensumi/core/assets/13082375/4c3a055d-50b2-423f-a03c-6a845924e3a3">

**Comment by erha19** [comment]
@geekeren 你是在问 JavaScript Debug Terminal 的实现原理？可以看一下这个文章 https://mp.weixin.qq.com/s/Qve5TbHiEkOZBxqU2qNpzw
