### ISSUE TITLE
[Question]  opensumi 2.24.5 的版本支持 插件里面加载 webview 吗？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3004]
大家好呀，我想请问下 opensumi 2.24.5 的版本支持 插件里面加载 webview 吗？

windows 11 环境
electron
开发的 vscode 插件，使用 vue 生成 webview

**Comment by Ricbet** [comment]
任何版本都支持的，这是插件的基础能力。是有什么问题吗

**Comment by zhuzeyu22** [comment]
@Ricbet 
我自己用 vue 写了一个 html ，打包好了放在了插件目录里，单独浏览器可以打开。
使用插件 通过 webview 的方式加载就打开的是个空白页。

`
  let disposable = commands.registerCommand("etest.test.client", () => {

    // window.showInformationMessage("Hello World etest.test.client!");
    const column = window.activeTextEditor
      ? window.activeTextEditor.viewColumn
      : undefined;

    const q = getWebviewOptions(context.extensionUri);
    log("getWebviewOptions(context.extensionUri)", q);
    
    // debugger;
    const panel = window.createWebviewPanel(
      "qwe",
      "qwe",
      column || ViewColumn.One,
      getWebviewOptions(context.extensionUri)
    );

  });


function getWebviewOptions(extensionUri: Uri): WebviewOptions {
  return {
    // Enable javascript in the webview
    enableScripts: true,

    // And restrict the webview to only loading content from our extension's `media` directory.
    localResourceRoots: [Uri.joinPath(extensionUri, "dist", "webview")],
  };
}
`

**Comment by Ricbet** [comment]
看看控制台有什么报错信息，或者提供一下完整的代码

**Comment by zhuzeyu22** [comment]
@Ricbet 
只有这么一条
warning.js:6 Warning: `info.item` is deprecated since we will move to function component that not provides React Node instance in future.

**Comment by zhuzeyu22** [comment]
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack://ETest/node_modules/.pnpm/rc-util@5.29.3_wcqkhtmu7mswc6yz4uyexck3ty/node_modules/rc-util/es/warning.js:6" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">warning.js:6</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Warning: `info.item` is deprecated since we will move to function component that not provides React Node instance in future.</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | warning | @ | warning.js:6
-- | -- | -- | --
  | call | @ | warning.js:20
  | warningOnce | @ | warning.js:25
  | get | @ | warnUtil.js:14
  | （匿名） | @ | index.js:33
  | InternalMenu.handleClick | @ | index.js:75
  | （匿名） | @ | Menu.js:320
  | （匿名） | @ | useMemoCallback.js:15
  | onInternalClick | @ | MenuItem.js:136
  | callCallback | @ | react-dom.development.js:188
  | invokeGuardedCallbackDev | @ | react-dom.development.js:237
  | invokeGuardedCallback | @ | react-dom.development.js:292
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:306
  | executeDispatch | @ | react-dom.development.js:389
  | executeDispatchesInOrder | @ | react-dom.development.js:414
  | executeDispatchesAndRelease | @ | react-dom.development.js:3278
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.development.js:3287
  | forEachAccumulated | @ | react-dom.development.js:3259
  | runEventsInBatch | @ | react-dom.development.js:3304
  | runExtractedPluginEventsInBatch | @ | react-dom.development.js:3514
  | handleTopLevel | @ | react-dom.development.js:3558
  | batchedEventUpdates$1 | @ | react-dom.development.js:21871
  | batchedEventUpdates | @ | react-dom.development.js:795
  | dispatchEventForLegacyPluginEventSystem | @ | react-dom.development.js:3568
  | attemptToDispatchEvent | @ | react-dom.development.js:4267
  | dispatchEvent | @ | react-dom.development.js:4189
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | discreteUpdates$1 | @ | react-dom.development.js:21887
  | discreteUpdates | @ | react-dom.development.js:806
  | dispatchDiscreteEvent

</span></div>
</body>
</html>

**Comment by zhuzeyu22** [comment]
@Ricbet 
const panel = window.createWebviewPanel(
      "xxx",
      "xxx",
      column || ViewColumn.One,
      {}
    );

panel.webview.html =`<!DOCTYPE html>
    <html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Vue App</title>
    </head>
    
    <body>
        <div id="app"></div>
        <script
            src="vscode-resource:/d%3A/workspace/extensions/xxx/dist/webview/js/index.69026ff7.js"></script>
    </body>
    </html>`

目前定位的问题是 webview 的使用方式应该是没有问题的，但是其中对于插件内的资源引用似乎是失效的。因为没有任何输出信息因此难以定位。

**Comment by zhuzeyu22** [comment]
@Ricbet 而且 webview 使用事件通信似乎也失效了，不确定是 opensumi 和 vscode 插件版本不一致导致的还是别的什么原因导致的。

基于 vscode 1.67.0 版本开发的插件。这块可能需要一个 opensumi 和 vscode 的版本对应关系列表。

window.addEventListener('message', event => { xxxxxx

**Comment by zhuzeyu22** [comment]
@Ricbet 补充一点，如果webview 使用不了的情况下，希望兼容 vue 来做自定义编辑器组件的功能开发。或者支持插件使用 electron 的能力

**Comment by Ricbet** [comment]
单从提供的代码上来看确实没什么问题，可能还需要你提供更多完整的代码示例（例如整个插件包）。
因为确实不好排查定位是否是通信的原因，不过你可以先自己尝试 debug 调试一下，看看整个通信过程在哪里断开了。

-----
自定义编辑器组件可以参考这个文档，https://github.com/opensumi/opensumi-module-samples/blob/main/modules/editor-monaco-component/README.md

**Comment by zhuzeyu22** [comment]
@Ricbet  看上去是 webview 加载脚本资源异常导致是空白页，没有时间去定位具体原因。自定义编辑器可能不太满足，因为我需要编辑器内容是一个 vue 页面。

**Comment by zhuzeyu22** [comment]
@Ricbet 可能是 webview 加载异常的原因分析是因为，vscode 可以正常加载插件并且显示 vue 页面。因此定位是 opensumi 框架缺陷。

**Comment by erha19** [comment]
@zhuzeyu22 可以基于 https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample  修改一个可复现问题的 Demo 方便我们排查相关问题。
