### ISSUE TITLE
[Question] 纯前端版如何通过编程方式创建文件？如何重新获取文件树？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3006]
我在文件树的右键菜单中加了一些新按钮，点击这些按钮会创建一个或一系列模板文件，尝试调用http-file.server,ts文件中的createFile方法，无报错，成功调用创建文件接口，但文件树无显示，又尝试调用刷新文件树方法，刷新后文件树消失。请问是否有其他创建文件的方法或案例？

**Comment by erha19** [comment]
@Augustjoe 所有文件树数据的请求都是从这里发起的，可以调试看一下是不是创建文件后没有获取到具体的文件信息 https://github.com/opensumi/ide-startup-lite/blob/399649246615a3cbe91c56fea028589f9a2a10f5/web-lite/file-provider/browser-fs-provider.ts#L347

**Comment by Augustjoe** [comment]
@erha19 请问官方有推荐的通过代码实现创建文件的方式吗？

**Comment by erha19** [comment]
> @erha19 请问官方有推荐的通过代码实现创建文件的方式吗？

没有，文件的创建于对接的服务强相关，实现上还是遵照上面讲的，讲文件服务内的 createFile 方法进行实现，至于刷新后内容为空，可能是存在时序上的问题，你可以调试一下我上面给到的代码位置，例如创建文件后断点调试一下刷新是否正常请求了

**Comment by Augustjoe** [comment]
@erha19 进到了doGetStart方法里，但没有进到
`if (lstat.isDirectory()) {
        return await this.doCreateDirectoryStat(uri, lstat, depth);
  }`
这个判断里，没有报错

**Comment by erha19** [comment]
@Augustjoe 无法判断具体问题，这类业务问题只能自己看代码调试定位
