### ISSUE TITLE
[Question] 如何在启动的时候只激活部分插件

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#3008]
**描述你的问题（Describe you question here）**
如何在进程启动时，根据插件的 metadata ，只激活插件目录下的部分插件。

**Comment by erha19** [comment]
@sleepyyj 目前没有做这块实现，可以自行覆盖服务实现一下，相关问题见：

https://github.com/opensumi/core/issues/2864#issuecomment-1619494417
