### ISSUE TITLE
[Question] 我想在 opensumi 里面自定义一个 vue 页面的弹窗，请问怎么实现。

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3010]
功能需求：
1、基于 vue2 编译好的一个 html 页面
2、我想通过弹窗或者编辑器的形式打开并进行交互
3、并且以插件的形式实现热拔插。

解决方案：
1、我尝试使用了 webview ，opensumi 的webview 似乎不支持。

2、我又尝试使用 electron 的 BrowserWindow 来打开，打开是成功了，但是通信需要构造比较复杂的通信方式，（插件 -- opensumi --- elecron --- vue2） 

问题：
我想请教下有没有一些简便的思路。

**Comment by erha19** [comment]
@zhuzeyu22 在 OpenSumi 内插件可以使用 `sumi.ideWindow.createWebviewWindow` 去创建独立的窗口，其中，你可以使用其中封装的 postMessage / onMessage 方法进行通信，也可以通过传入 preload 的方式进行自定义通信设计。

相关代码见：
https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/extension/src/hosted/api/sumi/ext.host.window.ts#L133

**Comment by zhuzeyu22** [comment]
@erha19 似乎是个好思路，但是担心不稳定因此暂时绕过这一块了，直接使用 electron 的能力去实现，在 browser 层引用 node 的能力不再使用通信调用 node。这样也解决了 webview 没有 node 能力的问题。
