### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by javareny** [opensumi/core#3014]
请问下大佬，图1 new 了 一个对象，却没有走进图2 的 构造，能帮忙看下吗
![2](https://github.com/opensumi/core/assets/21698996/a9abc4af-3085-40ad-847e-e00087784b92)
![3](https://github.com/opensumi/core/assets/21698996/5f3d2cb3-56e1-4f46-8d84-218b20a7e015)

**Comment by bytemain** [comment]
打包工具使用 node_modules 里代码的时候，应该只用了 lib/ 下的代码，你这里改的是 node_modules 里的 src

**Comment by erha19** [comment]
@javareny @opensumi/* 包中引入了 src（源码）方便调试时使用，但实际构建编译使用的是 `lib` 代码，你需要自己进到同样路径下的 lib 目录下进行断点或 log
