### ISSUE TITLE
[Question] 请问如何操作左侧文件树？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3017]
项目需求要将左侧文件树变成数据库的结构如下图
![image](https://github.com/opensumi/core/assets/50567203/7cad8018-5eff-45b2-90b7-426aab9cabb2)
请问各位老师有没有单独操作左侧树的方法，如增删改查？

**Comment by erha19** [comment]
@Augustjoe https://github.com/opensumi/core/blob/b0407c99900a7bbda0fdef7e15c6cd7722d37adf/packages/components/src/recycle-tree/basic/index.tsx#L21 可以用 Tree 组件自行实现，原有文件树不具备这个能力

**Comment by Augustjoe** [comment]
@erha19 老师可以再说的具体点吗？我用这个组件创建完树后要放在哪里，如何实现呢？ 感谢！

**Comment by erha19** [comment]
@Augustjoe 注册组件的做法可以参考下面伪代码：
```ts
@Autowired(IMainLayoutService)
private readonly mainLayoutService: IMainLayoutService;
... 省略
onStart() {
  this.mainLayoutService.collectViewComponent(
      {
        id: RESOURCE_VIEW_ID, // 唯一的 ID
        name: this.getWorkspaceTitle(), // Tab 名称
        collapsed: false, // 是否折叠
        component: FileTree, // 具体渲染组件
      },
      EXPLORER_CONTAINER_ID,
    );
}
```

实现就是跟前端开发一致，你可以自己找开源组件做 Tree 渲染（但要做好主题适配）, 也可以使用上面提到的内置组件，就会有一定的限制，使用方法参考：

https://github.com/opensumi/core/blob/15bef1fb6a2665c17f75c87eb38a9369837d21c8/packages/debug/src/browser/view/breakpoints/debug-breakpoints.view.tsx#L178

**Comment by Augustjoe** [comment]
已解决，感谢
