### ISSUE TITLE
[BUG] 调试断点设置异常

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#3022]
**描述你的问题（Describe the bug）**
- 调试如下代码
- index.js
``` 
 const test = () => {
  // test
  console.log(Date.now());
  console.log(Date.now());
  console.log(Date.now());
 }

 test();
```

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Program",
      "program": "${workspaceFolder}/index.js",
      "request": "launch",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "node"
    }
  ]
}

```
https://github.com/opensumi/core/assets/13082375/b79f5213-5339-4eb7-93bb-431b7086f0b8

- 在最后一行 以及 test 函数注释后的第一行设置断点
- 进入调试，在第一个断点 暂停时，删除该行代码
将出现如下问题
- 出现报错：bundle.js:2 Uncaught (in promise) Error: Illegal value for lineNumber；
- 同时编辑器断点置灰，编辑器点击行号区域无法设置断点
- 左侧断点列表，最后一行断点行号异常：超出最大代码行

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by erha19** [comment]
@geekeren 确实存在问题，报错代码位于
https://github.com/opensumi/core/blob/5cbe9c19caddfb6321cb55d60267fcc90e0eb5c8/packages/debug/src/browser/editor/debug-model.ts#L435

这里有个逻辑是当编辑器内容变化时，自动将断点位置定位到下一个非空行位置上面，这里应该做一下处理避免报错。

有时间可以尝试解决一下，或者后面我来看下 ~

**Comment by geekeren** [comment]
@erha19 这里的问题是什么，根本原因是最后一行计算的行号不对吧。

**Comment by erha19** [comment]
> @erha19 这里的问题是什么，根本原因是最后一行计算的行号不对吧。

没细看，目前只是猜测

**Comment by geekeren** [comment]
@erha19 这个有修复计划吗

**Comment by erha19** [comment]
@geekeren 本周会修复这个问题，等我忙完手头的事情
