### ISSUE TITLE
[Question] 如何让CORE区域折叠？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3024]
![image](https://github.com/opensumi/core/assets/50567203/1d5c8055-bfb4-475a-9722-cf5ef00f8304)
![image](https://github.com/opensumi/core/assets/50567203/cb3737e1-a57f-4e5b-b089-22498302d2df)
我通过图上的方法让辅助功能折叠，但不知道如何让文件树，也就是CORE区域折叠，我不清楚CORE区域的id是什么？

**Comment by erha19** [comment]
@Augustjoe 这里 https://github.com/opensumi/core/blob/d288f3d41d4ba095d2674c4fb15a6b6d09e296f6/packages/file-tree-next/src/browser/file-tree-contribution.ts#L154

**Comment by Augustjoe** [comment]
@erha19  解决了 感谢！
