### ISSUE TITLE
[Question] 请问如何覆盖重写 WelcomeContribution 模块

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3025]
我想基于ide-electron 且不改动依赖包的情况下，通过 di 的方式重写 WelcomeContribution 这个模块，请问我应该怎样 使用 injector 来做注入覆盖？

**Comment by erha19** [comment]
@zhuzeyu22 不引入 WelcomeContribution，自行实现覆盖即可，例如：

```ts
@Domain(BrowserEditorContribution)
class CustomContribution {
...
  registerEditorComponent(registry: EditorComponentRegistry) {
    registry.registerEditorComponent({
      uid: 'custom-welcome',
      scheme: 'welcome',
      component: CustomWelcome,
      renderMode: EditorComponentRenderMode.ONE_PER_WORKBENCH,
    });
  }
...
}
```

可以自行控制默认打开的逻辑

**Comment by zhuzeyu22** [comment]
@erha19 ElectronBasicModule 引用了 WelcomeContribution ，这块的逻辑希望可以服用，包括打开的逻辑也希望可以复用，只想修改 welcome 的页面，有没有什么好的思路

**Comment by erha19** [comment]
@zhuzeyu22 你可以写一个新 module 拓展一下 BasicModule，例如：
```ts
@Injectable()
export class BasicModule extends ElectronBasicModule {

  providers = [ ...your contribution/service];
}
```

使用时，引入 BasicModule 这个就行了，本身也没啥内容

**Comment by zhuzeyu22** [comment]
@erha19  那我在 providers = [ ...your contribution/service]; 这个位置加的 WelcomeContribution  可以覆盖掉原来的吗？
有些框架的模块我想自己重写又不想改变原有的包

**Comment by erha19** [comment]
@zhuzeyu22   你可以完全拷贝 ElectronBasicModule 里面声明的内容过来，然后替换 WelcomeContribution 为你自己的逻辑

**Comment by zhuzeyu22** [comment]
可用的，只是用的时候需要注意引用关系直接指向包内模块。

**Comment by zhuzeyu22** [comment]
@erha19 补充提问一下，这种方式在 webpack watch 的时候导致每次编译量增加，有没有 gulp 模块化配置的参考？
