### ISSUE TITLE
[BUG] 多语言插件的一些偶现缺陷

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3029]
中文语言插件 和 官方的 git 插件同时使用时出现偶现汉化失败的现象

请问插件有加载顺序吗？还是有一些别的需要注意的事项？

目前 git 和语言包 版本 同步使用 1.62.3 版本

![image](https://github.com/opensumi/core/assets/13432873/f68d1ceb-29b8-4e19-b389-d664676b73b9)

预期稳定汉化

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by erha19** [comment]
@zhuzeyu22 你这边使用的 OpenSumi 版本是多少？好像修过类似问题

**Comment by erha19** [comment]
@zhuzeyu22 目前对于 i18n 的 languagePack，会在贡献点解析阶段提取做读取及提取写入，可能这块还是有一些时序问题，相关代码位置在 ：

https://github.com/opensumi/core/blob/ec4dea43c2b37548604364d721034b57dcdf931f/packages/extension/src/browser/vscode/contributes/localization.ts#L111

你也可以看看是不是这块的执行完成时间晚于 Git 插件的加载及展示

**Comment by zhuzeyu22** [comment]
@erha19    OpenSumi       2.24.5

**Comment by erha19** [comment]
@zhuzeyu22 看了一下相关修复在 https://github.com/opensumi/core/releases/tag/v2.24.1，这里应该还是有时序问题导致本地化不稳定

**Comment by zhuzeyu22** [comment]
@erha19  404 了

**Comment by zhuzeyu22** [comment]
@erha19  可能还是有问题， 我的 opensumi 版本是 2.24.5

**Comment by bytemain** [comment]
先更新到最新版再试试呗
