### ISSUE TITLE
[FEATURE] @opensumi/ide-dev-tool 没有发布到 NPM

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#3032]
我们实现了一些 opensumi 模块，参照官方包测试的写法写测试，发现 @opensumi/ide-dev-tool 没有发布到 npm 上，导致不能方便地进行 opensumi 模块的 mock

**Comment by bytemain** [comment]
是可以发布的，包括这个 `@opensumi/ide-dev-tool` 还有几个 cli 工具，比如说：

- `sumi rebuild`
https://github.com/opensumi/core/blob/main/package.json#L37
https://github.com/opensumi/core/blob/main/tools/dev-tool/cli/rebuild-native.js

**Comment by erha19** [comment]
@bytemain 这里更合适的应该是将这类针对 Injector 的 mock 方法移动至 @opensumi/di 这个库里面，实际上应该是是依赖例如 MockInjector 这些逻辑

**Comment by bytemain** [comment]
我想发布主要是因为可以不用每个项目自己写一遍 rebuild-native 了。

现在每一个项目都得自己写一遍这个脚本，自己更新一遍这个脚本
