### ISSUE TITLE
[Question] 控制台输出的右键菜单怎么注销掉？或者加展示条件

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3033]
请问一下，控制台输出的右键菜单怎么注销掉？或者增加某种展示条件，符合条件的情况下展示

**Comment by erha19** [comment]
@zhuzeyu22 你这里的控制台输出是指哪块界面？右键菜单目前都是可以通过 when 机制控制或卸载

**Comment by zhuzeyu22** [comment]
@erha19  指的是 channel 的 output ，主要是找不到右键菜单的 menu id ，应该是由菜单分组，但是不知道 id

**Comment by zhuzeyu22** [comment]
找到了，是 monaco editor 里面注册的，已解决。
