### ISSUE TITLE
当只打开一个自定义Editor，关闭的时候未能销毁Editor组件

### ISSUE THREAD

**Issue by xkaede** [opensumi/core#3034]
**描述你的问题（Describe the bug）**
当只打开一个自定义Editor，关闭的时候未能销毁Editor组件。
如果同时打开了其他Editor。关闭的时候能正确销毁。
 

**复现路径（To Reproduce）**
1、注册一个自定义Editor组件。
```
export const CustomEditorView: ReactEditorComponent = ()=>{
useEffect(() => {
    return () => {
       console.log(1);
    };
  }, []);
}
```
2、打开这个自定义组件（无其他Editor打开）。然后关闭。

**预期表现（Expected behavior）**
控制台输出：1

**环境信息（Environment）**

- OS: [Windows10]
- Browser: [electron]
- OpenSumi Version: [2.25.1]

翻了下代码，执行到https://github.com/opensumi/core/blob/1333888ee6bbcfe6d3c5c83f7d7b402ef567969b/packages/editor/src/browser/workbench-editor.service.ts#L1838
的时候。导致https://github.com/opensumi/core/blob/1333888ee6bbcfe6d3c5c83f7d7b402ef567969b/packages/editor/src/browser/editor.view.tsx#L362
发生重绘，但是此时
https://github.com/opensumi/core/blob/1333888ee6bbcfe6d3c5c83f7d7b402ef567969b/packages/editor/src/browser/workbench-editor.service.ts#L1844 还未移除当前关闭的resource。
同时上面移除掉resource后，没有再次触发重绘。

**Comment by erha19** [comment]
@xkaede 这个可能是由 Editor 的渲染策略影响的，目前有三种渲染策略，可以在注册编辑器组件时声明：
https://github.com/opensumi/core/blob/3d21ef2bb4f536953f23459a8ce2f16ec44281b4/packages/editor/src/browser/types.ts#L36-L49

相关类型声明如下：

```ts
/**
 * 默认值: ONE_PER_GROUP
 * ONE_PER_RESOURCE  - 每个资源只初始化一次组件
 * ONE_PER_GROUP     - 每个资源在同个 Group 下只初始化一次组件
 * ONE_PER_WORKBENCH - 整个渲染过程复用同一个组件，即组件仅会初始化一次
 */
export enum EditorComponentRenderMode {
  ONE_PER_RESOURCE = 1,
  ONE_PER_GROUP = 2,
  ONE_PER_WORKBENCH = 3,
}

```

**Comment by xkaede** [comment]
@erha19 我使用的是ONE_PER_RESOURCE，应该关闭的时候要销毁的吧？

**Comment by erha19** [comment]
> @erha19 我使用的是ONE_PER_RESOURCE，应该关闭的时候要销毁的吧？

@xkaede 这块需要看具体代码实现，可能考虑没做这层处理，如果有有修改思路的话可以提个 PR 上来，看代码可能更容易理解

**Comment by xkaede** [comment]
@erha19 好的

**Comment by xkaede** [comment]
@erha19 PR已提交
