### ISSUE TITLE
[Question] 我想在编辑的地方加个tab页显示表格，应该用布局插槽方法吗？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3035]
我想在这里（如下图）
![image](https://github.com/opensumi/core/assets/50567203/cd3ab811-6781-452b-a0c9-68ac415dd118)
显示如下效果（下图）
![image](https://github.com/opensumi/core/assets/50567203/6a98e126-cd4b-4340-a189-2c256734c1a8)
目前想到的是用动态注册方法  this.layoutService.collectTabbarComponent 但我写的并没有生效
![image](https://github.com/opensumi/core/assets/50567203/f6fc4100-aabc-4838-a1c7-7101f5831493)
请问，是否有更好的实现方法？如没有是否有可参考的在main位置使用自定义组件的实例，或帮忙看下我哪里写的不对？
十分感谢！！

**Comment by erha19** [comment]
这里可以使用自定义编辑器组件来实现， 可以参考这里的案例 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/add-welcome-content

**Comment by Augustjoe** [comment]
@erha19 感谢回答，功能已实现
