### ISSUE TITLE
[Question] 如何在自建的编辑窗口中支持sql语句的高亮和相关扩展？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3044]
**描述你的问题（Describe you question here）**
我已通过这个示例实现了创建编辑窗口的功能
https://github.com/opensumi/opensumi-module-samples/tree/main/modules/custom-editor-resource
但不知道如何设置让其支持sql语句的高亮和补全？

**Comment by erha19** [comment]
@Augustjoe https://github.com/opensumi/core/discussions/2396 可以看一下这个讨论

**Comment by Augustjoe** [comment]
![image](https://github.com/opensumi/core/assets/50567203/bc5f3b30-a15b-47ab-b2bc-4fe26fd0ac0f)
更改这里即可，已解决，感谢
