### ISSUE TITLE
[BUG] 多级目录下创建文件，目录层级展示异常

### ISSUE THREAD

**Issue by piLurk** [opensumi/core#3045]
在多级目录下创建文件，目录层级展示不对。如图（2.1 和 3.1 在一个层级了）
![img_v2_c43b826d-f23a-4d51-8723-6c9ab3115c8g](https://github.com/opensumi/core/assets/25706123/fd412315-1467-41cc-b0ab-c922357eb475)

**Comment by erha19** [comment]
@piLurk 你这边使用的 OpenSumi 版本是多少？我这边使用 2.26.* 版本，相关功能看起来是正常的，是否有稳定复现路径？

https://github.com/opensumi/core/assets/9823838/227a519d-7686-437c-b72a-28d50d033f52

**Comment by piLurk** [comment]
@erha19 明早我录个屏吧，我在最新版本可以复现。

**Comment by piLurk** [comment]
@erha19 看下这个，在 2 级目录新建文件时，3 级目录下的文件和 2 级目录下的文件同级了。 
https://github.com/opensumi/core/assets/25706123/b4c85280-ea49-436a-be66-afcc0f291a06

**Comment by erha19** [comment]
@piLurk 已经在 https://github.com/opensumi/core/pull/3053 解决，这个问题还是激活态的问题。

**Comment by piLurk** [comment]
@erha19 额，这个问题发现一个新的边界case。

![image](https://github.com/opensumi/core/assets/25706123/2f6fa269-3a18-46bb-b097-6fb5b37b8ea2)

目录结构
- 11
   - 22
      - 33
        - 3.1
        - 44
在 22 下新建文件时，3.1 这个文件的文件级别错误了
