### ISSUE TITLE
[Question] 如何动态改变顶部菜单插槽显示？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3046]
**描述你的问题（Describe you question here）**

![Uploading image.png…]()
想在如图位置加几个按钮，目前已经通过
https://github.com/opensumi/opensumi-module-samples/blob/main/modules/custom-toolbar/README.md
成功实现，但不知道怎么动态实现？

**Comment by Augustjoe** [comment]
![image](https://github.com/opensumi/core/assets/50567203/901f375e-f021-477b-9952-929e68ca9bc4)
补充图片

**Comment by erha19** [comment]
@Augustjoe 两种方式：

1. 自己通过 React 渲染的逻辑自行控制，可以结合一些服务/事件/mobx控制界面上的组件更新
2. 将该区域作为 Toolbar 区域，通过插件方式控制其上面的图标及展示 https://opensumi.com/zh/docs/extension/contributes/toolbar
