### ISSUE TITLE
[Question] 如何快速简单的禁用Terminal终端，感觉自己开发的业务代码在terminal那里相当于裸奔

### ISSUE THREAD

**Issue by justin2gh** [opensumi/core#3062]
如何快速简单的禁用Terminal终端，感觉自己开发的业务代码在terminal那里相当于裸奔

如何永久性的禁用终端，不能在IDE任何地方重新启动终端。

**Comment by justin2gh** [comment]
![image](https://github.com/opensumi/core/assets/35493268/960f57ac-c153-4177-a3a5-96f59c627802)
https://code.visualstudio.com/docs/terminal/advanced
opensumi有没有类似VScode这项terminal设置？

**Comment by justin2gh** [comment]
@erha19 帮忙看看，准备要开放给客户使用了，发现可以通过terminal看到所有业务代码。

**Comment by bytemain** [comment]
参考下这个文件，直接在 `LayoutConfig[SlotLocation.bottom].modules` 中移除 `'@opensumi/ide-terminal-next'` 即可。

[modules](https://github.com/opensumi/core/blob/e2ce5e466ecdada16237976cb9b413a12a537141/tools/electron/src/browser/layout.ts#L26)

**Comment by justin2gh** [comment]
@bytemain 能详细解释一下在那里修改么，我们的项目用的是[ide-startup]跑在docker上，不是electron。core里面的应该是改不了的，除非fork出来。

/workspace/.settings/settings.json

我们尝试修改setting，看看管不管用。
{
  "terminal.integrated.enablePersistentSessions": false,
  "terminal.integrated.allowWorkspaceShell": "disallow",
  "terminal.integrated.tabs.enabled": false,
  "terminal.integrated.tabs.hideCondition": true,
  "terminal.integrated.hideOnStartup": "always",
  "terminal.integrated.profiles.linux": {
    "sh": null,
    "bash": null,
    "zsh": null,
    "default": null
  }
}

**Comment by bytemain** [comment]
> 参考下这个文件，直接在 `LayoutConfig[SlotLocation.bottom].modules` 中移除 `'@opensumi/ide-terminal-next'` 即可。
> 
> [modules](https://github.com/opensumi/core/blob/e2ce5e466ecdada16237976cb9b413a12a537141/tools/electron/src/browser/layout.ts#L26)

这是一个配置项，文档在这：https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-view/#%E6%A6%82%E8%A7%88

![CleanShot 2023-09-14 at 16 35 46@2x](https://github.com/opensumi/core/assets/13938334/45a76d37-65e0-4ba7-b802-e6c6a5db230e)


ide-startup 里也有一样的内容，：
![CleanShot 2023-09-14 at 16 36 01@2x](https://github.com/opensumi/core/assets/13938334/a6d52092-201c-49ef-aec0-28b8ef46b529)

直接在 LayoutConfig[SlotLocation.bottom].modules 中移除 '@opensumi/ide-terminal-next' 即可。

**Comment by justin2gh** [comment]
@bytemain   非常感谢指导 ！ 在\ide-startup\src\browser\layout-config.ts 里面删除 '@opensumi/ide-terminal-next', 重新build可以了。


\ide-startup\src\browser\layout-config.ts

import { SlotLocation } from '@opensumi/ide-core-browser/lib/react-providers/slot';
import { defaultConfig } from '@opensumi/ide-main-layout/lib/browser/default-config';

export const layoutConfig = {
  ...defaultConfig,
  ...{
    [SlotLocation.top]: {
      modules: ['menu-bar-container', 'toolbar'],
      // modules: ['@opensumi/ide-menu-bar', 'toolbar'],
    },
    [SlotLocation.bottom]: {
          modules: ['@opensumi/ide-output', 'debug-console', '@opensumi/ide-markers'],
    },
  },
};
