### ISSUE TITLE
[BUG] 右键菜单删除文件只提供 “移入回收站”，没有提供如何从回收站恢复文件的选项，以及清空回收站的功能

### ISSUE THREAD

**Issue by justin2gh** [opensumi/core#3070]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/35493268/2f86dbcc-fa11-4918-b853-f014d7c54aa0)
![image](https://github.com/opensumi/core/assets/35493268/cefa32a5-1ba8-4f24-b089-ed4e7e6346fe)

**复现路径（To Reproduce）**
右键删除文件，移入回收站

**预期表现（Expected behavior）**

提供 从回收站恢复文件的选项，以及清空回收站的功能

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: chrome
- OpenSumi Version: 2.26.4

**Comment by justin2gh** [comment]
@bytemain 帮忙看看这个需求，如果没有删除撤销功能，是不是需要改成直接永久删除文件？

**Comment by erha19** [comment]
@justin2gh 这里更多考虑到了平台上的兼容性，如 Windows 下大部分文件是不允许“彻底删除”的，移入回收站不易出现权限问题，同时，IDE 删除文件操作属于高危操作，移入回收站可让用户可恢复。

如需彻底删除功能，可自行覆盖服务实现。
