### ISSUE TITLE
[Question] 请问如何管理自定义 Icon ？ 

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3075]
我再试用 registerResourceProvider 方法的时候希望加入自己的 Icon
里面的 icon 只能填入 string 指定类名，这里是需要我把 icon 转成 class 吗？我应该怎样操作？

**Comment by erha19** [comment]
@zhuzeyu22 你可以利用 iconService 基于一个资源路径生成 class，如：

```ts
const iconClass = this.iconService.fromIcon('', extension?.iconUrl, IconType.Background);
```
