### ISSUE TITLE
[Question] 想通过点击代码仓列表的方式打开远端代码文件，请问是否可行？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3076]
![image](https://github.com/opensumi/core/assets/50567203/b4d29e1f-5d16-4194-ba37-7278af15cdf6)
想实现点击下面的代码仓，上面的文件树就会更新为被点击的代码仓中的文件树，并可查看其中的代码，请问这个方案可以实现吗？
如可以实现，请问如何从远端重新获取文件树？
期待您的回答，感谢！！

**Comment by erha19** [comment]
@Augustjoe 可以实现，但需要你对文件树模块进行额外的拓展，例如在切换代码仓库时，更新文件树内容（重新初始化），基于现有的模块是无法直接实现的。

建议将文件树模块拷贝出来放到你自己的项目内进行改造，初始化文件树的逻辑在 https://github.com/opensumi/core/blob/8c05004215a20ecebb76a252857c5ec4158b3efd/packages/file-tree-next/src/browser/services/file-tree-model.service.ts#L296

**Comment by Augustjoe** [comment]
@erha19 感谢回答，有考虑添加重新初始化文件树的功能吗？ 感觉蛮实用的。

**Comment by Augustjoe** [comment]
@erha19 您能介绍介绍改造的思路吗？感觉有些难度

**Comment by erha19** [comment]
@Augustjoe 本身是具备重新初始化能力的，可以看一下代码理解一下，核心代码有两块：

1. 当仓库变化时，重新初始化 TreeModel，参考代码可以看下：

https://github.com/opensumi/core/blob/8c05004215a20ecebb76a252857c5ec4158b3efd/packages/file-tree-next/src/browser/services/file-tree-model.service.ts#L332-L337

像你这里纯前端情况下，主要需要更改一下 workspaceService 中的 workspace 指向，让 workspace 指向新的地址，另外，一些依赖 appConfig.workspaceDir 的地方也需要关联修改

2. 由文件树服务提供的 resolveChidren 获取文件树节点逻辑

https://github.com/opensumi/core/blob/4fc2ec7e4a3edb3f337d12f6848e6b455daedec2/packages/file-tree-next/src/browser/file-tree.service.ts

**Comment by Augustjoe** [comment]
@erha19  老师，如果我将文件树的区域先注销再打开，文件树会重新获取吗？

**Comment by Augustjoe** [comment]
![image](https://github.com/opensumi/core/assets/50567203/a889f33a-c0c3-4546-81cd-fbd2247ee857)
我想先注销文件树，点击时再重新生成文件树，请问可以实现吗？

**Comment by erha19** [comment]
@Augustjoe 通过注销来刷新的问题更多，不建议，一些基本实现方式可以参考这个 issue https://github.com/opensumi/core/issues/2437
