### ISSUE TITLE
[BUG] windows下electron版本终端面板使用ctrl+c无法结束当前正在执行的进程

### ISSUE THREAD

**Issue by shilin8805** [opensumi/core#3078]
**描述你的问题（Describe the bug）**

windows下electron版本终端面板使用ctrl+c无法结束当前正在执行的进程

**复现路径（To Reproduce）**

在终端面板使用ctrl+c命令

**预期表现（Expected behavior）**

能正常使用ctrl+c结束当前进程，同时不要影响复制等能力

**环境信息（Environment）**

- OS: [Windows10/Windows11]
- Browser: [electron]
- OpenSumi Version: [所有版本]

**Comment by erha19** [comment]
@shilin8805 这个看着像是跟终端复制的快捷键冲突导致的，可能要针对复制场景做更严格的条件限定，例如当存在文本选中时复制快捷键才会触发。

相关代码见：
```ts
https://github.com/opensumi/core/blob/18818dce9402e250c1a98443081985a4eda4875d/packages/terminal-next/src/browser/contribution/terminal.keybinding.ts#L24-L29
```

这里应该新增一个 TextSeleted 之类的 when 条件控制快捷键，目前应该是触发到拷贝的快捷键上面了

**Comment by shilin8805** [comment]
> @shilin8805 这个看着像是跟终端复制的快捷键冲突导致的，可能要针对复制场景做更严格的条件限定，例如当存在文本选中时复制快捷键才会触发。
> 
> 相关代码见：
> 
> ```ts
> https://github.com/opensumi/core/blob/18818dce9402e250c1a98443081985a4eda4875d/packages/terminal-next/src/browser/contribution/terminal.keybinding.ts#L24-L29
> ```
> 
> 这里应该新增一个 TextSeleted 之类的 when 条件控制快捷键，目前应该是触发到拷贝的快捷键上面了

好像不是这里，这个在windows上注册的快捷键是ctrl+shift+c，而且我把这段快捷键绑定注释掉了，ctrl+c也不能正常结束进程

**Comment by erha19** [comment]
@shilin8805 Windows 下可能与这个问题有关系 https://github.com/xtermjs/xterm.js/issues/1868，可能需要额外注册一个退出终端的快捷键才行

**Comment by shilin8805** [comment]
@erha19  #3100 提了个PR解决此问题
