### ISSUE TITLE
[Question] 在哪里可以看到当前vscode插件兼容版本？打算移植一些插件，预装到镜像里面

### ISSUE THREAD

**Issue by justin2gh** [opensumi/core#3079]
**描述你的问题（Describe you question here）**
在哪里可以看到当前vscode插件兼容版本？打算移植一些插件，预装到镜像里面，找些旧版兼容的插件，减少修改工作量。或者我是否可以从opensumi已经移植的插件下载下来，直接build到镜像里面。

**Comment by erha19** [comment]
@justin2gh 可以到这里找 https://marketplace.opentrs.cn/square

**Comment by erha19** [comment]
@justin2gh 这块目前没有教程，里面的应该基本都能用，但建议自行验证一下，所有插件都是下载下来放到框架的插件目录就能正常使用的，可以自行维护

**Comment by justin2gh** [comment]
@erha19 好的，感谢，我们测试看看
