### ISSUE TITLE
[Question] 为什么我单独编译 core 里面的模块的时候加入我的项目的时候运行后会提示  Uncaught Exception:  Error: Cannot find Provider of ExtensionModule 

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3087]
[Question] 为什么我单独编译 core 里面的模块的时候加入我的项目的时候运行后会提示  Uncaught Exception:  Error: Cannot find Provider of ExtensionModule ？

目前版本 2.24.5 ，我想修改 core 里面的某个包，然后 link 到 node_module 里面去做本地调试，为什么注入会有问题？

**Comment by erha19** [comment]
@zhuzeyu22 引用的 `@opensumi/di` 不是一个版本（资源）导致的
