### ISSUE TITLE
[BUG]  F2 快捷键「重命名符号」的 Tips 提示文案为 undefined

### ISSUE THREAD

**Issue by zmyiy** [opensumi/core#3089]
**描述你的问题（Describe the bug）**
<img width="744" alt="image" src="https://github.com/opensumi/core/assets/33682340/618e7bb1-6c60-4b93-815d-d88da879efa3">

**复现路径（To Reproduce）**
右键，点击 「重命名符号 F2」菜单选项

**预期表现（Expected behavior）**
![image](https://github.com/opensumi/core/assets/33682340/af297941-aada-46a7-90ab-507685f4caf3)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: 2.24.6-next-1691679000.0

**Comment by erha19** [comment]
@zmyiy 托管 monaco 默认快捷键的逻辑见：https://github.com/opensumi/core/blob/96477a517f05e47209e42aa3d53444baa4117b63/packages/monaco/src/browser/monaco.resolved-keybinding.ts

这里也可能是快捷键没注册，也有可能是 command 没注册

**Comment by zmyiy** [comment]
@erha19 有什么好的思路能给这个快捷键加回去吗？
Debug 看了下，调用的地方
![image](https://github.com/opensumi/core/assets/33682340/71cc02f2-5122-43ca-8c1f-361c24b320fa)
注册的地方实际上是把 acceptRenameInput 这个快捷键给过滤掉了，内置 defaultKeybindings 是有这个快捷键的。
![image](https://github.com/opensumi/core/assets/33682340/cd91bfa6-43d8-4d2f-9cd7-b909d03c24b4)

**Comment by erha19** [comment]
@zmyiy 这里确实是框架通过声明 `-{command}` 的方式卸载了的快捷键

<img width="860" alt="image" src="https://github.com/opensumi/core/assets/9823838/0df330de-5304-40fd-bf37-7548ee7118e5">

相关代码见：

https://github.com/opensumi/core/blob/2bf2b3bf06f3398ce3527b3b3cd0439119ccca5a/packages/monaco/src/browser/monaco.contribution.ts#L493-L494

这里可能需要对部分不允许用户修改的快捷键做个白名单处理（即用户就算修改了 `acceptRenameInput ` 命令快捷键，默认的快捷键依旧需要保留），否则后续用户如果在快捷键面板中修改了，同样也会造成问题
