### ISSUE TITLE
[BUG] 文件树中重命名目录后，状态没有同步到子文件，子文件无法打开

### ISSUE THREAD

**Issue by piLurk** [opensumi/core#3090]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/25706123/50dfaedb-d56b-4bfb-b530-2149e2c13c71)

**复现路径（To Reproduce）**
原始目录：
- test-1
   a.js

step1: 文件树点击 a.js 文件；

step2: 重命名 test-1 为 test-2；

step3: 文件树点击 a.js 文件；复现此问题

**Comment by piLurk** [comment]
@erha19 帮忙看下，这个问题看起来是 父级目录的路径信息变更没有同步到 子节点 和 workbench

**Comment by piLurk** [comment]
这个问题我本地用最新的 main 跑已经没问题了，是在哪个 PR 修复的呢？

**Comment by erha19** [comment]
@piLurk 你发现问题的版本是多少，可能得往前找一下版本看一下 https://github.com/opensumi/core/blob/main/CHANGELOG.md

**Comment by piLurk** [comment]
@erha19 更新一下，这个问题在最新版本也有问题，需要设置一下延迟时间，有比较大概率浮现。
![image](https://github.com/opensumi/core/assets/25706123/2d585c35-cfff-4f7d-a72a-3e8d760f1251)
