### ISSUE TITLE
TreeNode释放后未清理idToTreeNode和pathToTreeNode，会导致内存泄露问题。

### ISSUE THREAD

**Issue by xkaede** [opensumi/core#3096]
**描述你的问题（Describe the bug）**

TreeNode有两个静态字典idToTreeNode和pathToTreeNode会一直引用注册过的TreeNode。如果引用的TreeNode引用了其他业务对象。会导致该业务对象内存泄露。

**复现路径（To Reproduce）**
1、打开一个工作区。
2、关闭该工作区。

**预期表现（Expected behavior）**

关闭工作区后，对应的TreeNode的idToTreeNode和pathToTreeNode应该清除相关节点数据。

**环境信息（Environment）**

- OS: [Windows11]
- Browser: [electron]
- OpenSumi Version: [2.26.8]

**Comment by erha19** [comment]
@xkaede 你这里关闭工作区的场景是？一般工作区应该是一直跟随用户使用的

**Comment by xkaede** [comment]
我的实际场景是用到了RecycleTree，功能类似Outline，会随着当前上下文实时刷新。用工作区只是举例。其实系统内的Outline也存在内存泄露的问题。

**Comment by erha19** [comment]
@xkaede 翻了一下代码，确实是这样的，有一些历史原因忘记修正了，实际上可以在 TreeNode 类内的 dispose 里清理掉自身的引用，有兴趣的话你也可以提个 PR 优化一下，或这周我找个时间修复一下~

**Comment by xkaede** [comment]
我试一下吧，我看RecycleTree牵涉到的地方挺多的，当初可能是为了优化性能存储了相关节点的数据。怕修出问题，到时候麻烦帮忙仔细审核一下。

**Comment by xkaede** [comment]
@erha19 PR已提，TreeNode.pathToId牵涉地方太多，没有清理。使用到Tree的相关功能我看了下好多地方，比如Outline都缓存了Tree节点，不知道为何。加上相关功能不熟悉就没有调用Tree.Dispose方法清理。
file-tree.service里处理了下，当工作区切换、FileTreeService释放的时候清理了一下根节点。

**Comment by erha19** [comment]
@xkaede  pathToId 主要用于在二次渲染的时候，保障相同的节点路径使用相同的 ID 进行渲染，从而保证差量的 React 节点渲染，有点利用 React 渲染逻辑的
