### ISSUE TITLE
[FEATURE] 支持 Remote 模式连接远程容器

### ISSUE THREAD

**Issue by yantze** [opensumi/core#310]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

一个实际的场景，比如 OpenSumi 桌面端要连接远程的容器，桌面端所有的文件和命令行操作都是在操作远程容器的内容。

**描述你预期的功能表现（Describe the solution you'd like）**
- 支持在集成 OpenSumi 的时候，可以配置支持访问 OpenSumi 远端的容器
- 在 Remote 模式下：
  - 命令行使用远端命令行
  - 停止本地插件进程的创建和使用

**描述你考虑过的替代方案（Describe alternatives you've considered）**
未来可以考虑使用 ssh 连接，但这是更加底层的实现。

**补充信息（Additional context）**

- [x] 支持 Remote 模式 #311 
- [ ] 支持集成的时候可以配置
- [ ] 禁用本地的 Server 进程
- [ ] 更好的入口实现打开 Remote 模式

**Comment by Aaaaash** [comment]
是 IDE 的 Server  进程 不是插件进程...

**Comment by yantze** [comment]
> 是 IDE 的 Server 进程 不是插件进程...

好了
