### ISSUE TITLE
[BUG] 多语言模块有缺陷

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3105]
我使用 registerLocalizationBundle 手动注册多语言文本，将 中文插件包中的多语言信息注册到 opensumi 中，以期望解决偶现的多语言失败的问题，但是现在的现象是部分 翻译成功，部分翻译失败。

目前针对的是 git 插件的中文语言包

**环境信息（Environment）**

- OS: windows11
- Browser: electron
- OpenSumi Version: 2.24.5

**Comment by erha19** [comment]
Git 高版本插件使用的是 l10n API 进行的国际化，检查一下插件版本 ？

**Comment by zhuzeyu22** [comment]
> Git 高版本插件使用的是 l10n API 进行的国际化，检查一下插件版本 ？

使用的是 1.62.3 vscode 的内置 git 插件。版本看上去似乎没有问题

**Comment by zhuzeyu22** [comment]
> Git 高版本插件使用的是 l10n API 进行的国际化，检查一下插件版本 ？

使用的 vscode-nls 做的国际化

**Comment by erha19** [comment]
@zhuzeyu22 这里估计还是有时序问题没处理好，可以调试看看：
https://github.com/opensumi/core/blob/83531dc155a58c3a5986bfb543e8238f66d1922f/packages/extension/src/browser/extension.service.ts#L227

另外，目前 main 版本已经支持了 l10n 能力，本周会发布 2.27.0，后续可以试试高版本的 Git 插件

**Comment by shilin8805** [comment]
@erha19 1.74.0之后的git插件才支持l10n，这个版本插件目前2.27.0的opensumi也不支持。多语言时序的问题还是没完全解决，这个问题困扰快半年时间了，求大佬出马看一下吧~

**Comment by shilin8805** [comment]
@erha19 复现步骤，安装git1.70.2版本，语言包vscode-language-pack-zh-hans1.63.0版本，启动electron项目，第一次进入多语言是正常的，reload窗口，多语言会时不时的失效
<img width="1000" alt="image" src="https://github.com/opensumi/core/assets/3340210/7a0e32d3-37da-4586-b505-d21d51de3bc2">

**Comment by erha19** [comment]
@shilin8805 稍晚时候我看一下什么原因 ~ 大概得下周了

**Comment by shilin8805** [comment]
> @shilin8805 稍晚时候我看一下什么原因 ~ 大概得下周了

好的，感谢~

**Comment by erha19** [comment]
@shilin8805 @zhuzeyu22 应该是修复了，就是一个执行上的时序问题，可以试试这里的版本 https://github.com/opensumi/core/pull/3133 .
