### ISSUE TITLE
[BUG] 出现了两个小问题，不是很好定位，希望可以一起分析一下

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3110]
[1011/150201.017:ERROR:registration_protocol_win.cc(106)] CreateFile: 系统找不到指定的文件
。 (0x2)
[node][1011/150201.119:ERROR:registration_protocol_win.cc(106)] CreateFile: 系统找不到指定
的文件。 (0x2)
ation_protocol_win.cc(106)] CreateFile: 系统找不到指定的文件。 (0x2)                   itit.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by bytemain** [comment]
这看起来是 Electron 自己的报错，感觉是无关紧要的
