### ISSUE TITLE
左侧文件树右键菜单时，如何区分选中的是文件还是文件夹？并获取其路径 

### ISSUE THREAD

**Issue by sokach297** [opensumi/core#3112]
**描述你的问题（Describe you question here）**

**Comment by erha19** [comment]
如果是模块开发方式，可以参考 https://github.com/opensumi/core/blob/ea11d5e8905883ddedd872bc8b9e7e2978783303/packages/file-tree-next/src/browser/file-tree-contribution.ts#L566 , 通过 FileTreeModelService 去进行判断 @sokach297
