### ISSUE TITLE
[Question] 请问下，有支持文件在服务器上的方式吗

### ISSUE THREAD

**Issue by GregoryZQ** [opensumi/core#3114]
**描述你的问题（Describe you question here）**
目前，看到只支持打开git上的文件，希望能讲解一下怎么能支持打开文件在服务器上

**Comment by erha19** [comment]
@GregoryZQ https://opensumi.com/zh/docs/integrate/quick-start/lite#%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1 看一下这个文档
