### ISSUE TITLE
[BUG] 目录树无法搜索折叠起来的文件名

### ISSUE THREAD

**Issue by MilkWangStudio** [opensumi/core#3115]
**描述你的问题（Describe the bug）**
FileExplorer控件的目录树进行搜索时，只能搜索展开的目录下内容，对于被折叠起来的目录，无法通过文件名搜索其中的文件。

**复现路径（To Reproduce）**
<img width="352" alt="image" src="https://github.com/opensumi/core/assets/15866249/2c184f8f-3f4a-48aa-ae93-34d7fff866f8">

**预期表现（Expected behavior）**
搜索到折叠目录下的文件后，自动展开目录并定位到该文件。
<img width="298" alt="image" src="https://github.com/opensumi/core/assets/15866249/fdc305a9-4f33-44f1-b45a-e58a6f619150">

**环境信息（Environment）**
Opensumi版本：2.26.5
操作系统：Mac 13.0.1
浏览器：Chrome 117.0.5938.132

**Comment by erha19** [comment]
这里的功能并非搜索，而是筛选，仅能筛选展开的目录内容，这个是从性能上的考虑，无法做到搜索

**Comment by MilkWangStudio** [comment]
嗯嗯，了解，感谢回复~
