### ISSUE TITLE
[BUG] DebugLog类yellow 代码错误

### ISSUE THREAD

**Issue by djkloop** [opensumi/core#3116]
**描述你的问题（Describe the bug）**

```shell
yellow: '\x1b3[33m',
```

https://github.com/opensumi/core/blob/41a3427032f0e5b60a4db03f119ff9617e84390c/packages/core-common/src/log.ts#L234C27-L234C27
**复现路径（To Reproduce）**

无

**预期表现（Expected behavior）**
```sh
yellow: '\x1[33m',
```
**环境信息（Environment）**

- OS: all
- Browser: all
- OpenSumi Version: latest

**Comment by bytemain** [comment]
感谢反馈，看起来是一个很方便的修改，你有兴趣给我们提一个 PR 吗？

**Comment by djkloop** [comment]
@bytemain pr有了
