### ISSUE TITLE
[BUG] opensumi 启动报错，闪退

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3124]
![image](https://github.com/opensumi/core/assets/13432873/ff2909da-ad3c-443b-9447-8e5067c55a07)

- OS: [Windows11]
- Browser: [electron]
- OpenSumi Version: [2.24.5]

**Comment by erha19** [comment]
这个问题之前遇到过类似问题，可以自行排查一下 https://github.com/electron/electron/issues/35801

可能是错误的 Electron 版本中使用部分原生 API 导致的闪退

**Comment by zhuzeyu22** [comment]
> 这个问题之前遇到过类似问题，可以自行排查一下 [electron/electron#35801](https://github.com/electron/electron/issues/35801)
> 
> 可能是错误的 Electron 版本中使用部分原生 API 导致的闪退

目前使用的是
 node/14.17.6/x64 (Fermium) [current] [default] 

    "electron": "18.3.4",
    "electron-builder": "^23.6.0",
    "electron-devtools-installer": "^3.2.0",
    "electron-rebuild": "^3.2.9",

**Comment by zhuzeyu22** [comment]
> 这个问题之前遇到过类似问题，可以自行排查一下 [electron/electron#35801](https://github.com/electron/electron/issues/35801)
> 
> 可能是错误的 Electron 版本中使用部分原生 API 导致的闪退

补充，该编译打包后的版本在大部分计算机上正常运行，有问题的计算机型号为：
acer暗影骑士擎

**Comment by zhuzeyu22** [comment]
> @zhuzeyu22 单一机型的问题可能就是系统级别的问题，可以尝试升级一下 Electron 版本看是否能解决

是的，似乎是系统级别的问题，同型号机型其他的设备是正常使用的，可能是系统环境受到了影响，正在尝试清理系统环境。

**Comment by zhuzeyu22** [comment]
> @zhuzeyu22 单一机型的问题可能就是系统级别的问题，可以尝试升级一下 Electron 版本看是否能解决

尝试在 electron 层使用

**Comment by zhuzeyu22** [comment]
使用 --disable-sandox 临时解决该问题
