### ISSUE TITLE
[FEATURE] 希望纯前端版本能提供一个重新从远端代码仓获取代码的方法

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3135]
**如果你的需求与问题相关**
希望纯前端版本能提供一个重新从远端代码仓获取代码的方法，或者想看其他远端代码仓不用更改地址栏刷新的方法

现在两个人都在操作同一代码仓，一个人刚更新了代码到远端，另一个人想查看刚刚提交的代码，只能刷新整个页面

**描述你预期的功能表现（Describe the solution you'd like）**
希望提供一个可以调用的方法，调用后重新从远端拉下代码，不用刷新页面

**Comment by erha19** [comment]
暂时不支持，这类业务形态建议自定义视图方式自行实现 Tree 相关功能。
