### ISSUE TITLE
[Question] 如何去掉纯前端版离开页面前的提示弹窗

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3139]
![1698303666215_A6B519D9-EF5F-43f6-BAB7-A9CDCC18DA6A](https://github.com/opensumi/core/assets/50567203/e7381518-6e5b-409d-b5d7-72eca3bc63cd)

如图，去掉这个弹窗

**Comment by erha19** [comment]
@Augustjoe 可以通过默认配置关闭这个弹窗，如 :

```
'application.confirmExit': 'never'
```

自定义配置可见文档: [自定义配置](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config)

**Comment by Augustjoe** [comment]
@erha19  不可以用编程的方式关闭吗？

**Comment by erha19** [comment]
> @erha19 不可以用编程的方式关闭吗？

这个是集成配置，纯前端只能通过集成时控制

**Comment by Augustjoe** [comment]
@erha19 好的，感谢老师回答
