### ISSUE TITLE
[Question] 想更换侧边栏的icon，请问如何更换？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3145]
![image](https://github.com/opensumi/core/assets/50567203/c070fb97-e8d7-4282-89ac-b3b917cd4d5f)
如图想更换框里的图标，但查看collectTabbarComponent中options参数的类型没有找到可自定义的参数。
![image](https://github.com/opensumi/core/assets/50567203/f0098872-da87-482f-9556-427bcab7ee08)
另请问如何将“资源管理器”替换为其他文字？

**Comment by erha19** [comment]
@Augustjoe 可以参考这里 https://github.com/opensumi/opensumi-module-samples/blob/88c8702e5cb80ed6d07b401d47dbf124ddf71741/modules/terminal-env/browser/terminal-env.contribution.ts#L48-L55
