### ISSUE TITLE
[Question] 安装问题

### ISSUE THREAD

**Issue by gaoshengqing21** [opensumi/core#3151]
**
➤ YN0009: │ nsfw@npm:2.2.0 couldn't be built successfully (exit code 7, logs can be found here: C:\Users\AppData\Local\Temp\xfs-54f6c9e0\build.log)
➤ YN0009: │ spdlog@npm:0.9.0 couldn't be built successfully (exit code 7, logs can be found here: C:\Users\AppData\Local\Temp\xfs-eb206726\build.log)
➤ YN0009: │ node-pty@npm:0.11.0-beta19 [7bbc6] couldn't be built successfully (exit code 7, logs can be found here: C:\Users\AppData\Local\Temp\xfs-138e8ddc\build.log)
**
log 里面提示
# This file contains the result of Yarn building a package (spdlog@npm:0.9.0)
# Script code: node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@13.14.0 | win32 | x64
gyp info find Python using Python version 3.8.0 found at "D:\python3.8\python.exe"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn UNKNOWN
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:405:11)
gyp ERR! stack     at spawn (child_process.js:548:9)
gyp ERR! stack     at execFile (child_process.js:232:17)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2017OrNewer (D:\gitClone\core\node_modules\node-gyp\lib\find-visualstudio.js:141:17)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio (D:\core\node_modules\node-gyp\lib\find-visualstudio.js:63:10)
gyp ERR! stack     at findVisualStudio (D:\core\node_modules\node-gyp\lib\find-visualstudio.js:13:10)
gyp ERR! stack     at D:\gitClone\core\node_modules\node-gyp\lib\configure.js:87:9
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:23)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\core\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\gitClone\core\node_modules\spdlog
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

可以帮忙看下为什么一直安装失败吗，我这边的配置
windows 11
node 13.14.0  (node版本有尝试切换14.12.3  16.0.0 18.18.0）
node-gyp 9.3.1
yarn 3.2.4
python 3.8.0
开发工具 ： vscode

启动项目

D:\core>yarn run start
[]
{ _: [ 'rebuild' ] }
rebuilding native for node version v13.14.0
rebuilding node-pty: 0.11.0-beta19 for arch x64
cache dir C:\Users\.sumi-dev\opensumi_build_cache\node-v13.14.0-x64\node-pty-0.11.0-beta19
running command node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@13.14.0 | win32 | x64
gyp info find Python using Python version 3.8.0 found at "D:\python3.8\python.exe"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn UNKNOWN
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:405:11)
gyp ERR! stack     at spawn (child_process.js:548:9)
gyp ERR! stack     at execFile (child_process.js:232:17)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2017OrNewer (D:\core\node_modules\node-gyp\lib\find-visualstudio.js:141:17)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio (D:\gitClone\core\node_modules\node-gyp\lib\find-visualstudio.js:63:10)
gyp ERR! stack     at findVisualStudio (D:\gitClone\core\node_modules\node-gyp\lib\find-visualstudio.js:13:10)
gyp ERR! stack     at D:\gitClone\core\node_modules\node-gyp\lib\configure.js:87:9
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:23)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\core\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\gitClone\core\node_modules\node-pty
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp rebuild
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at rebuildModule (D:\gitClone\core\tools\dev-tool\cli\rebuild-native.js:64:5)
    at D:\gitClone\core\tools\dev-tool\cli\rebuild-native.js:84:5
    at Array.forEach (<anonymous>)
    at module.exports.rebuild (D:\gitClone\core\tools\dev-tool\cli\rebuild-native.js:83:17)
    at Object.handler (D:\gitClone\core\tools\dev-tool\cli\index.js:11:5)
    at Commander.run (D:\gitClone\core\tools\dev-tool\cli\commander\index.js:17:17)
    at Object.<anonymous> (D:\gitClone\core\tools\dev-tool\cli\index.js:16:11)
    at Module._compile (internal/modules/cjs/loader.js:1118:30) {
  status: 7,
  signal: null,
  output: [ null, null, null ],
  pid: 17064,
  stdout: null,
  stderr: null
}

**Comment by erha19** [comment]
@gaoshengqing21 这里看着是系统环境上存在问题，可以看一下 [开发环境准备](https://opensumi.com/zh/docs/develop/how-to-contribute#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87) 文档。
