### ISSUE TITLE
[Question] 现阶段不支持antd 5.0 吗？将来有更新的计划吗？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3153]
![image](https://github.com/opensumi/core/assets/50567203/fbc73c95-5b4b-4daa-b206-f77f6d7ac884)
更新到antd 5.11 会报错，如图

**Comment by erha19** [comment]
@Augustjoe 框架本身并不依赖 AntD，这里的问题是由于 Antd 4 和 Antd5 的集成差异导致的，建议看看文档解决，目前已知的目前的 OpenSumi Antd 主题包是不支持 Antd5 的
