### ISSUE TITLE
[BUG] Python 调试报错

### ISSUE THREAD

**Issue by zmyiy** [opensumi/core#3155]
**描述你的问题（Describe the bug）**
此版本下，智能提示与 lint 都正常，但是 debug 调试会提示报错：`The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.` 
- python 插件版本：[2020.3.71113](https://marketplace.opentrs.cn/extension/635f690d032f28bd715ae3f6)

- 错误堆栈
```
Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.
at /demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:49625
at Array.forEach (<anonymous>)
at e (/demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:49188)
at Object.t.plan (/demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:49703)
at /demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:46360
at e._get (/demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:46269)
at e.get (/demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:44980)
at a.get (/demo/extensions/python/out/client/debugger/debugAdapter/main.js:16:169479)
at new b (/demo/extensions/python/out/client/debugger/debugAdapter/main.js:1:230351)
```

**复现路径（To Reproduce）**
用 opensumi IDebugSessionManager.start 进行调试

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by zmyiy** [comment]
搜了下这个[错误](https://github.com/coder/code-server/issues/1821)，需要升级 2020.8.xxx 版本才可以，但是经过测试最多只能升级到 2020.6.xxx 以下，超过智能提示与 lint 都无法运行。

**Comment by erha19** [comment]
我来看一下这个问题

**Comment by erha19** [comment]
@zhuzeyu22 这主要受 monaco 版本及插件 API 的适配有关系，需要具体问题具体看了，近期事情比较多，会逐步升一把 VS Code 内置插件，不过没那么快。

**Comment by erha19** [comment]
@zhuzeyu22 @zmyiy  尝试了 2023 最新版本/ 2021 版本及 2020.10 版本，目前看下来适配 2020.10 的成本相对较低，插件内确实存在许多需要兼容的老逻辑，如 `workbench.editorAssociations` 在不同版本 VS Code 中存在不同默认值导致的问题及 Proposal API 等。

目前 2020.10 版本使用时会出现 crash 问题，原因是在插件激活过程中会发送一个较大的消息导致通信层奔溃，相关问题可参考这里展示的问题：
https://github.com/opensumi/core/issues/3119#issuecomment-1774872326

待通信层改造能比较合理的解决该问题，否则需要对 Python 插件进行源码解读及修改，成本更高且不具备延续性。

**Comment by xkaede** [comment]
试了下Opensumi-V3.3.0版本最高只能跑到[2019.11.1](https://open-vsx.org/extension/ms-python/python/2019.11.1)，跑2020.6.1以上插件就会报“JavaScript heap out of memory”,不知道有没有计划解决这个问题。 @erha19

**Comment by hacke2** [comment]
pylance 是闭源插件，根据协议只能在 VSCode下使用，可以参照 https://github.com/opensumi/core/pull/3600 ，我们适配了最近版本的开源平替插件

vscode-python 2024.5.11021008
pyright: 1.1.360
python-debuger: 2024.5.11001012

**Comment by xkaede** [comment]
@hacke2 试了下pyright: 1.1.360，在输出报这个问题“The language client requires VS Code version ^1.86.0 but received version 1.68.0”

**Comment by xkaede** [comment]
> @hacke2 试了下pyright: 1.1.360，在输出报这个问题“The language client requires VS Code version ^1.86.0 but received version 1.68.0”

抱歉，看了下可以自己定义AppConfig. customVSCodeEngineVersion.已经没有问题了。
