### ISSUE TITLE
[FEATURE] 希望支持VSCode插件以支持DX IDE的后续功能

### ISSUE THREAD

**Issue by guanyusgy** [opensumi/core#3158]
需要通过以下插件实现基于LLDB的调试功能
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

插件1:ios-debug version:0.4.0
插件2:CodeLLDB（依赖） version：1.10.0

使用场景和demo可以参考ios-debug文档里的使用说明

**Comment by guanyusgy** [comment]
插件市场的对应插件地址:
https://marketplace.visualstudio.com/items?itemName=nisargjhaveri.ios-debug
https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb

**Comment by erha19** [comment]
@guanyusgy 简单修复在本地将这个插件跑起来了，这里如果要在特定 IDE 使用，还有以下两块事情需要完成，涉及到改造插件的部分：

1. 插件内使用了大量未签名的脚本，用户需要在使用时手动通过 “打开 -> 确认” 方式绕开鉴权
2. 插件依赖一个基于系统版本的插件，分为 x64 及 arm64 版本，动态下载，这部分是针对 VS Code 的定向适配，需要改造

问题 2 会有另外两个问题：

1. 动态下载的插件为 .vsix , 在 OpenSumi IDE 中是无法直接使用的，需要解压及重新构建
2. GitHub Release 的下载地址无法正常访问导致下载失败

改造意见：参考其插件源码重新编写 codelldb-aarch64-darwin.vsix 资源下载安装流程（定向适配），解决脚本鉴权问题，否则使用上体验不会太好
