### ISSUE TITLE
[BUG] 问题面板样式

### ISSUE THREAD

**Issue by chaoyue1217** [opensumi/core#3165]
**markers模块样式问题**

当文件路径过长或者屏幕过小时，问题面板的标题会换行
![image](https://github.com/opensumi/core/assets/18662948/93cd376f-e858-4195-8d41-4b31e11141ee)

需要在 [此处](https://github.com/opensumi/core/blob/main/packages/markers/src/browser/tree/tree-node.module.less#L17)添加样式
```css
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
```

**Comment by erha19** [comment]
@chaoyue1217 感谢反馈，方便的话可以修改后提交个 PR 上来，或者我们后续处理一下 ~
