### ISSUE TITLE
同一个资源文件，注册类型是自定义组件，不是monaco editor ，如何实现拆分后操作同步更新 

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#3210]
![image](https://github.com/opensumi/core/assets/23164065/4ca3969b-fe19-4eaa-89ba-4c1f57376fdb)
如图 oneof.prot文件是是一个自定义组件，右侧操作删除掉部分内容，左侧没有同步更新，如何做到同步更新？还有注册的菜单命令只在一个组件内部生效，另一个组件内部的注册命令不可用

**Comment by erha19** [comment]
@767746649zyy 这里你可以直接基于 React 进行视图更新，可以在服务层通过事件去通知前台更新。

注册的菜单只在一个组件内部生效这个现象可以的话整一个可复现案例，还没遇到过这种情况。

**Comment by 767746649zyy** [comment]
注册的菜单因为是在组件内注册的，不是在贡献点里注册的，正确的做法是在哪里注册这个有规则吗

**Comment by erha19** [comment]
@767746649zyy 正确的做法是在贡献点做注册，这样会少许多时序问题，同时不建议在每次组件渲染注册，这样会出现很多冗余命令，建议做一下复用。

**Comment by 767746649zyy** [comment]
贡献点里注册怎么和组件通信呢

**Comment by erha19** [comment]
https://github.com/opensumi/core/blob/00b850abd21855138981a810b4eb07b89e05c583/packages/editor/src/browser/types.ts#L48 这里注册的菜单只在一个组件内生效，可能是受注册时候的 renderMode 影响，也可以一起看一下。

贡献点注册菜单可以看一下官方文档 [自定义菜单](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-menu)

**Comment by chaoyue1217** [comment]
@erha19 您好，在贡献点里注册的命令，如果想要去操作React组件状态的修改，像setState这种的，除了通过EventBus去通知React组件，还有别的方式吗

**Comment by chaoyue1217** [comment]
@erha19 您好，在贡献点里注册的命令，如果想要去操作React组件状态的修改，像setState这种的，除了通过EventBus去通知React组件，还有别的方式吗
