### ISSUE TITLE
[BUG] 不支持 python 插件 debug

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3211]
使用 python 插件 debug 运行时出现异常

![image](https://github.com/opensumi/core/assets/13432873/3635098f-15f5-49fb-bdf1-86dbe88f6dd1)

**环境信息（Environment）**

- OS: [e.g. Windows11]
- Browser: [e.g.  electron]
- OpenSumi Version: [2.24.5]

**Comment by erha19** [comment]
duplicated #3155
