### ISSUE TITLE
[Question] 纯前端版是否可以做成像本地vscode提交代码一样，在本地保存更改文件记录，最后通过git命令提交？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3215]
已经实现的效果是实时提交，用户保存文件后直接调用代码仓接口，同步更改远端仓库。现在客户想实现像本地的提交方式，通过git  commit，git push这种git命令。用户的user.name和user.email可以找地方配置保存。

**Comment by AhkunTa** [comment]
- 纯前端下没有终端能力， 无法完全实现 git 的所有功能
- 推荐通过SCM贡献点实现源代码管理的能力 具体贡献点可以参考 [SCM](https://code.visualstudio.com/api/references/vscode-api#scm) ，示例 [Codeblitz](https://github.com/opensumi/codeblitz)

https://github.com/opensumi/ide-startup-lite/issues/64

**Comment by Augustjoe** [comment]
@AhkunTa 收到，感谢回答
