### ISSUE TITLE
[BUG] 文件树组件缺陷

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3220]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/13432873/d07ed0ec-f8f2-4171-88fb-2b90781f4dc4)

点击文件的时候，抛出异常

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [Windows11]
- Browser: [electron]
- OpenSumi Version: [2.27.1]

**Comment by erha19** [comment]
@zhuzeyu22 有没有复现路径？必现问题吗？

**Comment by zhuzeyu22** [comment]
> @zhuzeyu22 有没有复现路径？必现问题吗？

打开项目，点击文件必现。

**Comment by zhuzeyu22** [comment]
@erha19 确认一下 npm 仓库中上传的是否是正确版本的包，
file-tree-model.service.js:60 Uncaught TypeError: this.selectedDecoration.clearAppliedTarget is not a function

我在 node_module 里面也没找到这个 function
