### ISSUE TITLE
[Question] 如何阻断文件的保存过程？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3223]
客户有一个需求，要求所有保存的代码需要通过一个质量校验，没通过的不许保存，我尝试了下，除了throw 一个error外，没法阻止保存，updataFile和writeFile方法都做了阻断还是不行，请问在哪里可以阻断保存？

**Comment by Ricbet** [comment]
@Augustjoe 参考这个 issue 的回复 https://github.com/opensumi/core/issues/2891

**Comment by erha19** [comment]
@Augustjoe 如果是行为控制，可以考虑覆盖相关服务进行自定义实现，如覆盖 workbenchService 覆盖相关逻辑

**Comment by Augustjoe** [comment]
@erha19 老师，请问要覆盖哪项服务？现在的客户的需求是，未通过校验的代码不进行保存，文件名右侧的未保存提示不消失
![image](https://github.com/opensumi/core/assets/50567203/d0fe97ca-72e6-4b6e-b5be-7660d27cea23)
如图的提示，用户还可以继续更改

**Comment by erha19** [comment]
大概在这个文件 https://github.com/opensumi/core/blob/00b850abd21855138981a810b4eb07b89e05c583/packages/editor/src/browser/workbench-editor.service.ts#L2180
