### ISSUE TITLE
[Question] 是否有不通过插件的方法实现代码提示？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3238]
![image](https://github.com/opensumi/core/assets/50567203/ba95c283-d57f-43ab-af64-512aa70560bd)
如图想在点后提示该数据库下的相关表名，现在表名的数据已经拿到了，不知道怎么显示？
最好能像代码提示那样展示 如图
![image](https://github.com/opensumi/core/assets/50567203/2bd5df38-b181-4785-956e-c0c39d98a78d)
有其他方法也可以
期待您的回答

**Comment by erha19** [comment]
@Augustjoe 可以尝试一下直接通过 monaco 实例去注册语言服务
```ts
monaco.languages.registerCompletionItemProvider('yourLanguageId', {
    provideCompletionItems: function(model, position) {
        // return your completion items here
        return {
            suggestions: [
                {
                    label: 'MyCompletionItem',
                    kind: monaco.languages.CompletionItemKind.Text,
                    insertText: 'MyCompletionItem',
                    documentation: 'This is a completion item'
                }
            ]
        };
    }
});
```

这些内容都可以通过 monaco 文档或 ChatGPT 获取到相关内容

**Comment by Augustjoe** [comment]
> @Augustjoe 可以尝试一下直接通过 monaco 实例去注册语言服务
> 
> ```ts
> monaco.languages.registerCompletionItemProvider('yourLanguageId', {
>     provideCompletionItems: function(model, position) {
>         // return your completion items here
>         return {
>             suggestions: [
>                 {
>                     label: 'MyCompletionItem',
>                     kind: monaco.languages.CompletionItemKind.Text,
>                     insertText: 'MyCompletionItem',
>                     documentation: 'This is a completion item'
>                 }
>             ]
>         };
>     }
> });
> ```
> 
> 这些内容都可以通过 monaco 文档或 ChatGPT 获取到相关内容

![image](https://github.com/opensumi/core/assets/50567203/0d067734-99eb-43f6-a5b6-03887998d7a6)
是这样获取吗？

**Comment by Augustjoe** [comment]
@erha19  老师请问是这么获取当前编辑的monaco 吗？（下图）
![image](https://github.com/opensumi/core/assets/50567203/889bb444-5a86-4527-a3cc-b23e4c69c0b1)

**Comment by Augustjoe** [comment]
@erha19 已实现，多谢老师！
![image](https://github.com/opensumi/core/assets/50567203/e1442722-ae35-4e3b-a778-443f7d4c0a59)
