### ISSUE TITLE
[Question] 请问打开文件的标签是否可以自定义？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3242]
![image](https://github.com/opensumi/core/assets/50567203/13835073-e739-42d0-8e5e-eff1fccc2e52)
如图第一个是打开文件的标签，第二个是自建的编辑区域，现在客户要求用背景色区分两钟编辑模式，并要求后一种可以重命名。
![image](https://github.com/opensumi/core/assets/50567203/fef1e71c-fc65-4d32-affc-dc1891c06e42)
我尝试了下，上图的name只接受string类型的值，请问客户要求可以实现吗？

**Comment by erha19** [comment]
支持不了，这类需求需要自行覆盖模块进行自定义实现。

**Comment by Augustjoe** [comment]
@erha19 可以说下具体是哪个模块吗？ 谢谢
