### ISSUE TITLE
[Question] 纯前端，用户调整设置里的选项后，代码库中会自动出现一个setting.json文件，请问相关的逻辑是怎样的？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3249]
因为现在的IDE已经对接了代码仓的接口，用户调整设置后会直接在用户正在编辑的代码仓中创建一个setting.json文件，这肯定是不被允许的，想问下相关代码在哪里？如何调整为从特定接口获取设置文件？如何调整默认的设置内容（如编辑器中的字号）？
![image](https://github.com/opensumi/core/assets/50567203/12e7e656-d84b-4cb7-8227-cb54c02d571c)

**Comment by AhkunTa** [comment]
可以配置preference  `files.exclude` 在文件树里隐藏文件 
获取首选项的配置以及修改配置 可以参考 [PreferenceService](https://github.com/opensumi/core/blob/main/packages/core-browser/src/preferences/types.ts)

**Comment by Augustjoe** [comment]
@AhkunTa 您能详细说说 preference files.exclude 怎么配置吗？

**Comment by erha19** [comment]
@AhkunTa 用户设置主要分为两种，工作区设置与用户配置，工作区配置在项目目录下的 `.sumi/settings.json` , 而用户配置在 `~/.sumi/settings.json` 内，纯前端内，你可以托管这部分配置存储到 LocalStorage 或远程服务中进行存储，实际上就是一些 key-value 值。

**Comment by Augustjoe** [comment]
@erha19 十分感谢您的回答，我想做的是托管到远程服务中进行存储，应该怎么配置，或修改哪里呢？

**Comment by erha19** [comment]
@AhkunTa 伪代码参考一下：

1. 监测到配置修改，同步配置到服务端
```ts
    // 手动修改设置后同步到服务端
    this.preferenceService.onPreferencesChanged(async (changes) => {
      const updatePromises: Array<Promise<any>> = [];
      for (const key in changes) {
        if (changes[key].scope === PreferenceScope.User) {
          updatePromises.push(this.applyUserPreference(key, changes[key].newValue));
        } else if (changes[key].scope === PreferenceScope.Default) {
          // 当配置被重置时，移除配置存储中的 Key
          updatePromises.push(this.applyUserPreference(key, undefined));
        }
      }
      await Promise.all(updatePromises);
    });
```

2. 初始化页面后，同步配置至至本地

```ts
private loadUserPreference() {
   // 服务端获取配置值
    this.getUserPreference().then(async (data) => {
      if (data) {
        const preferences = this.safeParseJson(data);
        for (const key of Object.keys(preferences)) {
          if (EXCLUDE_PREFERENCE_KEYS.includes(key)) {
            continue;
          } else {
            // 通过 JSON.parse 解析后，布尔值会变成字符串，所以这里需要转换回布尔值
            if (preferences[key] === 'false') {
              preferences[key] = false;
            } else if (preferences[key] === 'true') {
              preferences[key] = true;
            }
            this.preferenceService.update(key, preferences[key], PreferenceScope.User);
          }
        }
      }
    });
  }
```

**Comment by Augustjoe** [comment]
@erha19 使用this.preferenceService.update更新并没有生效，
![1709624797715_DF552FC1-5950-4bb5-B5EE-1CA11AF46AF1](https://github.com/opensumi/core/assets/50567203/17e6063a-2f10-41bc-a754-5ec7a2b8c057)

**Comment by erha19** [comment]
@Augustjoe OpenSumi 内的配置项都是分作用域的，用户配置如果是在工作区下修改，修改内容则会写入打开项目的 ./sumi/settings.json 中，此时，作用域为  PreferenceScope.Workspace ，优先级是高于 PreferenceScope.User 的。
