### ISSUE TITLE
[Question] 删除文件时，弹窗如何修改，希望增加一些逻辑控制

### ISSUE THREAD

**Issue by MilkWangStudio** [opensumi/core#3253]
目前删除文件时的弹窗只有一行固定文本。我希望增在弹窗中展示一些依赖项，每个依赖项都有个删除按钮。先删除一个一个删除依赖项后，才能点击“确认"按钮删除文件。

请问有什么方便的方案么？

**Comment by erha19** [comment]
@MilkWangStudio 没有很方便的方案，你可以自行覆盖相关方法实现，实现位置在 ：

https://github.com/opensumi/core/blob/41a3427032f0e5b60a4db03f119ff9617e84390c/packages/file-tree-next/src/browser/services/file-tree-model.service.ts#L980
