### ISSUE TITLE
[Question] “在系统文件中打开”选项中，如何应对 `isRemote: true` 的情况。

### ISSUE THREAD

**Issue by Moskize91** [opensumi/core#3261]
**描述你的问题（Describe you question here）**

在左侧文件浏览器中，对某个文件单击右键，选择“在系统文件中打开”。阅读代码可知，最终它会调用如下方法。

https://github.com/opensumi/core/blob/d983d100160ec5aed39f6a8223367ac8c38b3e60/packages/core-electron-main/src/bootstrap/services/ui.ts#L87-L89

它打开的路径是 `path`。这对于 node 服务器与 browser 在同一台设备的情况下是非常恰当的。但是如果 `isRemote: true`，node 服务器运行在远端的服务器，这将造成问题。

此时，后端服务器的文件系统必然和 browser 所在的文件系统不同。**此时，我们需要某种机制将 `path` 映射**。

请问 opensumi 现在是否支持某种机制（配置项、注入自定义代码）的形式来修改如上代码的行为。

**Comment by bytemain** [comment]
如果这里的是在远程模式的话，是不是可以移除掉在文件系统打开

**Comment by erha19** [comment]
@Moskize91  这个菜单感觉应该直接移除掉，你可以卸载掉菜单，另外框架内确实可以处理一下这种不可用命令逻辑。

**Comment by Moskize91** [comment]
@erha19 了解
