### ISSUE TITLE
[Question] “复制路径”选项中，如何应对 `isRemote: true` 的情况。

### ISSUE THREAD

**Issue by Moskize91** [opensumi/core#3262]
**描述你的问题（Describe you question here）**

在左侧文件浏览器中，对某个文件单击右键，选择“复制路径”。阅读代码可知，最终它会调用如下方法。

### 复制路径
https://github.com/opensumi/core/blob/d983d100160ec5aed39f6a8223367ac8c38b3e60/packages/file-tree-next/src/browser/file-tree-contribution.ts#L733-L752

### 复制相对路径
https://github.com/opensumi/core/blob/d983d100160ec5aed39f6a8223367ac8c38b3e60/packages/file-tree-next/src/browser/file-tree-contribution.ts#L754-L787

这对于 node 服务器与 browser 在同一台设备的情况下是非常恰当的。但是如果 isRemote: true，node 服务器运行在远端的服务器，这将造成问题。因为该操作会将服务端的路径复制进剪切板，而非 browser 中该文件对应的路径。

请问 opensumi 现在是否支持某种机制（配置项、注入自定义代码）的形式来修改如上代码的行为。

**Comment by erha19** [comment]
@Moskize91 这里建议可以覆盖一下 `clipboardService` 实现，根据不同情况进行剪切板的操作，这里统一至  `clipboardService`  也是为了可以自定义。
