### ISSUE TITLE
[BUG] 在 `isRemote: true` 模式下，会将不同 workspace 关闭前的页面 state 彼此混淆

### ISSUE THREAD

**Issue by Moskize91** [opensumi/core#3263]
**描述你的问题（Describe the bug）**

使用 `isRemote: true` 的形式，后端在远端服务器，客户端为 electron。我们发现，opensumi 区分项目的方式，是通过后端参数 `workspaceDir` 来决定的。这意味着，如果后端 `workspaceDir` 相同，哪怕实际是不同的项目，也会视为相同的项目。

**复现路径（To Reproduce）**

后端用 docker container 运行将后端参数 `workspaceDir` 设置一个固定路径。依次打开不同的 docker container 以展示不同的 workspace。在客户端看到的 layout state 总是上一次打开的结果，哪怕上一次打开的 workspace 完全是另一个也是如此。

**预期结果**

如果上一次打开的 workspace 是另一个，则不应该将错误的 workspace 的 layout state 展示。

**问题分析**

通过阅读如下代码可知，opensumi 其实将 layout state 信息存储到了 localStorage。彼此通过加前缀 `this.prefix` 来区分不同的项目。

https://github.com/opensumi/core/blob/d983d100160ec5aed39f6a8223367ac8c38b3e60/packages/workspace/src/browser/workspace-storage-service.ts#L53-L55

顺着 `this.prefix` 追踪可知，前缀由 `workspaceDir` 参数决定。

https://github.com/opensumi/core/blob/d983d100160ec5aed39f6a8223367ac8c38b3e60/packages/workspace/src/browser/workspace-service.ts#L195-L210

**解决方案**

从阅读代码来看，opensumi 似乎仅仅通过 `workspaceDir` 来区分不同的项目。这对于 `isRemote: false` 的情景是合情合理的。但对于 `isRemote: true` 的场景来看，后端可能运行在远端服务器，甚至 docker container 中。对于这些情景，后端服务器难以将前端的内容完全通过 `workspaceDir` 来区分。

除非在 `workspaceDir` 中加入 hash，并在自己的数据库中加入映射规则。但这样会令用户体验 termianl 时看到地址中有一串奇怪的 hash，令人困惑不解。

另一个方案是，也许 opensumi 可以支持自定义前缀，来让基于 opensumi 的开发者能将 hash 或 ID 作为 workspace 的标识符。

此外，向 `isRemote: true` 的客户端 localStorage 写内容有时也会带来困扰。首先，对于被用户删除或永远无法使用的项目，需要 opensumi 的开发者采取某种机制清理这些信息。此外，也需要向最终用户解释，为什么它的浏览器中被写入了许多信息。当然，这个问题是次要问题。

**Comment by erha19** [comment]
@Moskize91 确实是存在这层问题的（设计比较简单），目前有什么新的问题吗？

**Comment by Moskize91** [comment]
@erha19 目前没有新问题，我们通过打 patch 的方式将修改后的 @opensumi/core 代码替换，以解决这个问题。

**Comment by bytemain** [comment]
方便的话 可以给我们提pr～
