### ISSUE TITLE
[BUG]  launch.json 里面通过命令替换字符串的方式似乎是失效的！

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3269]
![image](https://github.com/opensumi/core/assets/13432873/af0ad997-ec78-4e75-944f-06d82b26ce33)

 launch.json 里面通过命令替换字符串的方式似乎是失效的！

希望可以生效

**Comment by zhuzeyu22** [comment]
我想要从我自定义的模块里面传入配置，来配置  python 的模块路径。这个路径和 opensumi 的安装路径相关，我应该怎么配置？

**Comment by erha19** [comment]
@zhuzeyu22  这种命令形式没有支持 .. 目前仅支持了部分 alias 类型的字符，相关代码在这里：

https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/variable/src/browser/variable-resolver.service.ts

**Comment by zhuzeyu22** [comment]
ok， 我注册了一些全局变量。
