### ISSUE TITLE
[FEATURE] filetree.revealInExplorer command 需要支持文件夹的定位

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#327]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

当调用 filetree.revealInExplorer 命令时传递的 uri 如果是文件夹则不会定位到对应的位置，但资源管理器是能正常打开的

目前在 vscode-java-test 插件里需要支持这种能力
![image](https://user-images.githubusercontent.com/20262815/149289558-3d1f5487-c324-4891-84a9-a46c8b711a3b.png)

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
测试了一下，这个命令是支持文件夹定位的，检查一下参数是否为 `URI`  @Ricbet

**Comment by erha19** [comment]
没问题先关掉啦 @Ricbet
