### ISSUE TITLE
[Question] 请问怎么把 python 插件中输出到【终端】选项卡里面的信息重定向到【输出】选项卡里面？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3273]
请问怎么把 python 插件中输出到【终端】选项卡里面的信息重定向到【输出】选项卡里面？

我这是为了保证多种输出的一致性？请问有什么好的思路？

**Comment by erha19** [comment]
除了修改插件，没有简单的实现方式，可以自己尝试一下
