### ISSUE TITLE
[Question] 有没有内部培训资料呀，opensumi 框架太大了，很多贡献点只看代码了解的太慢了

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3275]
有没有内部培训资料呀，opensumi 框架太大了，很多贡献点只看代码了解的太慢了，想要快速的熟练使用各种贡献点应该怎么办呀？包括了解框架整体结构

**Comment by erha19** [comment]
暂时没有，可以试试使用 GitHub Copilot 的 workspace chat 了解一下项目
