### ISSUE TITLE
[Question]  关于编辑器组件的一些问题

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3276]
registerEditorComponent 我知道是注册组件的

registerEditorComponentResolver 我不是很清楚，不太理解
**resolveEditorComponent 我不知道是干啥的**

**Comment by erha19** [comment]
`registerEditorComponentResolver ` 主要是用于自定义部分资源的处理方式，例如想在读取到 `test` 协议开头的文件时，采用 Component 方式渲染，伪代码如：
```ts
registry.registerEditorComponentResolver('test', (resource, _, resolver) =>
        resolver([{ type: EditorOpenType.component, componentId: TEST_EDITOR }]);
 );
```

这个类型还有如 `EditorOpenType.code` ...
