### ISSUE TITLE
[Question] service 里面的一些数据结构，怎样优雅的提供给 tsx 去使用

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3286]
关于代码结构的一些问题

service 里面的一些数据结构，怎样优雅的提供给 tsx 去使用，需不需要绑定到 useState，有没有示例？

**Comment by zhuzeyu22** [comment]
还是说 service 尽量做成无状态的？

**Comment by erha19** [comment]
@zhuzeyu22 https://github.com/opensumi/core/blob/main/packages/comments/src/browser/comments-panel.view.tsx#L13 可以参考这里的用法，使用 `useInjectable` 这个 hook

**Comment by zhuzeyu22** [comment]
> @zhuzeyu22 https://github.com/opensumi/core/blob/main/packages/comments/src/browser/comments-panel.view.tsx#L13 可以参考这里的用法，使用 `useInjectable` 这个 hook

看上去这里的 service 完全是无状态的，全部通过 view 来更新 service 的内部数据。

**Comment by erha19** [comment]
> 看上去这里的 service 完全是无状态的，全部通过 view 来更新 service 的内部数据。

是的，可以看需要使用。

**Comment by zhuzeyu22** [comment]
> > 看上去这里的 service 完全是无状态的，全部通过 view 来更新 service 的内部数据。
> 
> 是的，可以看需要使用。

我设计的还是 service 里面处理 model ，通过 event 和 view 通信， view 纯做展示。

**Comment by rwjCxgsy** [comment]
> > @zhuzeyu22 https://github.com/opensumi/core/blob/main/packages/comments/src/browser/comments-panel.view.tsx#L13 可以参考这里的用法，使用 `useInjectable` 这个 hook
> 
> 我尝试把数据放到 service 里面， 然后用 @observable 和 @computed 做响应 这样 tsx 里面全是 视图，感觉更加优雅一些。

大佬 我修改了service 里的数据 如何动态渲染view组件

**Comment by rwjCxgsy** [comment]
> 还是说 service 尽量做成无状态的？

大佬 修改service 里的数据如何 动态渲染组件啊

**Comment by bytemain** [comment]
> 大佬 修改service 里的数据如何 动态渲染组件啊

我自己会选择使用事件驱动:
- https://github.com/opensumi/core/blob/0cc59cda9ecb773a32ef9db318adec674843b20e/packages/scm/src/common/scm.service.ts#L98
