### ISSUE TITLE
[BUG] startup 中的 web-lite entry 无法 npm run start:lite / npm run bundle:lite

### ISSUE THREAD

**Issue by sinoon** [opensumi/core#329]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

1. clone project
1. npm install --canvas_binary_host_mirror=https://npmmirror.com/mirrors/node-canvas-prebuilt/
2. npm run init
1. cd startup
2. npm run start:lite

**预期表现（Expected behavior）**
正常启动 localhost:8080 端口

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: macOS 11.6.1 Apple Intel
- Browser: Chrome 97
- OpenSumi Version: https://github.com/opensumi/core/tree/a78c9a2754f7196d9f1614afd644e0fe8032ba80

**补充信息（Additional context）**

看起来是依赖找不到，在 [`packages/startup/entry/web-lite/modules/textmate-language-grammar/index.contribution.ts`](https://github.com/opensumi/core/blob/a78c9a2754/packages/startup/entry/web-lite/modules/textmate-language-grammar/index.contribution.ts#L4) 里面找不到 `@opensumi/kaitian-textmate-languages`，npm 上也没有[搜索到](https://www.npmjs.com/search?q=%40opensumi%2Fkaitian-textmate-languages)

![image](https://user-images.githubusercontent.com/6065488/149473190-501201da-5277-4f23-a838-1b6175db99e4.png)

**Comment by lengthmin** [comment]
看了一下原因：这个包改名成 `[@opensumi/textmate-languages](https://www.npmjs.com/package/@opensumi/textmate-languages)` 了。
