### ISSUE TITLE
[Question] 关于需要使用缓存的地方，应该怎么处理比较合适

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3299]
关于需要使用缓存的地方应该怎么处理比较合适，
我再core 里面没有搜索到使用 useLocalStorage ，是不是有什么代替的方式？

我的需求是需要 view 和 service 共用一个 dataList 并且要做缓存，下次打开可以使用上次的缓存，并且可以尽量及时更新缓存防止意外退出时数据丢失。

**Comment by erha19** [comment]
@zhuzeyu22 如果要使用 LocalStorage ，可以使用 `ScopedBrowserStorageService (跟随工作区) ` 和 `GlobalBrowserStorageService (全局)` 服务。

另外，如果希望落盘到本地文件的数据，可以通过 StorageProvider 方式注册一个固定的存储文件，参考代码见：

https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-browser/src/common/common.storage.ts#L6-L21
