### ISSUE TITLE
[Question] 文件监听排除某些目录

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#3325]
**描述你的问题（Describe you question here）**
目前服务启动后会默认监听 .sumi 文件夹，.sumi 文件夹下面包含的插件目录中的 node_modules 可能会包含大量文件，会引发 inotify 监听数量上限的问题。如何在监听文件夹时忽略 node_modules 目录，在什么地方调用这个 setWatchFileExcludes https://github.com/opensumi/core/blob/7a937c36fb5fb3aa50f13f83b6b2f1cdd327fd14/packages/file-service/src/node/file-service.ts#L122

@erha19

**Comment by erha19** [comment]
@sleepyyj  可以通过通用的配置进行管理，如 `files.watcherExclude` 控制，默认是会排除 node_modules 目录的，是否自定义修改过？

可以参考文档配置：[运行时配置](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

https://github.com/opensumi/core/blob/b8cb6e22c8b03d58242095ff438f447f928216cb/packages/core-browser/src/core-preferences.ts#L198

**Comment by sleepyyj** [comment]
@erha19 没有修改默认的配置，但是后端出现了这个错误。
![image](https://github.com/opensumi/core/assets/16175708/11cddf9b-92cc-4b1b-8789-50cc3c749a06)
当时也没有细看 .sumi 文件夹下有多少文件，现在复现不了了。。是不是不建议 修改 inotify 的默认最大监听数量。

**Comment by life2015** [comment]
个人还是比较建议修改 Inotify 上限的，因为项目在运行起来时，不管是 IDE 还是 webpack 还有其他程序都会进行 watch，上限太低的话会影响项目 watch 逻辑的运行。

**Comment by sleepyyj** [comment]
> 个人还是比较建议修改 Inotify 上限的，因为项目在运行起来时，不管是 IDE 还是 webpack 还有其他程序都会进行 watch，上限太低的话会影响项目 watch 逻辑的运行。

@life2015 OK 我尝试一下，主要是怕引发一些性能问题。

**Comment by life2015** [comment]
> > 个人还是比较建议修改 Inotify 上限的，因为项目在运行起来时，不管是 IDE 还是 webpack 还有其他程序都会进行 watch，上限太低的话会影响项目 watch 逻辑的运行。
> 
> @life2015 OK 我尝试一下，主要是怕引发一些性能问题。

正常使用的情况下是没问题的，担心的话可以做好 CPU 和 IO 的监控

**Comment by sleepyyj** [comment]
> > > 个人还是比较建议修改 Inotify 上限的，因为项目在运行起来时，不管是 IDE 还是 webpack 还有其他程序都会进行 watch，上限太低的话会影响项目 watch 逻辑的运行。
> > 
> > 
> > @life2015 OK 我尝试一下，主要是怕引发一些性能问题。
> 
> 正常使用的情况下是没问题的，担心的话可以做好 CPU 和 IO 的监控

@life2015 确实需要修改 Inotify 上限了，因为我查了一下发现同一台物理机上的所有容器是共享 `fs.inotify.max_user_watches`这个数量上限的。。超出之后启动项目会报这个错误。
```
[app:error] Uncaught Exception:  Error: NSFW was unable to start watching that directory.
[app:error] Error: NSFW was unable to start watching that directory.
```
