### ISSUE TITLE
[Question] 打开工程的时候前端如何监听文件系统（也就是目录树）加载完成 

### ISSUE THREAD

**Issue by Hexi1997** [opensumi/core#3328]
打开工程的时候如何监听文件系统（也就是目录树）加载完成

**Comment by erha19** [comment]
@Hexi1997 数据层面可以从 FileTreeModelService 中的 `initTreeModelReady` 状态进行判断，视图层面没有相关能力

**Comment by Hexi1997** [comment]
> @Hexi1997 数据层面可以从 FileTreeModelService 中的 `initTreeModelReady` 状态进行判断，视图层面没有相关能力

![image](https://github.com/opensumi/core/assets/66669483/c1cd96ea-c2ed-4281-8705-bc89fcdecea7)
按照目前代码的逻辑，好像可以用onFileTreeModelChangeEmitter进行监听

**Comment by erha19** [comment]
@Hexi1997 如果需要一个 Event 事件，可以通过 `onFileTreeModelChange` 监听，具体就是你找到的代码位置 。
