### ISSUE TITLE
[Question] 是否支持 ES Module 类型的插件

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#3340]
**描述你的问题（Describe you question here）**
目前是否只支持 CommonJS 类型的插件，不支持 ES Module
https://github.com/opensumi/core/blob/922ed9010fe3658f626401b559c5d1cae6afa760/packages/extension/src/hosted/ext.host.ts#L411
@erha19

**Comment by erha19** [comment]
@sleepyyj 这块目前还无法支持，有部分依赖会存在兼容问题。
