### ISSUE TITLE
[Question] 纯前端版如何设置默认字号？如何将相关的设置存放至服务器，并在编辑器初始化时加载？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3379]
https://github.com/opensumi/core/issues/3249
之前已经提问过相关问题，当时需求还没确定，所以没有实际操作。

尝试使用this.preferenceService.set设置并未生效。
![image](https://github.com/opensumi/core/assets/50567203/c011f995-b0f5-4b4c-bc9e-023d57cf94cb)

尝试使用引入类的方法，也未生效
![image](https://github.com/opensumi/core/assets/50567203/da9d05f6-6115-4a0e-9d94-fac33fe8487e)
![image](https://github.com/opensumi/core/assets/50567203/52038aa4-4f22-49a7-b850-17d4260a0c9d)
![image](https://github.com/opensumi/core/assets/50567203/94ecc162-10c9-4f8e-9db6-c2503ac92e14)
不太清楚问题出在哪？幸苦老师指点下，感谢！

**Comment by erha19** [comment]
@Augustjoe 终端字体为内置配置，你不需要额外进行定义去覆盖，直接修改即可，对于配置托管，可以参考 https://github.com/opensumi/core/issues/3249#issuecomment-1865675028 ，纯前端环境下不建议使用工作区配置

**Comment by Augustjoe** [comment]
@erha19 https://github.com/opensumi/core/blob/3cd1a3e41c0897e74bff0c145035075cb1adf16a/packages/core-browser/src/core-preferences.ts#L225C1-L228C7
是修改这里，改变默认字号吗？

**Comment by erha19** [comment]
> @erha19 https://github.com/opensumi/core/blob/3cd1a3e41c0897e74bff0c145035075cb1adf16a/packages/core-browser/src/core-preferences.ts#L225C1-L228C7 是修改这里，改变默认字号吗？

@Augustjoe 是的，你直接通过配置服务更新这个值就行了 `this.preferenceService.update(key, preferences[key], PreferenceScope.User);`

**Comment by Augustjoe** [comment]
@erha19  老师，我在onDidStart函数中调用了 this.preferenceService.update(key, preferences[key], PreferenceScope.User); 但并未生效
![image](https://github.com/opensumi/core/assets/50567203/72ef4d8d-5e14-4b46-8212-0660cfa7fd56)

**Comment by erha19** [comment]
@Augustjoe 你看一下是不是有默认的工作区配置顶掉这块配置了，另外如果需要修改默认配置，可以通过集成配置中的 defaultPreference 去配置

**Comment by Augustjoe** [comment]
![image](https://github.com/opensumi/core/assets/50567203/82818a7f-4b92-4995-9beb-e9160f8851b3)
是这么配置吗？ 并不生效，另外我把 defaultPreference 注释掉后 this.preferenceService.update 依然不生效

**Comment by erha19** [comment]
@Augustjoe 看一下问题是否能在 https://github.com/opensumi/ide-startup-lite 项目复现，如果可以提供一下修改后的内容，一般是生效的。

**Comment by Augustjoe** [comment]
@erha19 我用去年9月的代码尝试了下，是不行的
![image](https://github.com/opensumi/core/assets/50567203/3ef854d9-700b-443a-aaa1-484bd080dc28)

**Comment by Augustjoe** [comment]
@erha19  应该是版本不同的问题吧？ 我看了下现在使用的 2.22.7 版本的 packages/core-browser/src/core-preferences.ts 没有 ’terminal.fontSize‘ ，是不是换位置了？
https://github.com/opensumi/core/blob/v2.22.7/packages/core-browser/src/core-preferences.ts

**Comment by Augustjoe** [comment]
@erha19 还是不行啊，改了[core/packages/terminal-next/src/common/preference.ts](https://github.com/opensumi/core/blob/84f158587137b79518f882cb3a8315a564fa82c9/packages/terminal-next/src/common/preference.ts#L173) 也没有变化

**Comment by Augustjoe** [comment]
@erha19 
![image](https://github.com/opensumi/core/assets/50567203/5eb188de-8472-4616-9318-ff857489995d)
加上字体的设置就生效了
