### ISSUE TITLE
Support VSCode TerminalProfileProvider API

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#34]
TerminalProfile/TerminalProfileProvider/registerTerminalProfileProvider

**Comment by lengthmin** [comment]
- https://github.com/microsoft/vscode/issues/123171

**Comment by lengthmin** [comment]
接下来的任务（不分顺序）：
1. 前端实现 profile 的选择器
2. 前端实现终端的分栏
2. 用户支持在设置中设置自己的 terminal profile
3. 支持 vscode 的所有 terminal profile 相关配置项
3. 把设置默认终端的选项使用 terminal profile 实现

**Comment by lengthmin** [comment]
前端界面这个话题的两点分别是：

![image](https://user-images.githubusercontent.com/13938334/149512155-53bda0a4-7bd1-4f03-b471-70beb7179fa5.png)

![image](https://user-images.githubusercontent.com/13938334/149512198-b332f07b-aeda-494d-862c-85acc3aa3ddd.png)
