### ISSUE TITLE
ubuntu系统下读取asar包的问题 

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/core#3410]
**描述你的问题（Describe you question here）**
使用 node 的 fs 或者filesrevice读取asar包里文件内容在ubuntu下读取失败，是不支持吗

**Comment by 767746649zyy** [comment]
目前遇到的问题 中文路径文件有问题 读取失败 英文路径文件没问题 这块 是什么原因 要怎么处理呢

**Comment by bytemain** [comment]
<img width="941" alt="image" src="https://github.com/opensumi/core/assets/13938334/134c6e8e-95a3-415c-83a9-72cc722bc848">

看了下代码，这部分的逻辑很简单，就是调用 fs-extra 进行读取文件，electron 下对 asar 文件的读取是 electron 自己支持的

我目前手上没有 ubuntu 的环境，你可以尝试修改下 node_modules 的代码自己调试下
