### ISSUE TITLE
[Question] 纯WEB版添加插件，如何实现本地安装插件

### ISSUE THREAD

**Issue by weberFlying** [opensumi/core#3465]
**描述你的问题（Describe you question here）**

根据官网示例打包的opensumi插件，怎么安装在本地项目中；尝试把插件目录直接copy进去，在已安装的列表里面可以显示该插件，但是插件注册的命令、视图等都法使用； 应该有个注册或安装的入口吧，找了好几天一直没找到正确的办法，求教

**Comment by erha19** [comment]
@weberFlying 纯前端版本能添加的插件需要特殊适配，可以看一下这个文档了解一下 https://opensumi.com/zh/docs/extension/web-extension 。

你可以讲完成开发的插件托管至 oss 中，以 url 方式引入 IDE 中，具体也可以参考 ide-startup-lite 等项目中的插件引入方式。
