### ISSUE TITLE
[Question] 请问 ide-debug 对应 core 代码库的哪个文件

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3510]
我想修改 debug command，在命令前后做操作，但是注册的时候 不太清楚命令 debug.start 是在什么时候注册的，在其他模块做 commands.afterExecuteCommand 的注册的时候，似乎是失效了，因此想问问看，应该怎么改比较好？？？

请问 ide-debug 对应 core 代码库的哪个文件，我的想法是通过源码进行替换，但是全替换文件太多了，因此想先看看是怎么实现的，再想想怎么解决。

**Comment by erha19** [comment]
可以看一下这里，执行的代码在这里 https://github.com/opensumi/core/blob/a53fac57ec78743997f602682e661ba9594ec99e/packages/debug/src/browser/debug-session-manager.ts#L284

另外也可以考虑注册一个 task 之后通过调试配置的 preLaunchTask 去执行特定操作。

**Comment by Ricbet** [comment]
CommandRegistry 有个 beforeExecuteCommand 函数，可以对各种 command 命令做前置处理
![image](https://github.com/opensumi/core/assets/20262815/d6eb02dc-08a9-43bf-b4a0-a8a03c83b5c1)

**Comment by zhuzeyu22** [comment]
> 可以看一下这里，执行的代码在这里
> 
> https://github.com/opensumi/core/blob/a53fac57ec78743997f602682e661ba9594ec99e/packages/debug/src/browser/debug-session-manager.ts#L284
> 
> 另外也可以考虑注册一个 task 之后通过调试配置的 preLaunchTask 去执行特定操作。

因为命令是不能重复注册的，所以我注销之后马上又重新注册了一遍，强行做了命令注册的更新，请问会对其他模块的before after 这类的关联操作有影响吗？

**Comment by zhuzeyu22** [comment]
beforeExecuteCommand 这里我又尝试了下，生效了，很开心

**Comment by erha19** [comment]
@zhuzeyu22 感觉你需要这个东西 https://github.com/opensumi/core/pull/3468

**Comment by zhuzeyu22** [comment]
@erha19 感觉 debug tools 里面没有调用 DEBUG_COMMANDS.START 里面的命令，命令注册进去了，但是没有调用到

**Comment by zhuzeyu22** [comment]
@erha19 这里遇到个问题 DebugToolbarService 里面 reload 直接调用的是 doRestart 函数对 this.model.restart(); 这里拦截不到。很烦
