### ISSUE TITLE
[Question] 如何弹出系统风格的窗口？

### ISSUE THREAD

**Issue by chcarmen** [opensumi/core#3534]
**如何弹出系统风格的窗口？**

如在 MAC 上可以弹出这样的窗口：

<img width="321" alt="截屏2024-04-12 下午12 06 49" src="https://github.com/opensumi/core/assets/33441480/1f7e7c18-4143-4e2e-9cd4-d3f685122a74">

其中窗口可以自定义内容和样式，可以进行主题与国际化适配。

**Comment by bytemain** [comment]
你图中的这个框是 electron 的关于页面，是由 electron 根据你配置的属性自己展示的： https://www.electronjs.org/docs/latest/api/app#appname

如果想放入更多内容，可以自己用 electron dialog api 来弹窗: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts#L72

如果想定义框里的样式，你可以用 BroswerWindow： https://www.electronjs.org/docs/latest/api/browser-window
