### ISSUE TITLE
[FEATURE] 优化 `ErrorBoundary` 组件样式及展示内容

### ISSUE THREAD

**Issue by erha19** [opensumi/core#355]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

错误面板的展示有点丑，核心报错信息应该直接展示出来

![image](https://user-images.githubusercontent.com/9823838/150261753-a3d5852f-e427-432a-904b-8bd86bdaa85b.png)

**描述你预期的功能表现（Describe the solution you'd like）**

展示核心报错信息，同时优化样式

**Comment by erha19** [comment]
同时, `enumDescriptions` 设置后的效果如下：

配置：

```json
{
  "contributes": {
    "configuration": {
      "magicCode.sdk.osOverride": {
        "type": "string",
        "default": "",
        "enum": [
          "",
          "windows",
          "macos",
          "linux"
        ],
        "enumDescriptions": [
          "(Current OS)",
          "Windows",
          "Mac OS",
          "Linux"
        ],
        "description": "Select from which os type, the sdk artifacts will be downloaded",
        "scope": "application"
      },
    }
  }
}
```

展示：
![image](https://user-images.githubusercontent.com/9823838/150264203-72a770ae-8b62-41db-a225-1d6e4b8bb87e.png)

**Comment by bytemain** [comment]
这个是完成了吗？
- https://github.com/opensumi/core/pull/537

**Comment by erha19** [comment]
done in #537
