### ISSUE TITLE
I have cloned ide-electron but require English version of it

### ISSUE THREAD

**Issue by Ahmed-Bilal-01** [opensumi/core#3555]
Please let me know how I can have English version of app when I execute npm start? at the moment app opens in Chinese version

**Comment by erha19** [comment]
@Ahmed-Bilal-01 The core project language should be English by default, maybe you can change the language on the bottom left, see

<img width="262" alt="image" src="https://github.com/opensumi/core/assets/9823838/c2c093d5-2278-42fd-bf7a-99a74a71a8eb">

<img width="637" alt="image" src="https://github.com/opensumi/core/assets/9823838/7b659361-f9e9-46e9-af30-7468416b17f7">
