### ISSUE TITLE
[Question] 纯Web版离线使用

### ISSUE THREAD

**Issue by weberFlying** [opensumi/core#3556]
**描述你的问题（Describe you question here）**

请问下纯WEB版安装成功后能在断网(脱离互联网)环境下使用吗？看到有很多样式文件和图标文件需要加载，请问下样式和图标如何自定义？

**Comment by erha19** [comment]
@weberFlying https://opensumi.com/zh/docs/integrate/universal-integrate-case/offline-deployment 可以看下这个文档，其他如有问题可能需要单独解决
