### ISSUE TITLE
[BUG] DesignModule 样式适配

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#3562]
在不同的主题下，DesignModule 的各个按钮会有一些样式的问题，记录在这个 issue 中修复

**Comment by bytemain** [comment]
主题： dark vscode
![CleanShot 2024-04-19 at 11 21 52@2x](https://github.com/opensumi/core/assets/13938334/f0be9bad-51b4-49a8-9e93-66e280cf0b19)
![CleanShot 2024-04-19 at 11 22 13@2x](https://github.com/opensumi/core/assets/13938334/c16e483c-d1d6-4916-adea-a99e69bba385)

**Comment by sunshinesmilelk** [comment]
主题：default light
<img width="1919" alt="iShot_2024-04-23_17 31 08" src="https://github.com/opensumi/core/assets/41573506/c991b05d-e22e-4f07-829e-7b9b870ad9ca">

**Comment by sunshinesmilelk** [comment]
主题：deafult dark
<img width="1919" alt="image" src="https://github.com/opensumi/core/assets/41573506/c4c25b37-9dc7-452a-9b56-17e1a5151042">
