### ISSUE TITLE
[FEATURE] Support `enum` and `enumDescriptions` on Preference Settings View

### ISSUE THREAD

**Issue by erha19** [opensumi/core#357]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

configuration 贡献点声明如下：

```json
{
   "contributes": {
     "configuration": {
       "magicCode.sdk.channel": {
          "type": "number",
          "default": 1,
          "enum": [
            1,
            2,
            3,
            4
          ],
          "enumDescriptions": [
            "稳定版本(#1 Stable)",
            "灰度版本(#2 Beta)",
            "开发版本(#3 Dev)",
            "尝鲜版本(#4 Canary)"
          ],
          "description": "Select from which channel to download sdk updates",
          "scope": "application"
        }
     }
   }
}
```

**描述你预期的功能表现（Describe the solution you'd like）**

设置面板响应位置应该展示为数组下拉选项，同时支持 `description` 展示

![image](https://user-images.githubusercontent.com/9823838/150263465-808a7941-1ff7-4806-aa6d-a9cd60c88748.png)

**补充信息（Additional context）**

初步定位 configuration 的贡献点是有存入数据结构的 [configurationDefaults.ts](https://github.com/opensumi/core/tree/main/packages/extension/src/browser/vscode/contributes/configurationDefaults.ts)

需要针对视图展示做一下额外处理，视图处理逻辑见 [preferenceItem.view.tsx#L38](https://github.com/opensumi/core/blob/main/packages/preferences/src/browser/preferences.view.tsx#L38)，展示还没时间修复，有兴趣的同学可以着手修复一下

**Comment by erha19** [comment]
设置 `enumDescriptions` 情况下：

```json
{
  "contributes": {
    "configuration": {
      "magicCode.sdk.osOverride": {
        "type": "string",
        "default": "",
        "enum": [
          "",
          "windows",
          "macos",
          "linux"
        ],
        "enumDescriptions": [
          "(Current OS)",
          "Windows",
          "Mac OS",
          "Linux"
        ],
        "description": "Select from which os type, the sdk artifacts will be downloaded",
        "scope": "application"
      },
    }
  }
}
```

选择后应该展示不同选项的描述信息：

![image](https://user-images.githubusercontent.com/9823838/150452335-5d6e239d-07e0-44cc-bb2d-d6401afa6a6a.png)

**Comment by sinoon** [comment]
I am working on this issue
