### ISSUE TITLE
[Question] 请问终端是在哪里创建的？

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/core#3590]
我在改写 python 调试器，里面启动时候启动的终端请问是在哪个代码模块里面启动的？

**Comment by Ricbet** [comment]
看一下这里
https://github.com/opensumi/core/blob/main/packages/debug/src/browser/debug-session.ts#L143

**Comment by zhuzeyu22** [comment]
看到了 runInTerminal  这里的请求是插件发起的吗？还是别的哪里发起的，我想找到发起方修改 cmd 的第一个参数。

**Comment by Ricbet** [comment]
插件发起的一个 RunInTerminal Request DAP 请求。你要修改的参数在 launch.json 里也可以配置的

**Comment by zhuzeyu22** [comment]
比如说我想要使用 python 插件，启动指定路径的 python，但是插件里面默认启动的是系统环境里面的 python ，这个  launch.json 里面哪个字段可以配置？

**Comment by Ricbet** [comment]
噢，你指的是这个配置啊，可以在 setting.json 里配的，python 插件都是有提供配置项的，具体可以看看 python 插件的文档
