### ISSUE TITLE
[Question] 开发模式下右键菜单可以正常显示粘贴选项，打包放到服务器上粘贴选项反而消失了？

### ISSUE THREAD

**Issue by Augustjoe** [opensumi/core#3591]
![image](https://github.com/opensumi/core/assets/50567203/485fbdfe-71c2-4d49-bc69-4df444089523)
开发环境可以正常显示
![image](https://github.com/opensumi/core/assets/50567203/c7ef9254-82d8-40c7-9fec-f4cb663f4ff1)
服务器上无法显示粘贴
找了好久也不知道是什么问题，能不能给点提示？

**Comment by erha19** [comment]
@Augustjoe 看一下网页权限，可能关闭了剪切板权限，另外 iframe 嵌入应该也有一些权限声明会影响这块能力。

**Comment by Augustjoe** [comment]
@erha19 感谢回答，请问是粘贴功能是用什么实现的？是用Clipboard吗？目前服务部署在http下，好像会被禁止粘贴。我尝试添加权限，但因为网页协议为http，浏览器不允许添加

**Comment by erha19** [comment]
@Augustjoe 默认是 `navigator.clipboard`.

**Comment by Augustjoe** [comment]
@erha19 那应该是禁用了，只有HTTPS协议（或者开发环境、本地环境下）的页面才能使用clipboard，有其他方法可以在http下实现粘贴功能吗？用clipboard.js,我自己添加一个粘贴按钮，能实现吗？
