### ISSUE TITLE
[BUG] 主题设置为OpenSumi Light时不生效 其他的正常

### ISSUE THREAD

**Issue by life2015** [opensumi/core#361]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/12879047/150272476-3fb7a7e4-50e4-4603-a685-fc1cc8617ed6.png)

**复现路径（To Reproduce）**

设置主题为OpenSumi Light即可

**预期表现（Expected behavior）**

主题被切换为OpenSumi Light

**问题截图（Screenshots）**

如上

**环境信息（Environment）**

- OS: macOS Mojave
- Browser chrome
- OpenSumi Version 2.13.7-next-1642579482.0

**Comment by Aaaaash** [comment]
opensumi.default-themes 主题版本是多少？

**Comment by erha19** [comment]
@life2015 安装最新 OpenSumi 主题包，无法复现该问题

**Comment by hacke2** [comment]
opensumi 插件版本发一下

**Comment by hacke2** [comment]
opensumi-theme 2.5.4 问题，Cloud IDE 内置插件已经更新 2.5.5 了，正常了
