### ISSUE TITLE
如何使用插件实现，匹配文件类型，渲染自定义编辑器组件

### ISSUE THREAD

**Issue by zhang-xiaoyan** [opensumi/core#3676]
**描述你的问题（Describe you question here）**

**用插件实现**：匹配文件 .test，点击 .test 文件，渲染自定义编辑器组件
**遇到的问题**：
1、匹配到 .test 文件，点击 .test 文件不知道怎么去打开自定义编辑器组件
https://opensumi.com/zh/docs/extension/interface/custom-editor-component
![1715741309309](https://github.com/opensumi/core/assets/16955480/3bdafe5a-3a2f-4091-90a0-88c8c0b2bd8b)

3、版本： "@opensumi/sumi": "2.24.5",

**Comment by erha19** [comment]
@zhang-xiaoyan 如果希望从底层拦截文件打开方式，建议使用模块进行拓展，参考案例：https://github.com/opensumi/opensumi-module-samples/tree/main/modules/use-antd

**Comment by zhang-xiaoyan** [comment]
> @zhang-xiaoyan 如果希望从底层拦截文件打开方式，建议使用模块进行拓展，参考案例：https://github.com/opensumi/opensumi-module-samples/tree/main/modules/use-antd

用插件可以实现吗
