### ISSUE TITLE
[Question] 想用插件实现一个功能，匹配文件类型，渲染 react 自定义编辑器，除了用插件内置的 webview 实现之外，还有其他办法吗？

### ISSUE THREAD

**Issue by zhang-xiaoyan** [opensumi/core#3677]
**描述你的问题（Describe you question here）**

1、用插件实现
2、匹配某种类型文件
3、渲染 react 自定义编辑器

**Comment by hacke2** [comment]
https://opensumi.com/zh/docs/extension/interface/custom-editor-component

**Comment by zhang-xiaoyan** [comment]
> https://opensumi.com/zh/docs/extension/interface/custom-editor-component

package.json 中我该怎么写呢？帮忙写个 demo

**Comment by zhang-xiaoyan** [comment]
我在 package.json 这样写的，未生效
![企业微信截图_17157427761819](https://github.com/opensumi/core/assets/16955480/7919453a-5ca6-4e46-a0b2-6866a46a2ac3)

**Comment by erha19** [comment]
@zhang-xiaoyan 插件定制不支持对特定文件进行拦截，只能定义特定协议文件，如 `custom-schema://` 文件的打开方式
