### ISSUE TITLE
[BUG] 刷新页面保持上次的terminal状态，而不是新建一个terminal

### ISSUE THREAD

**Issue by zhanba** [opensumi/core#3707]
**描述你的问题（Describe the bug）**

刷新页面保持上次的terminal状态，而不是新建一个terminal；
如果terminal中正在执行任务，刷新页面后就没法找到这个任务了；

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by life2015** [comment]
看样子是新版更新引入的问题，我来跟进一下

**Comment by life2015** [comment]
#3713

**Comment by life2015** [comment]
Fixed in #3713
