### ISSUE TITLE
纯web版本如何使用ai模块

### ISSUE THREAD

**Issue by UU-see** [opensumi/core#3717]
**描述你的问题（Describe you question here）**
纯web版本如何使用ai模块

看到core仓库和ide-startup-lite仓库的纯前端代码版本比较低，没法引入AINativeModule

**Comment by Ricbet** [comment]
纯 web 版目前还不能无缝引入 AI Native module。
因为 2.x 到 3.x 版本的升级涉及到通信层的重构改造，纯 web 版是需要做适配的
目前正在往 [codeblitz](https://github.com/opensumi/codeblitz) 当中做这块工作
