### ISSUE TITLE
[Question] 如何约束模块加载的顺序？ 如何动态注册加载一个module？

### ISSUE THREAD

**Issue by shileima** [opensumi/core#3800]
**描述你的问题（Describe you question here）**
希望点击边栏按钮后，动态加载某个模块，这部分功能是否支持？

**Comment by shileima** [comment]
@bytemain  这个功能有开发的方案吗

**Comment by bytemain** [comment]
module 的载入需要在 initialize 内完成，initialize 后再注入 layoutConfig 是没用的。比较好的方案是先加载，默认隐藏，某个时期再显示。或者使用 React 懒加载。
