### ISSUE TITLE
[BUG] 文件名对大小写不敏感

### ISSUE THREAD

**Issue by chcarmen** [opensumi/core#3806]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/33441480/299fc20b-8c9d-49d0-90a8-6031f6377d9c)

**复现路径（To Reproduce）**
1. 打开 Opensumi IDE 
2. 修改文件名大小写
3. 如上图，不允许改动，提示：source and destination must not be the same

**预期表现（Expected behavior）**

大小写敏感，应当作不同的字符进行区分

**环境信息（Environment）**

- OS: macOS 11.7 Intel Chip
- Browser: electron
- OpenSumi Version: 2.27.2

**Comment by erha19** [comment]
@chcarmen 尝试了一下 VS Code 表现，也是不支持同名文件大小写创建的，还得看看复现路径，可能有一些系统配置不同导致的
![image](https://github.com/opensumi/core/assets/9823838/49d97cf9-8294-48dc-851c-084af1e1079a)

**Comment by erha19** [comment]
@chcarmen  目前 OpenSumi 内插件文件采用的是 `fs-extra` ，相关代码如下，可以尝试本地复现一下这个问题

https://github.com/opensumi/core/blob/5d722c57a79dad3e1ee9de1e94fc836770791b53/packages/file-service/src/node/disk-file-system.provider.ts#L451

这个问题可能与传入 `writeFile` 方法的参数不足导致的。

**Comment by chcarmen** [comment]
不支持同名文件大小写创建的行为，我 VS Code 本地是跟你一样的。

但是，我想确认的是文件重命名问题，我同一系统，VS Code 允许重命名文件大小写，但 Opensumi IDE 却不能。

<img width="360" alt="截屏2024-06-26 下午2 57 59" src="https://github.com/opensumi/core/assets/33441480/66200345-74fc-4d2c-b668-9c4fa2ddb3be">

**Comment by erha19** [comment]
@chcarmen 根据我上面提供的代码，你可以本地写个 NodeJS 函数验证一下，是否缺少相关配置，没办法复现你这边问题，我也不好排查

**Comment by erha19** [comment]
@chcarmen 你这边使用的是什么版本？我拿最新的 main ，重命名是没这个问题的，可能得升级一下版本

**Comment by chcarmen** [comment]
我 2.27.2，我更新下试下

**Comment by chcarmen** [comment]
更新到 3.1.3 了，还是有这个问题：

<img width="370" alt="截屏2024-06-26 下午6 30 05" src="https://github.com/opensumi/core/assets/33441480/db57e61d-6a2b-46c4-8cf6-a5d065a90db0">

**Comment by chcarmen** [comment]
更新 fs-extra 版本至 "11.2.0"， 解决了该问题。
