### ISSUE TITLE
[Question] custom file icon does not work

### ISSUE THREAD

**Issue by stimw** [opensumi/core#3824]
**描述你的问题（Describe you question here）**

开发了一个vscode语言插件，需要为该语言的文件后缀配相应的自定义 icon，通过在插件的 package.json contribute 中配置 icon ：

```json
"contributes": {
    "languages": [
      {
        // other fields ...
        "icon": {
          "light": "./icon.svg",
          "dark": "./icon.svg"
        }
      }
    ],
}
```
在 vscode 中可以正常显示 icon，opensumi 中没有用。这块的 api 暂时没有实现吗？

**Comment by Ricbet** [comment]
插件注册的 languages 贡献点是在这个 LanguagesContributionPoint 进行处理的
https://github.com/opensumi/core/blob/main/packages/extension/src/browser/vscode/contributes/language.ts#L22

在 contribute 函数里可以新增对 icon 图标注册的处理
icon 注册可以参考这里的代码
https://github.com/opensumi/core/blob/main/packages/extension/src/browser/vscode/contributes/icon.ts#L73

**Comment by Aimee1608** [comment]
> 插件注册的 languages 贡献点是在这个 LanguagesContributionPoint 进行处理的 https://github.com/opensumi/core/blob/main/packages/extension/src/browser/vscode/contributes/language.ts#L22
> 
> 可以在 contribute 函数里新增对 icon 图标注册的逻辑。
> 
> 可以参考这里的代码 https://github.com/opensumi/core/blob/main/packages/extension/src/browser/vscode/contributes/icon.ts#L73

请问能具体说明一下 怎么调整适配吗？
