### ISSUE TITLE
[BUG] AI Native左侧面板尺寸无法拖大

### ISSUE THREAD

**Issue by wangxiaojuan** [opensumi/core#3825]
**描述你的问题（Describe the bug）**
搜索内容比较多时，想把左侧面板放大查看更详细的内容
![image](https://github.com/opensumi/core/assets/1762334/84671141-278d-4e8c-b536-50c790c9c7bc)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by bytemain** [comment]
Done in https://github.com/opensumi/core/pull/3828
