### ISSUE TITLE
[BUG] 插件进程的 logUri 不是来自 AppConfig 而是来自 Browser 的设置

### ISSUE THREAD

**Issue by yantze** [opensumi/core#384]
**描述你的问题（Describe the bug）**

如题，插件进程有自己的 AppConfig 里面配置 logDir
https://github.com/opensumi/core/blob/468bc5e1d91f8cab1e6b6d0f22afc13f522f8193/packages/extension-storage/src/browser/storage-path.ts#L146

前后端分离的场景，前端的 Browser 的 logDir 有可能是前端单独设置的 loggerManager，而插件进程是另外一个 AppConfig 设置的，所以不能因为前端 logger 设置直接影响到后端

**复现路径（To Reproduce）**
1. 设置 Browser 的 AppConfig ，设置 Server 进程的 AppConfig 
2. 最后用的是 Browser 的 logDir

**预期表现（Expected behavior）**
使用 Server 进程初始化的 AppConfig

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: macOS
- Browser: Chrome
- OpenSumi Version: main

**补充信息（Additional context）**

**Comment by erha19** [comment]
这里是不是本来就应该只有一个 `logDir` 不应该有两个配置才对？

**Comment by yantze** [comment]
看起来是我搞混了，客户端劫持了 ILogServiceForClient ，导致获取的路径是错误的
