### ISSUE TITLE
[BUG] Output Channel 切换框没有做好主题适配

### ISSUE THREAD

**Issue by chcarmen** [opensumi/core#3841]
**Output Channel 切换框没有做好深浅主题适配**
<img width="520" alt="截屏2024-07-05 下午3 02 57" src="https://github.com/opensumi/core/assets/33441480/ecfe669d-594e-4f87-8854-c2f2ae412c29">

**复现路径（To Reproduce）**
1. 打开 Output（输出）面板
2. 切换 Channel
3. Channel 列表所在的对话框没有做好深浅主题适配（深色主题下，该框背景依然为浅色）

**预期表现（Expected behavior）**
切换框适配深浅主题

**环境信息（Environment）**
- OS: macOS 11.2， Windows
- Browser: electron
- OpenSumi Version: 3.1.3

**Comment by erha19** [comment]
@chcarmen  Electron 环境下，Selection 均使用的原生选择框，故这里不存在适配的需求
