### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 15805276741** [opensumi/core#3864]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
![4607db0080c8b869ea5af373e9ef9c944fe6577ac50b2d7e29482bc078603d83QzpcVXNlcnNceHVfemhvbmd4dVxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjcxODI3ODcyMV92MlxJbWFnZUZpbGVzXDE3MjEzNTQxODE2NjRfMDU3NjFCMTAtOEI1NC00MDk4LTlDNTYtMzY1NzExRUUyQ0ExLnBuZw==](https://github.com/user-attachments/assets/442e7f48-b881-4c21-b06e-31943935a63f)
安装依赖 报错

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by bytemain** [comment]
https://opensumi.com/zh/docs/develop/how-to-contribute

参考一下文档中的这部分：
![CleanShot 2024-07-19 at 14 15 29@2x](https://github.com/user-attachments/assets/75c13212-05c2-4e2a-8568-78c4a66c0449)
