### ISSUE TITLE
[Question] 可以在renderApp里给workspaceDir设置为当前电脑中的appData路径吗

### ISSUE THREAD

**Issue by chaoyue1217** [opensumi/core#3889]
**描述你的问题（Describe you question here）**
有办法可以在renderApp里获取当前电脑中的 AppData 的路径吗？
![image](https://github.com/user-attachments/assets/e43d92d8-e17b-4a53-bdf3-572089f471f7)

**Comment by erha19** [comment]
@chaoyue1217 你可以在 URI 内传入或通过 Node 层自行处理逻辑
