### ISSUE TITLE
[BUG] 改进 inline chat 悬浮块的位置显示，避免遮挡代码

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#3915]
**描述你的问题（Describe the bug）**

当选中某个单词或只选中某一行时，inline chat 出现的位置会遮挡下方代码，影响阅读体验

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by hacke2** [comment]
现状：

![image](https://github.com/user-attachments/assets/f0296d5b-0c34-4a6d-ba23-87cc538617d8)

cursor：

![image](https://github.com/user-attachments/assets/d811f542-302b-4474-827c-31cb20b347cd)
