### ISSUE TITLE
[Question] 如何通过按钮切换main区域的自定义视图

### ISSUE THREAD

**Issue by HaiBoWon** [opensumi/core#3968]
**描述你的问题（Describe you question here）**
如何通过自定义按钮切换main区域的自定义视图
<img width="798" alt="image" src="https://github.com/user-attachments/assets/68dd2168-37b9-4049-a110-106bece59cf4">

**Comment by HaiBoWon** [comment]
还有一个延伸问题，如果main区域内先展示自定义视图并且隐藏掉bottom区域，然后通过按钮切换后，在main区域切换显示ide-editor且bottom再显示(包括输出和调试控制台等)，实现思路是怎样的，有可参考的案例吗？

**Comment by bytemain** [comment]
可以看下这个例子能不能满足你的诉求：

支持用外部按钮展示切换左右和底部

https://github.com/opensumi/opensumi-module-samples/pull/26

**Comment by erha19** [comment]
@HaiBoWon 可以参考这个案例 https://github.com/opensumi/opensumi-module-samples/tree/main/modules/toggle-panel

**Comment by HaiBoWon** [comment]
@bytemain @erha19 

谢谢了，这2个例子看过，不是我说的问题

我的问题是，首先在main中显示自定义视图，并且隐藏bottom(不是收起，彻底隐藏包括占位)，当点击按钮时，在main中切换显示ide-editor，且bottom区域也同时显示出来(包括输出和调试控制台等)

**Comment by Ricbet** [comment]
https://github.com/opensumi/opensumi-module-samples/blob/main/modules/toggle-panel/browser/toggle-panel.contribution.ts#L40 参考下这里的代码。

你可以把你自定义的视图放在单独的 slot 里，然后点击按钮的时候通过 IMainLayoutService DI 提供的 toggleSlot 方法把 main 和 bottom 隐藏，再把你的自定义视图 slot 显示

**Comment by HaiBoWon** [comment]
自定义视图，在ide-electron中，src/browser/index.ts 里使用的

**Comment by HaiBoWon** [comment]
> https://github.com/opensumi/opensumi-module-samples/blob/main/modules/toggle-panel/browser/toggle-panel.contribution.ts#L40 参考下这里的代码。
> 
> 你可以把你自定义的视图放在单独的 slot 里，然后点击按钮的时候通过 IMainLayoutService DI 提供的 toggleSlot 方法把 main 和 bottom 隐藏，再把你的自定义视图 slot 显示

main控制无效，无法隐藏

**Comment by HaiBoWon** [comment]
> 自定义视图，在ide-electron中，src/browser/index.ts 里使用的

<img width="989" alt="image" src="https://github.com/user-attachments/assets/dccd0d40-41dc-4886-bdec-121919cfa1c9">

**Comment by Ricbet** [comment]
slot main 可能比较特殊，确实无法通过 layoutService 控制显隐。

你还是试试在你的 MainLayout 组件里通过变量去控制显隐吧，然后通过 eventBus 去做通信
```typescript
@Autowired(IEventBus)
private eventBus: IEventBus;
```

**Comment by HaiBoWon** [comment]
> slot main 可能比较特殊，确实无法通过 layoutService 控制显隐。
> 
> 你还是试试在你的 MainLayout 组件里通过变量去控制显隐吧，然后通过 eventBus 去做通信
> 
> ```ts
> @Autowired(IEventBus)
> private eventBus: IEventBus;
> ```

**Comment by HaiBoWon** [comment]
> slot main 可能比较特殊，确实无法通过 layoutService 控制显隐。
> 
> 你还是试试在你的 MainLayout 组件里通过变量去控制显隐吧，然后通过 eventBus 去做通信
> 
> ```ts
> @Autowired(IEventBus)
> private eventBus: IEventBus;
> ```

通过变量控制main区域显隐后，发现在对ide-editor编辑器操作后切换出去再切换回来，编辑器保留了之前的操作状态，请问编辑器如何重置展示？

**Comment by Ricbet** [comment]
没看太懂，可以举个例子或者贴个图吗 @HaiBoWon

**Comment by HaiBoWon** [comment]
> slot main 可能比较特殊，确实无法通过 layoutService 控制显隐。
> 
> 你还是试试在你的 MainLayout 组件里通过变量去控制显隐吧，然后通过 eventBus 去做通信
> 
> ```ts
> @Autowired(IEventBus)
> private eventBus: IEventBus;
> ```

还有一个问题，通过变量控制了SlotRenderer显隐后，其高度改变不能还原，查看css是height被重写了
<img width="762" alt="image" src="https://github.com/user-attachments/assets/e883b084-e433-43c3-9423-4a16187fec5d">
<img width="685" alt="image" src="https://github.com/user-attachments/assets/b81b2ddf-cba2-43ec-a1f2-74d9380f4e6d">
<img width="602" alt="image" src="https://github.com/user-attachments/assets/07e50e3a-7d79-4bbe-8a81-645746b7074d">

**Comment by Ricbet** [comment]
> > > slot main 可能比较特殊，确实无法通过 layoutService 控制显隐。
> > > 你还是试试在你的 MainLayout 组件里通过变量去控制显隐吧，然后通过 eventBus 去做通信
> > > ```ts
> > > @Autowired(IEventBus)
> > > private eventBus: IEventBus;
> > > ```
> > 
> > 
> > 通过变量控制main区域显隐后，发现在对ide-editor编辑器操作后切换出去再切换回来，编辑器保留了之前的操作状态，请问编辑器如何重置展示？
> 
> @Ricbet
> 
> 导航1(main+bottom区域) 和 导航2(自定义区域)，通过按钮切换展示。导航1的main区域包含ide-editor编辑器，bottom区域包含调试控制台输出等。当切换导航1时，做一些操作，如关闭一个编辑器tab或调试控制台最小化，这个状态会被保存，从导航2切换回导航1时，这些展示没有被重置，请问如何重置？
> 
> <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/8159621/362193448-5bb40d78-1c6c-4bf8-acc8-8159f8618493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTY3MDEsIm5iZiI6MTcyNDg5NjQwMSwicGF0aCI6Ii84MTU5NjIxLzM2MjE5MzQ0OC01YmI0MGQ3OC0xYzZjLTRiZjgtYWNjOC04MTU5Zjg2MTg0OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDE1MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA0NWY1Y2FiY2I0NDk2NzJmMjY2OWRlNWIyYjU0ZDM0NDU4ODQ5NGRiMzFiYzhmZTZlMDk1NDZlYmQ5OGI5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fr22DtiKj9TVKJTIrxSABpn7OOYdi757RM6HmnQJP6w">

状态会被保留这个是最基础的特性，并没有直接提供恢复重置的方法，不过可以换一种思路。
在切换回来的时候用 toggleSlot 方法把 bottom 展开，完了之后手动打开 welcome 协议的文件，像这样
https://github.com/opensumi/core/blob/1807a2e5f5a29999158f573020a46d865e37db71/packages/electron-basic/src/browser/welcome/contribution.ts#L62

**Comment by HaiBoWon** [comment]
> > > > slot main 可能比较特殊，确实无法通过 layoutService 控制显隐。
> > > > 你还是试试在你的 MainLayout 组件里通过变量去控制显隐吧，然后通过 eventBus 去做通信
> > > > ```ts
> > > > @Autowired(IEventBus)
> > > > private eventBus: IEventBus;
> > > > ```
> > > 
> > > 
> > > 通过变量控制main区域显隐后，发现在对ide-editor编辑器操作后切换出去再切换回来，编辑器保留了之前的操作状态，请问编辑器如何重置展示？
> > 
> > 
> > @Ricbet
> > 导航1(main+bottom区域) 和 导航2(自定义区域)，通过按钮切换展示。导航1的main区域包含ide-editor编辑器，bottom区域包含调试控制台输出等。当切换导航1时，做一些操作，如关闭一个编辑器tab或调试控制台最小化，这个状态会被保存，从导航2切换回导航1时，这些展示没有被重置，请问如何重置？
> > <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/8159621/362193448-5bb40d78-1c6c-4bf8-acc8-8159f8618493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTY3MDEsIm5iZiI6MTcyNDg5NjQwMSwicGF0aCI6Ii84MTU5NjIxLzM2MjE5MzQ0OC01YmI0MGQ3OC0xYzZjLTRiZjgtYWNjOC04MTU5Zjg2MTg0OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDE1MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA0NWY1Y2FiY2I0NDk2NzJmMjY2OWRlNWIyYjU0ZDM0NDU4ODQ5NGRiMzFiYzhmZTZlMDk1NDZlYmQ5OGI5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fr22DtiKj9TVKJTIrxSABpn7OOYdi757RM6HmnQJP6w">
> 
> 状态会被保留这个是最基础的特性，并没有直接提供恢复重置的方法，不过可以换一种思路。 在切换回来的时候用 toggleSlot 方法把 bottom 展开，完了之后手动打开 welcome 协议的文件，像这样
> 
> https://github.com/opensumi/core/blob/1807a2e5f5a29999158f573020a46d865e37db71/packages/electron-basic/src/browser/welcome/contribution.ts#L62

谢谢，通过size控制解决了
