### ISSUE TITLE
[BUG] AI 对话面板 回答中包含多个代码块时界面闪烁

### ISSUE THREAD

**Issue by damengziSRM** [opensumi/core#4008]
**描述你的问题（Describe the bug）**

AI对话面板中，当回答是流式数据时，且返回数据包含多个代码块片段，界面渲染频繁闪烁。

https://github.com/user-attachments/assets/5c1b70dd-a9d0-4c53-bfe8-18827fbc1633

**复现路径（To Reproduce）**
startup模块中修改模拟 stream 数据的示例代码，修改为两个代码片段。

![多个代码片段](https://github.com/user-attachments/assets/ad2edb99-0690-4762-b79f-d37b0cf714fe)

**预期表现（Expected behavior）**

界面显示正常，不闪烁

**环境信息（Environment）**

- OS: [e.g. macOS 12.1 Apple M1]
- Browser: [chrome, electron]
- OpenSumi Version: [3.3]

**Comment by hacke2** [comment]
确实会有这个问题，感谢提供复现方式
