### ISSUE TITLE
[Question] 在ide-electron项目中，使用antd4.x，不能识别组件

### ISSUE THREAD

**Issue by HaiBoWon** [opensumi/core#4046]
**描述你的问题（Describe you question here）**

在 ide-electron 中，使用antd4.x的List组件，List.Item 无法识别

<img width="642" alt="lQLPKHUNVt51dnfNA-bNBQSwvyH7HuKfCacG28WOixnAAA_1284_998" src="https://github.com/user-attachments/assets/85e49f55-50a9-4fb8-a563-8556fcd34f9f">

**Comment by Ricbet** [comment]
装一下 @types/react 依赖或者看下 antd 的这个 issue https://github.com/ant-design/ant-design/issues/4892

**Comment by HaiBoWon** [comment]
> 装一下 @types/react 依赖或者看下 antd 的这个 issue [ant-design/ant-design#4892](https://github.com/ant-design/ant-design/issues/4892)

可以了
