### ISSUE TITLE
[BUG] VS Code 支持已经过时两年了吗？

### ISSUE THREAD

**Issue by gitizenss** [opensumi/core#4060]
**描述你的问题（Describe the bug）**

![image](https://github.com/user-attachments/assets/d56e1a6a-7e83-4192-81f5-ee6a1866c771)

[1.68.0](https://github.com/microsoft/vscode/releases/tag/1.68.0)
 - Jun 8, 2022 
 
OpenSumi 网站称其仅落后 VSCode 3 个月。 

看起来比VSCode落后了两年多。 

我尝试过手动添加两个半活动扩展。两者都失败了。 

如果是这么久以前，仅此一点就完全阻止我的公司使用这个 IDE，无论其功能如何。没有什么可以证明成本是合理的。我希望我错了。

**Comment by erha19** [comment]
@gitizenss 在 1.68.0 版本开始，OpenSumi 就已不再全面跟进 VS Code 标准 API 适配，而是选择实际业务插件需要的 API 进行适配，故内核版本不再往上追加，你可以自己通过修改插件进程构造文件进行自定义版本，如：https://github.com/opensumi/ide-startup/blob/main/src/extension/ext-host.ts#L6
