### ISSUE TITLE
[BUG] window11下 docker官方指导设置编译成功，docker日志无错误，端口8000可访问有404错误，开放3个端口，8080，8000，8899

### ISSUE THREAD

**Issue by ahange** [opensumi/core#4067]
**描述你的问题（Describe the bug）**
按官方开发命令docker官方指导设置编译成功
1、docker服务器日志无错误
2、8000端口可以访问404错误
3、8080 端口、8899端口步不可以

**复现路径（To Reproduce）**
#docker文件
# 第一阶段：builder
FROM node:lts as builder

ENV WORKSPACE_DIR /workspace
ENV EXTENSION_DIR /root/.sumi/extensions
ENV EXT_MODE js
ENV NODE_ENV production

# 用户工作空间，用于打包到前端工作空间地址
ENV WEBIDE /app/webide

# 设置各种镜像和下载主机
ENV ELECTRON_MIRROR https://npmmirror.com/mirrors/electron/
ENV PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries
ENV sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
ENV sharp_binary_host=https://mirrors.cloud.tencent.com/npm/sharp/-/sharp-0.31.1.tgz
ENV sentrycli_cdnurl=https://mirrors.cloud.tencent.com/npm/sentry-cli/
ENV electron_mirror=https://mirrors.cloud.tencent.com/npm/electron/
ENV chromedriver_cdnurl=https://mirrors.cloud.tencent.com/npm/chromedriver
ENV operadriver_cdnurl=https://mirrors.cloud.tencent.com/npm/operadriver
ENV python_mirror=https://pypi.tuna.tsinghua.edu.cn/simple/
ENV electron_builder_binaries_mirror=https://mirrors.cloud.tencent.com/npm/electron-builder-binaries/
ENV node_sqlite3_binary_host_mirror=https://mirrors.cloud.tencent.com/npm
ENV puppeteer_download_host=https://mirrors.cloud.tencent.com/npm
ENV sqlite3_binary_site=https://mirrors.cloud.tencent.com/npm/sqlite3/
ENV selenium_cdnurl=https://mirrors.cloud.tencent.com/npm/selenium
ENV node_inspector_cdnurl=https://mirrors.cloud.tencent.com/npm/node-inspector

# 创建目录
RUN mkdir -p ${WORKSPACE_DIR}  &&\
    mkdir -p ${EXTENSION_DIR}
RUN mkdir -p ${WEBIDE}

# 复制所有项目文件到 ${WEBIDE}
COPY . ${WEBIDE}

WORKDIR ${WEBIDE}

# 配置 npm 镜像
RUN yarn config set -H npmRegistryServer "https://registry.npmmirror.com" && \
    yarn --network-timeout 1000000

# 安装必要的库
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libsecret-1-dev && \
    rm -rf /var/lib/apt/lists/*

# 设置 PKG_CONFIG_PATH 环境变量
ENV PKG_CONFIG_PATH /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig

# 分步执行命令并增加日志输出
RUN yarn install && echo "yarn install completed"
RUN yarn run rebuild:node && echo "yarn run rebuild:node completed"
RUN yarn run init && echo "yarn run init completed"

# 构建项目
RUN yarn run build && echo "yarn run build completed"
RUN yarn run download-extension && echo "yarn run download-extension completed"
# 第二阶段：app
FROM builder

# 暴露端口
EXPOSE 8080
EXPOSE 8000
EXPOSE 8899
ENV HOST 0.0.0.0

# 启动命令
CMD [ "yarn", "start" ]

**环境信息（Environment）**
# 第一阶段：builder
FROM node:lts as builder

ENV WORKSPACE_DIR /workspace
ENV EXTENSION_DIR /root/.sumi/extensions
ENV EXT_MODE js
ENV NODE_ENV production

# 用户工作空间，用于打包到前端工作空间地址
ENV WEBIDE /app/webide

# 设置各种镜像和下载主机
ENV ELECTRON_MIRROR https://npmmirror.com/mirrors/electron/
ENV PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries
ENV sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
ENV sharp_binary_host=https://mirrors.cloud.tencent.com/npm/sharp/-/sharp-0.31.1.tgz
ENV sentrycli_cdnurl=https://mirrors.cloud.tencent.com/npm/sentry-cli/
ENV electron_mirror=https://mirrors.cloud.tencent.com/npm/electron/
ENV chromedriver_cdnurl=https://mirrors.cloud.tencent.com/npm/chromedriver
ENV operadriver_cdnurl=https://mirrors.cloud.tencent.com/npm/operadriver
ENV python_mirror=https://pypi.tuna.tsinghua.edu.cn/simple/
ENV electron_builder_binaries_mirror=https://mirrors.cloud.tencent.com/npm/electron-builder-binaries/
ENV node_sqlite3_binary_host_mirror=https://mirrors.cloud.tencent.com/npm
ENV puppeteer_download_host=https://mirrors.cloud.tencent.com/npm
ENV sqlite3_binary_site=https://mirrors.cloud.tencent.com/npm/sqlite3/
ENV selenium_cdnurl=https://mirrors.cloud.tencent.com/npm/selenium
ENV node_inspector_cdnurl=https://mirrors.cloud.tencent.com/npm/node-inspector

# 创建目录
RUN mkdir -p ${WORKSPACE_DIR}  &&\
    mkdir -p ${EXTENSION_DIR}
RUN mkdir -p ${WEBIDE}

# 复制所有项目文件到 ${WEBIDE}
COPY . ${WEBIDE}

WORKDIR ${WEBIDE}

# 配置 npm 镜像
RUN yarn config set -H npmRegistryServer "https://registry.npmmirror.com" && \
    yarn --network-timeout 1000000

# 安装必要的库
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libsecret-1-dev && \
    rm -rf /var/lib/apt/lists/*

# 设置 PKG_CONFIG_PATH 环境变量
ENV PKG_CONFIG_PATH /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig

# 分步执行命令并增加日志输出
RUN yarn install && echo "yarn install completed"
RUN yarn run rebuild:node && echo "yarn run rebuild:node completed"
RUN yarn run init && echo "yarn run init completed"

# 构建项目
RUN yarn run build && echo "yarn run build completed"
RUN yarn run download-extension && echo "yarn run download-extension completed"
# 第二阶段：app
FROM builder

# 暴露端口
EXPOSE 8080
EXPOSE 8000
EXPOSE 8899
ENV HOST 0.0.0.0

# 启动命令
CMD [ "yarn", "start" ]
#Steps to reproduce the behavior:
1. dockerfile放在根目录下
2. 执行 docker run -d --name=sumi1  -p 8080:8080 -p 8000:8000 -p 8899:8899   sumi-core 

**预期表现（Expected behavior）**

- OS: [Windows11]
- Browser: [e.g. chrome]
- OpenSumi Version: [e.g. 3.4.1]

**Comment by bytemain** [comment]
你应该访问 8080

**Comment by bytemain** [comment]
启动命令换成这个：yarn start:remote

**Comment by ahange** [comment]
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack://opensumi/node_modules/@opensumi/reconnecting-websocket/dist/reconnecting-websocket-mjs.js:527" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">reconnecting-websocket-mjs.js:527</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">WebSocket connection to 'ws:<span class="devtools-link" title="//0.0.0.0" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">//0.0.0.0:8000</span>/service' failed: </span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 640.714px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | （匿名） | @ | reconnecting-websocket-mjs.js:527
-- | -- | -- | --


</span></div>
</body>
</html>

> yarn start 只监听了 localhost

启动命令yarn start:remote修改过后，可以访问8080端口，但是出现ws://127.0.0.1:8000/serve错误

**Comment by ahange** [comment]
> 启动命令换成这个：yarn start:remote

替换完了，出现WebSocket connection to 'ws://0.0.0.0:8000/service' failed: 错误

**Comment by ahange** [comment]
> 是不是运行的时候没有加 -p 8080:8080 -p 8000:8000 -p 8899:8899
> 
> 我这里完全没问题：
> 
> ```shell
> docker run -d --name=sumi1 -p 8080:8080 -p 8000:8000 -p 8899:8899 sumi-core
> ```
> 
> ![CleanShot 2024-10-09 at 14 14 20@2x](https://private-user-images.githubusercontent.com/13938334/374826875-d9dd23f2-9687-40ae-865c-2b53285015f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjI2MTMsIm5iZiI6MTcyODQ2MjMxMywicGF0aCI6Ii8xMzkzODMzNC8zNzQ4MjY4NzUtZDlkZDIzZjItOTY4Ny00MGFlLTg2NWMtMmI1MzI4NTAxNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTU2MTlmZmQ1Mzg0N2UxM2E1ZWU5Yjg3MzgzNTllNjk2M2E3NTZjNWYxODI3NWI2MGY4Njk3MDAxNmE5NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8bevG8YUBOQbLPP5Rwvg6UOOZyFD_38TlUgwNbr1y3Y)
> 
> ![CleanShot 2024-10-09 at 14 14 23@2x](https://private-user-images.githubusercontent.com/13938334/374826883-ebf26656-034d-419d-8625-144dbd09d1e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjI2MTMsIm5iZiI6MTcyODQ2MjMxMywicGF0aCI6Ii8xMzkzODMzNC8zNzQ4MjY4ODMtZWJmMjY2NTYtMDM0ZC00MTlkLTg2MjUtMTQ0ZGJkMDlkMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMmQzMTgzOTNlNWJiNTcxMzEyMmVkMjA5NGIxMGExZDlkMzU3NGM3ZjBlOWEyZmY5MjM0NmI3NWUxN2U3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WK3kXn3ivG_1iMrlxq1PPV8-4CgQ3LgCHIFFrRQeoUk)
> 
> ```dockerfile
> FROM node:lts as builder
> 
> # 用户工作空间，用于打包到前端工作空间地址
> ENV WORKSPACE_DIR workspace
> ENV EXTENSION_DIR extensions
> ENV WEBIDE /app/webide
> 
> # 设置各种镜像和下载主机
> ENV ELECTRON_MIRROR https://npmmirror.com/mirrors/electron/
> ENV PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries
> ENV sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
> ENV sharp_binary_host=https://mirrors.cloud.tencent.com/npm/sharp/-/sharp-0.31.1.tgz
> ENV sentrycli_cdnurl=https://mirrors.cloud.tencent.com/npm/sentry-cli/
> ENV electron_mirror=https://mirrors.cloud.tencent.com/npm/electron/
> ENV chromedriver_cdnurl=https://mirrors.cloud.tencent.com/npm/chromedriver
> ENV operadriver_cdnurl=https://mirrors.cloud.tencent.com/npm/operadriver
> ENV python_mirror=https://pypi.tuna.tsinghua.edu.cn/simple/
> ENV electron_builder_binaries_mirror=https://mirrors.cloud.tencent.com/npm/electron-builder-binaries/
> ENV node_sqlite3_binary_host_mirror=https://mirrors.cloud.tencent.com/npm
> ENV puppeteer_download_host=https://mirrors.cloud.tencent.com/npm
> ENV sqlite3_binary_site=https://mirrors.cloud.tencent.com/npm/sqlite3/
> ENV selenium_cdnurl=https://mirrors.cloud.tencent.com/npm/selenium
> ENV node_inspector_cdnurl=https://mirrors.cloud.tencent.com/npm/node-inspector
> 
> # 创建目录
> RUN mkdir -p ${WORKSPACE_DIR}  &&\
>     mkdir -p ${EXTENSION_DIR}
> RUN mkdir -p ${WEBIDE}
> 
> # 复制所有项目文件到${WEBIDE}
> COPY . ${WEBIDE}
> 
> WORKDIR ${WEBIDE}
> 
> # 配置npm镜像
> RUN yarn config set -H npmRegistryServer "https://registry.npmmirror.com" && \
>     yarn --network-timeout 1000000
> 
> # 安装必要的库
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends \
>     libsecret-1-dev && \
>     rm -rf /var/lib/apt/lists/*
> 
> # 设置 PKG_CONFIG_PATH 环境变量
> ENV PKG_CONFIG_PATH /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig
> 
> # 分步执行命令并增加日志输出
> RUN yarn install && echo "yarn install completed"
> RUN yarn run rebuild:node && echo "yarn run rebuild:node completed"
> RUN yarn run init && echo "yarn run init completed"
> 
> EXPOSE 8080
> EXPOSE 8000
> EXPOSE 8899
> ENV HOST 0.0.0.0
> 
> CMD [ "yarn", "start:remote" ]
> ```

就是这个命令

**Comment by ahange** [comment]
> 是不是运行的时候没有加 -p 8080:8080 -p 8000:8000 -p 8899:8899
> 
> 我这里完全没问题：
> 
> ```shell
> docker run -d --name=sumi1 -p 8080:8080 -p 8000:8000 -p 8899:8899 sumi-core
> ```
> 
> ![CleanShot 2024-10-09 at 14 14 20@2x](https://private-user-images.githubusercontent.com/13938334/374826875-d9dd23f2-9687-40ae-865c-2b53285015f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjU1ODEsIm5iZiI6MTcyODQ2NTI4MSwicGF0aCI6Ii8xMzkzODMzNC8zNzQ4MjY4NzUtZDlkZDIzZjItOTY4Ny00MGFlLTg2NWMtMmI1MzI4NTAxNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA5MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNTk0OGE3NzBjZWJkMTVlYjg3NDUxMDY1N2JhYzE2NWJjMTMzMGQ1MzlkYTdkMTNmZDdlMWZjMmFiZGRjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x4dAGJ3_OZ_RgSniUj_ad56cTG8o_R_0O7iPGIjFUUg)
> 
> ![CleanShot 2024-10-09 at 14 14 23@2x](https://private-user-images.githubusercontent.com/13938334/374826883-ebf26656-034d-419d-8625-144dbd09d1e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjU1ODEsIm5iZiI6MTcyODQ2NTI4MSwicGF0aCI6Ii8xMzkzODMzNC8zNzQ4MjY4ODMtZWJmMjY2NTYtMDM0ZC00MTlkLTg2MjUtMTQ0ZGJkMDlkMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA5MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTQ4ODg1MzI3ODJjOTdiMTNiYzhjYmNlOGI1YzAxMzY4ZGRjNmZmZWNjZDNjM2E3MTQ4YzkzMjRlZmU3OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oxZoLFXwffHG4RWar4JWDRriZgYXz8J-utKohqU3V-A)
> 
> ```dockerfile
> FROM node:lts as builder
> 
> # 用户工作空间，用于打包到前端工作空间地址
> ENV WORKSPACE_DIR workspace
> ENV EXTENSION_DIR extensions
> ENV WEBIDE /app/webide
> 
> # 设置各种镜像和下载主机
> ENV ELECTRON_MIRROR https://npmmirror.com/mirrors/electron/
> ENV PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries
> ENV sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
> ENV sharp_binary_host=https://mirrors.cloud.tencent.com/npm/sharp/-/sharp-0.31.1.tgz
> ENV sentrycli_cdnurl=https://mirrors.cloud.tencent.com/npm/sentry-cli/
> ENV electron_mirror=https://mirrors.cloud.tencent.com/npm/electron/
> ENV chromedriver_cdnurl=https://mirrors.cloud.tencent.com/npm/chromedriver
> ENV operadriver_cdnurl=https://mirrors.cloud.tencent.com/npm/operadriver
> ENV python_mirror=https://pypi.tuna.tsinghua.edu.cn/simple/
> ENV electron_builder_binaries_mirror=https://mirrors.cloud.tencent.com/npm/electron-builder-binaries/
> ENV node_sqlite3_binary_host_mirror=https://mirrors.cloud.tencent.com/npm
> ENV puppeteer_download_host=https://mirrors.cloud.tencent.com/npm
> ENV sqlite3_binary_site=https://mirrors.cloud.tencent.com/npm/sqlite3/
> ENV selenium_cdnurl=https://mirrors.cloud.tencent.com/npm/selenium
> ENV node_inspector_cdnurl=https://mirrors.cloud.tencent.com/npm/node-inspector
> 
> # 创建目录
> RUN mkdir -p ${WORKSPACE_DIR}  &&\
>     mkdir -p ${EXTENSION_DIR}
> RUN mkdir -p ${WEBIDE}
> 
> # 复制所有项目文件到${WEBIDE}
> COPY . ${WEBIDE}
> 
> WORKDIR ${WEBIDE}
> 
> # 配置npm镜像
> RUN yarn config set -H npmRegistryServer "https://registry.npmmirror.com" && \
>     yarn --network-timeout 1000000
> 
> # 安装必要的库
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends \
>     libsecret-1-dev && \
>     rm -rf /var/lib/apt/lists/*
> 
> # 设置 PKG_CONFIG_PATH 环境变量
> ENV PKG_CONFIG_PATH /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig
> 
> # 分步执行命令并增加日志输出
> RUN yarn install && echo "yarn install completed"
> RUN yarn run rebuild:node && echo "yarn run rebuild:node completed"
> RUN yarn run init && echo "yarn run init completed"
> 
> EXPOSE 8080
> EXPOSE 8000
> EXPOSE 8899
> ENV HOST 0.0.0.0
> 
> CMD [ "yarn", "start:remote" ]
> ```
可以了
