### ISSUE TITLE
[BUG] 调用 keytar.setpassword 失败

### ISSUE THREAD

**Issue by susundingkai** [opensumi/core#4087]
**描述你的问题（Describe the bug）**
@opensumi/ide-core-node/src/common-module/credential.server.ts 中的 `await keytar.setPassword(service, account, password);` 报错 TypeError: keytar.setPassword is not a function。打印出来发现需要更改成keytar.default.setPassword才可以正常使用。

复现问题 
使用 Genie 或者其他需要输入密码或 api key的插件，设置完 api key 后就会在控制台收到报错。

**Comment by erha19** [comment]
我来看下这个问题

**Comment by erha19** [comment]
@susundingkai 看一下你项目 TS 的构建配置，开启一下下面开关即可：
```json
{
     "compilerOptions": {
       "allowSyntheticDefaultImports": true
     }
 }
```
开启 `allowSyntheticDefaultImports` 后编译会自动处理 .default 这种引用

**Comment by susundingkai** [comment]
> @susundingkai 看一下你项目 TS 的构建配置，开启一下下面开关即可：
> 
> ```json
> {
>      "compilerOptions": {
>        "allowSyntheticDefaultImports": true
>      }
>  }
> ```
> 
> 开启 `allowSyntheticDefaultImports` 后编译会自动处理 .default 这种引用

解决了，非常感谢🙏
