### ISSUE TITLE
[BUG] npm@7 以上会导致依赖安装重复

### ISSUE THREAD

**Issue by zWingz** [opensumi/core#409]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

- npm run init
- npm start
**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/13031838/151482793-e099aa20-0d1c-4039-973c-88ea00833b03.png)

![image](https://user-images.githubusercontent.com/13031838/151482684-e2e0a60a-8c35-4ae0-8f1e-65247cfe13ee.png)

**环境信息（Environment）**

- OS: MAC
- Browser afari]

**补充信息（Additional context）**

**Comment by lengthmin** [comment]
你好，看起来有可能是 react-dom 被装了多次。

1. 可以提供一下使用的 node 版本，使用的包管理工具以及其版本嘛？
2. 可以提供一下 执行 `npm ls react` 或者 `yarn why react` 的执行结果嘛（用你安装时的包管理工具）

**Comment by lengthmin** [comment]
3. 查看一下 `packages/components/node_modules` 下是不是有 react 以及 react-dom 这两个包。然后在根目录的 node_modules 也有 react 和 react-dom。

这种情况可能是高版本 npm 的安装策略有变化，可以暂时先删除  `packages/components/node_modules` 下的 react 和 react-dom

**Comment by zWingz** [comment]
用过yarn也用过npm, 一样, node版本v12.22.1

**Comment by zWingz** [comment]
`packages/components`和根目录都有`react-dom`

**Comment by lengthmin** [comment]
可以暂时先手动删除 packages/components/node_modules 下的 react 和 react-dom。我们看看怎么解决这个问题。

可以提供一下你的 npm 版本嘛？

```sh
npm -v
```

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/151484371-f23acc75-a4e2-49b5-b083-a837811d7854.png)

**Comment by zWingz** [comment]
删除了ok了
