### ISSUE TITLE
[Question] 安装了golang 插件后，一直提示安装 go-outline，并且语法高亮也不生效

### ISSUE THREAD

**Issue by nxps** [opensumi/core#4107]
**描述你的问题（Describe you question here）**

安装了golang 插件后，一直提示安装 go-outline，并且语法高亮也不生效, 请问有解决方案吗？
```
The "go-outline" command is not available. Run "go get -v github.com/ramya-rao-a/go-outline" to install.
来源: Go
```

![image](https://github.com/user-attachments/assets/4571127c-477f-462b-ae5d-c01410b3a381)

opensumi 版本: 3.4.4
os: mac OS m1

**Comment by Ricbet** [comment]
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md?plain=1#L21

检查一下 go-outline 是否有安装

**Comment by nxps** [comment]
@Ricbet 你好，我遇到了2个问题，一是按照弹窗提示安装，go 输出是是安装成功的，但是 GOBIN 目录下其实没有

![Snip20241021_34](https://github.com/user-attachments/assets/d2327cfd-04ca-4319-b2d6-c661aca4fd3d)

二是我通过 go install 安装所有 tool 后，插件不再报错，golint 检查也正常，但是语法高亮还是没有生效，tree-sitter.wasm 和 tree-sitter-go.wasm 是加载成功的

![image](https://github.com/user-attachments/assets/c8562f20-c8ba-41ac-ae6f-991391c9c196)

**Comment by nxps** [comment]
@Ricbet 我测试了 3.0 之后的几个版本，都是 golang 语法无法高亮，请问是 golang 插件原因吗

**Comment by Ricbet** [comment]
@nxps 语法高亮是需要安装 go language basics 插件的，这个插件你可以在 https://open-vsx.org/extension/vscode/go 搜索到。

当然还有一种方式是打开 go 的语义高亮，打开 setting.json 然后配置 gopls
```json
  "gopls": {
    "ui.semanticTokens": true
  }
```

**Comment by nxps** [comment]
我在 https://open-vsx.org 下载插件，已测试完部分主流语言和插件的兼容性(go、rust、python、java)，部分受限于 vscode version 限制，可以通过修改 customVSCodeEngineVersion 解决，部分受限于 vscode api, 这个只能等待 opensumi 兼容
