### ISSUE TITLE
[BUG] 连续两次执行 npm run start:election 会失败

### ISSUE THREAD

**Issue by sinoon** [opensumi/core#416]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

1. git clone https://github.com/opensumi/core.git && cd core && npm install --canvas_binary_host_mirror=https://npmmirror.com/mirrors/node-canvas-prebuilt/ && npm run init && npm run start:electron

此时会成功，然后再执行就会报错了
2. npm run start:election

terminal record：https://asciinema.org/a/Nq076A7zmxD8fOaAHgBHmJanD

**预期表现（Expected behavior）**

可以多次执行

**问题截图（Screenshots）**
![image](https://user-images.githubusercontent.com/6065488/151656959-53ad2da5-b01c-4dd7-a77d-6aafb2c6ad5d.png)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**
node: v14.18.3
npm: 6.14.15
lerna：4.0.0

**Comment by yantze** [comment]
第一次装依赖就出问题了，因为原生模块都没有编译。你可以先试试单纯的 Electron 版本 https://github.com/opensumi/ide-electron

这个问题我看看

**Comment by sinoon** [comment]
之前我提过一个 pr 解决这个问题，当时我以为是 lerna 重复安装的问题，但是如果从 clone 开始的话就没事了，https://github.com/opensumi/core/pull/381。

现在发现似乎是 npm 的问题，因为只要在 tools/election 再次执行 npm i 就会报错了（在根目录执行过 npm run start:electron）

**Comment by yantze** [comment]
看起来有点像这个问题，在 start:electron 中会 link-local [说明](https://github.com/opensumi/core/pull/381#issuecomment-1019677069) ，导致包安装依赖的时候判断出错了，在 .staging 中没有下载对的时候进行了 mv 操作，进而报错。所以简单的方法就是删除 tools/electron 中的 node_modules 就好了。

你的恢复步骤就是：
1. 删除 ./node_modules 和 tools/electron/node_modules
2. 重新执行 `npm install --canvas_binary_host_mirror=https://npmmirror.com/mirrors/node-canvas-prebuilt/ && npm run init && npm run start:electron` 即可

你可以看看这个 pr #417
