### ISSUE TITLE
[BUG] cloudide环境outputchannel日志显示问题

### ISSUE THREAD

**Issue by Raindragon-abc** [opensumi/core#4259]
**描述你的问题（Describe the bug）**
插件打印到outputchannel的日志信息没有换行显示
插件打印到outputchannel的日志只显示固定长度的日志历史日志信息无法通过滑动查看历史日志信息
插件打印到outputchannel的日志 时间不正确

这是cloudide环境中的日志显示信息
![image](https://github.com/user-attachments/assets/de00cb6c-092e-4d97-853b-9e4b3dd62a52)

**预期表现（Expected behavior）**
在vscode的outputchannel一样
打印的日志 能够通过滑块查看历史日志信息
日志能够换行显示且时间正确

**环境信息（Environment）**

- OS: [e.g. macOS 14.5 Apple M3 pro]
- Browser: [chrome]
- OpenSumi Version: [unknown]

**Comment by Ricbet** [comment]
这些日志的输出内容都是由插件提供的
方便截一下在 vscode 当中的表现吗？

**Comment by Raindragon-abc** [comment]
这是日志输出在vscode中的表现
每一行日志都有换行信息
且可以通过滑动查看历史日志信息
并且打印的日志时间是正确的
![image](https://github.com/user-attachments/assets/af234a1e-97fb-425d-9e1d-a75876ae7cbe)

**Comment by Ricbet** [comment]
仔细看了下确实，我优化一下，感谢反馈
