### ISSUE TITLE
[FEATURE] limit the button text count on message box

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#438]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

<img width="433" alt="image" src="https://user-images.githubusercontent.com/13938334/153990305-25c66eb4-7be8-4879-b0c2-e5f44c40ceba.png">

if a extension `showInfo` with a long button text, it's looks like a bit strange.

**描述你预期的功能表现（Describe the solution you'd like）**

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
@bytemain 看能不能补充一些信息

**Comment by bytemain** [comment]
![CleanShot 2022-07-12 at 11 25 02@2x](https://user-images.githubusercontent.com/13938334/178402152-9811e317-f802-4180-9d6a-495190da58e4.png)

右下角那个提示，两个按钮水平方向不一样高

**Comment by bytemain** [comment]
Closed By: https://github.com/opensumi/core/pull/1599
