### ISSUE TITLE
🤖 OpenSumi Pre-Release 2.14.5-next

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#453]
### [43a8d4733ff16e14e251e9ec69aeb1c934239596](https://github.com/opensumi/core/compare/d6abd22521c8209373866b1b6e666aef034429c6...43a8d4733ff16e14e251e9ec69aeb1c934239596)

> 23 February 2022

#### 🎉 New Features

- 拦截 telemetry 模块的实现 [#441](https://github.com/opensumi/core/pull/441) by [@Ricbet](https://github.com/Ricbet)

- 引入Nodemon- Nodemon自定义配置 [#443](https://github.com/opensumi/core/pull/443) by [@life2015](https://github.com/life2015)

- display the remote title in the remote mode [#450](https://github.com/opensumi/core/pull/450) by [@yantze](https://github.com/yantze)

#### 🐛 Bug Fixes

- quicksearch possible infinite recursion [#399](https://github.com/opensumi/core/pull/399) by [@hacke2](https://github.com/hacke2)

- open with editor open if scm node no command [#426](https://github.com/opensumi/core/pull/426) by [@hacke2](https://github.com/hacke2)

- editor decoration alignment [#430](https://github.com/opensumi/core/pull/430) by [@hacke2](https://github.com/hacke2)

- 修复 tabbar 插入 item 后 hidden 状态丢失问题 [#442](https://github.com/opensumi/core/pull/442) by [@EAGzzyCSL](https://github.com/EAGzzyCSL)

- fix: nodemon remove tools watch (#446) [#446](https://github.com/opensumi/core/pull/446) by [@life2015](https://github.com/life2015)

- pseudo terminal output [#448](https://github.com/opensumi/core/pull/448) by [@bytemain](https://github.com/bytemain)

- inject env to terminal [#449](https://github.com/opensumi/core/pull/449) by [@bytemain](https://github.com/bytemain)

- Add missing TerminalLink definition [#454](https://github.com/opensumi/core/pull/454) by [@bytemain](https://github.com/bytemain)

- popover querySelector css escape [#455](https://github.com/opensumi/core/pull/455) by [@hacke2](https://github.com/hacke2)

- 修复 status-bar 中 Popover 下元素的布局问题 [#457](https://github.com/opensumi/core/pull/457) by [@EAGzzyCSL](https://github.com/EAGzzyCSL)

- fix: missing sumi api (#466) [#466](https://github.com/opensumi/core/pull/466) by [@Aaaaash](https://github.com/Aaaaash)

- fix: pty process exit issue (#470) [#470](https://github.com/opensumi/core/pull/470) by [@Aaaaash](https://github.com/Aaaaash)

- hide pophover if no tooltip [#476](https://github.com/opensumi/core/pull/476) by [@hacke2](https://github.com/hacke2)

- 修复命令面板按 esc 键无法隐藏的问题 [#478](https://github.com/opensumi/core/pull/478) by [@Ricbet](https://github.com/Ricbet)

- hide statusbar popover if no command [#489](https://github.com/opensumi/core/pull/489) by [@hacke2](https://github.com/hacke2)

- only web env deal with openNewWindow external prop [#485](https://github.com/opensumi/core/pull/485) by [@yantze](https://github.com/yantze)

- empty editor background show logic [#499](https://github.com/opensumi/core/pull/499) by [@erha19](https://github.com/erha19)

- 修复拆分终端场景下无法监听终端设置的问题 [#503](https://github.com/opensumi/core/pull/503) by [@Aaaaash](https://github.com/Aaaaash)

- 修复撤销、回退失效的问题 [#504](https://github.com/opensumi/core/pull/504) by [@Ricbet](https://github.com/Ricbet)

#### 💄 Style Changes

- 优化编辑器 tab 栏加载中图标 [#500](https://github.com/opensumi/core/pull/500) by [@Aaaaash](https://github.com/Aaaaash)

#### 🪚 Refactors

- optimize framework dependency structure [#432](https://github.com/opensumi/core/pull/432) by [@erha19](https://github.com/erha19)

#### 🚀 Performance Improvements

- add message batcher for output channel [#436](https://github.com/opensumi/core/pull/436) by [@Aaaaash](https://github.com/Aaaaash)

#### 🏗️ Build System

- feat: add core-browser nodemon ignore (#467) [#467](https://github.com/opensumi/core/pull/467) by [@life2015](https://github.com/life2015)

#### 🧹 Chores

- chore: upgrade monaco-editor version (#429) [#429](https://github.com/opensumi/core/pull/429) by [@Ricbet](https://github.com/Ricbet)

- chore: remove unused file (#434) [#434](https://github.com/opensumi/core/pull/434) by [@bytemain](https://github.com/bytemain)

- chore: generate tsconfig resolves (#435) [#435](https://github.com/opensumi/core/pull/435) by [@bytemain](https://github.com/bytemain)

- Update release workflow [#463](https://github.com/opensumi/core/pull/463) by [@Aaaaash](https://github.com/Aaaaash)

- add permission check logic on workflow [#464](https://github.com/opensumi/core/pull/464) by [@erha19](https://github.com/erha19)

- fix: workflow syntax error (#465) [#465](https://github.com/opensumi/core/pull/465) by [@Aaaaash](https://github.com/Aaaaash)

- remove useless self re-export [#474](https://github.com/opensumi/core/pull/474) by [@EAGzzyCSL](https://github.com/EAGzzyCSL)

**Comment by Aaaaash** [comment]
- #471

**Comment by bytemain** [comment]
测试报告: #479 

- https://github.com/opensumi/core/issues/492
- https://github.com/opensumi/core/issues/490
- https://github.com/opensumi/core/issues/481
- https://github.com/opensumi/core/issues/440
- https://github.com/opensumi/core/issues/484
- https://github.com/opensumi/core/issues/483
- https://github.com/opensumi/core/issues/482
