### ISSUE TITLE
[BUG] 启动调试后断点错位

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#475]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
1. 安装 Node Debug 及 Node Debug(legacy) 插件
2. 任意 JavaScript 添加断点(如图)
3. 启动调试，大概率断点错位

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/17701805/154883314-59186e2f-ab43-4c5b-93f0-41fd74cb365e.png)

![js-debug-bk](https://user-images.githubusercontent.com/17701805/154883428-73bb226b-0abf-4154-b427-0a6fa43d996d.gif)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
这个问题是因为 debug server 它返回回来的断点位置信息就是如此。所以在 opensumi 侧并不能算是一个 bug

**Comment by Ricbet** [comment]
所以我关闭了
