### ISSUE TITLE
[BUG] 选择空格符功能失效

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#481]
**描述你的问题（Describe the bug）**

![123](https://user-images.githubusercontent.com/13938334/154896102-0ee3dbcd-dbf2-44a8-bf79-3c8f61b4ef47.png)
鼠标移上去没有显示点击按钮，只有一个 tips

**Comment by erha19** [comment]
@hacke2 这个选择空格符的功能失效问题看看？

**Comment by hacke2** [comment]
![image](https://user-images.githubusercontent.com/6399899/155051773-a7949666-a7f7-4186-959a-2cbd1f35301f.png)


之前应该没有实现这个功能

**Comment by erha19** [comment]
@hacke2  暂时把 hover 的提示隐藏掉？
