### ISSUE TITLE
[BUG] language status 展示效果问题

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#482]
**描述你的问题（Describe the bug）**

<img width="312" alt="image" src="https://user-images.githubusercontent.com/13938334/154896370-3c819fb8-85ba-451b-9ad6-8542f6a75450.png">

这个 status 偶尔展示不全。

https://user-images.githubusercontent.com/13938334/154896498-6b10e6d6-e462-4d2c-a75e-7b9479760f5e.mp4

**Comment by hacke2** [comment]
https://github.com/opensumi/core/commit/a56a76533b136348eeb165e3aad227d5c190c297 这个 commit 修复了
