### ISSUE TITLE
[BUG] 文件树点击根目录的焦点有问题

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#483]
**描述你的问题（Describe the bug）**

我想在根目录建一个文件，但是新建文件的焦点不正确。
根本无法选中到根目录。

https://user-images.githubusercontent.com/13938334/154897126-c5476932-f1b6-477d-b263-924f15273910.mp4

**Comment by bytemain** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/13938334/154897323-8922b82d-a98f-49b6-b9df-1ece56b14664.png">

这个问题还会导致复制了一个文件之后无法在根目录粘贴。

**Comment by erha19** [comment]
@bytemain 工具栏上的菜单目前是使用选中节点作为目标节点的，这个是符合预期的，空白区域右键菜单没有粘贴选项的问题应该是条件问题，我修一下
