### ISSUE TITLE
[BUG] 大纲中跟随光标功能失效

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#484]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/13938334/154897784-f9c2df49-fdc1-4c39-94f3-c84f1babed4e.png">

开启跟随光标后，在文件中点击。大纲的并没有跟随。

**Comment by erha19** [comment]
这个其实是不怎么灵，我看看咋回事

**Comment by bytemain** [comment]
在一个超大的 app.json 中没有复现。
之后再说吧
