### ISSUE TITLE
[BUG] Cmd+P quick open 有些文件无法查找到

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#490]
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13938334/155059932-c676d416-88fe-40e4-92ef-0d167b3d4055.png">
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13938334/155060348-038cc1cf-14e8-4cdc-bf4b-7c6e348b3606.png">

打开一个已有 .gitignore 文件的文件夹，不要点击打开 .gitignore  
打开一个已有 .gitignore 文件的文件夹，不要点击打开 .gitignore  
打开一个已有 .gitignore 文件的文件夹，不要点击打开 .gitignore  

然后 cmd+p，搜索文件，查找不到 gitignore 这个文件。

**Comment by hacke2** [comment]
这应该是搜不到 . 开头的文件

**Comment by bytemain** [comment]
补充一下：如果我打开了这个 .gitignore，又可以搜到了

**Comment by erha19** [comment]
这个目前应该是 byDesign,  针对部分配置文件可能需要额外做一层数据检索
