### ISSUE TITLE
[BUG] 插件市场禁用功能失效

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#492]
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13938334/155061129-1bf534e8-776f-4242-995b-a91c2bf41e1b.png">

<img width="357" alt="image" src="https://user-images.githubusercontent.com/13938334/155067073-0cbadc2e-e08c-4452-93f6-14d7eae1d15a.png">

右键菜单里除了卸载也全都不能点击。

**Comment by hacke2** [comment]
这个和插件市场无关，内部讨论吧
