### ISSUE TITLE
[FEATURE] 如果 Workspace 没有指定，Terminal 应该默认进入 home 目录

### ISSUE THREAD

**Issue by yantze** [opensumi/core#542]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

如果 Workspace 没有指定，Terminal 展开的 cwd 是 home 目录。目前是到了 `/` 目录。
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/2226423/156508307-6c46f94c-b218-439f-9a3c-78fcf4ed6be5.png">

**描述你预期的功能表现（Describe the solution you'd like）**

比如在 ide-electron 里面，没有指定 workspace 的目录，默认显示 Home 的目录。

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by bytemain** [comment]
这个在设计上有考虑到，代码见：https://github.com/opensumi/core/blob/main/packages/terminal-next/src/node/pty.ts#L221

但看起来没有生效。

**Comment by bytemain** [comment]
test case 倒是也能跑过：https://github.com/opensumi/core/blob/main/packages/terminal-next/__tests__/node/pty.test.ts#L50

**Comment by yantze** [comment]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/2226423/156509166-67916716-cd49-4212-bca6-384ab7191165.png">
目前默认是到了 `/` 目录

**Comment by Aaaaash** [comment]
描述不准确，没有「不可用提示」吧?

**Comment by bytemain** [comment]
debug 了一下，https://github.com/opensumi/core/blob/main/packages/terminal-next/src/browser/terminal.client.ts#L342 这里取到的工作目录是 `/`，我来修一下吧。
<img width="211" alt="image" src="https://user-images.githubusercontent.com/13938334/156510619-2571e757-bd9d-4ea0-9261-83405043e213.png">

**Comment by yantze** [comment]
> 描述不准确，没有「不可用提示」吧?

<img width="26" alt="image" src="https://user-images.githubusercontent.com/2226423/156511163-b4a6dc04-fc8f-452e-a6b4-9a3e865ce479.png"> 这个是啥

**Comment by bytemain** [comment]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/13938334/156511464-94b52ad2-d761-4a3b-b65a-4adf11241cde.png">

**Comment by Aaaaash** [comment]
主题？不可用提示应该不长这样..

**Comment by yantze** [comment]
> 主题？不可用提示应该不长这样..

应该是 zsh 的主题，我改一下
