### ISSUE TITLE
[BUG] 选择默认的 bash 作为 Shell，自动转为 zsh

### ISSUE THREAD

**Issue by yantze** [opensumi/core#543]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
1. 设置为 bash，新建 Terminal就会出现

<img width="894" alt="image" src="https://user-images.githubusercontent.com/2226423/156510542-c9e4a420-05b5-498a-88d2-29379c31a7c5.png">

**预期表现（Expected behavior）**
期望打开的是 bash 的 Terminal

**问题截图（Screenshots）**
![screenshort_20220303-144139](https://user-images.githubusercontent.com/2226423/156510910-5aede65c-6d6d-4865-a08d-58683875963f.gif)

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
这个已知问题
没有 workspaceDir 时 workspace 设置不生效

**Comment by yantze** [comment]
1. 重新打开，默认选择的还是 bash
2. 就算是切换为 zsh，似乎一些 zsh 配置没有加载

**Comment by bytemain** [comment]
我感觉是符合预期的，在选中 bash 的时候，实际上执行的命令是：`bash -l`
<img width="573" alt="image" src="https://user-images.githubusercontent.com/13938334/156527887-03949268-9bd1-496a-a12f-821e973a9405.png">

**Comment by bytemain** [comment]
根据这篇文章：
https://unix.stackexchange.com/questions/277944/what-sets-the-shell-environment-variable

感觉 $SHELL 的值也是符合预期的。

<img width="667" alt="image" src="https://user-images.githubusercontent.com/13938334/156528393-9c407651-cae8-4516-aff1-5f4a973742b2.png">

**Comment by bytemain** [comment]
可以加一个配置项来取消这种 `-l` 的表现。

**Comment by yantze** [comment]
> 可以加一个配置项来取消这种 `-l` 的表现。

bash -l 的表现就是以 login shell 启动，确实这样 $SHELL 显示的行为是一致的。

不建议消除 -l，通过 login shell 启动 PATH 会加上 /usr/local/bin 这个路径，如果没有会导致一些命令执行异常

**Comment by bytemain** [comment]
那就保持原样了？这个 close 掉？
