### ISSUE TITLE
[BUG] npm run init 报错

### ISSUE THREAD

**Issue by mbpz** [opensumi/core#545]
**描述你的问题（Describe the bug）**
npm run init
报错

**复现路径（To Reproduce）**

npm install --legacy-peer-deps
npm install --canvas_binary_host_mirror=https://npmmirror.com/mirrors/canvas/
npm run init

**预期表现（Expected behavior）**

本地可以正常运行。

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/19383199/156522061-03a41283-32eb-40ed-8d85-7698b48042a1.png)

**环境信息（Environment）**

- OS: [Windows10]
- Browser [chrome]
- OpenSumi Version [2.14.4]

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
看错误信息需要先配置一下 node-gyp 相关的环境，可以参考下这个文档 https://github.com/nodejs/node-gyp#on-windows
