### ISSUE TITLE
[FEATURE] 几个功能建议

### ISSUE THREAD

**Issue by wjx0912** [opensumi/core#546]
1. 支持多用户
2. 可以直接打开git地址

感谢

**Comment by Aaaaash** [comment]
> 1. 支持多用户

多用户是指？

> 2. 可以直接打开 git 地址

打开 git 地址这个功能不适合在框架层面默认提供，但后续会有实现 「打开 git 地址」的示例项目

**Comment by Aaaaash** [comment]
> 1. 支持多用户

多用户是指？

> 2. 可以直接打开 git 地址

打开 git 地址这个功能不适合在框架层面默认提供，但后续会有实现 「打开 git 地址」的示例项目

**Comment by bytemain** [comment]
> > 1. 支持多用户
> 
> 多用户是指？
> 
> > 2. 可以直接打开 git 地址
> 
> 打开 git 地址这个功能不适合在框架层面默认提供，但后续会有实现 「打开 git 地址」的示例项目

打开 git 地址这个我们可以做一个纯前端预览 github 的应用来做例子。

**Comment by wjx0912** [comment]
@Aaaaash 
感谢答复。多用户就是希望每个用户有自己的工作空间，配置文件

**Comment by erha19** [comment]
> @Aaaaash 感谢答复。多用户就是希望每个用户有自己的工作空间，配置文件

@wjx0912 实现这个需求，你一般需要一个上层的服务去负责创建并管理每个用户的工作空间及配置服务，框架默认只提供了基础的能力，需要你自己进行上层搭建，如：

当你的上层服务给用户创建了工作空间后，通过在框架运行的 `workspaceDir` 中指定工作空间路径，即可让用户在改路径下打开编辑器，同时，配置文件将会在对应目录结构下的 `~/.sumi` 下默认创建，你也可以在配置中，通过修改 `preferenceDirName ` 进行配置，详细配置可见：https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config

**Comment by wjx0912** [comment]
@erha19 谢谢
