### ISSUE TITLE
[FEATURE] 关于多用户

### ISSUE THREAD

**Issue by Small-Miao** [opensumi/core#560]
我想问下 关于多用户的支持

是否可以做到同文件多人协作

以及最简单的多用户认证 例如单独的账号密码 
以及根据认证的 多用户单独 工作空间

**Comment by Aaaaash** [comment]
> 是否可以做到同文件多人协作

我们有在做一些多人协作的探索，比如 [sumi-collaboration](https://github.com/Aaaaash/sumi-collaboration) 是基于 Yjs 的一个简单的多人协作模块，现在处于调研阶段，后面会逐步完善，并作为 OpenSumi 的可选模块

> 以及最简单的多用户认证 例如单独的账号密码
以及根据认证的 多用户单独 工作空间

多用户认证、工作空间这些实际是构建在框架上层的服务，或者换句话说与框架无关的，OpenSumi 目前只提供 Cloud/Desktop IDE 的框架和基础的集成示例。对于多用户认证这些其实完全可以自行搭建，多用户单独的工作空间可以理解为是一套类似 K8s 容器集群管理服务，而 OpenSumi 只是运行在容器中的服务。

**Comment by Small-Miao** [comment]
@Aaaaash 
感谢您的回复
我也找到了这个模块 在研究如何将它添加到OpenSumi中
我技术力不够 还在慢慢理解

**Comment by Aaaaash** [comment]
有个示例，只需要把 `CollaborationBorwserModule` 添加到 `renderApp` 的 modules 列表里即可

[example](https://github.com/Aaaaash/sumi-collaboration/blob/main/example/src/browser/index.ts#L18)

**Comment by Small-Miao** [comment]
我去试试

**Comment by Small-Miao** [comment]
docker 的那个默认网页镜像是不是没法更改加新的模块

**Comment by Aaaaash** [comment]
是的，如果要加新的模块需要 fork 或基于 ide-startup 创建一个新的项目，然后修改代码

**Comment by Small-Miao** [comment]
好的好的
我这边项目没法构建 Node Gyp一直都有问题 编译就报错 
期待你们这个功能成熟后能正式部署在默认上吧
