### ISSUE TITLE
[BUG]  执行报错。

### ISSUE THREAD

**Issue by houming818** [opensumi/core#565]
**描述你的问题（Describe the bug）**

```
export HOST=192.168.1.103; export IDE_FRONT_PORT=5504; npm run start
```

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/5498826/157022377-eb9e831a-0b42-4f00-8dcd-dbbd9d01f1b7.png)

![image](https://user-images.githubusercontent.com/5498826/157022429-06f1af18-a9d1-401b-819b-5dc10debd3ae.png)

![image](https://user-images.githubusercontent.com/5498826/157022475-0ac58c6c-f622-4acf-96dd-5e6a37eab132.png)

**环境信息（Environment）**

```
OS：  ubuntu-20.04
nvm:  v16.14.0
node: v16.14.0
代码版本： v2.15.3（d4297082a）
npm： 8.3.1

```

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
Node.js 和 npm 版本是?

**Comment by houming818** [comment]
已更新。

**Comment by Aaaaash** [comment]
由于底层依赖问题，npm 7 以上版本在安装依赖时会重复安装 react 和 react-dom，main 分支暂时解决了这个问题，2.15.3 的话建议安装依赖的时候加一个 flag `--legacy-peer-deps` 试试

**Comment by houming818** [comment]
推荐的依赖环境版本是什么？比如node npm ？

**Comment by Aaaaash** [comment]
推荐 Node.js 14, npm 6

**Comment by houming818** [comment]
![image](https://user-images.githubusercontent.com/5498826/157029815-567ac85b-e04e-4832-be48-7fda8d7be503.png)

```
Now using node v14.19.0 (npm v6.14.16)
代码版本： v2.15.3（d4297082a）
```

**Comment by erha19** [comment]
@houming818 从截图部分信息看可能是构建出现问题了，可以提供一下控制台完整报错，同时检查一下运行 `npm run start` 的控制台是否有报错信息。

**Comment by bytemain** [comment]
先 close 了。
根据沟通，应该就是 npm@7 以上安装依赖的问题，可以在 #531 中解决。

- https://github.com/opensumi/core/issues/531
