### ISSUE TITLE
OpenSumi 可以在 CentOS 上运行吗

### ISSUE THREAD

**Issue by 7FanZhi** [opensumi/core#568]
请问下core模块用centos可以启动嚒 ？最近我在尝试在centos启动core 。 多有打扰，谢谢啦。

**Comment by hacke2** [comment]
可以的，我们内部 Cloud IDE 目前就是在 centos 上运行的

**Comment by 7FanZhi** [comment]
十分感谢您的解答，也十分感谢OpenSumi能够开源

**Comment by erha19** [comment]
这个 issue 暂时先关闭了，如有使用上的问题，欢迎新建 issue 反馈，感谢你的使用
