### ISSUE TITLE
Support TypeHierarchy API

### ISSUE THREAD

**Issue by erha19** [opensumi/core#579]
like:
- TypeHierarchyItem
- TypeHierarchyProvider
- registerTypeHierarchyProvider

ref: https://code.visualstudio.com/api/references/vscode-api#TypeHierarchyItem

**Comment by bytemain** [comment]
目前是遇到了 vscode-eslint 2.2.2(https://github.com/Microsoft/vscode-eslint) 这个插件不可用。

发现是依赖了 vscode-languageclient 8.0 (https://github.com/microsoft/vscode-eslint/blob/main/client/package.json#L24) 导致这个 api 相关的不可用

**Comment by Aaaaash** [comment]
closed #819
