### ISSUE TITLE
高版本 less 编译报错 [BUG] 

### ISSUE THREAD

**Issue by winixt** [opensumi/core#586]
**描述你的问题（Describe the bug）**

Error evaluating function `unit`: the first argument to unit must be a number.

**问题截图（Screenshots）**

<img width="859" alt="image" src="https://user-images.githubusercontent.com/20717402/157185134-567f9ffe-8eaf-4e21-a6f5-c5402bda7ee8.png">

**代码路径**
https://github.com/opensumi/core/blob/main/packages/components/src/style/mixins.less

**可用修复方式**

```css
@font-scale: unit(@size / 12px);
```

改成：
```css
@font-scale: unit((@size / 12px));
```

**Comment by erha19** [comment]
@winixt 提交个 PR 吧，修到 v2.15 分支，我们会在今天发布相应的 patch 版本

**Comment by winixt** [comment]
OK
