### ISSUE TITLE
[BUG] ide-startup项目插件不展示详情

### ISSUE THREAD

**Issue by ChesterBu** [opensumi/core#604]
**描述你的问题（Describe the bug）**

 ide-startup项目， 打开插件市场，插件不展示详情网页详情
<img width="1472" alt="截屏2022-03-10 下午8 03 15" src="https://user-images.githubusercontent.com/16631758/157657933-d802fdf8-a382-450b-9e0d-4cde37e44d4d.png">

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
@ChesterBu 你这边是用什么路径访问的？ `0.0.0.0`, `127.0.0.1`, `localhost` ?

**Comment by ChesterBu** [comment]
127.0.0.1

**Comment by ChesterBu** [comment]
<img width="1791" alt="截屏2022-03-16 上午11 01 08" src="https://user-images.githubusercontent.com/16631758/158508197-6692d290-fa37-483c-9be2-765261315665.png">

**Comment by erha19** [comment]
duplicate https://github.com/opensumi/ide-startup/issues/8.
