### ISSUE TITLE
[FEATURE] 支持 QuickInput 框不保留上次内容

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#609]

**Comment by hacke2** [comment]
保留上次内容是 feature，可以加个配置来不保留

**Comment by erha19** [comment]
@hacke2 可以加一加

**Comment by Aaaaash** [comment]
quickOpen 有个配置 `workbench.quickOpen.preserveInput`，是不是应该用这一个配置就可以了？

**Comment by erha19** [comment]
> quickOpen 有个配置 `workbench.quickOpen.preserveInput`，是不是应该用这一个配置就可以了？

@hacke2 @bytemain 感觉按照这个配置搞一下就行了
