### ISSUE TITLE
[FEATURE] 搜索区折叠扩展部分

### ISSUE THREAD

**Issue by yantze** [opensumi/core#622]
**如果你的需求与问题相关，请在下面描述一下**

1. 启用默认排除项和图标挨得太近
2. 要包含的文件和要排除的文件应该折叠
3. 优化翻译

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2226423/158117500-e3469b38-a677-49e6-a4a3-2da1e49480a5.png">

**描述你预期的功能表现**

1. 文字图标有空见
2. 则跌高级设置
3. ”查看您的设置配置排除, 并检查您的 gitignore 文件“ 翻译应该是 ”查看您的设置排除配置, 并检查您的 gitignore 文件“

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
> 文字图标有空见

空间？空隙？

> 则跌高级设置

则跌 > 折叠

`则跌高级设置` 是什么意思

> 要包含的文件和要排除的文件应该折叠

点击「显示搜索条件」选择框会折叠
