### ISSUE TITLE
extension-storage 的 sorage-path.js 不依赖 crypto 是不是好一些？[BUG] 

### ISSUE THREAD

**Issue by winixt** [opensumi/core#627]
**描述你的问题（Describe the bug）**

extension-storage 的 sorage-path.js 依赖 `crypto`，构建纯前端 webIDE 的时候，会提示 `crypto` 不存在，只能通过 hack 的手段处理。

看了下源码，这是一个浏览器模块，又仅仅用到了 `crypto` 的 md5，所以是否可以用纯 md5 的包？或者其他方案？

**预期表现（Expected behavior）**

不依赖 `crypto`

**Comment by erha19** [comment]
确实，这边看了一下，可以考虑用浏览器中的 [crypto](https://developer.mozilla.org/en-US/docs/Web/API/crypto_property) 来处理一下对应逻辑，有兴趣可以起个 PR 处理下试试 @winixt

**Comment by bytemain** [comment]
https://github.com/opensumi/github-bot/blob/main/src/crypto.ts
贴一下浏览器中的 crypto API 的几个例子，估计有用

**Comment by winixt** [comment]
@erha19

**Comment by bytemain** [comment]
我来解决这个问题。

**Comment by winixt** [comment]
@erha19 我这边尝试跑项目单元测试，发现原本的测试案例好像就有问题，是不是因为 jest 版本升级没有同步跟新单元测试

**Comment by erha19** [comment]
> @erha19 我这边尝试跑项目单元测试，发现原本的测试案例好像就有问题，是不是因为 jest 版本升级没有同步跟新单元测试 

@winixt 你这里看起来的报错原因是 jest 升级后 async 于 done 不能同时使用了，后续会在这个 PR 修复 #461.

**Comment by bytemain** [comment]
这个可否改成用的 web assembly 那个 hash？ @Aaaaash
