### ISSUE TITLE
[BUG] QuickOpen 样式错乱

### ISSUE THREAD

**Issue by yantze** [opensumi/core#632]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
直接打开 QuickOpen 就会出现

**预期表现（Expected behavior）**

<img width="631" alt="image" src="https://user-images.githubusercontent.com/2226423/158294864-af1cf8a6-e5ee-4354-a07f-9c9f0fda0bb6.png">

**问题截图（Screenshots）**
<img width="631" alt="image" src="https://user-images.githubusercontent.com/2226423/158294695-d8c5c918-c13d-47d8-a7f3-f7c010e3185e.png">

**环境信息（Environment）**

- OS: macOS Catalina
- Browser: O2
- OpenSumi Version 2.16 测试版，2.15.6-next-1646985692.0

**补充信息（Additional context）**

**Comment by bytemain** [comment]
建议把前面这部分的宽度限制一下。整行的布局设置为 Flex，7:3 之类的，然后左侧 7 overflow auto

**Comment by yantze** [comment]
1. 提示太多有点不够简洁
2. 滚动可能操作也不够友好

**Comment by yantze** [comment]
比如你输入数字，然后在 quickOpen 里面提示跳转到多少行，这样的提示会更好一点

**Comment by yantze** [comment]
再加一个 ":" ，提示变为跳转到第几行第几个字符，这样更符合直觉一些
