### ISSUE TITLE
[BUG] ide-extension 包默认导出了 node 下的文件

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#633]
https://github.com/opensumi/core/blob/main/packages/extension/src/index.ts

<img width="589" alt="image" src="https://user-images.githubusercontent.com/13938334/158313641-9509ec2d-9238-4f07-8966-cf4b13888874.png">

**Comment by Aaaaash** [comment]
尝试了一下可以直接删掉，但不确定会不会有集成依赖这个行为
