### ISSUE TITLE
[BUG] .gitignore 中的文件并没有以淡色展示

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#638]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/13938334/158336926-f192003b-f1f6-4712-80fc-8475955ca681.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/13938334/158337077-f36f670b-f77f-4af6-ba32-be1ecbb37f82.png">

**Comment by Aaaaash** [comment]
确认下 Git 插件是不是激活了

**Comment by bytemain** [comment]
使用了 git 1.44.2 没有该问题，先关了
