### ISSUE TITLE
[BUG] viewContainer 的 icon 字段需要支持 resolver

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#647]
vscode pull request 这个插件注册 viewContainer 时传的图标是 $(github)，需要 icon resolver 一下才能展示出来。

https://github.com/microsoft/vscode-pull-request-github/blob/main/package.json#L383

现在会显示成这样：
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/13938334/158408616-0f3a0d73-fd54-4fe9-aca0-c5ed14a9f06d.png">

**Comment by Aaaaash** [comment]
这个印象中有的, 我瞅一下
