### ISSUE TITLE
[REFACTOR] 重构内部的 Preference 模块 

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#651]
获取用户配置的那些 API，最好可以与插件进程使用的那一套 ConfigurationModule 结合起来。

**Comment by erha19** [comment]
@bytemain 这个可能要展开讲讲，希望支持的特性细节？重构的目的？

**Comment by bytemain** [comment]
可以专项优化一下各种 preference 的 i18n

**Comment by bytemain** [comment]
no stale
