### ISSUE TITLE
[FEATURE] 文件树支持快捷键

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#670]
ctrlcmd + a: 选中当前层级的所有节点

enter 重命名，进入重命名后再按 esc，文件树焦点就丢失了，再按 enter 就失效了

![CleanShot 2022-03-17 at 15 26 37](https://user-images.githubusercontent.com/13938334/158758175-f281413e-fe44-4f7a-9639-c0593ab65ef9.gif)

右键菜单快捷键对比：

<img width="295" alt="image" src="https://user-images.githubusercontent.com/13938334/158758293-041e5597-ffc3-4f0a-9497-e9dca66395af.png">
<img width="223" alt="image" src="https://user-images.githubusercontent.com/13938334/158758348-ea04d18b-922f-4a08-9b09-6139e90ad9d1.png">

**Comment by bytemain** [comment]
还没完全完成

**Comment by erha19** [comment]
supported on #714.
