### ISSUE TITLE
[BUG] 包内部存在循环引用导致 Rollup 构建产物无效

### ISSUE THREAD

**Issue by zhyupe** [opensumi/core#698]
**描述你的问题（Describe the bug）**

由于包（例如 `@opensumi/ide-core-browser`）内部存在循环引用，构建后产物在运行时报错

**复现路径（To Reproduce）**

使用 Vite 构建，并引入产物

**预期表现（Expected behavior）**

正常引入无报错

**问题截图（Screenshots）**

<img width="898" alt="image" src="https://user-images.githubusercontent.com/2197479/159434921-b04d0e4d-1c6f-4078-aaba-0845dd756011.png">

**环境信息（Environment）**

- OS: macOS
- Browser Chrome 99.0.4844.74
- OpenSumi Version 2.16.0

**补充信息（Additional context）**

![image](https://user-images.githubusercontent.com/2197479/159441504-a9d1a5de-b12f-4b8a-8d85-352dad824ccf.png)
![image](https://user-images.githubusercontent.com/2197479/159442973-358ce713-1135-4d10-ba63-15986fe5f7a5.png)
![image](https://user-images.githubusercontent.com/2197479/159443015-942b9fd3-7c8c-46ea-b7f6-775055b43ce6.png)
![image](https://user-images.githubusercontent.com/2197479/159443161-e88a885f-571b-4913-8ad5-5cc1613789b3.png)

**Comment by erha19** [comment]
@zhyupe 有相应的工程 DEMO 仓库提供吗？

**Comment by erha19** [comment]
测试仓库地址： https://github.com/zhyupe/opensumi-prebuilt

**Comment by bytemain** [comment]
似乎已经不存在这个问题了，先关掉了。

如果还有问题可以 reopen
