### ISSUE TITLE
[FEATURE] 将发布包中的 less 构建为 css

### ISSUE THREAD

**Issue by zhyupe** [opensumi/core#700]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

发布包中包含 less 格式的样式文件，例如：
https://unpkg.com/browse/@opensumi/ide-core-browser@2.16.0/lib/progress/progress.module.less

在其他项目引入时，可能产生不必要的额外依赖

**描述你预期的功能表现（Describe the solution you'd like）**

将 less 文件构建为 css 文件，并引用 css 文件

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by erha19** [comment]
@zhyupe 由于特殊的项目结构设计，如果将项目内的 less 打包为 css，整体 IDE 在打包环节的设计会更加复杂（也需要将 TS 一并打包，后续可能会把核心包组合后有一个统一的打包版本，单个包暂时无计划），我们比较推荐基于 OpenSumi 的项目结构进一步搭建你自己的 IDE 项目，可以参考一下我们的三个案例：

- Web IDE：https://github.com/opensumi/ide-startup
- Electron：https://github.com/opensumi/ide-electron
- Lite IDE：https://github.com/opensumi/ide-startup-lite

这个问题我先关闭了，后续有问题可以再开 Issue 讨论 ~
