### ISSUE TITLE
[FEATURE] Add dockerfile to deploy image at server.

### ISSUE THREAD

**Issue by xyj404** [opensumi/core#707]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**
 https://github.com/opensumi/ide-startup/issues/10

ide-startup project have some problem and this project no problem. But i don't know how to build docker image use this project.

**描述你预期的功能表现（Describe the solution you'd like）**
I hope this project can provide dockerfile to deploy like ide-startup project.

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by bytemain** [comment]
https://github.com/opensumi/ide-startup

这里的这份 Dockerfile 可以参考一下

**Comment by xyj404** [comment]
我尝试在core项目里用webpack打包dist和dist-node，但遇到很多问题，对于整个项目逻辑我还不够了解。

**Comment by erha19** [comment]
@xyj404 可以把你具体的集成工程仓库提供一下，把报错信息提供一下，也许我们可以帮你解答掉部分问题
