### ISSUE TITLE
[BUG] 搜索内容出错

### ISSUE THREAD

**Issue by ChesterBu** [opensumi/core#718]
**描述你的问题（Describe the bug）**
搜索文件内容出错

yarn start 启动core项目 搜索文件时出错

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**
<img width="761" alt="截屏2022-03-23 下午7 48 03" src="https://user-images.githubusercontent.com/16631758/159692649-bb5e6581-be4e-4f28-9d35-b9104d052191.png">

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by bytemain** [comment]
看一下该路径有没有内容：

```sh
ls node_modules/@opensumi/vscode-ripgrep/bin
```

有的话执行一下
```sh
file node_modules/@opensumi/vscode-ripgrep/bin/rg
node -e "console.log(process.arch)"
```

**Comment by ChesterBu** [comment]
<img width="695" alt="截屏2022-03-25 上午9 45 52" src="https://user-images.githubusercontent.com/16631758/160038343-a1107f75-b149-4470-9aa6-ec48e13e2305.png">
<img width="345" alt="截屏2022-03-25 上午9 46 15" src="https://user-images.githubusercontent.com/16631758/160038378-68ac83b5-d8bd-4432-be86-d33ae05ff1c7.png">
没有这个bin文件

**Comment by bytemain** [comment]
那可能需要手动在 node_modules/@opensumi/vscode-ripgrep 这个路径下执行一下 npm run postinstall

可能是安装依赖时下载这个 bin 文件出错了，手动执行一下看看可不可以，如果不行的话再贴一下报错

**Comment by ChesterBu** [comment]
<img width="1069" alt="截屏2022-03-28 下午4 57 44" src="https://user-images.githubusercontent.com/16631758/160363945-0ed0d1a3-e778-44e1-a601-1b3c2a6330ee.png">
在服务器上安装时显示超时

**Comment by bytemain** [comment]
是国外的服务器嘛？

**Comment by ChesterBu** [comment]
不是的

**Comment by ChesterBu** [comment]
公司内网的服务器

**Comment by bytemain** [comment]
这个地址是支付宝的静态资源cdn地址，是否公司网关对这个地址有拦截/HOST定义等。。。

**Comment by ChesterBu** [comment]
我尝试通过 yarn install --ignore-scripts 跳过这个安装，然后创建，但是又遇到了_https://github.com/opensumi/core/issues/743_这个问题。。。

**Comment by ChesterBu** [comment]
> 

我查下这个

**Comment by bytemain** [comment]
请问你可以手动 wget 下载一下那个地址嘛？看看是不是CDN下载太慢了？

```
wget https://gw.alipayobjects.com/os/lib/opensumi/vscode-ripgrep-prebuilt/1.4.0/build/ripgrep-v13.0.0-4-x86_64-unknown-linux-musl/rg.wasm
```

我们之后可以试着延长一下下载时间。
