### ISSUE TITLE
[BUG] QuickOpen 多选框点击后会立即消失

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#742]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/20262815/160349564-3d7d8ebd-3904-4dee-aa3a-5862b8ef6a7b.png)
点击这里不仅没有选中，还会消失

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by bytemain** [comment]
这个是怎么触发的呢？我已经装了 Java 插件了

**Comment by Ricbet** [comment]
> 这个是怎么触发的呢？我已经装了 Java 插件了

source action... -> generate constructors

**Comment by bytemain** [comment]
给个代码示例吧

**Comment by bytemain** [comment]
复现了
