### ISSUE TITLE
已安装插件没有在“扩展市场”列表中删除

### ISSUE THREAD

**Issue by zlweicoder** [opensumi/core#750]
![image](https://user-images.githubusercontent.com/13825714/160542988-1f7834fc-493a-433f-8c7b-a519b529b5b5.png)
![image](https://user-images.githubusercontent.com/13825714/160543070-4a3fcc72-2cba-42ab-9a90-375f6c432f12.png)

**Comment by erha19** [comment]
相关代码位置见：[extension-manager/src/browser/vsx-extension.view.tsx](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/extension-manager/src/browser/vsx-extension.view.tsx)

这里可以优化一下部分图标间距展现效果，同时针对在拓展市场中搜索到的结果，相同版本的情况下，需要过滤掉已安装的插件版本，不同版本的情况下需要修改文案为 “更新”

**Comment by songhn233** [comment]
@erha19 Please assign to me.
