### ISSUE TITLE
[BUG] [Java 插件] quick fix... -> create class xxx 操作会导致控制台报错

### ISSUE THREAD

**Issue by Ricbet** [opensumi/core#751]
**描述你的问题（Describe the bug）**

在最新的 java 插件 1.0.0 版本中，在需要 quick fix ... 的地方选择 create class xxx 文件
![image](https://user-images.githubusercontent.com/20262815/160584505-39d40b3f-d9ee-4504-863e-69a01c6fb414.png)

点击后控制台报如下错误
![image](https://user-images.githubusercontent.com/20262815/160584636-c773b856-dd9b-4fd7-9a5d-54ba6fa3e6c1.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Ricbet** [comment]
经过排查后发现是 java 插件底层的 eclipse.jdt.ls 的问题，它仅返回一个 "写" 操作的 worksoace edits ，但在写之前并没有返回 "创建文件" 的 workspace edits。
才导致如图所示的报错，导致功能不可用
目前通过 hack 的方式在插件层解决，该 issue 可关闭

**Comment by bytemain** [comment]
vscode 没有一样的问题嘛

**Comment by Ricbet** [comment]
> 

没有，所以还需要在 jdt.ls 侧排查解决，但这并不属于该 repo 的 bug 了

**Comment by bytemain** [comment]
会不会是因为 vscode 兼容了： 写一个空的 workspace edits 时，不存在则会自己创建这个文件

**Comment by Ricbet** [comment]
> 会不会是因为 vscode 兼容了： 写一个空的 workspace edits 时，不存在则会自己创建这个文件

不会，因为我写了个最小 demo 试过了

**Comment by Ricbet** [comment]
![image](https://user-images.githubusercontent.com/20262815/160991473-367d0501-3c49-493b-bd3b-b7a31aa5660d.png)
