### ISSUE TITLE
[Feature] 移除或替换无效的 `ApplicationError` 逻辑

### ISSUE THREAD

**Issue by erha19** [opensumi/core#779]
**描述你的问题（Describe the bug）**

当前位于 `core-common` 中的 [application-error.ts](https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-common/src/application-error.ts) 与 `FileService` 存在逻辑依赖但无实际用处，可以考虑移除该逻辑，或修改让该逻辑可正常使用。

PS：由于 RPC 通信无法透传 Class `ApplicationError（后端） !== ApplicationError（前端）`

**预期表现（Expected behavior）**

重新梳理该块逻辑

**Comment by iamxukai** [comment]
我有兴趣解决一下

**Comment by iamxukai** [comment]
后端好像本来就只返回 stack 和 message。
![error node](https://user-images.githubusercontent.com/85668115/167528034-3bdeac7b-b5d9-4951-87d3-488a16397593.png)

**Comment by iamxukai** [comment]
![bc5235bdbe44358894b60213b725f5ade370d47577747aa7d0b86a3c38012231QzpcVXNlcnNcNDkzNzBcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDIxNTUwNjgwNzdfdjJcSW1hZ2VGaWxlc1wxNjUyMTY3NTM1ODcyXzJBQ0E0N0QwLUQzNUMtNGE2NS05OEQ2LTJDQTY5NTIzQkZBRC5wbmc=](https://user-images.githubusercontent.com/85668115/167573121-b5574b3d-80a4-4b39-8948-50c4848ec8f2.png)
原有的ERROR属性就这几个，怎么才能给前端 足够的属性来 使用 FileSystemError呢？

**Comment by erha19** [comment]
@iamxukai 可以试试换一下思路，例如把 error 相关的信息整合到 message 里面，前端的 is 判断针对消息体做解构进行判断，不过建议还是先梳理一下哪些地方在用这种判断逻辑，如果没必要，该去掉就去掉了

**Comment by bytemain** [comment]
[debug-configuration-manager.ts#L394](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/debug/src/browser/debug-configuration-manager.ts#L394) 这里的判断应该是对的，因为它是接收的 browser 层的 packages/file-service/src/browser/file-service-client.ts 的错误，这里的判断应该不存在问题吧

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/13938334/167578517-1cc7420d-c11b-4f75-90a4-f849de5d9ec0.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/13938334/167578590-9e3e9962-826e-4e0e-b9ec-202f62920de2.png">

**Comment by iamxukai** [comment]
> [debug-configuration-manager.ts#L394](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/debug/src/browser/debug-configuration-manager.ts#L394) 这里的判断应该是对的，因为它是接收的 browser 层的 packages/file-service/src/browser/file-service-client.ts 的错误，这里的判断应该不存在问题吧
> 
> <img alt="image" width="1143" src="https://user-images.githubusercontent.com/13938334/167578517-1cc7420d-c11b-4f75-90a4-f849de5d9ec0.png">
> 
> <img alt="image" width="1383" src="https://user-images.githubusercontent.com/13938334/167578590-9e3e9962-826e-4e0e-b9ec-202f62920de2.png">

我应该修复好了前端使用这个判断的功能

**Comment by erha19** [comment]
> 所以 @erha19 的意思是 `provider.stat()` 会抛错，这个是 JSON RPC 抛出的错，并不能被 `Application.is` 中的 instanceof 判断对？

嗯，这个判断是失效的，可以看一下这个 [proxy.ts#L118](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/connection/src/common/proxy.ts#L118)
