### ISSUE TITLE
[BUG] extensionService.executeExtensionCommand 无法执行 builtinCommands

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#808]
OpenSumi Desktop 有个调试插件进程的工具，在 extProcessInit 时传入了 builtinCommands，但是调用的时候显示：`没有插件注册该命令`。

调用方式及 workaround 见：

- https://github.com/opensumi/ide-electron/commit/9d0ca4f7bcdd6ded47c086f928261cf44da3340b

**Comment by Aaaaash** [comment]
builtinCommands 只能在插件进程调用，这个行为是 by design

**Comment by Aaaaash** [comment]
要手动开启可以在代码里调 extensionNodeService.tryEnableInspectPort, 用 extensionService.getProcessInspectPort 获取端口号

https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/extension/src/node/extension.profiler.service.ts#L30-L37

**Comment by bytemain** [comment]
其实我觉得用户在初始化 extProcessInit 时传入的 builtinCommands，是希望可以在其他地方调用的。

**Comment by Aaaaash** [comment]
没有，这个在 extProcessInit 里传入 builtinCommands 的功能最开始就是为了注入一些私有的 token ，让插件进程里的一些插件可以获取到。同时不希望被除了插件进程之外的地方调用到，例如如果在 mainthread 直接调用，会通过通信直接明文泄露这些 token
