### ISSUE TITLE
[BUG] 设置面板转到 JSON 功能只会转到工作区的 JSON

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#821]
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/13938334/163088324-3ca59e08-4b3f-46dc-a5d7-fb56f3b2f79e.png">

这两个 tab 下，按转到 json ，都会在工作区创建并打开一个 json

**Comment by erha19** [comment]
@bytemain 这个还有这个问题吗？我本地试了一下好像没这个问题

**Comment by bytemain** [comment]
没有复现了
