### ISSUE TITLE
[BUG] [偶现]文件树右键菜单缺少`删除`选项

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#842]
**描述你的问题（Describe the bug）**

![image](https://user-images.githubusercontent.com/17701805/163538178-84a07682-a3de-4cfc-bbf5-528f97ced673.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by erha19** [comment]
看起来 `registerCommand` 中的 `isVisible` 条件有概率不正确或不生效

**Comment by bytemain** [comment]
![image](https://user-images.githubusercontent.com/13938334/165923878-ae1a0abb-daa6-4680-b59c-11184ad49115.png)

filter 模式下删除按钮会消失

**Comment by erha19** [comment]
复现路径：点击筛选按钮后，删除功能就会不展示，这个是早期功能设计带来的变化

修复可以简单调整一下，菜单的命令注册中的 `isVisible` 条件，去掉筛选条件判断，相关代码见：

[file-tree-next/src/browser/file-tree-contribution.ts#L275](https://github.com/opensumi/core/blob/1fa22e3972251597d29a6e75e252d293fd6c1557/packages/file-tree-next/src/browser/file-tree-contribution.ts#L275)

可以移除多处地方的 `FilesExplorerFilteredContext.not` 条件，但在进行操作前需要先退出一下筛选（快照）模式，例如调用一下 `fileTreeService` 中的 `toggleFilterMode` 方法。
