### ISSUE TITLE
[BUG] 插件进程重启流程无响应，无法走到结束流程

### ISSUE THREAD

**Issue by bk1012** [opensumi/core#859]
**描述你的问题（Describe the bug）**
![image](https://user-images.githubusercontent.com/12130901/163773295-765557d7-f54d-414a-a288-f2a3d3431062.png)
插件进程重启流程被阻塞，提示框无法自动关闭

**复现路径（To Reproduce）**
1、切换至浏览器非 IDE tab
2、电脑休眠等待插件进程超时被销毁
3、结束电脑休眠，等待一会后切换回浏览器 IDE 的 tab
4、此时右下角会有一个“插件进程重启中”的提示框，且不会被关闭

**Comment by bytemain** [comment]
是 main 分支测试的吗？

**Comment by bytemain** [comment]
- https://github.com/opensumi/core/pull/836

main 分支试试？这个应该不知道 #836 修了没有

**Comment by bk1012** [comment]
这个的原因应该是切换 tab 以后，chrome 会对 socket 限流，导致插件进程重启的时候激活插件的 rpc 调用一直等不到返回

可以验证下
