### ISSUE TITLE
[BUG] 文件服务中的 watcher 多余的事件

### ISSUE THREAD

**Issue by erha19** [opensumi/core#867]
**描述你的问题（Describe the bug）**

文件操作事件不能被正确处理，如编辑文件 A，会产生 A 文件的添加事件，不太合理，排除定位到是 nsfw 发出的事件不准确，一次编辑操作一般情况下会产生 6 次 A 文件的添加事件，2 次 删除事件，且存在多种情况发生，可以考虑替换 `nsfw` 为 `@parcel/watche`

**复现路径（To Reproduce）**

mac 环境下编辑文件

**预期表现（Expected behavior）**

正常处理事件

**问题截图（Screenshots）**

<img width="1110" alt="截屏2022-04-19 上午11 55 33" src="https://user-images.githubusercontent.com/9823838/163917419-2b1d444a-79a4-4064-8f3d-545ef662d188.png">

**Comment by erha19** [comment]
相关处理逻辑文件：

- [file-service-watcher.ts](https://github.com/opensumi/core/blob/66832158e6ec439e2f072dd0fe889dfae1e57970/packages/file-service/src/node/file-service-watcher.ts)
- [file-change-collection.ts](https://github.com/opensumi/core/blob/f8fb5703623c5ee586071157373fb6c49b4f6e05/packages/file-service/src/node/file-change-collection.ts)

**Comment by Aaaaash** [comment]
https://github.com/opensumi/core/blob/4218171299716d2a074e6331b0fea0f98e6e0412/packages/file-service/src/node/file-service-watcher.ts#L170-L157

看了下代码，这里会把原文件修改的事件和临时文件的事件合并，多余的事件应该是从这里来的，比如两次 DELETE 是不是实际是由删除临时文件产生的

**Comment by Aaaaash** [comment]
修改文件会产生这些事件
```json
[
  {
    "action": 0,   // CREATED 临时文件
    "directory": "/path/to/opensumi/core",
    "file": "package.json.289451759"
  },
  {
    "action": 1,    // DELETE 临时文件
    "directory": "/path/to/opensumi/core",
    "file": "package.json.289451759"
  },
  {
    "action": 0,    // CREATED package.json
    "directory": "/path/to/opensumi/core",
    "file": "package.json"
  },
  {
    "action": 0,    // CREATED package.json
    "directory": "/path/to/opensumi/core",
    "file": "package.json"
  }
]
```
经过这个 `trimChangeEvent` 会变成
```json
[
  {
    "action": 0,    // CREATED package.json
    "directory": "/path/to/opensumi/core",
    "file": "package.json"
  },
  {
    "action": 1,    // DELETE package.json
    "directory": "/path/to/opensumi/core",
    "file": "package.json"
  },
  {
    "action": 0,    // CREATED package.json
    "directory": "/path/to/opensumi/core",
    "file": "package.json"
  },
  {
    "action": 0,    // CREATED package.json
    "directory": "/path/to/opensumi/core",
    "file": "package.json"
  }
]
```
