### ISSUE TITLE
为啥不用golang的wails开发，比electron暂用内存小，包也小

### ISSUE THREAD

**Issue by yangpeng1994** [opensumi/core#869]
为啥不用golang的wails开发，比electron暂用内存小，包也小

**Comment by erha19** [comment]
> 为啥不用golang的wails开发，比electron暂用内存小，包也小

由于 Electron 比较丰富的开发者生态，我们在前期的功能建设及技术选型上选择了 Electron 作为桌面端的框架，目前也暂无切换到其他桌面端框架计划，如果对 wails 框架有兴趣，可以考虑使用它来包装一下 OpenSumi，有需要帮助的地方可以到 issue 提问，我们也会尽力帮助你的。
