### ISSUE TITLE
[FEATURE]  补全时的图标主题和文件树保持一致

### ISSUE THREAD

**Issue by MMhunter** [opensumi/core#920]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

补全时的图标主题和文件树保持一致

OPENSUMI
![image](https://user-images.githubusercontent.com/1378130/165433546-33a93809-b487-4e5f-8771-dc977ed61aee.png)

VSCODE:
![image](https://user-images.githubusercontent.com/1378130/165433789-f9548d9b-c5cb-4b25-8063-815b90aa9d5f.png)

**描述你考虑过的替代方案（Describe alternatives you've considered）**

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
需要 patch 一下 monaco 内置的 standaloneThemeService
