### ISSUE TITLE
[BUG] Windwos上路径和vscode格式不同，会导致插件功能错误

### ISSUE THREAD

**Issue by kidswong999** [opensumi/core#927]
sumi的现在的格式  `/c:/Users/kaizhi/Desktop/test`
vscode的格式 `C:\\Users\\kaizhi\\Desktop\\test`

在使用debugpy时，需要pathMappings参数，现在的路径格式，会出错。

最好可以保持和vscode一致。

**Comment by kidswong999** [comment]
复现步骤：安装ms-python插件，并launch.json中使用 attach。无法正常进入断点。

**Comment by erha19** [comment]
@kidswong999 这里可以补充一下具体是从什么逻辑或接口中获取到 `/c:/Users/kaizhi/Desktop/test` 这个路径的吗？
