### ISSUE TITLE
[BUG] Terminal 刷新恢复后需要按一下回车才能继续使用

### ISSUE THREAD

**Issue by erha19** [opensumi/core#938]
**描述你的问题（Describe the bug）**

终端会展示 Terminal Restore，需要按一下回车才能正常使用

**复现路径（To Reproduce）**

开终端，然后刷新

**预期表现（Expected behavior）**

没有 `Terminal Restore` 文案，终端可以直接使用

**问题截图（Screenshots）**

![image](https://user-images.githubusercontent.com/9823838/166860754-bce15523-7bc2-45dc-bb7d-fa1c3b306edb.png)

**Comment by life2015** [comment]
本来是个Feature，但是如果要做到完美放置Terminal restore位置的话技术成本太高。
那就先把这个功能去掉吧
