### ISSUE TITLE
[FEATURE] preference 映射支持任意文件夹

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#943]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

![image](https://user-images.githubusercontent.com/13938334/166878323-c5091c2f-8286-4211-ba05-f8e4200be4b9.png)

希望我的配置文件不用只在 .mini-ide 内，这个约定定的太死了，然后本来起watcher 在 preferenceProvider 里面自己起的逻辑不挺好。本来就不应该越俎代庖

**Comment by erha19** [comment]
这里的情况应该在 #942 就改回去了，让 preferenceProvider 里面自己自定义更新逻辑了，需求的背景应该是希望提供一种通过服务注册方式自定义配置文件读取的能力？一个官方的默认实现 demo？

**Comment by MMhunter** [comment]
![image](https://user-images.githubusercontent.com/1378130/166879776-b719df83-42e5-4284-bcd1-0045c7fa8ad7.png)
按照原来的设计 preferenceProvider  的 getUri 应该和 此处的 createUri 一致，目前只支持根据 configName 来修改json名。 希望是能完整支持 

1. 对于一个 folder 工作区，由 preferenceProvider 提供的配置文件可以指定任意一个 configUri，而不是只能通过修改 configName 名称来
2. configUri 允许包含 `.`，现在由于 getConfigUri 和 configPath 和 configName 耦合，导致整个逻辑定的非常死

![image](https://user-images.githubusercontent.com/1378130/166880796-c91184f5-9b2c-41bf-96f3-10ad58962aca.png)

**Comment by erha19** [comment]
简单理解，就是希望对于配置文件路径类似 `$workspacefolder/a.b.json` 的配置值读取可以转换为  `a-b.xxxxx` 这样的配置值进行读取。

这里可以利用 `FolderPreferenceProvider` 和 `PreferenceContribution`, `PreferenceConfiguration` 配合使用来实现改能力，我来补充一个文档
