### ISSUE TITLE
[BUG] 是否废弃内置的 Markdown 预览功能

### ISSUE THREAD

**Issue by Aaaaash** [opensumi/core#949]
**描述你的问题（Describe the bug）**

Markdown language features 插件提供了 `预览` 能力，对于需要 Markdown 预览功能的安装该插件即可。
由于内置m Markdown 预览功能的存在，导致安装插件以后右下角打开方式变得有些重复

![image](https://user-images.githubusercontent.com/17701805/167054982-b7641bcc-f470-46ab-967a-d2a7e60df5e3.png)

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by moreJs** [comment]
@Aaaaash 我来搞下

**Comment by songhn233** [comment]
这个我理解应该先需要把 Markdown language features 加进预置插件列表里，然后再移除原先 opensumi 对 markdown 文件的支持

**Comment by Aaaaash** [comment]
> 这个我理解应该先需要把 Markdown language features 加进预置插件列表里，然后再移除原先 opensumi 对 markdown 文件的支持

是的，但是在框架层面只能提供建议，最终还是取决于集成用户的选择，预置插件这个操作是可以在集成时自定义的

**Comment by erha19** [comment]
done #968 .
