### ISSUE TITLE
[BUG] 编辑器中提示字体太大

### ISSUE THREAD

**Issue by yantze** [opensumi/core#955]
**描述你的问题（Describe the bug）**

提示的字体太大

**复现路径（To Reproduce）**
1. 打开一个 IDE 不能识别的格式，比如 tiff
2. 提示内容：我们无法在编辑器中展示这个文件。使用外部软件打开

**预期表现（Expected behavior）**
是用 13px 字体大小即可

**问题截图（Screenshots）**
<img width="479" alt="image" src="https://user-images.githubusercontent.com/2226423/167098560-ce063d5d-4c31-4bbf-9065-5328e3121f3a.png">

**环境信息（Environment）**

- OS: macOS catalina 
- Browser: electron
- OpenSumi Version: 2.16.10

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
应该已经有默认值了 #928

**Comment by yantze** [comment]
那关了
