### ISSUE TITLE
[BUG] 终端及插件市场滚动条较宽，视觉效果不统一

### ISSUE THREAD

**Issue by erha19** [opensumi/core#960]
**描述你的问题（Describe the bug）**

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/9823838/167233981-bdc3e74a-7fff-42ee-bca8-995740885b5b.png">

https://user-images.githubusercontent.com/9823838/167234009-e05fd312-a5a1-494d-8215-473e70d5bba5.mp4

目前终端及插件市场的滚动条宽度在 20 px 左右，而文件树等界面滚动条宽度在 6 px 左右，整体不协调
**复现路径（To Reproduce）**

打开页面，拉宽插件市场列表

终端分栏后多按几下回车，出现滚动条

**预期表现（Expected behavior）**

各区域滚动条保持一致，统一使用 10px 作为滚动条的默认（纵向）宽度和（横向）高度

**Comment by songhn233** [comment]
Please assign to me.
