### ISSUE TITLE
[FEATURE] 请问目前纯前端版本是无法支持gitlab吗？

### ISSUE THREAD

**Issue by czz362100** [opensumi/core#971]
业务场景：codeReview

**Comment by erha19** [comment]
@czz362100 可以支持的，只是我们目前提供的 Demo 是以对接 GitHub 为例，有需求可以根据我们提供的样例进行修改，GitHub 上的接口应该都是可以在 GitLab 中找到对应接口的

**Comment by czz362100** [comment]
好的，谢谢
