### ISSUE TITLE
[FEATURE] 统一压缩/解压功能的依赖

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#976]
目前使用了以下的压缩功能的依赖：
- 'archiver'
- 'yauzl'

想换成：https://www.npmjs.com/package/compressing ，虽然没怎么更新了，但由于是同事(fengmk2)在维护，方便更新

**Comment by bytemain** [comment]
统一依赖后，可以在 core-node 里放一个封装好的供压缩相关能力的函数

**Comment by Aaaaash** [comment]
用 yauzl 是因为 compressing 不支持解压时保留 mode，对于一些包含了可执行文件的插件，使用 compressing 解压后会丢失执行权限，导致插件运行失败

**Comment by songhn233** [comment]
> 统一依赖后，可以在 core-node 里放一个封装好的供压缩相关能力的函数

这个可以先统一成 archiver，看到类似的问题被解决过 https://github.com/mholt/archiver/issues/133

**Comment by bytemain** [comment]
Compressing 现在支持解压保存 mode 了

- https://github.com/node-modules/compressing/pull/68

**Comment by erha19** [comment]
@songhn233 这个有时间做吗？感觉可以搞一下

**Comment by songhn233** [comment]
> @songhn233 这个有时间做吗？感觉可以搞一下

👌，assign 给我吧
