### ISSUE TITLE
[FEATURE] 统一命令处理能力（yargs）

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#980]
可以发现有重复依赖 commander / yargs 等包

**Comment by dqhl76** [comment]
这个我可以来吗？
TODO：
把[packages/remote-cli/src/index.ts](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/remote-cli/src/index.ts)的commander更换为yargs实现

**Comment by dqhl76** [comment]
请问这个怎么测试啊，我找到了这个[#288](https://github.com/opensumi/core/pull/288)，然后试图按照截图的方式去测试，结果提示需要cli，是需要自己实现这个吗？[/remote-cli/bin/open](https://github.com/opensumi/core/blob/main/packages/remote-cli/bin/open)

**Comment by Aaaaash** [comment]
> 请问这个怎么测试啊，我找到了这个[#288](https://github.com/opensumi/core/pull/288)，然后试图按照截图的方式去测试，结果提示需要cli，是需要自己实现这个吗？[/remote-cli/bin/open](https://github.com/opensumi/core/blob/main/packages/remote-cli/bin/open) @Aaaaash

这个本地开发的话需要编译后手动执行，运行一下 packages/remote-cli 里的 build 脚本，然后执行 [/remote-cli/bin/open](https://github.com/opensumi/core/blob/main/packages/remote-cli/bin/open)
