### ISSUE TITLE
[BUG] 终端搜索框的关闭键不生效

### ISSUE THREAD

**Issue by dqhl76** [opensumi/core#986]
**描述你的问题（Describe the bug）**

终端中进行搜索后，关闭键无法使用，只能按[ESC]关闭

**复现路径（To Reproduce）**

1. 打开终端
2. 点击搜索
3. 搜索框关闭按钮无法使用

**预期表现（Expected behavior）**

按关闭键关闭终端搜索框

**问题截图（Screenshots）**

https://user-images.githubusercontent.com/69136320/167358168-08518642-a3de-426a-93ca-11fb0cd73a3c.mp4

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- OpenSumi Version [e.g. 2.13.0]

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
可以补充一下版本以及环境信息吗，我在最新版本 2.17.2 下无法复现

https://user-images.githubusercontent.com/17701805/167369879-e57a995d-e7ee-41bd-a5c3-462943c58d49.mp4

**Comment by dqhl76** [comment]
环境信息（Environment）
OS: [macOS 12.3 Apple M1]
Browser [chrome]
OpenSumi Version [2.17.2]

我用[ide-startup](https://github.com/opensumi/ide-startup)这个试了一下是没问题的
