### ISSUE TITLE
[BUG] electron 标题栏高度不一致

### ISSUE THREAD

**Issue by kidswong999** [opensumi/core#989]
版本更新到2.17.2，标题栏的高度不一致。

![截图_16520942653390](https://user-images.githubusercontent.com/9582040/167397397-c007fc43-fad6-452d-a3e5-c7fa60738f46.png)

![截图_16520940924287](https://user-images.githubusercontent.com/9582040/167397027-8a092dbc-9c3f-4602-829a-bf2a16076ef6.png)

**Comment by yantze** [comment]
感谢反馈，已修复
