### ISSUE TITLE
[FEATURE] 更好的 Dialog 主题色适配

### ISSUE THREAD

**Issue by erha19** [opensumi/core#993]
**如果你的需求与问题相关，请在下面描述一下（Is your feature request related to a problem? Please describe.）**

![image](https://user-images.githubusercontent.com/9823838/167534818-e42d6a2d-57bf-4789-bbae-88cb8abb0e19.png)

**描述你预期的功能表现（Describe the solution you'd like）**

能根据主题调整颜色，当前使用的 token 颜色并不太合适

**补充信息（Additional context）**

当前弹窗使用的颜色 token 为 `--kt-modal-background` , 代码见 [dialog/styles.less#L3](https://github.com/opensumi/core/blob/cd28d3439406c0186883fb7bc3b297be2bac1e6b/packages/components/src/dialog/styles.less#L3) 

实际上在暗色主题下写死了色值，见：[color-tokens/custom/modal.ts#L11](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/theme/src/common/color-tokens/custom/modal.ts#L11), 这里实际上可以都用 `NOTIFICATIONS_BACKGROUND`,  而不需要特殊指定固定颜色

相关联部分建议都将固定的值写法修改掉

**Comment by iamxukai** [comment]
我有兴趣解决一下

**Comment by iamxukai** [comment]
@erha19 
![QQ截图20220512234907](https://user-images.githubusercontent.com/85668115/168116394-9b7db802-ffa3-4fd0-b3a7-cc2366123efc.png)
就算我重新build，对话框的background颜色仍然为 `#35393d ` 
![QQ截图20220512235146](https://user-images.githubusercontent.com/85668115/168116998-c6e78139-fe1a-462f-b7e0-caf39d1105bb.png)
感觉和[notification.ts #L56](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/theme/src/common/color-tokens/notification.ts#L56)和[editor.ts #L86](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/theme/src/common/color-tokens/editor.ts#L82)不符。

**我只要替换固定值为`NOTIFICATIONS_BACKGROUND`之类的就行了吗？**
